INSERT INTO public.hit_questions (id, module, test_type, question_index, question_text, sub_domain, response_type, reverse_scored, scoring_key)
VALUES
  ('pt_e01', 'personality_type', 'A', 0, '처음 만난 사람들과도 자연스럽게 대화를 시작하는 편이다.', 'E', 'likert7', false, '{"axis":"EI","direction":"E","discCross":["I"],"spowerContrib":["interpersonal"]}'::jsonb),
  ('pt_e02', 'personality_type', 'A', 1, '회의에서 아이디어가 떠오르면 바로 말하는 편이다.', 'E', 'likert7', false, '{"axis":"EI","direction":"E","discCross":["D","I"],"spowerContrib":["creativity","interpersonal"]}'::jsonb),
  ('pt_e03', 'personality_type', 'A', 2, '혼자 일하는 것보다 여러 사람과 함께할 때 에너지가 올라간다.', 'E', 'likert7', false, '{"axis":"EI","direction":"E","discCross":["I"],"spowerContrib":["interpersonal"]}'::jsonb),
  ('pt_e04', 'personality_type', 'A', 3, '새로운 팀에 합류하면 먼저 다가가서 인사하는 편이다.', 'E', 'likert7', false, '{"axis":"EI","direction":"E","discCross":["I"],"spowerContrib":["interpersonal"]}'::jsonb),
  ('pt_e05', 'personality_type', 'A', 4, '말로 설명하면서 생각을 정리하는 경우가 많다.', 'E', 'likert7', false, '{"axis":"EI","direction":"E","discCross":["I"],"spowerContrib":["interpersonal"]}'::jsonb),
  ('pt_e06', 'personality_type', 'A', 5, '발표나 프레젠테이션 상황에서 에너지가 높아진다.', 'E', 'likert7', false, '{"axis":"EI","direction":"E","discCross":["D","I"],"spowerContrib":["interpersonal","breakthrough"]}'::jsonb),
  ('pt_e07', 'personality_type', 'A', 6, '네트워킹 행사에 참석하면 여러 사람과 두루 이야기하는 편이다.', 'E', 'likert7', false, '{"axis":"EI","direction":"E","discCross":["I"],"spowerContrib":["interpersonal"]}'::jsonb),
  ('pt_e08', 'personality_type', 'A', 7, '팀 브레인스토밍이 혼자 고민하는 것보다 효과적이라고 느낀다.', 'E', 'likert7', false, '{"axis":"EI","direction":"E","discCross":["I"],"spowerContrib":["interpersonal","creativity"]}'::jsonb),
  ('pt_i01', 'personality_type', 'A', 8, '회의가 끝나면 혼자 생각을 정리하는 시간이 필요하다.', 'I', 'likert7', false, '{"axis":"EI","direction":"I","discCross":["S","C"],"spowerContrib":["analytical"]}'::jsonb),
  ('pt_i02', 'personality_type', 'A', 9, '글로 정리한 후에 말하는 것이 더 정확하다고 느낀다.', 'I', 'likert7', false, '{"axis":"EI","direction":"I","discCross":["C"],"spowerContrib":["analytical"]}'::jsonb),
  ('pt_i03', 'personality_type', 'A', 10, '소규모 깊은 대화가 대규모 네트워킹보다 의미 있다.', 'I', 'likert7', false, '{"axis":"EI","direction":"I","discCross":["S"],"spowerContrib":["harmony"]}'::jsonb),
  ('pt_i04', 'personality_type', 'A', 11, '하루 종일 사람을 만난 날은 저녁에 혼자 충전해야 한다.', 'I', 'likert7', false, '{"axis":"EI","direction":"I","discCross":["S"],"spowerContrib":["harmony"]}'::jsonb),
  ('pt_i05', 'personality_type', 'A', 12, '브레인스토밍보다 혼자 아이디어를 먼저 정리한 후 공유하는 것이 효과적이다.', 'I', 'likert7', false, '{"axis":"EI","direction":"I","discCross":["C"],"spowerContrib":["analytical"]}'::jsonb),
  ('pt_i06', 'personality_type', 'A', 13, '개방형 사무실보다 집중할 수 있는 독립 공간이 업무 효율에 좋다.', 'I', 'likert7', false, '{"axis":"EI","direction":"I","discCross":["C"],"spowerContrib":["analytical"]}'::jsonb),
  ('pt_i07', 'personality_type', 'A', 14, '사람을 많이 만나는 날보다 집중 작업을 한 날이 더 보람차다.', 'I', 'likert7', false, '{"axis":"EI","direction":"I","discCross":["C","S"],"spowerContrib":["analytical"]}'::jsonb),
  ('pt_n01', 'personality_type', 'A', 15, '구체적인 데이터보다 전체적인 흐름과 패턴이 먼저 눈에 들어온다.', 'N', 'likert7', false, '{"axis":"NS","direction":"N","discCross":["D"],"spowerContrib":["strategic"]}'::jsonb),
  ('pt_n02', 'personality_type', 'A', 16, '"만약에 이렇게 하면?"이라는 가능성을 자주 상상한다.', 'N', 'likert7', false, '{"axis":"NS","direction":"N","discCross":["I"],"spowerContrib":["creativity"]}'::jsonb),
  ('pt_n03', 'personality_type', 'A', 17, '기존 방식에 의문을 갖고 새로운 접근법을 시도하는 편이다.', 'N', 'likert7', false, '{"axis":"NS","direction":"N","discCross":["D"],"spowerContrib":["creativity","breakthrough"]}'::jsonb),
  ('pt_n04', 'personality_type', 'A', 18, '세부 실행보다 전략과 방향을 설정하는 일에 더 끌린다.', 'N', 'likert7', false, '{"axis":"NS","direction":"N","discCross":["D"],"spowerContrib":["strategic"]}'::jsonb),
  ('pt_n05', 'personality_type', 'A', 19, '현재 상황보다 3~5년 후의 변화가 더 흥미롭다.', 'N', 'likert7', false, '{"axis":"NS","direction":"N","discCross":["D"],"spowerContrib":["strategic"]}'::jsonb),
  ('pt_n06', 'personality_type', 'A', 20, '정해진 매뉴얼을 따르는 것보다 새로운 방법을 찾는 것이 재미있다.', 'N', 'likert7', false, '{"axis":"NS","direction":"N","discCross":["D"],"spowerContrib":["creativity"]}'::jsonb),
  ('pt_n07', 'personality_type', 'A', 21, '복잡한 문제에서 숨겨진 연결고리를 발견하는 일이 즐겁다.', 'N', 'likert7', false, '{"axis":"NS","direction":"N","discCross":["C"],"spowerContrib":["analytical","strategic"]}'::jsonb),
  ('pt_n08', 'personality_type', 'A', 22, '아이디어가 많아서 오히려 하나에 집중하기 어려울 때가 있다.', 'N', 'likert7', true, '{"axis":"NS","direction":"N","discCross":["I"],"spowerContrib":["creativity"]}'::jsonb),
  ('pt_s01', 'personality_type', 'A', 23, '구체적인 사례나 데이터가 있을 때 확신이 생긴다.', 'S', 'likert7', false, '{"axis":"NS","direction":"S","discCross":["C"],"spowerContrib":["analytical"]}'::jsonb),
  ('pt_s02', 'personality_type', 'A', 24, '업무 지시를 받으면 "구체적으로 어떻게?"를 먼저 묻는다.', 'S', 'likert7', false, '{"axis":"NS","direction":"S","discCross":["C"],"spowerContrib":["analytical","execution"]}'::jsonb),
  ('pt_s03', 'personality_type', 'A', 25, '이미 검증된 방법이 있으면 굳이 새로운 방법을 찾지 않는다.', 'S', 'likert7', false, '{"axis":"NS","direction":"S","discCross":["S"],"spowerContrib":["guard"]}'::jsonb),
  ('pt_s04', 'personality_type', 'A', 26, '추상적인 토론보다 실행 가능한 계획이 더 가치 있다고 생각한다.', 'S', 'likert7', false, '{"axis":"NS","direction":"S","discCross":["D","C"],"spowerContrib":["execution"]}'::jsonb),
  ('pt_s05', 'personality_type', 'A', 27, '숫자, 날짜, 이름 등 구체적 정보를 잘 기억하는 편이다.', 'S', 'likert7', false, '{"axis":"NS","direction":"S","discCross":["C"],"spowerContrib":["analytical"]}'::jsonb),
  ('pt_s06', 'personality_type', 'A', 28, '"가능성"보다 "현실"에 기반한 판단을 선호한다.', 'S', 'likert7', false, '{"axis":"NS","direction":"S","discCross":["S","C"],"spowerContrib":["guard","execution"]}'::jsonb),
  ('pt_s07', 'personality_type', 'A', 29, '경험해보지 않은 것을 추천하거나 결정하는 것이 불편하다.', 'S', 'likert7', true, '{"axis":"NS","direction":"S","discCross":["S"],"spowerContrib":["guard"]}'::jsonb),
  ('pt_t01', 'personality_type', 'A', 30, '의사결정 시 "논리적으로 맞는가"를 가장 먼저 확인한다.', 'T', 'likert7', false, '{"axis":"TF","direction":"T","discCross":["C","D"],"spowerContrib":["analytical","strategic"]}'::jsonb),
  ('pt_t02', 'personality_type', 'A', 31, '감정보다 근거가 설득력의 핵심이라고 생각한다.', 'T', 'likert7', false, '{"axis":"TF","direction":"T","discCross":["C"],"spowerContrib":["analytical"]}'::jsonb),
  ('pt_t03', 'personality_type', 'A', 32, '피드백을 줄 때 상대의 기분보다 정확한 사실 전달이 우선이다.', 'T', 'likert7', false, '{"axis":"TF","direction":"T","discCross":["D"],"spowerContrib":["execution"]}'::jsonb),
  ('pt_t04', 'personality_type', 'A', 33, '비용 대비 효과를 따져보지 않으면 결정하기 어렵다.', 'T', 'likert7', false, '{"axis":"TF","direction":"T","discCross":["C"],"spowerContrib":["analytical"]}'::jsonb),
  ('pt_t05', 'personality_type', 'A', 34, '상대의 논리에 허점이 보이면 즉시 지적하는 편이다.', 'T', 'likert7', false, '{"axis":"TF","direction":"T","discCross":["D"],"spowerContrib":["strategic","analytical"]}'::jsonb),
  ('pt_t06', 'personality_type', 'A', 35, '성과 평가는 관계와 무관하게 객관적으로 해야 한다.', 'T', 'likert7', false, '{"axis":"TF","direction":"T","discCross":["D","C"],"spowerContrib":["analytical"]}'::jsonb),
  ('pt_t07', 'personality_type', 'A', 36, '복잡한 상황에서 감정을 배제하고 냉정하게 판단할 수 있다.', 'T', 'likert7', false, '{"axis":"TF","direction":"T","discCross":["D"],"spowerContrib":["strategic","execution"]}'::jsonb),
  ('pt_f01', 'personality_type', 'A', 37, '논리적으로 옳아도 사람이 상처받으면 그 방법은 재고해야 한다.', 'F', 'likert7', false, '{"axis":"TF","direction":"F","discCross":["S"],"spowerContrib":["harmony"]}'::jsonb),
  ('pt_f02', 'personality_type', 'A', 38, '팀 분위기가 좋을 때 개인 성과도 올라간다고 믿는다.', 'F', 'likert7', false, '{"axis":"TF","direction":"F","discCross":["S","I"],"spowerContrib":["harmony","interpersonal"]}'::jsonb),
  ('pt_f03', 'personality_type', 'A', 39, '갈등 상황에서 상대의 감정을 먼저 살피는 편이다.', 'F', 'likert7', false, '{"axis":"TF","direction":"F","discCross":["S"],"spowerContrib":["harmony","interpersonal"]}'::jsonb),
  ('pt_f04', 'personality_type', 'A', 40, '동료가 힘들어하면 업무 중에도 먼저 말을 걸어본다.', 'F', 'likert7', false, '{"axis":"TF","direction":"F","discCross":["S","I"],"spowerContrib":["interpersonal"]}'::jsonb),
  ('pt_f05', 'personality_type', 'A', 41, '칭찬과 인정이 업무 동기에 큰 영향을 미친다.', 'F', 'likert7', false, '{"axis":"TF","direction":"F","discCross":["I"],"spowerContrib":["interpersonal"]}'::jsonb),
  ('pt_f06', 'personality_type', 'A', 42, '결정을 내릴 때 관련된 사람들의 상황을 먼저 고려한다.', 'F', 'likert7', false, '{"axis":"TF","direction":"F","discCross":["S"],"spowerContrib":["harmony"]}'::jsonb),
  ('pt_f07', 'personality_type', 'A', 43, '누군가의 노력을 알아주지 않는 조직 문화가 견디기 어렵다.', 'F', 'likert7', true, '{"axis":"TF","direction":"F","discCross":["S"],"spowerContrib":["harmony"]}'::jsonb),
  ('pt_f08', 'personality_type', 'A', 44, '비판적 피드백을 줄 때 상대가 받아들일 수 있는 방식을 고민한다.', 'F', 'likert7', false, '{"axis":"TF","direction":"F","discCross":["S","I"],"spowerContrib":["harmony","interpersonal"]}'::jsonb),
  ('pt_j01', 'personality_type', 'A', 45, '일을 시작하기 전에 단계별 계획을 세우는 편이다.', 'J', 'likert7', false, '{"axis":"JP","direction":"J","discCross":["C"],"spowerContrib":["execution","guard"]}'::jsonb),
  ('pt_j02', 'personality_type', 'A', 46, '마감을 넉넉히 앞당겨 끝내는 것이 편하다.', 'J', 'likert7', false, '{"axis":"JP","direction":"J","discCross":["C"],"spowerContrib":["execution"]}'::jsonb),
  ('pt_j03', 'personality_type', 'A', 47, '결론이 나지 않은 상태로 회의가 끝나면 불편하다.', 'J', 'likert7', true, '{"axis":"JP","direction":"J","discCross":["D","C"],"spowerContrib":["execution"]}'::jsonb),
  ('pt_j04', 'personality_type', 'A', 48, '갑작스러운 일정 변경이 스트레스를 준다.', 'J', 'likert7', true, '{"axis":"JP","direction":"J","discCross":["S","C"],"spowerContrib":["guard"]}'::jsonb),
  ('pt_j05', 'personality_type', 'A', 49, '할 일 목록을 만들고 하나씩 체크하는 것이 습관이다.', 'J', 'likert7', false, '{"axis":"JP","direction":"J","discCross":["C"],"spowerContrib":["execution"]}'::jsonb),
  ('pt_j06', 'personality_type', 'A', 50, '프로젝트 초반에 전체 구조를 잡아놓아야 안심이 된다.', 'J', 'likert7', false, '{"axis":"JP","direction":"J","discCross":["C"],"spowerContrib":["execution","guard"]}'::jsonb),
  ('pt_j07', 'personality_type', 'A', 51, '결정을 미루는 것보다 빠르게 정하고 실행하는 것이 낫다.', 'J', 'likert7', false, '{"axis":"JP","direction":"J","discCross":["D"],"spowerContrib":["execution","breakthrough"]}'::jsonb),
  ('pt_p01', 'personality_type', 'A', 52, '계획을 세우더라도 상황에 따라 유연하게 바꾸는 편이다.', 'P', 'likert7', false, '{"axis":"JP","direction":"P","discCross":["D","I"],"spowerContrib":["creativity","breakthrough"]}'::jsonb),
  ('pt_p02', 'personality_type', 'A', 53, '마감 직전에 집중력이 가장 높아진다.', 'P', 'likert7', false, '{"axis":"JP","direction":"P","discCross":["D"],"spowerContrib":["breakthrough"]}'::jsonb),
  ('pt_p03', 'personality_type', 'A', 54, '옵션을 열어두는 것이 빨리 결정하는 것보다 낫다고 생각한다.', 'P', 'likert7', false, '{"axis":"JP","direction":"P","discCross":["I"],"spowerContrib":["creativity"]}'::jsonb),
  ('pt_p04', 'personality_type', 'A', 55, '즉흥적으로 한 일이 오히려 좋은 결과를 낳은 경험이 있다.', 'P', 'likert7', false, '{"axis":"JP","direction":"P","discCross":["I"],"spowerContrib":["creativity"]}'::jsonb),
  ('pt_p05', 'personality_type', 'A', 56, '업무 중에도 재미있는 것이 생기면 잠시 들여다보는 편이다.', 'P', 'likert7', true, '{"axis":"JP","direction":"P","discCross":["I"],"spowerContrib":["creativity"]}'::jsonb),
  ('pt_p06', 'personality_type', 'A', 57, '정해진 프로세스를 따르는 것보다 나만의 방식을 찾는 것이 편하다.', 'P', 'likert7', false, '{"axis":"JP","direction":"P","discCross":["D"],"spowerContrib":["creativity","breakthrough"]}'::jsonb),
  ('pt_p07', 'personality_type', 'A', 58, '여러 프로젝트를 동시에 진행하는 것이 하나에 집중하는 것보다 잘 맞는다.', 'P', 'likert7', false, '{"axis":"JP","direction":"P","discCross":["I"],"spowerContrib":["creativity"]}'::jsonb),
  ('pt_p08', 'personality_type', 'A', 59, '예상 밖의 상황이 생기면 오히려 흥분되는 편이다.', 'P', 'likert7', false, '{"axis":"JP","direction":"P","discCross":["D","I"],"spowerContrib":["breakthrough","creativity"]}'::jsonb),
  ('pt_val01', 'personality_type', 'A', 60, '나는 지금까지 단 한 번도 거짓말을 한 적이 없다.', 'DECOY', 'likert7', false, '{"axis":"DECOY","direction":"DECOY","discCross":[],"spowerContrib":[]}'::jsonb),
  ('pt_val02', 'personality_type', 'A', 61, '다른 사람에 대해 부정적인 생각을 해본 적이 전혀 없다.', 'DECOY', 'likert7', false, '{"axis":"DECOY","direction":"DECOY","discCross":[],"spowerContrib":[]}'::jsonb);
