INSERT INTO public.hit_questions (id, module, test_type, question_index, question_text, sub_domain, response_type, reverse_scored, scoring_key)
VALUES
  ('bt_d_01', 'behavior_type', 'A', 0, '팀 프로젝트에서 마감이 다가오면 다른 사람의 의견보다 결과 달성을 우선시한다.', 'D', 'likert7', false, '{"btType":"D","mbtiTags":["T","J"],"darkTag":null}'::jsonb),
  ('bt_d_02', 'behavior_type', 'A', 1, '경쟁 상황에서 주도권을 잡으려 적극적으로 움직인다.', 'D', 'likert7', false, '{"btType":"D","mbtiTags":["E","T"],"darkTag":"SP"}'::jsonb),
  ('bt_d_03', 'behavior_type', 'A', 2, '목표가 명확하면 다른 사람의 반대에도 자기 판단을 밀고 간다.', 'D', 'likert7', false, '{"btType":"D","mbtiTags":["T","E"],"darkTag":"SP"}'::jsonb),
  ('bt_d_04', 'behavior_type', 'A', 3, '문제가 발생하면 원인 분석보다 해결책을 먼저 찾는 편이다.', 'D', 'likert7', false, '{"btType":"D","mbtiTags":["P"],"darkTag":null}'::jsonb),
  ('bt_d_05', 'behavior_type', 'A', 4, '도전적인 목표가 주어지면 의욕이 크게 상승한다.', 'D', 'likert7', false, '{"btType":"D","mbtiTags":["E","J"],"darkTag":null}'::jsonb),
  ('bt_d_06', 'behavior_type', 'A', 5, '상대방이 망설이면 직접 방향을 정해서 끌고 가는 편이다.', 'D', 'likert7', false, '{"btType":"D","mbtiTags":["E"],"darkTag":"SP"}'::jsonb),
  ('bt_d_07', 'behavior_type', 'A', 6, '토론에서 상대가 강하게 나오면 더 강하게 맞서는 편이다.', 'D', 'likert7', false, '{"btType":"D","mbtiTags":["T"],"darkTag":null}'::jsonb),
  ('bt_d_08', 'behavior_type', 'A', 7, '리스크가 있더라도 속도 있는 결단을 선호한다.', 'D', 'likert7', false, '{"btType":"D","mbtiTags":["P","E"],"darkTag":"SP"}'::jsonb),
  ('bt_d_09', 'behavior_type', 'A', 8, '결과가 중요하다면 방법은 유연하게 바꿀 수 있다.', 'D', 'likert7', false, '{"btType":"D","mbtiTags":["P"],"darkTag":null}'::jsonb),
  ('bt_d_10', 'behavior_type', 'A', 9, '다른 사람을 설득하여 내 의견대로 이끄는 것에 자신이 있다.', 'D', 'likert7', false, '{"btType":"D","mbtiTags":["E"],"darkTag":null}'::jsonb),
  ('bt_i_01', 'behavior_type', 'A', 10, '처음 만나는 사람과도 금세 편한 분위기를 만들 수 있다.', 'I', 'likert7', false, '{"btType":"I","mbtiTags":["E"],"darkTag":null}'::jsonb),
  ('bt_i_02', 'behavior_type', 'A', 11, '팀 분위기가 가라앉으면 먼저 농담이나 밝은 이야기를 꺼낸다.', 'I', 'likert7', false, '{"btType":"I","mbtiTags":["E"],"darkTag":null}'::jsonb),
  ('bt_i_03', 'behavior_type', 'A', 12, '나의 열정이 주변 사람에게 자연스럽게 전달되는 편이다.', 'I', 'likert7', false, '{"btType":"I","mbtiTags":["E"],"darkTag":null}'::jsonb),
  ('bt_i_04', 'behavior_type', 'A', 13, '여러 사람 앞에서 발표하거나 사회를 볼 때 에너지가 올라간다.', 'I', 'likert7', false, '{"btType":"I","mbtiTags":["E"],"darkTag":null}'::jsonb),
  ('bt_i_05', 'behavior_type', 'A', 14, '칭찬과 격려를 자주 표현하여 동료의 사기를 높이는 편이다.', 'I', 'likert7', false, '{"btType":"I","mbtiTags":["F","E"],"darkTag":null}'::jsonb),
  ('bt_i_06', 'behavior_type', 'A', 15, '워크숍이나 회의에서 아이디어 브레인스토밍을 주도한다.', 'I', 'likert7', false, '{"btType":"I","mbtiTags":["N","E"],"darkTag":null}'::jsonb),
  ('bt_i_07', 'behavior_type', 'A', 16, '새로운 사람을 만나면 공통점을 빠르게 찾아 대화를 이어간다.', 'I', 'likert7', false, '{"btType":"I","mbtiTags":["E"],"darkTag":null}'::jsonb),
  ('bt_i_08', 'behavior_type', 'A', 17, '업무 관계를 넘어 인간적 유대를 쌓는 것이 자연스럽다.', 'I', 'likert7', false, '{"btType":"I","mbtiTags":["F","E"],"darkTag":null}'::jsonb),
  ('bt_i_09', 'behavior_type', 'A', 18, '딱딱한 분위기의 회의보다 자유로운 토론이 효과적이라고 느낀다.', 'I', 'likert7', false, '{"btType":"I","mbtiTags":["P"],"darkTag":null}'::jsonb),
  ('bt_i_10', 'behavior_type', 'A', 19, '네트워킹을 의식적으로 하지 않아도 인맥이 자연스럽게 넓어진다.', 'I', 'likert7', false, '{"btType":"I","mbtiTags":["E"],"darkTag":null}'::jsonb),
  ('bt_s_01', 'behavior_type', 'A', 20, '주변 사람이 어려움을 겪으면 내 일을 미뤄서라도 도와주는 편이다.', 'S', 'likert7', false, '{"btType":"S","mbtiTags":["F"],"darkTag":null}'::jsonb),
  ('bt_s_02', 'behavior_type', 'A', 21, '급한 변화가 생겨도 차분하게 대응하려고 노력한다.', 'S', 'likert7', false, '{"btType":"S","mbtiTags":["S"],"darkTag":null}'::jsonb),
  ('bt_s_03', 'behavior_type', 'A', 22, '팀 내 갈등이 있으면 양쪽 이야기를 다 들은 뒤 조율하는 편이다.', 'S', 'likert7', false, '{"btType":"S","mbtiTags":["F","S"],"darkTag":null}'::jsonb),
  ('bt_s_04', 'behavior_type', 'A', 23, '변화보다 안정적이고 예측 가능한 환경을 선호한다.', 'S', 'likert7', false, '{"btType":"S","mbtiTags":["J"],"darkTag":null}'::jsonb),
  ('bt_s_05', 'behavior_type', 'A', 24, '약속을 반드시 지키며, 그것이 장기적 신뢰의 기반이라고 믿는다.', 'S', 'likert7', false, '{"btType":"S","mbtiTags":["J"],"darkTag":null}'::jsonb),
  ('bt_s_06', 'behavior_type', 'A', 25, '반복적인 업무라도 꾸준히 수행하는 것이 크게 힘들지 않다.', 'S', 'likert7', false, '{"btType":"S","mbtiTags":["S"],"darkTag":null}'::jsonb),
  ('bt_s_07', 'behavior_type', 'A', 26, '다른 사람의 감정을 상하게 하지 않으려 표현을 신중히 고른다.', 'S', 'likert7', false, '{"btType":"S","mbtiTags":["F"],"darkTag":null}'::jsonb),
  ('bt_s_08', 'behavior_type', 'A', 27, '급격한 조직 변화(인수합병, 구조조정 등)에서 스트레스를 크게 받는다.', 'S', 'likert7', true, '{"btType":"S","mbtiTags":["J"],"darkTag":null}'::jsonb),
  ('bt_s_09', 'behavior_type', 'A', 28, '묵묵히 맡은 바를 해내는 것이 나의 기여 방식이다.', 'S', 'likert7', false, '{"btType":"S","mbtiTags":["S"],"darkTag":null}'::jsonb),
  ('bt_s_10', 'behavior_type', 'A', 29, '새 프로젝트 시작 시 팀원 모두가 동의할 때까지 시간을 갖는 편이다.', 'S', 'likert7', false, '{"btType":"S","mbtiTags":["F"],"darkTag":null}'::jsonb),
  ('bt_c_01', 'behavior_type', 'A', 30, '결정을 내리기 전 가능한 한 많은 데이터를 수집하고 검토한다.', 'C', 'likert7', false, '{"btType":"C","mbtiTags":["T","S"],"darkTag":null}'::jsonb),
  ('bt_c_02', 'behavior_type', 'A', 31, '절차와 규칙을 어기는 것은 거의 하지 않는다.', 'C', 'likert7', false, '{"btType":"C","mbtiTags":["J"],"darkTag":null}'::jsonb),
  ('bt_c_03', 'behavior_type', 'A', 32, '결과물을 제출하기 전 오류를 여러 번 확인하는 편이다.', 'C', 'likert7', false, '{"btType":"C","mbtiTags":["J","T"],"darkTag":null}'::jsonb),
  ('bt_c_04', 'behavior_type', 'A', 33, '세부 지침 없이 진행되는 프로젝트에서 불안감을 느낀다.', 'C', 'likert7', true, '{"btType":"C","mbtiTags":["J"],"darkTag":null}'::jsonb),
  ('bt_c_05', 'behavior_type', 'A', 34, '보고서는 내용뿐 아니라 구조와 형식까지 통일되어야 한다고 생각한다.', 'C', 'likert7', false, '{"btType":"C","mbtiTags":["J","T"],"darkTag":null}'::jsonb),
  ('bt_c_06', 'behavior_type', 'A', 35, '수치나 그래프 등 객관적 근거가 있을 때 안심된다.', 'C', 'likert7', false, '{"btType":"C","mbtiTags":["T"],"darkTag":null}'::jsonb),
  ('bt_c_07', 'behavior_type', 'A', 36, '작업 프로세스를 표준화하면 효율이 크게 올라간다고 믿는다.', 'C', 'likert7', false, '{"btType":"C","mbtiTags":["J"],"darkTag":null}'::jsonb),
  ('bt_c_08', 'behavior_type', 'A', 37, '품질 기준에 미달하면 마감이 늦더라도 수정을 선택한다.', 'C', 'likert7', false, '{"btType":"C","mbtiTags":["J"],"darkTag":null}'::jsonb),
  ('bt_c_09', 'behavior_type', 'A', 38, '세부 일정표를 만들어 진행 상황을 체계적으로 추적한다.', 'C', 'likert7', false, '{"btType":"C","mbtiTags":["J"],"darkTag":null}'::jsonb),
  ('bt_c_10', 'behavior_type', 'A', 39, '모든 세부 사항이 정리되지 않으면 프로젝트를 시작하기 어렵다.', 'C', 'likert7', true, '{"btType":"C","mbtiTags":["J"],"darkTag":null}'::jsonb);
