INSERT INTO public.hit_questions (id, module, test_type, question_index, question_text, sub_domain, response_type, reverse_scored, scoring_key)
VALUES
  ('ch_c01', 'character_core', 'A', 0, '한 번 한 약속은 상황이 바뀌어도 지키려고 노력한다.', 'integrity', 'likert7', false, '{"area":"integrity","subDomain":"conscience","darkTag":null}'::jsonb),
  ('ch_c02', 'character_core', 'A', 1, '하기 싫은 일도 해야 할 때는 미루지 않고 처리한다.', 'integrity', 'likert7', false, '{"area":"integrity","subDomain":"self_discipline","darkTag":null}'::jsonb),
  ('ch_c03', 'character_core', 'A', 2, '장기적 목표를 위해 당장의 즐거움을 참을 수 있다.', 'integrity', 'likert7', false, '{"area":"integrity","subDomain":"self_discipline","darkTag":null}'::jsonb),
  ('ch_c04', 'character_core', 'A', 3, '결과물의 품질이 기대에 미치지 못하면 제출하기 어렵다.', 'integrity', 'likert7', false, '{"area":"integrity","subDomain":"perfectionism","darkTag":null}'::jsonb),
  ('ch_c05', 'character_core', 'A', 4, '실수했을 때 변명보다 솔직한 인정이 먼저다.', 'integrity', 'likert7', false, '{"area":"integrity","subDomain":"conscience","darkTag":null}'::jsonb),
  ('ch_c06', 'character_core', 'A', 5, '마감이 다가와야 움직이는 경향이 있다.', 'integrity', 'likert7', true, '{"area":"integrity","subDomain":"self_discipline","darkTag":null}'::jsonb),
  ('ch_c07', 'character_core', 'A', 6, '계획한 루틴을 꾸준히 유지하는 편이다.', 'integrity', 'likert7', false, '{"area":"integrity","subDomain":"self_discipline","darkTag":null}'::jsonb),
  ('ch_c08', 'character_core', 'A', 7, '결과를 위해 과정의 룰을 어기는 것은 용납할 수 있다.', 'integrity', 'likert7', true, '{"area":"integrity","subDomain":"conscience","darkTag":"MK"}'::jsonb),
  ('ch_r01', 'character_core', 'A', 8, '동료가 힘들어 보이면 먼저 말을 건넨다.', 'relational', 'likert7', false, '{"area":"relational","subDomain":"warmth","darkTag":null}'::jsonb),
  ('ch_r02', 'character_core', 'A', 9, '상대방의 표정 변화를 민감하게 알아차린다.', 'relational', 'likert7', false, '{"area":"relational","subDomain":"sensitivity","darkTag":null}'::jsonb),
  ('ch_r03', 'character_core', 'A', 10, '많은 사람 앞에서 자기 의견을 말하는 것이 어렵지 않다.', 'relational', 'likert7', false, '{"area":"relational","subDomain":"social_boldness","darkTag":null}'::jsonb),
  ('ch_r04', 'character_core', 'A', 11, '누군가 기뻐하면 나도 덩달아 기분이 좋아진다.', 'relational', 'likert7', false, '{"area":"relational","subDomain":"warmth","darkTag":null}'::jsonb),
  ('ch_r05', 'character_core', 'A', 12, '불합리한 상황에서 이의를 제기하는 편이다.', 'relational', 'likert7', false, '{"area":"relational","subDomain":"social_boldness","darkTag":null}'::jsonb),
  ('ch_r06', 'character_core', 'A', 13, '타인의 감정에 별로 관심이 없는 편이다.', 'relational', 'likert7', true, '{"area":"relational","subDomain":"warmth","darkTag":"PP"}'::jsonb),
  ('ch_r07', 'character_core', 'A', 14, '처음 보는 그룹에서 대화를 시작하는 것이 어렵다.', 'relational', 'likert7', true, '{"area":"relational","subDomain":"social_boldness","darkTag":null}'::jsonb),
  ('ch_r08', 'character_core', 'A', 15, '다른 사람이 비판받는 것을 보면 내 일처럼 마음이 아프다.', 'relational', 'likert7', false, '{"area":"relational","subDomain":"sensitivity","darkTag":null}'::jsonb),
  ('ch_e01', 'character_core', 'A', 16, '여러 일이 겹치면 압도당하는 느낌이 든다.', 'emotional', 'likert7', true, '{"area":"emotional","subDomain":"tension","darkTag":null}'::jsonb),
  ('ch_e02', 'character_core', 'A', 17, '어려운 상황에서도 좋은 면을 찾으려고 한다.', 'emotional', 'likert7', false, '{"area":"emotional","subDomain":"optimism","darkTag":null}'::jsonb),
  ('ch_e03', 'character_core', 'A', 18, '화가 나도 감정을 조절하여 상황에 맞게 표현할 수 있다.', 'emotional', 'likert7', false, '{"area":"emotional","subDomain":"control","darkTag":null}'::jsonb),
  ('ch_e04', 'character_core', 'A', 19, '실패해도 "다음에는 잘 될 것"이라고 생각하는 편이다.', 'emotional', 'likert7', false, '{"area":"emotional","subDomain":"optimism","darkTag":null}'::jsonb),
  ('ch_e05', 'character_core', 'A', 20, '작은 실수에도 오래 신경이 쓰인다.', 'emotional', 'likert7', true, '{"area":"emotional","subDomain":"tension","darkTag":null}'::jsonb),
  ('ch_e06', 'character_core', 'A', 21, '스트레스가 쌓여도 업무 품질을 유지하려고 노력한다.', 'emotional', 'likert7', false, '{"area":"emotional","subDomain":"control","darkTag":null}'::jsonb),
  ('ch_e07', 'character_core', 'A', 22, '아침에 일어나면 오늘 하루가 기대되는 편이다.', 'emotional', 'likert7', false, '{"area":"emotional","subDomain":"optimism","darkTag":null}'::jsonb),
  ('ch_e08', 'character_core', 'A', 23, '충동적으로 후회할 말을 한 경험이 종종 있다.', 'emotional', 'likert7', true, '{"area":"emotional","subDomain":"control","darkTag":null}'::jsonb),
  ('ch_x01', 'character_core', 'A', 24, '아무도 보지 않아도 올바른 행동을 선택하는 편이다.', 'ethics', 'likert7', false, '{"area":"ethics","subDomain":"conscience","darkTag":null}'::jsonb),
  ('ch_x02', 'character_core', 'A', 25, '주변의 반대가 있어도 옳다고 믿는 바를 지킨다.', 'ethics', 'likert7', false, '{"area":"ethics","subDomain":"independence","darkTag":null}'::jsonb),
  ('ch_x03', 'character_core', 'A', 26, '이익이 되더라도 비윤리적인 방법은 사용하지 않는다.', 'ethics', 'likert7', false, '{"area":"ethics","subDomain":"conscience","darkTag":null}'::jsonb),
  ('ch_x04', 'character_core', 'A', 27, '다수의 의견에 동조하기보다 자기 판단을 따르는 편이다.', 'ethics', 'likert7', false, '{"area":"ethics","subDomain":"independence","darkTag":null}'::jsonb),
  ('ch_x05', 'character_core', 'A', 28, '처음 만난 사람의 친절에 숨은 의도가 있을 수 있다고 생각한다.', 'ethics', 'likert7', true, '{"area":"ethics","subDomain":"suspicion","darkTag":"MK"}'::jsonb),
  ('ch_x06', 'character_core', 'A', 29, '사람은 기본적으로 선하다고 믿는다.', 'ethics', 'likert7', false, '{"area":"ethics","subDomain":"suspicion","darkTag":null}'::jsonb),
  ('ch_x07', 'character_core', 'A', 30, '상사의 지시라도 납득이 안 되면 의문을 제기한다.', 'ethics', 'likert7', false, '{"area":"ethics","subDomain":"independence","darkTag":null}'::jsonb),
  ('ch_x08', 'character_core', 'A', 31, '다른 사람의 말을 쉽게 믿지 않는 편이다.', 'ethics', 'likert7', true, '{"area":"ethics","subDomain":"suspicion","darkTag":"MK"}'::jsonb),
  ('ch_g01', 'character_core', 'A', 32, '나와 완전히 다른 의견도 일단 들어보려 한다.', 'growth', 'likert7', false, '{"area":"growth","subDomain":"openness","darkTag":null}'::jsonb),
  ('ch_g02', 'character_core', 'A', 33, '안전한 선택보다 흥미로운 도전을 선호한다.', 'growth', 'likert7', false, '{"area":"growth","subDomain":"adventure","darkTag":null}'::jsonb),
  ('ch_g03', 'character_core', 'A', 34, '새로운 분야를 공부하면 시간 가는 줄 모른다.', 'growth', 'likert7', false, '{"area":"growth","subDomain":"intellect","darkTag":null}'::jsonb),
  ('ch_g04', 'character_core', 'A', 35, '기존 방식을 바꾸는 것에 거부감이 적다.', 'growth', 'likert7', false, '{"area":"growth","subDomain":"openness","darkTag":null}'::jsonb),
  ('ch_g05', 'character_core', 'A', 36, '실패 가능성이 있어도 시도해보는 것이 낫다.', 'growth', 'likert7', false, '{"area":"growth","subDomain":"adventure","darkTag":null}'::jsonb),
  ('ch_g06', 'character_core', 'A', 37, '"왜?"라는 질문을 자주 던지는 편이다.', 'growth', 'likert7', false, '{"area":"growth","subDomain":"intellect","darkTag":null}'::jsonb),
  ('ch_g07', 'character_core', 'A', 38, '예측 가능한 일상이 편하고 좋다.', 'growth', 'likert7', true, '{"area":"growth","subDomain":"adventure","darkTag":null}'::jsonb),
  ('ch_g08', 'character_core', 'A', 39, '전공이나 업무와 무관한 분야도 자주 탐색한다.', 'growth', 'likert7', false, '{"area":"growth","subDomain":"intellect","darkTag":null}'::jsonb);
