INSERT INTO public.hit_questions (id, module, test_type, question_index, question_text, sub_domain, response_type, reverse_scored, scoring_key)
VALUES
  ('ap_r01', 'aptitude_core', 'A', 0, '물건을 직접 만들거나 조립하는 작업이 즐겁다.', 'R', 'likert7', false, '{"hollandType":"R","discCross":["S"],"mbtiCross":["S"]}'::jsonb),
  ('ap_r02', 'aptitude_core', 'A', 1, '체력을 쓰거나 야외에서 하는 활동에 끌린다.', 'R', 'likert7', false, '{"hollandType":"R","discCross":["D"],"mbtiCross":["S"]}'::jsonb),
  ('ap_r03', 'aptitude_core', 'A', 2, '도구나 장비를 다루는 것에 흥미가 있다.', 'R', 'likert7', false, '{"hollandType":"R","discCross":["C"],"mbtiCross":["S"]}'::jsonb),
  ('ap_r04', 'aptitude_core', 'A', 3, '결과물이 눈에 보이는 일이 추상적 업무보다 만족스럽다.', 'R', 'likert7', false, '{"hollandType":"R","discCross":["S"],"mbtiCross":["S"]}'::jsonb),
  ('ap_r05', 'aptitude_core', 'A', 4, '기술적 문제를 직접 손으로 해결하는 것이 재미있다.', 'R', 'likert7', false, '{"hollandType":"R","discCross":["D"],"mbtiCross":["S","T"]}'::jsonb),
  ('ap_i01', 'aptitude_core', 'A', 5, '복잡한 문제의 원인을 파고드는 것이 즐겁다.', 'I', 'likert7', false, '{"hollandType":"I","discCross":["C"],"mbtiCross":["N","T"]}'::jsonb),
  ('ap_i02', 'aptitude_core', 'A', 6, '데이터를 분석하여 패턴을 발견하는 일에 흥미가 있다.', 'I', 'likert7', false, '{"hollandType":"I","discCross":["C"],"mbtiCross":["N","T"]}'::jsonb),
  ('ap_i03', 'aptitude_core', 'A', 7, '전문 자료나 논문을 읽으면서 시간 가는 줄 모른다.', 'I', 'likert7', false, '{"hollandType":"I","discCross":["C"],"mbtiCross":["N"]}'::jsonb),
  ('ap_i04', 'aptitude_core', 'A', 8, '"왜 그럴까?"에서 출발하는 프로젝트가 끌린다.', 'I', 'likert7', false, '{"hollandType":"I","discCross":["C"],"mbtiCross":["N"]}'::jsonb),
  ('ap_i05', 'aptitude_core', 'A', 9, '가설을 세우고 검증하는 과정 자체가 보람 있다.', 'I', 'likert7', false, '{"hollandType":"I","discCross":["C"],"mbtiCross":["N","T"]}'::jsonb),
  ('ap_a01', 'aptitude_core', 'A', 10, '무언가를 새롭게 만들어내는 과정이 가장 즐겁다.', 'A', 'likert7', false, '{"hollandType":"A","discCross":["I"],"mbtiCross":["N","P"]}'::jsonb),
  ('ap_a02', 'aptitude_core', 'A', 11, '글, 그림, 영상, 음악 등 표현 활동에 끌린다.', 'A', 'likert7', false, '{"hollandType":"A","discCross":["I"],"mbtiCross":["N","F"]}'::jsonb),
  ('ap_a03', 'aptitude_core', 'A', 12, '정해진 틀보다 자유로운 방식의 작업을 선호한다.', 'A', 'likert7', false, '{"hollandType":"A","discCross":["I"],"mbtiCross":["N","P"]}'::jsonb),
  ('ap_a04', 'aptitude_core', 'A', 13, '일상에서 디자인이나 미적 요소에 관심이 많다.', 'A', 'likert7', false, '{"hollandType":"A","discCross":["I"],"mbtiCross":["N","S"]}'::jsonb),
  ('ap_a05', 'aptitude_core', 'A', 14, '콘텐츠(영상, 글, 이미지)를 기획·제작하는 것이 재미있다.', 'A', 'likert7', false, '{"hollandType":"A","discCross":["I"],"mbtiCross":["N"]}'::jsonb),
  ('ap_s01', 'aptitude_core', 'A', 15, '다른 사람의 문제를 함께 해결해주는 것이 보람차다.', 'S', 'likert7', false, '{"hollandType":"S","discCross":["S"],"mbtiCross":["F"]}'::jsonb),
  ('ap_s02', 'aptitude_core', 'A', 16, '가르치거나 설명하는 일에 자연스러운 즐거움이 있다.', 'S', 'likert7', false, '{"hollandType":"S","discCross":["I"],"mbtiCross":["F","E"]}'::jsonb),
  ('ap_s03', 'aptitude_core', 'A', 17, '누군가의 성장을 돕는 것이 가장 큰 동기부여다.', 'S', 'likert7', false, '{"hollandType":"S","discCross":["S"],"mbtiCross":["F"]}'::jsonb),
  ('ap_s04', 'aptitude_core', 'A', 18, '상담이나 코칭 활동에 관심이 있다.', 'S', 'likert7', false, '{"hollandType":"S","discCross":["S"],"mbtiCross":["F","I"]}'::jsonb),
  ('ap_s05', 'aptitude_core', 'A', 19, '팀의 분위기와 구성원의 감정을 살피는 역할에 끌린다.', 'S', 'likert7', false, '{"hollandType":"S","discCross":["S"],"mbtiCross":["F"]}'::jsonb),
  ('ap_e01', 'aptitude_core', 'A', 20, '사람들을 설득하여 함께 움직이게 하는 것이 즐겁다.', 'E', 'likert7', false, '{"hollandType":"E","discCross":["D"],"mbtiCross":["E","T"]}'::jsonb),
  ('ap_e02', 'aptitude_core', 'A', 21, '사업 아이디어를 구상하고 실현하는 과정에 끌린다.', 'E', 'likert7', false, '{"hollandType":"E","discCross":["D"],"mbtiCross":["N","J"]}'::jsonb),
  ('ap_e03', 'aptitude_core', 'A', 22, '협상이나 거래 상황에서 흥분되는 에너지를 느낀다.', 'E', 'likert7', false, '{"hollandType":"E","discCross":["D"],"mbtiCross":["E","T"]}'::jsonb),
  ('ap_e04', 'aptitude_core', 'A', 23, '프로젝트의 방향을 정하고 이끄는 역할이 자연스럽다.', 'E', 'likert7', false, '{"hollandType":"E","discCross":["D"],"mbtiCross":["E","J"]}'::jsonb),
  ('ap_e05', 'aptitude_core', 'A', 24, '시장 트렌드를 분석하고 기회를 포착하는 일에 관심이 있다.', 'E', 'likert7', false, '{"hollandType":"E","discCross":["D"],"mbtiCross":["N","T"]}'::jsonb),
  ('ap_c01', 'aptitude_core', 'A', 25, '데이터를 정리하고 분류하는 작업이 편안하다.', 'C', 'likert7', false, '{"hollandType":"C","discCross":["C"],"mbtiCross":["S","J"]}'::jsonb),
  ('ap_c02', 'aptitude_core', 'A', 26, '절차와 규칙에 따라 체계적으로 일하는 것이 좋다.', 'C', 'likert7', false, '{"hollandType":"C","discCross":["C"],"mbtiCross":["S","J"]}'::jsonb),
  ('ap_c03', 'aptitude_core', 'A', 27, '숫자나 재무 관련 업무에 관심이 있다.', 'C', 'likert7', false, '{"hollandType":"C","discCross":["C"],"mbtiCross":["T","J"]}'::jsonb),
  ('ap_c04', 'aptitude_core', 'A', 28, '문서 관리, 기록 유지 같은 일이 성가시지 않다.', 'C', 'likert7', false, '{"hollandType":"C","discCross":["C"],"mbtiCross":["S","J"]}'::jsonb),
  ('ap_c05', 'aptitude_core', 'A', 29, '표준화된 프로세스를 만들고 관리하는 것에 흥미가 있다.', 'C', 'likert7', false, '{"hollandType":"C","discCross":["C"],"mbtiCross":["J"]}'::jsonb);
