INSERT INTO public.hit_questions (id, module, test_type, question_index, question_text, sub_domain, response_type, reverse_scored, scoring_key)
VALUES
  ('chx_pf01', 'character_deep', 'A', 0, '사소한 오류도 눈에 띄어서 그냥 넘기기 힘들다.', 'perfectionism', 'likert7', false, '{"subscale":"perfectionism","darkTag":null}'::jsonb),
  ('chx_pf02', 'character_deep', 'A', 1, '80점짜리를 빨리 내는 것보다 100점짜리를 늦게 내는 것이 낫다.', 'perfectionism', 'likert7', false, '{"subscale":"perfectionism","darkTag":null}'::jsonb),
  ('chx_pf03', 'character_deep', 'A', 2, '남들은 괜찮다고 하지만 내 기준에는 부족하다고 느낄 때가 많다.', 'perfectionism', 'likert7', true, '{"subscale":"perfectionism","darkTag":null}'::jsonb),
  ('chx_pf04', 'character_deep', 'A', 3, '완벽하지 않으면 시작하지 않는 편이다.', 'perfectionism', 'likert7', true, '{"subscale":"perfectionism","darkTag":null}'::jsonb),
  ('chx_pf05', 'character_deep', 'A', 4, '작업 결과에 대한 내 기준이 동료들보다 높다고 느낀다.', 'perfectionism', 'likert7', false, '{"subscale":"perfectionism","darkTag":"NR"}'::jsonb),
  ('chx_sn01', 'character_deep', 'A', 5, '영화나 책에서 슬픈 장면에 쉽게 감정이입된다.', 'sensitivity', 'likert7', false, '{"subscale":"sensitivity","darkTag":null}'::jsonb),
  ('chx_sn02', 'character_deep', 'A', 6, '분위기나 감정의 미세한 변화를 잘 포착한다.', 'sensitivity', 'likert7', false, '{"subscale":"sensitivity","darkTag":null}'::jsonb),
  ('chx_sn03', 'character_deep', 'A', 7, '감정적 상황에서도 별로 동요하지 않는 편이다.', 'sensitivity', 'likert7', true, '{"subscale":"sensitivity","darkTag":"PP"}'::jsonb),
  ('chx_sn04', 'character_deep', 'A', 8, '타인의 고통에 공감하는 것이 자연스럽다.', 'sensitivity', 'likert7', false, '{"subscale":"sensitivity","darkTag":null}'::jsonb),
  ('chx_tn01', 'character_deep', 'A', 9, '일이 잘 풀리지 않으면 쉽게 초조해진다.', 'tension', 'likert7', true, '{"subscale":"tension","darkTag":null}'::jsonb),
  ('chx_tn02', 'character_deep', 'A', 10, '중요한 발표 전날 잠을 설치는 편이다.', 'tension', 'likert7', true, '{"subscale":"tension","darkTag":null}'::jsonb),
  ('chx_tn03', 'character_deep', 'A', 11, '불확실한 상황에서도 비교적 편안하게 지낼 수 있다.', 'tension', 'likert7', false, '{"subscale":"tension","darkTag":"PP"}'::jsonb),
  ('chx_tn04', 'character_deep', 'A', 12, '미래에 대한 걱정이 현재의 즐거움을 방해할 때가 있다.', 'tension', 'likert7', true, '{"subscale":"tension","darkTag":null}'::jsonb),
  ('chx_wm01', 'character_deep', 'A', 13, '처음 만난 사람에게도 따뜻하게 다가가는 편이다.', 'warmth', 'likert7', false, '{"subscale":"warmth","darkTag":null}'::jsonb),
  ('chx_wm02', 'character_deep', 'A', 14, '사람들이 나를 만나면 편안해한다는 이야기를 듣는다.', 'warmth', 'likert7', false, '{"subscale":"warmth","darkTag":null}'::jsonb),
  ('chx_wm03', 'character_deep', 'A', 15, '업무 관계에서도 인간적 유대가 중요하다고 생각한다.', 'warmth', 'likert7', false, '{"subscale":"warmth","darkTag":null}'::jsonb),
  ('chx_sb01', 'character_deep', 'A', 16, '지위가 높은 사람 앞에서도 당당하게 이야기할 수 있다.', 'social_boldness', 'likert7', false, '{"subscale":"social_boldness","darkTag":null}'::jsonb),
  ('chx_sb02', 'character_deep', 'A', 17, '주목받는 상황이 부담보다 자연스럽다.', 'social_boldness', 'likert7', false, '{"subscale":"social_boldness","darkTag":"NR"}'::jsonb),
  ('chx_sb03', 'character_deep', 'A', 18, '자신의 성과를 적극적으로 어필할 수 있다.', 'social_boldness', 'likert7', false, '{"subscale":"social_boldness","darkTag":"NR"}'::jsonb),
  ('chx_op01', 'character_deep', 'A', 19, '유머로 분위기를 전환하는 것에 능숙하다.', 'optimism', 'likert7', false, '{"subscale":"optimism","darkTag":null}'::jsonb),
  ('chx_op02', 'character_deep', 'A', 20, '힘든 시기도 결국 지나간다고 믿는다.', 'optimism', 'likert7', false, '{"subscale":"optimism","darkTag":null}'::jsonb),
  ('chx_op03', 'character_deep', 'A', 21, '일이 잘 안 되면 쉽게 의욕을 잃는다.', 'optimism', 'likert7', true, '{"subscale":"optimism","darkTag":null}'::jsonb),
  ('chx_ct01', 'character_deep', 'A', 22, '감정적으로 격앙되었을 때 먼저 심호흡하는 습관이 있다.', 'control', 'likert7', false, '{"subscale":"control","darkTag":null}'::jsonb),
  ('chx_ct02', 'character_deep', 'A', 23, '감정에 휩쓸려 중요한 결정을 잘못 내린 적이 있다.', 'control', 'likert7', true, '{"subscale":"control","darkTag":null}'::jsonb),
  ('chx_ct03', 'character_deep', 'A', 24, '압박 상황에서도 침착하게 판단할 수 있다고 자신한다.', 'control', 'likert7', false, '{"subscale":"control","darkTag":"PP"}'::jsonb),
  ('chx_sd01', 'character_deep', 'A', 25, '유혹이 있어도 스스로 정한 기준을 잘 지킨다.', 'self_discipline', 'likert7', false, '{"subscale":"self_discipline","darkTag":null}'::jsonb),
  ('chx_sd02', 'character_deep', 'A', 26, '운동, 학습 등 자기계발 루틴을 유지하고 있다.', 'self_discipline', 'likert7', false, '{"subscale":"self_discipline","darkTag":null}'::jsonb),
  ('chx_in01', 'character_deep', 'A', 27, '유행이나 트렌드에 크게 영향받지 않는다.', 'independence', 'likert7', false, '{"subscale":"independence","darkTag":null}'::jsonb),
  ('chx_in02', 'character_deep', 'A', 28, '다른 사람의 평가가 내 결정에 큰 영향을 미친다.', 'independence', 'likert7', true, '{"subscale":"independence","darkTag":null}'::jsonb),
  ('chx_in03', 'character_deep', 'A', 29, '혼자서도 결정을 내리고 책임질 수 있다.', 'independence', 'likert7', false, '{"subscale":"independence","darkTag":null}'::jsonb),
  ('chx_su01', 'character_deep', 'A', 30, '협력 제안을 받으면 상대방의 이익을 먼저 따져본다.', 'suspicion', 'likert7', true, '{"subscale":"suspicion","darkTag":"MK"}'::jsonb),
  ('chx_su02', 'character_deep', 'A', 31, '뒤에서 나에 대해 이야기한다고 느낄 때가 있다.', 'suspicion', 'likert7', true, '{"subscale":"suspicion","darkTag":null}'::jsonb),
  ('chx_su03', 'character_deep', 'A', 32, '새로운 사람도 일단 신뢰하고 보는 편이다.', 'suspicion', 'likert7', false, '{"subscale":"suspicion","darkTag":null}'::jsonb),
  ('chx_op2_01', 'character_deep', 'A', 33, '익숙하지 않은 문화나 관습에 대해 호기심이 크다.', 'openness', 'likert7', false, '{"subscale":"openness","darkTag":null}'::jsonb),
  ('chx_op2_02', 'character_deep', 'A', 34, '다양한 배경의 사람과 일하는 것이 즐겁다.', 'openness', 'likert7', false, '{"subscale":"openness","darkTag":null}'::jsonb),
  ('chx_op2_03', 'character_deep', 'A', 35, '변화가 많은 환경이 지루한 환경보다 낫다.', 'openness', 'likert7', false, '{"subscale":"openness","darkTag":null}'::jsonb),
  ('chx_op2_04', 'character_deep', 'A', 36, '자기 생각과 다른 정보는 무시하는 경향이 있다.', 'openness', 'likert7', true, '{"subscale":"openness","darkTag":null}'::jsonb),
  ('chx_ad01', 'character_deep', 'A', 37, '해본 적 없는 일에 지원하는 것이 두렵지 않다.', 'adventure', 'likert7', false, '{"subscale":"adventure","darkTag":null}'::jsonb),
  ('chx_ad02', 'character_deep', 'A', 38, '안정적인 직장보다 도전적인 환경에 끌린다.', 'adventure', 'likert7', false, '{"subscale":"adventure","darkTag":null}'::jsonb),
  ('chx_ad03', 'character_deep', 'A', 39, '위험 부담이 큰 결정도 과감하게 내릴 수 있다.', 'adventure', 'likert7', false, '{"subscale":"adventure","darkTag":"SP"}'::jsonb),
  ('chx_iq01', 'character_deep', 'A', 40, '복잡한 문제를 파고드는 것이 스트레스가 아니라 즐거움이다.', 'intellect', 'likert7', false, '{"subscale":"intellect","darkTag":null}'::jsonb),
  ('chx_iq02', 'character_deep', 'A', 41, '단순 반복 업무를 오래 하면 지적으로 갈증을 느낀다.', 'intellect', 'likert7', false, '{"subscale":"intellect","darkTag":null}'::jsonb),
  ('chx_iq03', 'character_deep', 'A', 42, '배움에 대한 욕구가 나이와 무관하게 강하다.', 'intellect', 'likert7', false, '{"subscale":"intellect","darkTag":null}'::jsonb),
  ('chx_con01', 'character_deep', 'A', 43, '양심에 어긋나는 일을 하면 오래 마음이 불편하다.', 'conscience', 'likert7', false, '{"subscale":"conscience","darkTag":null}'::jsonb),
  ('chx_val01', 'character_deep', 'A', 44, '나는 다른 사람을 한 번도 판단해본 적이 없다.', 'DECOY', 'likert7', false, '{"subscale":"DECOY","darkTag":null}'::jsonb);
