INSERT INTO public.hit_questions (id, module, test_type, question_index, question_text, sub_domain, response_type, reverse_scored, scoring_key)
VALUES
  ('apx_r01', 'aptitude_deep', 'A', 0, '기계나 장비의 작동 원리를 빠르게 파악할 수 있다.', 'R', 'likert7', false, '{"hollandType":"R"}'::jsonb),
  ('apx_r02', 'aptitude_deep', 'A', 1, '물리적 공간을 효율적으로 구성하는 것에 자신 있다.', 'R', 'likert7', false, '{"hollandType":"R"}'::jsonb),
  ('apx_r03', 'aptitude_deep', 'A', 2, '손재주가 필요한 작업에서 남들보다 빠르다.', 'R', 'likert7', false, '{"hollandType":"R"}'::jsonb),
  ('apx_r04', 'aptitude_deep', 'A', 3, '안전 규정과 절차를 정확히 따르며 작업할 수 있다.', 'R', 'likert7', false, '{"hollandType":"R"}'::jsonb),
  ('apx_r05', 'aptitude_deep', 'A', 4, '실물을 다루는 프로젝트를 처음부터 끝까지 완수할 수 있다.', 'R', 'likert7', false, '{"hollandType":"R"}'::jsonb),
  ('apx_i01', 'aptitude_deep', 'A', 5, '통계나 수치 데이터를 해석하는 것에 자신 있다.', 'I', 'likert7', false, '{"hollandType":"I"}'::jsonb),
  ('apx_i02', 'aptitude_deep', 'A', 6, '연구 방법론을 이해하고 적용할 수 있다.', 'I', 'likert7', false, '{"hollandType":"I"}'::jsonb),
  ('apx_i03', 'aptitude_deep', 'A', 7, '복잡한 정보를 체계적으로 정리하는 능력이 있다.', 'I', 'likert7', false, '{"hollandType":"I"}'::jsonb),
  ('apx_i04', 'aptitude_deep', 'A', 8, '객관적 근거를 기반으로 결론을 도출할 수 있다.', 'I', 'likert7', false, '{"hollandType":"I"}'::jsonb),
  ('apx_i05', 'aptitude_deep', 'A', 9, '장기간 독립적으로 연구·분석 프로젝트를 수행할 수 있다.', 'I', 'likert7', false, '{"hollandType":"I"}'::jsonb),
  ('apx_a01', 'aptitude_deep', 'A', 10, '독창적인 아이디어를 자주 떠올리는 편이다.', 'A', 'likert7', false, '{"hollandType":"A"}'::jsonb),
  ('apx_a02', 'aptitude_deep', 'A', 11, '시각적으로 보기 좋게 정리하는 것에 자신 있다.', 'A', 'likert7', false, '{"hollandType":"A"}'::jsonb),
  ('apx_a03', 'aptitude_deep', 'A', 12, '스토리텔링이나 내러티브 구성 능력이 있다.', 'A', 'likert7', false, '{"hollandType":"A"}'::jsonb),
  ('apx_a04', 'aptitude_deep', 'A', 13, '디자인 도구(포토샵, 피그마, 영상 편집 등)를 다룰 수 있다.', 'A', 'likert7', false, '{"hollandType":"A"}'::jsonb),
  ('apx_a05', 'aptitude_deep', 'A', 14, '컨셉을 시각적/언어적으로 구체화하는 것에 자신 있다.', 'A', 'likert7', false, '{"hollandType":"A"}'::jsonb),
  ('apx_s01', 'aptitude_deep', 'A', 15, '갈등 상황에서 중재 역할을 효과적으로 할 수 있다.', 'S', 'likert7', false, '{"hollandType":"S"}'::jsonb),
  ('apx_s02', 'aptitude_deep', 'A', 16, '상대방의 감정 상태를 빠르게 파악할 수 있다.', 'S', 'likert7', false, '{"hollandType":"S"}'::jsonb),
  ('apx_s03', 'aptitude_deep', 'A', 17, '복잡한 개념을 쉽게 설명하는 능력이 있다.', 'S', 'likert7', false, '{"hollandType":"S"}'::jsonb),
  ('apx_s04', 'aptitude_deep', 'A', 18, '다양한 사람들과 신뢰 관계를 빠르게 형성한다.', 'S', 'likert7', false, '{"hollandType":"S"}'::jsonb),
  ('apx_s05', 'aptitude_deep', 'A', 19, '타인의 동기를 북돋우는 것에 자신 있다.', 'S', 'likert7', false, '{"hollandType":"S"}'::jsonb),
  ('apx_e01', 'aptitude_deep', 'A', 20, '다수 앞에서 설득력 있는 프레젠테이션을 할 수 있다.', 'E', 'likert7', false, '{"hollandType":"E"}'::jsonb),
  ('apx_e02', 'aptitude_deep', 'A', 21, '전략을 수립하고 실행 계획을 구체화할 수 있다.', 'E', 'likert7', false, '{"hollandType":"E"}'::jsonb),
  ('apx_e03', 'aptitude_deep', 'A', 22, '팀을 조직하고 역할을 배분하는 것에 자신 있다.', 'E', 'likert7', false, '{"hollandType":"E"}'::jsonb),
  ('apx_e04', 'aptitude_deep', 'A', 23, '예산과 자원을 효율적으로 관리할 수 있다.', 'E', 'likert7', false, '{"hollandType":"E"}'::jsonb),
  ('apx_e05', 'aptitude_deep', 'A', 24, '불확실한 상황에서도 의사결정을 내릴 수 있다.', 'E', 'likert7', false, '{"hollandType":"E"}'::jsonb),
  ('apx_c01', 'aptitude_deep', 'A', 25, '엑셀이나 스프레드시트를 능숙하게 다룰 수 있다.', 'C', 'likert7', false, '{"hollandType":"C"}'::jsonb),
  ('apx_c02', 'aptitude_deep', 'A', 26, '대량의 정보를 체계적으로 분류하고 관리할 수 있다.', 'C', 'likert7', false, '{"hollandType":"C"}'::jsonb),
  ('apx_c03', 'aptitude_deep', 'A', 27, '오류 없이 정확하게 데이터를 입력하고 처리할 수 있다.', 'C', 'likert7', false, '{"hollandType":"C"}'::jsonb),
  ('apx_c04', 'aptitude_deep', 'A', 28, '복잡한 일정이나 스케줄을 관리하는 것에 자신 있다.', 'C', 'likert7', false, '{"hollandType":"C"}'::jsonb),
  ('apx_c05', 'aptitude_deep', 'A', 29, '규정과 매뉴얼을 정확히 이해하고 적용할 수 있다.', 'C', 'likert7', false, '{"hollandType":"C"}'::jsonb);
