-- HIT Layer C: 122문항 (120 + 미끼 2)
-- HIT_C_Final.md 설계서 기반
-- 자동 생성: scripts/seed-hit-layer-c.js

DELETE FROM public.hit_questions WHERE module = 'layer_c';

INSERT INTO public.hit_questions
  (id, module, test_type, question_index, question_text, sub_domain, response_type, reverse_scored, scoring_key)
VALUES
  ('c_de01', 'layer_c', 'C', 0, '현재 직무에서 동료들이 나에게 자문을 구하는 영역이 있다.', 'domain_expertise', 'likert7', false, '{"section":"capital","subscale":"domain_expertise","crossTags":["SP:Strategic","BT:C"]}'::jsonb),
  ('c_de02', 'layer_c', 'C', 1, '내 전문 분야에서 최신 트렌드를 꾸준히 파악하고 있다.', 'domain_expertise', 'likert7', false, '{"section":"capital","subscale":"domain_expertise","crossTags":["PT:N","UF:intellect"]}'::jsonb),
  ('c_de03', 'layer_c', 'C', 2, '업무에서 남들이 쉽게 따라하기 어려운 나만의 노하우가 있다.', 'domain_expertise', 'likert7', false, '{"section":"capital","subscale":"domain_expertise","crossTags":["SP:Guard","BT:C"]}'::jsonb),
  ('c_de04', 'layer_c', 'C', 3, '현재 직무에서 3년 전보다 확실히 성장했다고 느낀다.', 'domain_expertise', 'likert7', false, '{"section":"capital","subscale":"domain_expertise","crossTags":["UF:self","CH:growth"]}'::jsonb),
  ('c_de05', 'layer_c', 'C', 4, '현재 역할에서 더 배울 것이 없다고 느낄 때가 있다.', 'domain_expertise', 'likert7', true, '{"section":"capital","subscale":"domain_expertise","crossTags":["SP:Breakthrough"]}'::jsonb),
  ('c_de06', 'layer_c', 'C', 5, '내 전문성이 현재 회사 밖에서도 통할 것이라 자신한다.', 'domain_expertise', 'likert7', false, '{"section":"capital","subscale":"domain_expertise","crossTags":["SP:Strategic","UF:self"]}'::jsonb),
  ('c_de07', 'layer_c', 'C', 6, '업무 관련 자격증, 교육, 인증을 지속적으로 취득하고 있다.', 'domain_expertise', 'likert7', false, '{"section":"capital","subscale":"domain_expertise","crossTags":["CH:integrity","PT:J"]}'::jsonb),
  ('c_de08', 'layer_c', 'C', 7, '내 업무 경험을 체계적으로 정리할 수 있다.', 'domain_expertise', 'likert7', false, '{"section":"capital","subscale":"domain_expertise","crossTags":["BT:C","PT:J"]}'::jsonb),
  ('c_de09', 'layer_c', 'C', 8, '같은 직무의 타사 담당자와 비교했을 때 경쟁력이 있다고 생각한다.', 'domain_expertise', 'likert7', false, '{"section":"capital","subscale":"domain_expertise","crossTags":["UF:self","BT:D"]}'::jsonb),
  ('c_de10', 'layer_c', 'C', 9, '내 전문 분야가 향후 5년간 시장에서 수요가 있을 것이라 본다.', 'domain_expertise', 'likert7', false, '{"section":"capital","subscale":"domain_expertise","crossTags":["PT:N","SP:Strategic"]}'::jsonb),
  ('c_ac01', 'layer_c', 'C', 10, '재직 중 수치로 증명할 수 있는 성과가 있다.', 'achievement', 'likert7', false, '{"section":"capital","subscale":"achievement","crossTags":["SP:Execution","BT:D"]}'::jsonb),
  ('c_ac02', 'layer_c', 'C', 11, '내가 주도한 프로젝트가 조직에 실질적 변화를 가져온 적이 있다.', 'achievement', 'likert7', false, '{"section":"capital","subscale":"achievement","crossTags":["BT:D","SP:Breakthrough"]}'::jsonb),
  ('c_ac03', 'layer_c', 'C', 12, '상사나 동료로부터 업무 성과에 대해 긍정적 피드백을 자주 받는다.', 'achievement', 'likert7', false, '{"section":"capital","subscale":"achievement","crossTags":["BT:I","UF:peer"]}'::jsonb),
  ('c_ac04', 'layer_c', 'C', 13, '기대 이상의 결과를 낸 경험이 이직 시 강력한 어필 포인트가 될 수 있다.', 'achievement', 'likert7', false, '{"section":"capital","subscale":"achievement","crossTags":["SP:Execution"]}'::jsonb),
  ('c_ac05', 'layer_c', 'C', 14, '내 성과를 객관적으로 설명하는 것이 어렵다.', 'achievement', 'likert7', true, '{"section":"capital","subscale":"achievement","crossTags":["BT:C_low","PT:I"]}'::jsonb),
  ('c_ac06', 'layer_c', 'C', 15, '실패한 프로젝트에서도 배운 점을 명확하게 말할 수 있다.', 'achievement', 'likert7', false, '{"section":"capital","subscale":"achievement","crossTags":["UF:trauma","CH:growth"]}'::jsonb),
  ('c_ac07', 'layer_c', 'C', 16, '업무에서 새로운 방법을 제안하고 실행해본 적이 있다.', 'achievement', 'likert7', false, '{"section":"capital","subscale":"achievement","crossTags":["PT:N","BT:D","SP:Creativity"]}'::jsonb),
  ('c_ac08', 'layer_c', 'C', 17, '조직 내에서 승진이나 보상으로 성과를 인정받은 경험이 있다.', 'achievement', 'likert7', false, '{"section":"capital","subscale":"achievement","crossTags":["BT:D"]}'::jsonb),
  ('c_ac09', 'layer_c', 'C', 18, '나의 성과가 팀 전체의 성과에 기여한 정도를 설명할 수 있다.', 'achievement', 'likert7', false, '{"section":"capital","subscale":"achievement","crossTags":["BT:I","SP:Harmony"]}'::jsonb),
  ('c_ac10', 'layer_c', 'C', 19, '현재 직무에서의 성과가 다른 산업에서도 의미 있을 것이라 생각한다.', 'achievement', 'likert7', false, '{"section":"capital","subscale":"achievement","crossTags":["SP:Strategic","PT:N"]}'::jsonb),
  ('c_re01', 'layer_c', 'C', 20, '직장 밖에서도 유지되는 업무 관련 인맥이 있다.', 'relational', 'likert7', false, '{"section":"capital","subscale":"relational","crossTags":["BT:I","PT:E"]}'::jsonb),
  ('c_re02', 'layer_c', 'C', 21, '필요할 때 조언을 구할 수 있는 업계 선배나 멘토가 있다.', 'relational', 'likert7', false, '{"section":"capital","subscale":"relational","crossTags":["UF:parent","BT:S"]}'::jsonb),
  ('c_re03', 'layer_c', 'C', 22, '이직 시 나를 추천해줄 수 있는 사람이 2명 이상 있다.', 'relational', 'likert7', false, '{"section":"capital","subscale":"relational","crossTags":["BT:I","SP:Interpersonal"]}'::jsonb),
  ('c_re04', 'layer_c', 'C', 23, '타 부서/타사 사람들과의 협업 경험이 풍부하다.', 'relational', 'likert7', false, '{"section":"capital","subscale":"relational","crossTags":["BT:I","PT:E"]}'::jsonb),
  ('c_re05', 'layer_c', 'C', 24, '업무 네트워크를 의식적으로 관리하는 편이다.', 'relational', 'likert7', false, '{"section":"capital","subscale":"relational","crossTags":["PT:J","BT:I"]}'::jsonb),
  ('c_re06', 'layer_c', 'C', 25, '같은 업계 종사자들과 정기적으로 교류한다.', 'relational', 'likert7', false, '{"section":"capital","subscale":"relational","crossTags":["BT:I","PT:E"]}'::jsonb),
  ('c_re07', 'layer_c', 'C', 26, '새로운 사람과 업무적 관계를 맺는 것에 거부감이 없다.', 'relational', 'likert7', false, '{"section":"capital","subscale":"relational","crossTags":["PT:E","CH:relational"]}'::jsonb),
  ('c_re08', 'layer_c', 'C', 27, '현재 직장의 인맥이 이직 후에도 도움이 될 것이라 생각한다.', 'relational', 'likert7', false, '{"section":"capital","subscale":"relational","crossTags":["SP:Interpersonal"]}'::jsonb),
  ('c_re09', 'layer_c', 'C', 28, '업계 커뮤니티, 세미나, 컨퍼런스 등에 참여한 경험이 있다.', 'relational', 'likert7', false, '{"section":"capital","subscale":"relational","crossTags":["PT:E","BT:I"]}'::jsonb),
  ('c_re10', 'layer_c', 'C', 29, '내 평판이 업계에서 긍정적이라고 생각한다.', 'relational', 'likert7', false, '{"section":"capital","subscale":"relational","crossTags":["UF:self","BT:I"]}'::jsonb),
  ('c_tr01', 'layer_c', 'C', 30, '업무 외 영역(기획, 프레젠테이션, 데이터 분석 등)에서도 강점이 있다.', 'transferable', 'likert7', false, '{"section":"capital","subscale":"transferable","crossTags":["SP:multi","PT:N"]}'::jsonb),
  ('c_tr02', 'layer_c', 'C', 31, '다양한 부서의 사람들과 효과적으로 소통할 수 있다.', 'transferable', 'likert7', false, '{"section":"capital","subscale":"transferable","crossTags":["BT:I","SP:Interpersonal"]}'::jsonb),
  ('c_tr03', 'layer_c', 'C', 32, '새로운 도구나 시스템을 배우는 데 거부감이 없다.', 'transferable', 'likert7', false, '{"section":"capital","subscale":"transferable","crossTags":["CH:growth","PT:P"]}'::jsonb),
  ('c_tr04', 'layer_c', 'C', 33, '외국어로 업무를 수행할 수 있다.', 'transferable', 'likert7', false, '{"section":"capital","subscale":"transferable","crossTags":["SP:Strategic"]}'::jsonb),
  ('c_tr05', 'layer_c', 'C', 34, '복잡한 문제를 구조화하여 해결하는 능력이 있다.', 'transferable', 'likert7', false, '{"section":"capital","subscale":"transferable","crossTags":["BT:C","SP:Analytical","PT:T"]}'::jsonb),
  ('c_tr06', 'layer_c', 'C', 35, '직무가 바뀌어도 활용할 수 있는 핵심 역량이 무엇인지 안다.', 'transferable', 'likert7', false, '{"section":"capital","subscale":"transferable","crossTags":["UF:self","SP:Strategic"]}'::jsonb),
  ('c_tr07', 'layer_c', 'C', 36, '프로젝트 관리(일정, 자원, 리스크)를 독립적으로 할 수 있다.', 'transferable', 'likert7', false, '{"section":"capital","subscale":"transferable","crossTags":["BT:D","PT:J","SP:Execution"]}'::jsonb),
  ('c_tr08', 'layer_c', 'C', 37, '데이터를 기반으로 의사결정하는 습관이 있다.', 'transferable', 'likert7', false, '{"section":"capital","subscale":"transferable","crossTags":["BT:C","PT:T","SP:Analytical"]}'::jsonb),
  ('c_tr09', 'layer_c', 'C', 38, '글이든 말이든, 내 생각을 논리적으로 전달하는 데 자신이 있다.', 'transferable', 'likert7', false, '{"section":"capital","subscale":"transferable","crossTags":["BT:I","BT:C","PT:T"]}'::jsonb),
  ('c_tr10', 'layer_c', 'C', 39, '현재 직무와 다른 분야에서도 일할 수 있다는 자신감이 있다.', 'transferable', 'likert7', false, '{"section":"capital","subscale":"transferable","crossTags":["UF:self","SP:Breakthrough"]}'::jsonb),
  ('c_pu01', 'layer_c', 'C', 40, '현재 직장에서 성장의 한계를 느낀다.', 'push', 'likert7', false, '{"section":"motivation","subscale":"push","crossTags":["CH:growth","SP:Breakthrough"]}'::jsonb),
  ('c_pu02', 'layer_c', 'C', 41, '내 역할과 능력 사이에 괴리가 있다고 느낀다.', 'push', 'likert7', false, '{"section":"motivation","subscale":"push","crossTags":["UF:self","SP:multi"]}'::jsonb),
  ('c_pu03', 'layer_c', 'C', 42, '현재 받는 보상이 내 기여도에 비해 부족하다고 느낀다.', 'push', 'likert7', false, '{"section":"motivation","subscale":"push","crossTags":["BT:D"]}'::jsonb),
  ('c_pu04', 'layer_c', 'C', 43, '직속 상사와의 관계에서 스트레스를 받는다.', 'push', 'likert7', false, '{"section":"motivation","subscale":"push","crossTags":["UF:parent","CH:emotional"]}'::jsonb),
  ('c_pu05', 'layer_c', 'C', 44, '조직 문화가 나와 맞지 않는다고 느낀다.', 'push', 'likert7', false, '{"section":"motivation","subscale":"push","crossTags":["CH:all","PT:all"]}'::jsonb),
  ('c_pu06', 'layer_c', 'C', 45, '현재 직무가 내 가치관과 점점 멀어지고 있다.', 'push', 'likert7', false, '{"section":"motivation","subscale":"push","crossTags":["CH:ethics","AP:mismatch"]}'::jsonb),
  ('c_pu07', 'layer_c', 'C', 46, '일과 삶의 균형이 지속적으로 무너지고 있다.', 'push', 'likert7', false, '{"section":"motivation","subscale":"push","crossTags":["CH:emotional"]}'::jsonb),
  ('c_pu08', 'layer_c', 'C', 47, '회사의 미래 전망이 불안하다.', 'push', 'likert7', false, '{"section":"motivation","subscale":"push","crossTags":["PT:N"]}'::jsonb),
  ('c_pu09', 'layer_c', 'C', 48, '같은 업무의 반복으로 동기가 떨어졌다.', 'push', 'likert7', false, '{"section":"motivation","subscale":"push","crossTags":["CH:growth","SP:Creativity"]}'::jsonb),
  ('c_pu10', 'layer_c', 'C', 49, '내 의견이 조직에서 반영되지 않는다고 느낀다.', 'push', 'likert7', false, '{"section":"motivation","subscale":"push","crossTags":["BT:D","PT:E"]}'::jsonb),
  ('c_pu11', 'layer_c', 'C', 50, '현재 역할에서 의미와 보람을 찾기 어렵다.', 'push', 'likert7', false, '{"section":"motivation","subscale":"push","crossTags":["AP:mismatch"]}'::jsonb),
  ('c_pu12', 'layer_c', 'C', 51, '건강이나 체력적으로 현재 업무를 지속하기 어렵다고 느낀다.', 'push', 'likert7', false, '{"section":"motivation","subscale":"push","crossTags":["CH:emotional"]}'::jsonb),
  ('c_pl01', 'layer_c', 'C', 52, '새로운 도전을 통해 더 성장하고 싶다.', 'pull', 'likert7', false, '{"section":"motivation","subscale":"pull","crossTags":["CH:growth","SP:Breakthrough"]}'::jsonb),
  ('c_pl02', 'layer_c', 'C', 53, '특정 산업이나 분야로 전환하고 싶은 명확한 목표가 있다.', 'pull', 'likert7', false, '{"section":"motivation","subscale":"pull","crossTags":["AP:direction","PT:J"]}'::jsonb),
  ('c_pl03', 'layer_c', 'C', 54, '더 높은 보상을 기대하고 있다.', 'pull', 'likert7', false, '{"section":"motivation","subscale":"pull","crossTags":["BT:D"]}'::jsonb),
  ('c_pl04', 'layer_c', 'C', 55, '내 가치관과 맞는 조직에서 일하고 싶다.', 'pull', 'likert7', false, '{"section":"motivation","subscale":"pull","crossTags":["CH:ethics"]}'::jsonb),
  ('c_pl05', 'layer_c', 'C', 56, '더 큰 규모 또는 더 민첩한 조직에서 일해보고 싶다.', 'pull', 'likert7', false, '{"section":"motivation","subscale":"pull","crossTags":["BT:D","BT:S"]}'::jsonb),
  ('c_pl06', 'layer_c', 'C', 57, '리더/매니저 역할로 성장하고 싶다.', 'pull', 'likert7', false, '{"section":"motivation","subscale":"pull","crossTags":["BT:D","SP:Execution"]}'::jsonb),
  ('c_pl07', 'layer_c', 'C', 58, '해외 또는 글로벌 환경에서 일해보고 싶다.', 'pull', 'likert7', false, '{"section":"motivation","subscale":"pull","crossTags":["CH:adventure"]}'::jsonb),
  ('c_pl08', 'layer_c', 'C', 59, '내 전문성을 더 깊이 발휘할 수 있는 환경을 원한다.', 'pull', 'likert7', false, '{"section":"motivation","subscale":"pull","crossTags":["SP:Strategic"]}'::jsonb),
  ('c_pl09', 'layer_c', 'C', 60, '사회적으로 의미 있는 일을 하고 싶다.', 'pull', 'likert7', false, '{"section":"motivation","subscale":"pull","crossTags":["CH:ethics","AP:S"]}'::jsonb),
  ('c_pl10', 'layer_c', 'C', 61, '유연한 근무 환경을 원한다.', 'pull', 'likert7', false, '{"section":"motivation","subscale":"pull","crossTags":["PT:P"]}'::jsonb),
  ('c_pl11', 'layer_c', 'C', 62, '함께 일하고 싶은 사람들이 있는 곳으로 가고 싶다.', 'pull', 'likert7', false, '{"section":"motivation","subscale":"pull","crossTags":["BT:I","SP:Interpersonal"]}'::jsonb),
  ('c_pl12', 'layer_c', 'C', 63, '창업이나 독립을 위한 경험을 쌓고 싶다.', 'pull', 'likert7', false, '{"section":"motivation","subscale":"pull","crossTags":["BT:D","AP:E","SP:Breakthrough"]}'::jsonb),
  ('c_st01', 'layer_c', 'C', 64, '현재 직무의 핵심 역량이 목표 직무에서도 필요하다.', 'skill_transfer', 'likert7', false, '{"section":"transferability","subscale":"skill_transfer","crossTags":["SP:all"]}'::jsonb),
  ('c_st02', 'layer_c', 'C', 65, '목표 직무의 핵심 업무 내용을 구체적으로 이해하고 있다.', 'skill_transfer', 'likert7', false, '{"section":"transferability","subscale":"skill_transfer","crossTags":["PT:S","BT:C"]}'::jsonb),
  ('c_st03', 'layer_c', 'C', 66, '현재 역량과 목표 직무 사이의 갭이 무엇인지 파악하고 있다.', 'skill_transfer', 'likert7', false, '{"section":"transferability","subscale":"skill_transfer","crossTags":["SP:Analytical","UF:self"]}'::jsonb),
  ('c_st04', 'layer_c', 'C', 67, '그 갭을 메우기 위해 구체적인 학습 계획이 있다.', 'skill_transfer', 'likert7', false, '{"section":"transferability","subscale":"skill_transfer","crossTags":["PT:J","CH:integrity"]}'::jsonb),
  ('c_st05', 'layer_c', 'C', 68, '과거에 직무나 역할이 바뀌었을 때 빠르게 적응한 경험이 있다.', 'skill_transfer', 'likert7', false, '{"section":"transferability","subscale":"skill_transfer","crossTags":["UF:temperament","CH:growth"]}'::jsonb),
  ('c_st06', 'layer_c', 'C', 69, '목표 직무에서 요구하는 도구나 기술을 이미 일부 보유하고 있다.', 'skill_transfer', 'likert7', false, '{"section":"transferability","subscale":"skill_transfer","crossTags":["BT:C"]}'::jsonb),
  ('c_st07', 'layer_c', 'C', 70, '목표 산업의 비즈니스 구조와 트렌드를 이해하고 있다.', 'skill_transfer', 'likert7', false, '{"section":"transferability","subscale":"skill_transfer","crossTags":["PT:N","SP:Strategic"]}'::jsonb),
  ('c_st08', 'layer_c', 'C', 71, '현재 직무 경험이 목표 직무에서 차별화 요소가 될 수 있다.', 'skill_transfer', 'likert7', false, '{"section":"transferability","subscale":"skill_transfer","crossTags":["SP:Strategic"]}'::jsonb),
  ('c_st09', 'layer_c', 'C', 72, '목표 직무를 수행하는 사람과 대화하거나 정보를 수집한 적이 있다.', 'skill_transfer', 'likert7', false, '{"section":"transferability","subscale":"skill_transfer","crossTags":["BT:I","PT:E"]}'::jsonb),
  ('c_st10', 'layer_c', 'C', 73, '경력 전환에 필요한 자격증이나 교육을 확인해보았다.', 'skill_transfer', 'likert7', false, '{"section":"transferability","subscale":"skill_transfer","crossTags":["PT:J","BT:C"]}'::jsonb),
  ('c_st11', 'layer_c', 'C', 74, '전혀 다른 분야로의 전환도 고려 중이다.', 'skill_transfer', 'likert7', false, '{"section":"transferability","subscale":"skill_transfer","crossTags":["SP:Breakthrough","CH:adventure"]}'::jsonb),
  ('c_st12', 'layer_c', 'C', 75, '역량 갭을 메우는 데 필요한 시간과 비용을 현실적으로 예측할 수 있다.', 'skill_transfer', 'likert7', false, '{"section":"transferability","subscale":"skill_transfer","crossTags":["PT:S","PT:J","SP:Analytical"]}'::jsonb),
  ('c_mf01', 'layer_c', 'C', 76, '목표 직무의 채용 시장이 활발하다고 판단한다.', 'market_fit', 'likert7', false, '{"section":"transferability","subscale":"market_fit","crossTags":["PT:N"]}'::jsonb),
  ('c_mf02', 'layer_c', 'C', 77, '내 경력 수준에 맞는 포지션이 시장에 존재한다.', 'market_fit', 'likert7', false, '{"section":"transferability","subscale":"market_fit","crossTags":["SP:Strategic"]}'::jsonb),
  ('c_mf03', 'layer_c', 'C', 78, '목표 직무의 평균 보상 수준을 조사해보았다.', 'market_fit', 'likert7', false, '{"section":"transferability","subscale":"market_fit","crossTags":["PT:S","BT:C"]}'::jsonb),
  ('c_mf04', 'layer_c', 'C', 79, '나의 경력 경로가 목표 기업에서 매력적으로 보일 것이라 생각한다.', 'market_fit', 'likert7', false, '{"section":"transferability","subscale":"market_fit","crossTags":["UF:self","BT:D"]}'::jsonb),
  ('c_mf05', 'layer_c', 'C', 80, '목표 직무에서 내 나이/경력이 유리하게 작용할 수 있다.', 'market_fit', 'likert7', false, '{"section":"transferability","subscale":"market_fit","crossTags":["SP:Strategic"]}'::jsonb),
  ('c_mf06', 'layer_c', 'C', 81, '현재 산업에서 목표 산업으로 이동한 사례를 알고 있다.', 'market_fit', 'likert7', false, '{"section":"transferability","subscale":"market_fit","crossTags":["PT:N"]}'::jsonb),
  ('c_mf07', 'layer_c', 'C', 82, '채용 공고를 분석하여 요구 역량을 파악해본 적이 있다.', 'market_fit', 'likert7', false, '{"section":"transferability","subscale":"market_fit","crossTags":["BT:C","PT:J"]}'::jsonb),
  ('c_mf08', 'layer_c', 'C', 83, '내가 목표하는 포지션의 경쟁 강도를 현실적으로 인식하고 있다.', 'market_fit', 'likert7', false, '{"section":"transferability","subscale":"market_fit","crossTags":["PT:S","UF:self"]}'::jsonb),
  ('c_mf09', 'layer_c', 'C', 84, '이직 시 보상 수준을 유지하거나 높일 수 있다고 생각한다.', 'market_fit', 'likert7', false, '{"section":"transferability","subscale":"market_fit","crossTags":["BT:D"]}'::jsonb),
  ('c_mf10', 'layer_c', 'C', 85, '헤드헌터나 채용 담당자로부터 연락을 받은 경험이 있다.', 'market_fit', 'likert7', false, '{"section":"transferability","subscale":"market_fit","crossTags":["BT:I"]}'::jsonb),
  ('c_mf11', 'layer_c', 'C', 86, '링크드인이나 직무 커뮤니티에서 내 프로필이 활성화되어 있다.', 'market_fit', 'likert7', false, '{"section":"transferability","subscale":"market_fit","crossTags":["BT:I","PT:E"]}'::jsonb),
  ('c_mf12', 'layer_c', 'C', 87, '목표 기업 리스트가 구체적으로 있다.', 'market_fit', 'likert7', false, '{"section":"transferability","subscale":"market_fit","crossTags":["PT:J","BT:C"]}'::jsonb),
  ('c_ad01', 'layer_c', 'C', 88, '새로운 조직 문화에 적응하는 것에 자신이 있다.', 'adaptation', 'likert7', false, '{"section":"transferability","subscale":"adaptation","crossTags":["UF:temperament","CH:growth"]}'::jsonb),
  ('c_ad02', 'layer_c', 'C', 89, '낯선 업무 방식도 빠르게 익힐 수 있다.', 'adaptation', 'likert7', false, '{"section":"transferability","subscale":"adaptation","crossTags":["CH:growth","PT:P"]}'::jsonb),
  ('c_ad03', 'layer_c', 'C', 90, '직급이 낮아지더라도 원하는 직무라면 수용할 수 있다.', 'adaptation', 'likert7', false, '{"section":"transferability","subscale":"adaptation","crossTags":["UF:self","BT:S"]}'::jsonb),
  ('c_ad04', 'layer_c', 'C', 91, '보상이 일시적으로 줄어도 장기적 성장 가능성을 선택할 수 있다.', 'adaptation', 'likert7', false, '{"section":"transferability","subscale":"adaptation","crossTags":["PT:N","CH:growth"]}'::jsonb),
  ('c_ad05', 'layer_c', 'C', 92, '현재 직무의 익숙함을 포기하는 것이 두렵다.', 'adaptation', 'likert7', true, '{"section":"transferability","subscale":"adaptation","crossTags":["UF:temperament","CH:emotional"]}'::jsonb),
  ('c_ad06', 'layer_c', 'C', 93, '이직 후 초기 적응 기간의 스트레스를 감당할 자신이 있다.', 'adaptation', 'likert7', false, '{"section":"transferability","subscale":"adaptation","crossTags":["CH:emotional","UF:self"]}'::jsonb),
  ('c_ad07', 'layer_c', 'C', 94, '새로운 상사의 스타일에 맞추는 것에 유연하다.', 'adaptation', 'likert7', false, '{"section":"transferability","subscale":"adaptation","crossTags":["BT:S","PT:P"]}'::jsonb),
  ('c_ad08', 'layer_c', 'C', 95, '기존 방식과 다른 업무 프로세스도 받아들일 수 있다.', 'adaptation', 'likert7', false, '{"section":"transferability","subscale":"adaptation","crossTags":["PT:P","CH:growth"]}'::jsonb),
  ('c_ad09', 'layer_c', 'C', 96, '이직으로 인한 인간관계 변화를 감수할 준비가 되어 있다.', 'adaptation', 'likert7', false, '{"section":"transferability","subscale":"adaptation","crossTags":["CH:relational","BT:I"]}'::jsonb),
  ('c_ad10', 'layer_c', 'C', 97, '새로운 환경에서 처음부터 신뢰를 쌓아가는 과정을 즐길 수 있다.', 'adaptation', 'likert7', false, '{"section":"transferability","subscale":"adaptation","crossTags":["BT:I","UF:peer"]}'::jsonb),
  ('c_ad11', 'layer_c', 'C', 98, '이직 후 기대와 현실의 차이가 있을 수 있음을 인정한다.', 'adaptation', 'likert7', false, '{"section":"transferability","subscale":"adaptation","crossTags":["PT:S","CH:emotional"]}'::jsonb),
  ('c_ad12', 'layer_c', 'C', 99, '변화 자체가 나에게 에너지를 주는 편이다.', 'adaptation', 'likert7', false, '{"section":"transferability","subscale":"adaptation","crossTags":["CH:adventure","SP:Breakthrough"]}'::jsonb),
  ('c_dc01', 'layer_c', 'C', 100, '최신 이력서가 준비되어 있다.', 'doc', 'likert7', false, '{"section":"readiness","subscale":"doc","crossTags":["PT:J","BT:C"]}'::jsonb),
  ('c_dc02', 'layer_c', 'C', 101, '이직 사유를 긍정적이고 설득력 있게 설명할 수 있다.', 'doc', 'likert7', false, '{"section":"readiness","subscale":"doc","crossTags":["BT:I","PT:T"]}'::jsonb),
  ('c_dc03', 'layer_c', 'C', 102, '포트폴리오나 성과 자료를 체계적으로 정리해두었다.', 'doc', 'likert7', false, '{"section":"readiness","subscale":"doc","crossTags":["BT:C","PT:J"]}'::jsonb),
  ('c_dc04', 'layer_c', 'C', 103, '자기소개서를 목표 기업에 맞게 커스터마이즈할 수 있다.', 'doc', 'likert7', false, '{"section":"readiness","subscale":"doc","crossTags":["PT:N","BT:C"]}'::jsonb),
  ('c_dc05', 'layer_c', 'C', 104, '링크드인/직무 플랫폼 프로필이 최신 상태다.', 'doc', 'likert7', false, '{"section":"readiness","subscale":"doc","crossTags":["BT:I"]}'::jsonb),
  ('c_iv01', 'layer_c', 'C', 105, '경력 기반 면접(STAR 기법)에 대비하고 있다.', 'interview', 'likert7', false, '{"section":"readiness","subscale":"interview","crossTags":["BT:C","PT:J"]}'::jsonb),
  ('c_iv02', 'layer_c', 'C', 106, '"왜 이직하려 하는가"에 대한 명확한 답변이 준비되어 있다.', 'interview', 'likert7', false, '{"section":"readiness","subscale":"interview","crossTags":["BT:D","PT:T"]}'::jsonb),
  ('c_iv03', 'layer_c', 'C', 107, '연봉 협상 전략이 있다.', 'interview', 'likert7', false, '{"section":"readiness","subscale":"interview","crossTags":["BT:D","SP:Strategic"]}'::jsonb),
  ('c_iv04', 'layer_c', 'C', 108, '모의 면접이나 피드백을 받아본 경험이 있다.', 'interview', 'likert7', false, '{"section":"readiness","subscale":"interview","crossTags":["CH:growth"]}'::jsonb),
  ('c_iv05', 'layer_c', 'C', 109, '면접에서 나의 강점을 구체적 사례와 함께 설명할 수 있다.', 'interview', 'likert7', false, '{"section":"readiness","subscale":"interview","crossTags":["BT:I","SP:all"]}'::jsonb),
  ('c_tm01', 'layer_c', 'C', 110, '이직 시점을 전략적으로 고려하고 있다.', 'timing', 'likert7', false, '{"section":"readiness","subscale":"timing","crossTags":["SP:Strategic","PT:J"]}'::jsonb),
  ('c_tm02', 'layer_c', 'C', 111, '이직 활동에 투자할 시간을 확보하고 있다.', 'timing', 'likert7', false, '{"section":"readiness","subscale":"timing","crossTags":["PT:J"]}'::jsonb),
  ('c_tm03', 'layer_c', 'C', 112, '현 직장에서의 퇴사 절차를 계획하고 있다.', 'timing', 'likert7', false, '{"section":"readiness","subscale":"timing","crossTags":["PT:J","CH:integrity"]}'::jsonb),
  ('c_tm04', 'layer_c', 'C', 113, '이직이 지연될 경우를 대비한 플랜 B가 있다.', 'timing', 'likert7', false, '{"section":"readiness","subscale":"timing","crossTags":["SP:Strategic","PT:N"]}'::jsonb),
  ('c_tm05', 'layer_c', 'C', 114, '이직 기간 동안의 생활비를 감당할 재정적 여유가 있다.', 'timing', 'likert7', false, '{"section":"readiness","subscale":"timing","crossTags":["PT:S"]}'::jsonb),
  ('c_ps01', 'layer_c', 'C', 115, '이직 결심이 일시적 감정이 아닌 충분한 고민의 결과다.', 'psychological', 'likert7', false, '{"section":"readiness","subscale":"psychological","crossTags":["PT:T","CH:emotional"]}'::jsonb),
  ('c_ps02', 'layer_c', 'C', 116, '가족이나 가까운 사람이 이직 계획을 지지한다.', 'psychological', 'likert7', false, '{"section":"readiness","subscale":"psychological","crossTags":["UF:parent","UF:family"]}'::jsonb),
  ('c_ps03', 'layer_c', 'C', 117, '이직 과정에서 거절당해도 계속 도전할 의지가 있다.', 'psychological', 'likert7', false, '{"section":"readiness","subscale":"psychological","crossTags":["UF:self","SP:Breakthrough"]}'::jsonb),
  ('c_ps04', 'layer_c', 'C', 118, '이직 후 후회할 가능성에 대해 충분히 생각해보았다.', 'psychological', 'likert7', false, '{"section":"readiness","subscale":"psychological","crossTags":["PT:T","PT:S"]}'::jsonb),
  ('c_ps05', 'layer_c', 'C', 119, '지금이 이직할 적절한 시점이라고 확신한다.', 'psychological', 'likert7', false, '{"section":"readiness","subscale":"psychological","crossTags":["BT:D","UF:self"]}'::jsonb),
  ('c_val01', 'layer_c', 'C', 120, '나는 직장에서 단 한 번도 불만을 느낀 적이 없다.', 'DECOY', 'likert7', false, '{"section":"decoy","subscale":"DECOY","crossTags":[]}'::jsonb),
  ('c_val02', 'layer_c', 'C', 121, '내가 내린 결정은 항상 최선의 결과를 낳았다.', 'DECOY', 'likert7', false, '{"section":"decoy","subscale":"DECOY","crossTags":[]}'::jsonb);
