-- HIT Layer D: 142문항 (140 + 미끼 2)
-- HIT_D_Final.md 설계서 기반
-- 자동 생성: scripts/seed-hit-layer-d.js

DELETE FROM public.hit_questions WHERE module = 'layer_d';

INSERT INTO public.hit_questions
  (id, module, test_type, question_index, question_text, sub_domain, response_type, reverse_scored, scoring_key)
VALUES
  ('d_dd01', 'layer_d', 'D', 0, '내 분야에서 10년 이상 쌓아온 독자적 관점이나 철학이 있다.', 'domain_depth', 'likert7', false, '{"section":"expertise","subscale":"domain_depth","crossTags":["SP:Strategic","UF:self"]}'::jsonb),
  ('d_dd02', 'layer_d', 'D', 1, '후배나 팀원에게 체계적으로 지식을 전수할 수 있다.', 'domain_depth', 'likert7', false, '{"section":"expertise","subscale":"domain_depth","crossTags":["BT:S","SP:Harmony"]}'::jsonb),
  ('d_dd03', 'layer_d', 'D', 2, '내 전문 분야에서 업계가 인정하는 수준의 전문성이 있다.', 'domain_depth', 'likert7', false, '{"section":"expertise","subscale":"domain_depth","crossTags":["SP:Guard","BT:C"]}'::jsonb),
  ('d_dd04', 'layer_d', 'D', 3, '경험으로 체득한 암묵지가 나의 핵심 자산이다.', 'domain_depth', 'likert7', false, '{"section":"expertise","subscale":"domain_depth","crossTags":["BT:C","PT:S"]}'::jsonb),
  ('d_dd05', 'layer_d', 'D', 4, '해당 분야의 역사와 변천을 설명할 수 있다.', 'domain_depth', 'likert7', false, '{"section":"expertise","subscale":"domain_depth","crossTags":["PT:N","SP:Strategic"]}'::jsonb),
  ('d_dd06', 'layer_d', 'D', 5, '내 전문성이 최신 기술/트렌드 변화에도 유효하다고 판단한다.', 'domain_depth', 'likert7', false, '{"section":"expertise","subscale":"domain_depth","crossTags":["PT:N","CH:growth"]}'::jsonb),
  ('d_dd07', 'layer_d', 'D', 6, '복잡한 문제 상황에서 경험에 기반한 직관적 판단이 정확한 편이다.', 'domain_depth', 'likert7', false, '{"section":"expertise","subscale":"domain_depth","crossTags":["PT:N","SP:Strategic"]}'::jsonb),
  ('d_dd08', 'layer_d', 'D', 7, '내 분야에서 강의, 멘토링, 기고 등을 해본 경험이 있다.', 'domain_depth', 'likert7', false, '{"section":"expertise","subscale":"domain_depth","crossTags":["BT:I","AP:S"]}'::jsonb),
  ('d_dd09', 'layer_d', 'D', 8, '타 분야 전문가와 협업할 때 내 전문성의 가치를 명확히 전달할 수 있다.', 'domain_depth', 'likert7', false, '{"section":"expertise","subscale":"domain_depth","crossTags":["BT:I","PT:T"]}'::jsonb),
  ('d_dd10', 'layer_d', 'D', 9, '내 분야가 AI나 자동화로 대체될 가능성을 현실적으로 평가해보았다.', 'domain_depth', 'likert7', false, '{"section":"expertise","subscale":"domain_depth","crossTags":["PT:N","PT:T","SP:Strategic"]}'::jsonb),
  ('d_tk01', 'layer_d', 'D', 10, '매뉴얼에 없지만 내가 아는 업무 노하우가 많다.', 'tacit_knowledge', 'likert7', false, '{"section":"expertise","subscale":"tacit_knowledge","crossTags":["SP:Guard","BT:C"]}'::jsonb),
  ('d_tk02', 'layer_d', 'D', 11, '위기 상황에서 경험 기반의 판단이 매뉴얼보다 효과적이었던 적이 있다.', 'tacit_knowledge', 'likert7', false, '{"section":"expertise","subscale":"tacit_knowledge","crossTags":["SP:Breakthrough","BT:D"]}'::jsonb),
  ('d_tk03', 'layer_d', 'D', 12, '내 경험을 콘텐츠(글, 강의, 코칭)로 전환할 수 있다.', 'tacit_knowledge', 'likert7', false, '{"section":"expertise","subscale":"tacit_knowledge","crossTags":["BT:I","AP:A","AP:S"]}'::jsonb),
  ('d_tk04', 'layer_d', 'D', 13, '후임자가 나의 역할을 완전히 대체하기 어려울 것이다.', 'tacit_knowledge', 'likert7', false, '{"section":"expertise","subscale":"tacit_knowledge","crossTags":["SP:Guard"]}'::jsonb),
  ('d_tk05', 'layer_d', 'D', 14, '내가 쌓은 노하우를 시스템이나 프로세스로 문서화할 수 있다.', 'tacit_knowledge', 'likert7', false, '{"section":"expertise","subscale":"tacit_knowledge","crossTags":["BT:C","PT:J"]}'::jsonb),
  ('d_tk06', 'layer_d', 'D', 15, '고객, 파트너와의 관계에서 나만 아는 맥락이 중요한 역할을 한다.', 'tacit_knowledge', 'likert7', false, '{"section":"expertise","subscale":"tacit_knowledge","crossTags":["BT:I","SP:Interpersonal"]}'::jsonb),
  ('d_tk07', 'layer_d', 'D', 16, '비슷한 직급의 다른 사람과 비교했을 때 내 경험의 폭이 넓다.', 'tacit_knowledge', 'likert7', false, '{"section":"expertise","subscale":"tacit_knowledge","crossTags":["UF:self","SP:multi"]}'::jsonb),
  ('d_tk08', 'layer_d', 'D', 17, '내 전문성을 기반으로 컨설팅이나 자문 역할을 할 수 있다.', 'tacit_knowledge', 'likert7', false, '{"section":"expertise","subscale":"tacit_knowledge","crossTags":["BT:D","SP:Strategic"]}'::jsonb),
  ('d_tk09', 'layer_d', 'D', 18, '실무 감각을 유지하면서도 전략적 시야를 갖추고 있다.', 'tacit_knowledge', 'likert7', false, '{"section":"expertise","subscale":"tacit_knowledge","crossTags":["SP:Strategic","SP:Execution"]}'::jsonb),
  ('d_tk10', 'layer_d', 'D', 19, '내 경험이 조직을 떠나면 대부분 사라질 것이라 느낀다.', 'tacit_knowledge', 'likert7', true, '{"section":"expertise","subscale":"tacit_knowledge","crossTags":["UF:self"]}'::jsonb),
  ('d_rd01', 'layer_d', 'D', 20, '현재 전문성을 다른 산업에 적용할 수 있는 방법을 생각해본 적이 있다.', 'redeployment', 'likert7', false, '{"section":"expertise","subscale":"redeployment","crossTags":["PT:N","SP:Creativity"]}'::jsonb),
  ('d_rd02', 'layer_d', 'D', 21, '전문성의 핵심 원리는 산업이 바뀌어도 유효하다.', 'redeployment', 'likert7', false, '{"section":"expertise","subscale":"redeployment","crossTags":["SP:Strategic"]}'::jsonb),
  ('d_rd03', 'layer_d', 'D', 22, '내 경험이 스타트업/중소기업에서 특히 가치 있을 수 있다.', 'redeployment', 'likert7', false, '{"section":"expertise","subscale":"redeployment","crossTags":["BT:D","SP:Execution"]}'::jsonb),
  ('d_rd04', 'layer_d', 'D', 23, '교육·컨설팅·코칭 분야로의 전환을 구체적으로 고려해본 적이 있다.', 'redeployment', 'likert7', false, '{"section":"expertise","subscale":"redeployment","crossTags":["AP:S","BT:I"]}'::jsonb),
  ('d_rd05', 'layer_d', 'D', 24, '내 전문성으로 독립(프리랜서, 1인 기업)할 수 있다고 생각한다.', 'redeployment', 'likert7', false, '{"section":"expertise","subscale":"redeployment","crossTags":["BT:D","SP:Breakthrough"]}'::jsonb),
  ('d_rd06', 'layer_d', 'D', 25, '다른 기능(마케팅→경영기획, 개발→CTO 등)으로 역할 전환이 가능하다.', 'redeployment', 'likert7', false, '{"section":"expertise","subscale":"redeployment","crossTags":["PT:N","SP:Strategic"]}'::jsonb),
  ('d_rd07', 'layer_d', 'D', 26, '해외에서도 내 전문성이 통할 수 있다.', 'redeployment', 'likert7', false, '{"section":"expertise","subscale":"redeployment","crossTags":["CH:adventure"]}'::jsonb),
  ('d_rd08', 'layer_d', 'D', 27, '현재 전문 분야와 인접한 새로운 영역에 관심이 있다.', 'redeployment', 'likert7', false, '{"section":"expertise","subscale":"redeployment","crossTags":["PT:N","CH:growth"]}'::jsonb),
  ('d_rd09', 'layer_d', 'D', 28, '10년 후에도 유효한 전문성을 갖추기 위해 지금 준비할 것이 있다.', 'redeployment', 'likert7', false, '{"section":"expertise","subscale":"redeployment","crossTags":["PT:N","PT:J","SP:Strategic"]}'::jsonb),
  ('d_rd10', 'layer_d', 'D', 29, '내 전문성을 디지털 환경에 맞게 업데이트할 필요를 느낀다.', 'redeployment', 'likert7', false, '{"section":"expertise","subscale":"redeployment","crossTags":["CH:growth"]}'::jsonb),
  ('d_pb01', 'layer_d', 'D', 30, '업계에서 나를 떠올리면 연상되는 전문 이미지가 있다.', 'personal_brand', 'likert7', false, '{"section":"expertise","subscale":"personal_brand","crossTags":["BT:I","SP:Strategic"]}'::jsonb),
  ('d_pb02', 'layer_d', 'D', 31, '나의 전문성을 한 문장으로 설명할 수 있다.', 'personal_brand', 'likert7', false, '{"section":"expertise","subscale":"personal_brand","crossTags":["PT:T","BT:C"]}'::jsonb),
  ('d_pb03', 'layer_d', 'D', 32, '소셜미디어나 업계 채널에서 전문적 콘텐츠를 공유한다.', 'personal_brand', 'likert7', false, '{"section":"expertise","subscale":"personal_brand","crossTags":["BT:I","PT:E"]}'::jsonb),
  ('d_pb04', 'layer_d', 'D', 33, '외부 강연, 기고, 인터뷰 등의 경험이 있다.', 'personal_brand', 'likert7', false, '{"section":"expertise","subscale":"personal_brand","crossTags":["BT:I","SP:Interpersonal"]}'::jsonb),
  ('d_pb05', 'layer_d', 'D', 34, '나의 경력 스토리를 설득력 있게 전달할 수 있다.', 'personal_brand', 'likert7', false, '{"section":"expertise","subscale":"personal_brand","crossTags":["BT:I","PT:T"]}'::jsonb),
  ('d_pb06', 'layer_d', 'D', 35, '채용 시장에서 내 이름이 알려져 있다고 생각한다.', 'personal_brand', 'likert7', false, '{"section":"expertise","subscale":"personal_brand","crossTags":["UF:self"]}'::jsonb),
  ('d_pb07', 'layer_d', 'D', 36, '내가 만든 결과물이나 프로젝트가 업계에서 레퍼런스가 된 적이 있다.', 'personal_brand', 'likert7', false, '{"section":"expertise","subscale":"personal_brand","crossTags":["SP:Execution"]}'::jsonb),
  ('d_pb08', 'layer_d', 'D', 37, '이직 시 브랜드 프리미엄이 있을 것이라 생각한다.', 'personal_brand', 'likert7', false, '{"section":"expertise","subscale":"personal_brand","crossTags":["UF:self","BT:D"]}'::jsonb),
  ('d_pb09', 'layer_d', 'D', 38, '전문가 커뮤니티에서 인정받고 있다.', 'personal_brand', 'likert7', false, '{"section":"expertise","subscale":"personal_brand","crossTags":["BT:I"]}'::jsonb),
  ('d_pb10', 'layer_d', 'D', 39, '내 전문성에 대한 외부 평판과 자기 인식 사이에 괴리가 있다.', 'personal_brand', 'likert7', true, '{"section":"expertise","subscale":"personal_brand","crossTags":["UF:self"]}'::jsonb),
  ('d_le01', 'layer_d', 'D', 40, '목표를 설정하면 실행 계획을 구체적으로 수립하는 편이다.', 'exec_leadership', 'likert7', false, '{"section":"leadership","subscale":"exec_leadership","crossTags":["BT:D","PT:J","SP:Execution"]}'::jsonb),
  ('d_le02', 'layer_d', 'D', 41, '팀의 진행 상황을 체계적으로 추적하고 관리한다.', 'exec_leadership', 'likert7', false, '{"section":"leadership","subscale":"exec_leadership","crossTags":["BT:C","PT:J"]}'::jsonb),
  ('d_le03', 'layer_d', 'D', 42, '결과가 나올 때까지 끝까지 밀어붙이는 추진력이 있다.', 'exec_leadership', 'likert7', false, '{"section":"leadership","subscale":"exec_leadership","crossTags":["BT:D","SP:Execution"]}'::jsonb),
  ('d_le04', 'layer_d', 'D', 43, '업무 프로세스를 개선하여 효율을 높인 경험이 있다.', 'exec_leadership', 'likert7', false, '{"section":"leadership","subscale":"exec_leadership","crossTags":["BT:C","SP:Execution"]}'::jsonb),
  ('d_le05', 'layer_d', 'D', 44, '위기 상황에서 빠르게 의사결정을 내릴 수 있다.', 'exec_leadership', 'likert7', false, '{"section":"leadership","subscale":"exec_leadership","crossTags":["BT:D","PT:T","SP:Breakthrough"]}'::jsonb),
  ('d_le06', 'layer_d', 'D', 45, '팀원에게 명확한 기대치와 마감을 설정한다.', 'exec_leadership', 'likert7', false, '{"section":"leadership","subscale":"exec_leadership","crossTags":["BT:D","PT:J"]}'::jsonb),
  ('d_le07', 'layer_d', 'D', 46, '성과 미달 시 원인을 분석하고 대안을 실행한다.', 'exec_leadership', 'likert7', false, '{"section":"leadership","subscale":"exec_leadership","crossTags":["BT:C","BT:D","SP:Analytical"]}'::jsonb),
  ('d_le08', 'layer_d', 'D', 47, '리소스가 부족한 상황에서도 결과를 만들어낸 경험이 있다.', 'exec_leadership', 'likert7', false, '{"section":"leadership","subscale":"exec_leadership","crossTags":["BT:D","SP:Breakthrough"]}'::jsonb),
  ('d_ls01', 'layer_d', 'D', 48, '조직의 중장기 방향을 설정하는 데 기여한 경험이 있다.', 'strategic_leadership', 'likert7', false, '{"section":"leadership","subscale":"strategic_leadership","crossTags":["SP:Strategic","PT:N"]}'::jsonb),
  ('d_ls02', 'layer_d', 'D', 49, '현재의 문제보다 3~5년 후의 변화를 먼저 생각하는 편이다.', 'strategic_leadership', 'likert7', false, '{"section":"leadership","subscale":"strategic_leadership","crossTags":["PT:N","SP:Strategic"]}'::jsonb),
  ('d_ls03', 'layer_d', 'D', 50, '복잡한 상황을 큰 그림으로 정리하여 팀에 전달할 수 있다.', 'strategic_leadership', 'likert7', false, '{"section":"leadership","subscale":"strategic_leadership","crossTags":["PT:N","BT:I"]}'::jsonb),
  ('d_ls04', 'layer_d', 'D', 51, '데이터와 직관을 결합하여 전략적 판단을 내린다.', 'strategic_leadership', 'likert7', false, '{"section":"leadership","subscale":"strategic_leadership","crossTags":["PT:N","PT:S","SP:Strategic"]}'::jsonb),
  ('d_ls05', 'layer_d', 'D', 52, '사업 기회를 발굴하고 새로운 방향을 제시한 경험이 있다.', 'strategic_leadership', 'likert7', false, '{"section":"leadership","subscale":"strategic_leadership","crossTags":["BT:D","SP:Creativity"]}'::jsonb),
  ('d_ls06', 'layer_d', 'D', 53, '조직 외부 환경의 변화를 예측하려 한다.', 'strategic_leadership', 'likert7', false, '{"section":"leadership","subscale":"strategic_leadership","crossTags":["PT:N","SP:Strategic"]}'::jsonb),
  ('d_ls07', 'layer_d', 'D', 54, '전략과 실행 사이의 간극을 좁히는 역할을 해왔다.', 'strategic_leadership', 'likert7', false, '{"section":"leadership","subscale":"strategic_leadership","crossTags":["SP:Strategic","SP:Execution"]}'::jsonb),
  ('d_ls08', 'layer_d', 'D', 55, '경영진에게 전략적 제안을 한 경험이 있다.', 'strategic_leadership', 'likert7', false, '{"section":"leadership","subscale":"strategic_leadership","crossTags":["BT:D","PT:T"]}'::jsonb),
  ('d_lc01', 'layer_d', 'D', 56, '팀원의 성장을 위해 시간과 에너지를 투자한다.', 'coaching_leadership', 'likert7', false, '{"section":"leadership","subscale":"coaching_leadership","crossTags":["BT:S","SP:Harmony","PT:F"]}'::jsonb),
  ('d_lc02', 'layer_d', 'D', 57, '비판보다 질문을 통해 스스로 답을 찾게 유도한다.', 'coaching_leadership', 'likert7', false, '{"section":"leadership","subscale":"coaching_leadership","crossTags":["BT:S","PT:F"]}'::jsonb),
  ('d_lc03', 'layer_d', 'D', 58, '팀원의 강점을 파악하고 적절한 역할을 배치한다.', 'coaching_leadership', 'likert7', false, '{"section":"leadership","subscale":"coaching_leadership","crossTags":["SP:Interpersonal","BT:S"]}'::jsonb),
  ('d_lc04', 'layer_d', 'D', 59, '실패한 팀원에게 비난보다 학습 기회를 제공한다.', 'coaching_leadership', 'likert7', false, '{"section":"leadership","subscale":"coaching_leadership","crossTags":["PT:F","UF:parent"]}'::jsonb),
  ('d_lc05', 'layer_d', 'D', 60, '내가 키운 사람이 성장하는 것이 가장 큰 보람이다.', 'coaching_leadership', 'likert7', false, '{"section":"leadership","subscale":"coaching_leadership","crossTags":["AP:S","SP:Harmony"]}'::jsonb),
  ('d_lc06', 'layer_d', 'D', 61, '1:1 면담을 정기적으로 실시한다.', 'coaching_leadership', 'likert7', false, '{"section":"leadership","subscale":"coaching_leadership","crossTags":["BT:S","PT:J"]}'::jsonb),
  ('d_lc07', 'layer_d', 'D', 62, '팀원의 커리어 방향에 대해 조언한 경험이 있다.', 'coaching_leadership', 'likert7', false, '{"section":"leadership","subscale":"coaching_leadership","crossTags":["SP:Interpersonal"]}'::jsonb),
  ('d_lc08', 'layer_d', 'D', 63, '다양한 세대(MZ세대 등)와 효과적으로 소통한다.', 'coaching_leadership', 'likert7', false, '{"section":"leadership","subscale":"coaching_leadership","crossTags":["PT:F","PT:E","UF:cultural"]}'::jsonb),
  ('d_li01', 'layer_d', 'D', 64, '팀을 이끄는 것보다 전문가로서 독립적으로 일하는 것이 편하다.', 'independent_leadership', 'likert7', false, '{"section":"leadership","subscale":"independent_leadership","crossTags":["PT:I","BT:C"]}'::jsonb),
  ('d_li02', 'layer_d', 'D', 65, '관리 업무보다 직접 문제를 해결하는 것이 더 즐겁다.', 'independent_leadership', 'likert7', false, '{"section":"leadership","subscale":"independent_leadership","crossTags":["BT:C","PT:S"]}'::jsonb),
  ('d_li03', 'layer_d', 'D', 66, '조직 정치보다 전문적 깊이에 에너지를 쓰고 싶다.', 'independent_leadership', 'likert7', false, '{"section":"leadership","subscale":"independent_leadership","crossTags":["PT:I","PT:T","BT:C"]}'::jsonb),
  ('d_li04', 'layer_d', 'D', 67, '소규모 팀이나 독자적 프로젝트에서 최고의 성과를 낸다.', 'independent_leadership', 'likert7', false, '{"section":"leadership","subscale":"independent_leadership","crossTags":["PT:I","SP:Analytical"]}'::jsonb),
  ('d_li05', 'layer_d', 'D', 68, '매니저 타이틀보다 전문가 타이틀에 더 끌린다.', 'independent_leadership', 'likert7', false, '{"section":"leadership","subscale":"independent_leadership","crossTags":["BT:C"]}'::jsonb),
  ('d_li06', 'layer_d', 'D', 69, '회의와 보고보다 몰입 작업 시간이 더 가치 있다.', 'independent_leadership', 'likert7', false, '{"section":"leadership","subscale":"independent_leadership","crossTags":["PT:I","BT:C"]}'::jsonb),
  ('d_li07', 'layer_d', 'D', 70, '프리랜서/계약직 형태도 만족스러울 수 있다.', 'independent_leadership', 'likert7', false, '{"section":"leadership","subscale":"independent_leadership","crossTags":["SP:Breakthrough"]}'::jsonb),
  ('d_li08', 'layer_d', 'D', 71, '조직 내 역할보다 프로젝트 기반 역할이 나에게 맞다.', 'independent_leadership', 'likert7', false, '{"section":"leadership","subscale":"independent_leadership","crossTags":["PT:P","BT:D"]}'::jsonb),
  ('d_is01', 'layer_d', 'D', 72, '"나는 OO 전문가다"라는 정체성이 매우 강하다.', 'identity_strength', 'likert7', false, '{"section":"identity","subscale":"identity_strength","crossTags":["UF:self"]}'::jsonb),
  ('d_is02', 'layer_d', 'D', 73, '현재 직함이 나를 설명하는 가장 중요한 요소다.', 'identity_strength', 'likert7', false, '{"section":"identity","subscale":"identity_strength","crossTags":["UF:self"]}'::jsonb),
  ('d_is03', 'layer_d', 'D', 74, '내 직업을 빼면 나를 설명하기 어렵다.', 'identity_strength', 'likert7', true, '{"section":"identity","subscale":"identity_strength","crossTags":["UF:self"]}'::jsonb),
  ('d_is04', 'layer_d', 'D', 75, '직무가 바뀌면 정체성의 혼란을 겪을 것 같다.', 'identity_strength', 'likert7', true, '{"section":"identity","subscale":"identity_strength","crossTags":["UF:self","CH:emotional"]}'::jsonb),
  ('d_is05', 'layer_d', 'D', 76, '주변 사람들도 나를 현재 직무와 강하게 연결 짓는다.', 'identity_strength', 'likert7', false, '{"section":"identity","subscale":"identity_strength","crossTags":["UF:peer"]}'::jsonb),
  ('d_is06', 'layer_d', 'D', 77, '내 분야를 떠나는 것은 나를 포기하는 것 같은 느낌이 든다.', 'identity_strength', 'likert7', true, '{"section":"identity","subscale":"identity_strength","crossTags":["UF:self"]}'::jsonb),
  ('d_is07', 'layer_d', 'D', 78, '10년간 쌓아온 경력을 보존하는 것이 중요하다.', 'identity_strength', 'likert7', false, '{"section":"identity","subscale":"identity_strength","crossTags":["SP:Guard"]}'::jsonb),
  ('d_is08', 'layer_d', 'D', 79, '현재 직무에서의 성취가 자존감의 큰 부분을 차지한다.', 'identity_strength', 'likert7', false, '{"section":"identity","subscale":"identity_strength","crossTags":["UF:self"]}'::jsonb),
  ('d_is09', 'layer_d', 'D', 80, '동종 업계 사람들과의 소속감이 강하다.', 'identity_strength', 'likert7', false, '{"section":"identity","subscale":"identity_strength","crossTags":["UF:peer","BT:S"]}'::jsonb),
  ('d_is10', 'layer_d', 'D', 81, '새로운 명함을 받으면 적응하는 데 오래 걸릴 것 같다.', 'identity_strength', 'likert7', true, '{"section":"identity","subscale":"identity_strength","crossTags":["UF:temperament"]}'::jsonb),
  ('d_nr01', 'layer_d', 'D', 82, '완전히 다른 역할을 맡아도 흥미롭게 해낼 수 있다.', 'new_role', 'likert7', false, '{"section":"identity","subscale":"new_role","crossTags":["CH:growth","SP:Breakthrough"]}'::jsonb),
  ('d_nr02', 'layer_d', 'D', 83, '타이틀이 아닌 역할의 내용이 더 중요하다.', 'new_role', 'likert7', false, '{"section":"identity","subscale":"new_role","crossTags":["UF:self"]}'::jsonb),
  ('d_nr03', 'layer_d', 'D', 84, '후배에게 보고하는 상황도 수용할 수 있다.', 'new_role', 'likert7', false, '{"section":"identity","subscale":"new_role","crossTags":["BT:S","CH:emotional"]}'::jsonb),
  ('d_nr04', 'layer_d', 'D', 85, '기존 경력과 무관한 일도 배울 의지가 있다.', 'new_role', 'likert7', false, '{"section":"identity","subscale":"new_role","crossTags":["CH:growth"]}'::jsonb),
  ('d_nr05', 'layer_d', 'D', 86, '"내 나이에 이런 일을?"이라는 생각이 드는 편이다.', 'new_role', 'likert7', true, '{"section":"identity","subscale":"new_role","crossTags":["UF:cultural"]}'::jsonb),
  ('d_nr06', 'layer_d', 'D', 87, '경력 전환자의 롤모델이 있다.', 'new_role', 'likert7', false, '{"section":"identity","subscale":"new_role","crossTags":["PT:N"]}'::jsonb),
  ('d_nr07', 'layer_d', 'D', 88, '스타트업이나 소규모 조직에서의 멀티 플레이어 역할도 가능하다.', 'new_role', 'likert7', false, '{"section":"identity","subscale":"new_role","crossTags":["BT:D","PT:P"]}'::jsonb),
  ('d_nr08', 'layer_d', 'D', 89, '새로운 분야에서 초보가 되는 것을 두려워하지 않는다.', 'new_role', 'likert7', false, '{"section":"identity","subscale":"new_role","crossTags":["UF:self","CH:growth"]}'::jsonb),
  ('d_nr09', 'layer_d', 'D', 90, '다양한 가능한 자아를 상상해본 적이 있다.', 'new_role', 'likert7', false, '{"section":"identity","subscale":"new_role","crossTags":["PT:N","SP:Creativity"]}'::jsonb),
  ('d_nr10', 'layer_d', 'D', 91, '과거의 역할에 집착하기보다 미래의 역할에 열려 있다.', 'new_role', 'likert7', false, '{"section":"identity","subscale":"new_role","crossTags":["CH:growth","SP:Breakthrough"]}'::jsonb),
  ('d_ir01', 'layer_d', 'D', 92, '내가 누구인지를 직업이 아닌 다른 기준으로 설명할 수 있다.', 'identity_recon', 'likert7', false, '{"section":"identity","subscale":"identity_recon","crossTags":["UF:self"]}'::jsonb),
  ('d_ir02', 'layer_d', 'D', 93, '삶의 다음 챕터를 적극적으로 설계하고 싶다.', 'identity_recon', 'likert7', false, '{"section":"identity","subscale":"identity_recon","crossTags":["CH:growth","SP:Breakthrough"]}'::jsonb),
  ('d_ir03', 'layer_d', 'D', 94, '경력 전환을 손실이 아닌 진화로 본다.', 'identity_recon', 'likert7', false, '{"section":"identity","subscale":"identity_recon","crossTags":["UF:trauma"]}'::jsonb),
  ('d_ir04', 'layer_d', 'D', 95, '나는 직업 외에도 다양한 역할로 정의된다.', 'identity_recon', 'likert7', false, '{"section":"identity","subscale":"identity_recon","crossTags":["UF:self"]}'::jsonb),
  ('d_ir05', 'layer_d', 'D', 96, '새 역할에서 기존 경험이 독특한 강점이 될 수 있다.', 'identity_recon', 'likert7', false, '{"section":"identity","subscale":"identity_recon","crossTags":["SP:Strategic"]}'::jsonb),
  ('d_ir06', 'layer_d', 'D', 97, '현재의 나와 미래의 나 사이의 연결고리를 찾을 수 있다.', 'identity_recon', 'likert7', false, '{"section":"identity","subscale":"identity_recon","crossTags":["PT:N","SP:Strategic"]}'::jsonb),
  ('d_ir07', 'layer_d', 'D', 98, '변화 속에서도 흔들리지 않는 나만의 핵심 가치가 있다.', 'identity_recon', 'likert7', false, '{"section":"identity","subscale":"identity_recon","crossTags":["CH:ethics","UF:self"]}'::jsonb),
  ('d_ir08', 'layer_d', 'D', 99, '경력 전환이 나를 더 풍요롭게 만들 수 있다고 믿는다.', 'identity_recon', 'likert7', false, '{"section":"identity","subscale":"identity_recon","crossTags":["CH:growth"]}'::jsonb),
  ('d_st01', 'layer_d', 'D', 100, '진심으로 커리어 조언을 구할 수 있는 사람이 3명 이상 있다.', 'strong_ties', 'likert7', false, '{"section":"network","subscale":"strong_ties","crossTags":["BT:I","UF:peer"]}'::jsonb),
  ('d_st02', 'layer_d', 'D', 101, '업계 핵심 인사와 신뢰 관계를 유지하고 있다.', 'strong_ties', 'likert7', false, '{"section":"network","subscale":"strong_ties","crossTags":["SP:Interpersonal"]}'::jsonb),
  ('d_st03', 'layer_d', 'D', 102, '이직 시 적극적으로 도와줄 사람이 있다.', 'strong_ties', 'likert7', false, '{"section":"network","subscale":"strong_ties","crossTags":["BT:I"]}'::jsonb),
  ('d_st04', 'layer_d', 'D', 103, '전 직장 동료들과도 관계를 유지하고 있다.', 'strong_ties', 'likert7', false, '{"section":"network","subscale":"strong_ties","crossTags":["BT:S","SP:Harmony"]}'::jsonb),
  ('d_st05', 'layer_d', 'D', 104, '업계 밖의 다른 분야 전문가 인맥이 있다.', 'strong_ties', 'likert7', false, '{"section":"network","subscale":"strong_ties","crossTags":["PT:N","BT:I"]}'::jsonb),
  ('d_st06', 'layer_d', 'D', 105, '이직 경험이 있는 선배로부터 조언을 받을 수 있다.', 'strong_ties', 'likert7', false, '{"section":"network","subscale":"strong_ties","crossTags":["UF:parent"]}'::jsonb),
  ('d_st07', 'layer_d', 'D', 106, '나를 위해 레퍼런스 체크에 응해줄 사람이 있다.', 'strong_ties', 'likert7', false, '{"section":"network","subscale":"strong_ties","crossTags":["SP:Interpersonal"]}'::jsonb),
  ('d_st08', 'layer_d', 'D', 107, '기업 의사결정자(CEO, 임원급)와 직접 소통할 수 있는 관계가 있다.', 'strong_ties', 'likert7', false, '{"section":"network","subscale":"strong_ties","crossTags":["BT:D","SP:Strategic"]}'::jsonb),
  ('d_st09', 'layer_d', 'D', 108, '내 네트워크가 경력 전환에 실질적 도움이 될 것이라 확신한다.', 'strong_ties', 'likert7', false, '{"section":"network","subscale":"strong_ties","crossTags":["UF:self"]}'::jsonb),
  ('d_st10', 'layer_d', 'D', 109, '관계 유지를 위해 의식적으로 시간을 투자한다.', 'strong_ties', 'likert7', false, '{"section":"network","subscale":"strong_ties","crossTags":["PT:J","BT:I"]}'::jsonb),
  ('d_wt01', 'layer_d', 'D', 110, '업계 행사나 컨퍼런스에서 새로운 사람을 만나는 것을 즐긴다.', 'weak_ties', 'likert7', false, '{"section":"network","subscale":"weak_ties","crossTags":["PT:E","BT:I"]}'::jsonb),
  ('d_wt02', 'layer_d', 'D', 111, '링크드인 등 전문 네트워크에서 활발하게 활동한다.', 'weak_ties', 'likert7', false, '{"section":"network","subscale":"weak_ties","crossTags":["BT:I","PT:E"]}'::jsonb),
  ('d_wt03', 'layer_d', 'D', 112, '다른 산업의 사람들과도 자연스럽게 대화할 수 있다.', 'weak_ties', 'likert7', false, '{"section":"network","subscale":"weak_ties","crossTags":["PT:E","SP:Interpersonal"]}'::jsonb),
  ('d_wt04', 'layer_d', 'D', 113, '예상치 못한 곳에서 기회가 온 경험이 있다.', 'weak_ties', 'likert7', false, '{"section":"network","subscale":"weak_ties","crossTags":["PT:P"]}'::jsonb),
  ('d_wt05', 'layer_d', 'D', 114, '내 전문성을 외부에 알리는 활동(기고, SNS, 강연)을 한다.', 'weak_ties', 'likert7', false, '{"section":"network","subscale":"weak_ties","crossTags":["BT:I"]}'::jsonb),
  ('d_wt06', 'layer_d', 'D', 115, '헤드헌터와 관계를 유지하고 있다.', 'weak_ties', 'likert7', false, '{"section":"network","subscale":"weak_ties","crossTags":["SP:Strategic"]}'::jsonb),
  ('d_wt07', 'layer_d', 'D', 116, '동문회, 직무 커뮤니티 등에 소속되어 있다.', 'weak_ties', 'likert7', false, '{"section":"network","subscale":"weak_ties","crossTags":["BT:S"]}'::jsonb),
  ('d_wt08', 'layer_d', 'D', 117, '나의 존재를 모르는 사람에게도 가치를 전달할 수 있는 채널이 있다.', 'weak_ties', 'likert7', false, '{"section":"network","subscale":"weak_ties","crossTags":["BT:I","SP:Strategic"]}'::jsonb),
  ('d_wt09', 'layer_d', 'D', 118, '우연한 만남에서도 기회를 포착하는 편이다.', 'weak_ties', 'likert7', false, '{"section":"network","subscale":"weak_ties","crossTags":["PT:P","BT:D"]}'::jsonb),
  ('d_wt10', 'layer_d', 'D', 119, '넓은 네트워크보다 깊은 네트워크가 중요하다고 생각한다.', 'weak_ties', 'likert7', false, '{"section":"network","subscale":"weak_ties","crossTags":["BT:S"]}'::jsonb),
  ('d_po01', 'layer_d', 'D', 120, '"왜 지금 이직하는가"에 대한 설득력 있는 답변이 있다.', 'positioning', 'likert7', false, '{"section":"readiness","subscale":"positioning","crossTags":["BT:I","PT:T"]}'::jsonb),
  ('d_po02', 'layer_d', 'D', 121, '내 경력 스토리를 3분 안에 매력적으로 전달할 수 있다.', 'positioning', 'likert7', false, '{"section":"readiness","subscale":"positioning","crossTags":["BT:I"]}'::jsonb),
  ('d_po03', 'layer_d', 'D', 122, '목표 기업이 나를 뽑아야 하는 이유를 명확히 설명할 수 있다.', 'positioning', 'likert7', false, '{"section":"readiness","subscale":"positioning","crossTags":["SP:Strategic","BT:D"]}'::jsonb),
  ('d_po04', 'layer_d', 'D', 123, '과거 이직 경험을 성장 스토리로 설명할 수 있다.', 'positioning', 'likert7', false, '{"section":"readiness","subscale":"positioning","crossTags":["UF:trauma"]}'::jsonb),
  ('d_po05', 'layer_d', 'D', 124, '고년차로서의 강점(경험, 안정성, 네트워크)을 어필할 수 있다.', 'positioning', 'likert7', false, '{"section":"readiness","subscale":"positioning","crossTags":["SP:all"]}'::jsonb),
  ('d_cm01', 'layer_d', 'D', 125, '내 시장 가치(연봉 수준)를 객관적으로 파악하고 있다.', 'compensation', 'likert7', false, '{"section":"readiness","subscale":"compensation","crossTags":["PT:T","SP:Analytical"]}'::jsonb),
  ('d_cm02', 'layer_d', 'D', 126, '연봉 외 조건(직급, 권한, 성과급 등)도 전략적으로 협상할 수 있다.', 'compensation', 'likert7', false, '{"section":"readiness","subscale":"compensation","crossTags":["BT:D","SP:Strategic"]}'::jsonb),
  ('d_cm03', 'layer_d', 'D', 127, '보상 수준이 현재보다 낮아지면 이직하지 않겠다.', 'compensation', 'likert7', true, '{"section":"readiness","subscale":"compensation","crossTags":["BT:S"]}'::jsonb),
  ('d_cm04', 'layer_d', 'D', 128, '이직 시 기대 연봉의 합리적 근거를 제시할 수 있다.', 'compensation', 'likert7', false, '{"section":"readiness","subscale":"compensation","crossTags":["PT:T","BT:C"]}'::jsonb),
  ('d_cm05', 'layer_d', 'D', 129, '단기 보상보다 중장기 경력 가치를 우선시할 수 있다.', 'compensation', 'likert7', false, '{"section":"readiness","subscale":"compensation","crossTags":["PT:N","SP:Strategic"]}'::jsonb),
  ('d_rf01', 'layer_d', 'D', 130, '레퍼런스 체크에 대비한 준비가 되어 있다.', 'reference', 'likert7', false, '{"section":"readiness","subscale":"reference","crossTags":["PT:J"]}'::jsonb),
  ('d_rf02', 'layer_d', 'D', 131, '경쟁사 이직 시 비경쟁 조항 등 법적 이슈를 확인했다.', 'reference', 'likert7', false, '{"section":"readiness","subscale":"reference","crossTags":["BT:C","PT:T"]}'::jsonb),
  ('d_rf03', 'layer_d', 'D', 132, '이직 기간이 3개월 이상 걸려도 인내할 수 있다.', 'reference', 'likert7', false, '{"section":"readiness","subscale":"reference","crossTags":["CH:emotional","UF:self"]}'::jsonb),
  ('d_rf04', 'layer_d', 'D', 133, '현 직장에서의 퇴사 프로세스를 전략적으로 계획하고 있다.', 'reference', 'likert7', false, '{"section":"readiness","subscale":"reference","crossTags":["PT:J","CH:integrity"]}'::jsonb),
  ('d_rf05', 'layer_d', 'D', 134, '이직 과정에서 현 직장에 미칠 영향을 고려하고 있다.', 'reference', 'likert7', false, '{"section":"readiness","subscale":"reference","crossTags":["CH:ethics","BT:S"]}'::jsonb),
  ('d_sp01', 'layer_d', 'D', 135, '10년 이상 쌓은 조직 내 위상을 포기하는 것이 두렵다.', 'senior_psych', 'likert7', true, '{"section":"readiness","subscale":"senior_psych","crossTags":["UF:self","CH:emotional"]}'::jsonb),
  ('d_sp02', 'layer_d', 'D', 136, '새 조직에서 다시 증명해야 한다는 것을 수용한다.', 'senior_psych', 'likert7', false, '{"section":"readiness","subscale":"senior_psych","crossTags":["CH:growth","BT:D"]}'::jsonb),
  ('d_sp03', 'layer_d', 'D', 137, '이직이 실패해도 다시 시도할 의지가 있다.', 'senior_psych', 'likert7', false, '{"section":"readiness","subscale":"senior_psych","crossTags":["UF:self","SP:Breakthrough"]}'::jsonb),
  ('d_sp04', 'layer_d', 'D', 138, '변화가 내 삶의 질을 향상시킬 것이라 기대한다.', 'senior_psych', 'likert7', false, '{"section":"readiness","subscale":"senior_psych","crossTags":["CH:growth"]}'::jsonb),
  ('d_sp05', 'layer_d', 'D', 139, '이직은 새로운 성장의 시작이라고 확신한다.', 'senior_psych', 'likert7', false, '{"section":"readiness","subscale":"senior_psych","crossTags":["SP:Breakthrough","UF:self"]}'::jsonb),
  ('d_val01', 'layer_d', 'D', 140, '나는 부하 직원과 한 번도 갈등을 겪은 적이 없다.', 'DECOY', 'likert7', false, '{"section":"decoy","subscale":"DECOY","crossTags":[]}'::jsonb),
  ('d_val02', 'layer_d', 'D', 141, '내가 내린 경영 판단은 항상 옳았다.', 'DECOY', 'likert7', false, '{"section":"decoy","subscale":"DECOY","crossTags":[]}'::jsonb);
