-- HIT Layer E: 142문항 (140 + 미끼 2)
-- HIT_E_Final.md 설계서 기반
-- 자동 생성: Scripts/seed-hit-layer-e.js

DELETE FROM public.hit_questions WHERE module = 'layer_e';

INSERT INTO public.hit_questions
  (id, module, test_type, question_index, question_text, sub_domain, response_type, reverse_scored, scoring_key)
VALUES
  ('e_ls01', 'layer_e', 'E', 0, '지금까지의 삶을 전체적으로 돌아보면 만족스럽다.', 'life_satisfaction', 'likert7', false, '{"section":"satisfaction","subscale":"life_satisfaction","crossTags":["UF:all"]}'::jsonb),
  ('e_ls02', 'layer_e', 'E', 1, '직업 생활에서 의미 있는 성취를 이루었다.', 'life_satisfaction', 'likert7', false, '{"section":"satisfaction","subscale":"life_satisfaction","crossTags":["SP:Execution"]}'::jsonb),
  ('e_ls03', 'layer_e', 'E', 2, '인간관계에서 깊은 유대를 경험했다.', 'life_satisfaction', 'likert7', false, '{"section":"satisfaction","subscale":"life_satisfaction","crossTags":["BT:S","BT:I","UF:peer"]}'::jsonb),
  ('e_ls04', 'layer_e', 'E', 3, '내가 선택한 길이 대체로 옳았다고 생각한다.', 'life_satisfaction', 'likert7', false, '{"section":"satisfaction","subscale":"life_satisfaction","crossTags":["UF:self"]}'::jsonb),
  ('e_ls05', 'layer_e', 'E', 4, '과거의 실패와 실수를 수용하고 있다.', 'life_satisfaction', 'likert7', false, '{"section":"satisfaction","subscale":"life_satisfaction","crossTags":["UF:trauma"]}'::jsonb),
  ('e_ls06', 'layer_e', 'E', 5, '나는 가치 있는 삶을 살아왔다.', 'life_satisfaction', 'likert7', false, '{"section":"satisfaction","subscale":"life_satisfaction","crossTags":["CH:ethics","UF:self"]}'::jsonb),
  ('e_ls07', 'layer_e', 'E', 6, '후회되는 선택이 있지만 그것도 나를 만든 일부다.', 'life_satisfaction', 'likert7', false, '{"section":"satisfaction","subscale":"life_satisfaction","crossTags":["UF:trauma"]}'::jsonb),
  ('e_ls08', 'layer_e', 'E', 7, '가정생활과 직업생활의 균형에 만족한다.', 'life_satisfaction', 'likert7', false, '{"section":"satisfaction","subscale":"life_satisfaction","crossTags":["UF:family"]}'::jsonb),
  ('e_ls09', 'layer_e', 'E', 8, '내 삶이 다른 사람에게 긍정적 영향을 주었다고 생각한다.', 'life_satisfaction', 'likert7', false, '{"section":"satisfaction","subscale":"life_satisfaction","crossTags":["SP:Harmony","CH:ethics"]}'::jsonb),
  ('e_ls10', 'layer_e', 'E', 9, '인생을 다시 산다면 비슷한 선택을 할 것이다.', 'life_satisfaction', 'likert7', false, '{"section":"satisfaction","subscale":"life_satisfaction","crossTags":["UF:self"]}'::jsonb),
  ('e_ls11', 'layer_e', 'E', 10, '아직 하지 못한 것에 대한 미련이 크다.', 'life_satisfaction', 'likert7', true, '{"section":"satisfaction","subscale":"life_satisfaction","crossTags":["CH:growth"]}'::jsonb),
  ('e_ls12', 'layer_e', 'E', 11, '내 인생의 전반전 점수를 매긴다면 합격점이다.', 'life_satisfaction', 'likert7', false, '{"section":"satisfaction","subscale":"life_satisfaction","crossTags":["UF:self"]}'::jsonb),
  ('e_rp01', 'layer_e', 'E', 12, '아직 이루고 싶은 것이 분명하게 있다.', 'residual_passion', 'likert7', false, '{"section":"satisfaction","subscale":"residual_passion","crossTags":["CH:growth","SP:Breakthrough"]}'::jsonb),
  ('e_rp02', 'layer_e', 'E', 13, '새로운 것을 배우고 싶은 욕구가 강하다.', 'residual_passion', 'likert7', false, '{"section":"satisfaction","subscale":"residual_passion","crossTags":["CH:growth"]}'::jsonb),
  ('e_rp03', 'layer_e', 'E', 14, '은퇴 후에도 일(넓은 의미에서)을 하고 싶다.', 'residual_passion', 'likert7', false, '{"section":"satisfaction","subscale":"residual_passion","crossTags":["BT:D","SP:Execution"]}'::jsonb),
  ('e_rp04', 'layer_e', 'E', 15, '특정 분야에 대한 열정이 나이와 무관하게 살아있다.', 'residual_passion', 'likert7', false, '{"section":"satisfaction","subscale":"residual_passion","crossTags":["AP:top","CH:growth"]}'::jsonb),
  ('e_rp05', 'layer_e', 'E', 16, '아침에 일어나면 하고 싶은 일이 있다.', 'residual_passion', 'likert7', false, '{"section":"satisfaction","subscale":"residual_passion","crossTags":["CH:emotional"]}'::jsonb),
  ('e_rp06', 'layer_e', 'E', 17, '체력이 허락한다면 도전하고 싶은 일이 있다.', 'residual_passion', 'likert7', false, '{"section":"satisfaction","subscale":"residual_passion","crossTags":["CH:adventure"]}'::jsonb),
  ('e_rp07', 'layer_e', 'E', 18, '취미나 관심사에 몰입하면 시간 가는 줄 모른다.', 'residual_passion', 'likert7', false, '{"section":"satisfaction","subscale":"residual_passion","crossTags":["AP:direction"]}'::jsonb),
  ('e_rp08', 'layer_e', 'E', 19, '사회에 기여하고 싶은 구체적인 방법이 있다.', 'residual_passion', 'likert7', false, '{"section":"satisfaction","subscale":"residual_passion","crossTags":["CH:ethics","AP:S"]}'::jsonb),
  ('e_rp09', 'layer_e', 'E', 20, '젊었을 때 못했던 일을 지금이라도 하고 싶다.', 'residual_passion', 'likert7', false, '{"section":"satisfaction","subscale":"residual_passion","crossTags":["UF:trauma","SP:Breakthrough"]}'::jsonb),
  ('e_rp10', 'layer_e', 'E', 21, '일하지 않으면 무기력해질 것 같다.', 'residual_passion', 'likert7', true, '{"section":"satisfaction","subscale":"residual_passion","crossTags":["CH:emotional"]}'::jsonb),
  ('e_rp11', 'layer_e', 'E', 22, '돈과 무관하게 하고 싶은 활동이 있다.', 'residual_passion', 'likert7', false, '{"section":"satisfaction","subscale":"residual_passion","crossTags":["AP:direction"]}'::jsonb),
  ('e_rp12', 'layer_e', 'E', 23, '내 열정의 방향이 직업 생활과는 다를 수 있다.', 'residual_passion', 'likert7', false, '{"section":"satisfaction","subscale":"residual_passion","crossTags":["PT:N","AP:change"]}'::jsonb),
  ('e_pt01', 'layer_e', 'E', 24, '직함이 없어져도 나의 가치는 변하지 않는다고 느낀다.', 'psych_transition', 'likert7', false, '{"section":"satisfaction","subscale":"psych_transition","crossTags":["UF:self"]}'::jsonb),
  ('e_pt02', 'layer_e', 'E', 25, '은퇴/퇴직을 끝이 아닌 새로운 시작으로 보고 있다.', 'psych_transition', 'likert7', false, '{"section":"satisfaction","subscale":"psych_transition","crossTags":["CH:growth"]}'::jsonb),
  ('e_pt03', 'layer_e', 'E', 26, '직업적 정체성 없이도 자신을 설명할 수 있다.', 'psych_transition', 'likert7', false, '{"section":"satisfaction","subscale":"psych_transition","crossTags":["UF:self"]}'::jsonb),
  ('e_pt04', 'layer_e', 'E', 27, '일상의 구조가 바뀌는 것에 대한 불안이 있다.', 'psych_transition', 'likert7', true, '{"section":"satisfaction","subscale":"psych_transition","crossTags":["UF:temperament","CH:emotional"]}'::jsonb),
  ('e_pt05', 'layer_e', 'E', 28, '사회적 지위의 변화를 담담하게 수용할 수 있다.', 'psych_transition', 'likert7', false, '{"section":"satisfaction","subscale":"psych_transition","crossTags":["UF:self","CH:emotional"]}'::jsonb),
  ('e_pt06', 'layer_e', 'E', 29, '새로운 루틴을 만들어갈 자신이 있다.', 'psych_transition', 'likert7', false, '{"section":"satisfaction","subscale":"psych_transition","crossTags":["PT:J","SP:Execution"]}'::jsonb),
  ('e_pt07', 'layer_e', 'E', 30, '나이가 들수록 물질보다 의미가 중요해진다.', 'psych_transition', 'likert7', false, '{"section":"satisfaction","subscale":"psych_transition","crossTags":["CH:ethics"]}'::jsonb),
  ('e_pt08', 'layer_e', 'E', 31, '은퇴 후의 나를 긍정적으로 상상할 수 있다.', 'psych_transition', 'likert7', false, '{"section":"satisfaction","subscale":"psych_transition","crossTags":["PT:N","CH:emotional"]}'::jsonb),
  ('e_re01', 'layer_e', 'E', 32, '경험을 살려 다른 조직에서 다시 일하고 싶다.', 're_employment', 'likert7', false, '{"section":"direction","subscale":"re_employment","crossTags":["BT:S","SP:Execution"]}'::jsonb),
  ('e_re02', 'layer_e', 'E', 33, '유연한 조건(파트타임, 계약직 등)이라도 일하고 싶다.', 're_employment', 'likert7', false, '{"section":"direction","subscale":"re_employment","crossTags":["PT:P"]}'::jsonb),
  ('e_re03', 'layer_e', 'E', 34, '후배 세대와 함께 일하는 것이 즐겁다.', 're_employment', 'likert7', false, '{"section":"direction","subscale":"re_employment","crossTags":["BT:I","UF:cultural"]}'::jsonb),
  ('e_re04', 'layer_e', 'E', 35, '내 경험이 필요한 곳이 있을 것이라 생각한다.', 're_employment', 'likert7', false, '{"section":"direction","subscale":"re_employment","crossTags":["UF:self","SP:all"]}'::jsonb),
  ('e_re05', 'layer_e', 'E', 36, '조직에 소속되어 있는 것이 심리적 안정감을 준다.', 're_employment', 'likert7', false, '{"section":"direction","subscale":"re_employment","crossTags":["BT:S","UF:peer"]}'::jsonb),
  ('e_re06', 'layer_e', 'E', 37, '재취업을 위한 구체적인 활동을 하고 있다.', 're_employment', 'likert7', false, '{"section":"direction","subscale":"re_employment","crossTags":["PT:J","SP:Execution"]}'::jsonb),
  ('e_en01', 'layer_e', 'E', 38, '내 사업을 시작하고 싶은 구체적인 아이디어가 있다.', 'entrepreneurship', 'likert7', false, '{"section":"direction","subscale":"entrepreneurship","crossTags":["BT:D","AP:E","SP:Creativity"]}'::jsonb),
  ('e_en02', 'layer_e', 'E', 39, '소규모라도 독립적으로 운영할 수 있는 자신감이 있다.', 'entrepreneurship', 'likert7', false, '{"section":"direction","subscale":"entrepreneurship","crossTags":["BT:D","UF:self"]}'::jsonb),
  ('e_en03', 'layer_e', 'E', 40, '리스크를 감수하더라도 내 이름으로 일하고 싶다.', 'entrepreneurship', 'likert7', false, '{"section":"direction","subscale":"entrepreneurship","crossTags":["BT:D","CH:adventure"]}'::jsonb),
  ('e_en04', 'layer_e', 'E', 41, '창업에 필요한 자금이나 자원을 확보할 수 있다.', 'entrepreneurship', 'likert7', false, '{"section":"direction","subscale":"entrepreneurship","crossTags":["PT:S"]}'::jsonb),
  ('e_en05', 'layer_e', 'E', 42, '사업 실패의 가능성도 수용할 수 있다.', 'entrepreneurship', 'likert7', false, '{"section":"direction","subscale":"entrepreneurship","crossTags":["CH:emotional","UF:trauma"]}'::jsonb),
  ('e_en06', 'layer_e', 'E', 43, '과거 업무 경험에서 사업 아이디어의 씨앗을 발견했다.', 'entrepreneurship', 'likert7', false, '{"section":"direction","subscale":"entrepreneurship","crossTags":["PT:N","SP:Strategic"]}'::jsonb),
  ('e_sc01', 'layer_e', 'E', 44, '보상 없이도 사회를 위해 기여하고 싶다.', 'social_contribution', 'likert7', false, '{"section":"direction","subscale":"social_contribution","crossTags":["CH:ethics","AP:S"]}'::jsonb),
  ('e_sc02', 'layer_e', 'E', 45, '비영리단체나 시민사회 활동에 관심이 있다.', 'social_contribution', 'likert7', false, '{"section":"direction","subscale":"social_contribution","crossTags":["AP:S","CH:ethics"]}'::jsonb),
  ('e_sc03', 'layer_e', 'E', 46, '내 경험이 소외된 사람들에게 도움이 될 수 있다.', 'social_contribution', 'likert7', false, '{"section":"direction","subscale":"social_contribution","crossTags":["SP:Harmony","BT:S"]}'::jsonb),
  ('e_sc04', 'layer_e', 'E', 47, '봉사활동을 통해 삶의 의미를 찾을 수 있다고 생각한다.', 'social_contribution', 'likert7', false, '{"section":"direction","subscale":"social_contribution","crossTags":["CH:ethics"]}'::jsonb),
  ('e_sc05', 'layer_e', 'E', 48, '사회 문제 해결에 직접 참여하고 싶은 분야가 있다.', 'social_contribution', 'likert7', false, '{"section":"direction","subscale":"social_contribution","crossTags":["AP:S","SP:Breakthrough"]}'::jsonb),
  ('e_mt01', 'layer_e', 'E', 49, '후배 세대에게 내 경험을 전수하고 싶다.', 'mentoring', 'likert7', false, '{"section":"direction","subscale":"mentoring","crossTags":["AP:S","BT:I"]}'::jsonb),
  ('e_mt02', 'layer_e', 'E', 50, '가르치는 것에서 보람을 느낀다.', 'mentoring', 'likert7', false, '{"section":"direction","subscale":"mentoring","crossTags":["AP:S"]}'::jsonb),
  ('e_mt03', 'layer_e', 'E', 51, '강의, 코칭, 멘토링을 해본 경험이 있다.', 'mentoring', 'likert7', false, '{"section":"direction","subscale":"mentoring","crossTags":["BT:I"]}'::jsonb),
  ('e_mt04', 'layer_e', 'E', 52, '내 전문 분야의 교육 콘텐츠를 만들 수 있다.', 'mentoring', 'likert7', false, '{"section":"direction","subscale":"mentoring","crossTags":["SP:Strategic","BT:C"]}'::jsonb),
  ('e_mt05', 'layer_e', 'E', 53, '학교나 교육기관에서 일하는 것에 관심이 있다.', 'mentoring', 'likert7', false, '{"section":"direction","subscale":"mentoring","crossTags":["AP:S"]}'::jsonb),
  ('e_mt06', 'layer_e', 'E', 54, '내 실패 경험까지 포함하여 솔직하게 전달할 수 있다.', 'mentoring', 'likert7', false, '{"section":"direction","subscale":"mentoring","crossTags":["UF:trauma","CH:integrity"]}'::jsonb),
  ('e_sr01', 'layer_e', 'E', 55, '일과 무관한 취미나 관심사에 몰두하고 싶다.', 'leisure', 'likert7', false, '{"section":"direction","subscale":"leisure","crossTags":["AP:A","PT:P"]}'::jsonb),
  ('e_sr02', 'layer_e', 'E', 56, '여행, 문화, 예술 등 새로운 경험을 원한다.', 'leisure', 'likert7', false, '{"section":"direction","subscale":"leisure","crossTags":["CH:adventure"]}'::jsonb),
  ('e_sr03', 'layer_e', 'E', 57, '건강 관리와 체력 유지가 최우선 과제다.', 'leisure', 'likert7', false, '{"section":"direction","subscale":"leisure","crossTags":["PT:S"]}'::jsonb),
  ('e_sr04', 'layer_e', 'E', 58, '느리게 사는 것도 가치 있는 삶이라고 생각한다.', 'leisure', 'likert7', false, '{"section":"direction","subscale":"leisure","crossTags":["PT:P","BT:S"]}'::jsonb),
  ('e_sr05', 'layer_e', 'E', 59, '특별한 역할 없이도 충분히 행복할 수 있다.', 'leisure', 'likert7', false, '{"section":"direction","subscale":"leisure","crossTags":["UF:self"]}'::jsonb),
  ('e_tl01', 'layer_e', 'E', 60, '수십 년간 쌓은 판단력과 통찰력이 여전히 날카롭다.', 'transferable_legacy', 'likert7', false, '{"section":"legacy","subscale":"transferable_legacy","crossTags":["SP:Strategic"]}'::jsonb),
  ('e_tl02', 'layer_e', 'E', 61, '위기 관리 경험이 어떤 환경에서든 유용할 것이다.', 'transferable_legacy', 'likert7', false, '{"section":"legacy","subscale":"transferable_legacy","crossTags":["SP:Breakthrough","UF:trauma"]}'::jsonb),
  ('e_tl03', 'layer_e', 'E', 62, '사람을 다루고 조율하는 능력이 핵심 자산이다.', 'transferable_legacy', 'likert7', false, '{"section":"legacy","subscale":"transferable_legacy","crossTags":["SP:Interpersonal","BT:I","BT:S"]}'::jsonb),
  ('e_tl04', 'layer_e', 'E', 63, '업무 외 영역에서도 활용할 수 있는 기획·분석 능력이 있다.', 'transferable_legacy', 'likert7', false, '{"section":"legacy","subscale":"transferable_legacy","crossTags":["SP:Analytical","SP:Strategic"]}'::jsonb),
  ('e_tl05', 'layer_e', 'E', 64, '글쓰기, 발표, 소통 능력이 다른 맥락에서도 쓸모 있다.', 'transferable_legacy', 'likert7', false, '{"section":"legacy","subscale":"transferable_legacy","crossTags":["BT:I","SP:Interpersonal"]}'::jsonb),
  ('e_tl06', 'layer_e', 'E', 65, '네트워크(인맥)가 2막에서도 자산이 될 것이다.', 'transferable_legacy', 'likert7', false, '{"section":"legacy","subscale":"transferable_legacy","crossTags":["BT:I"]}'::jsonb),
  ('e_tl07', 'layer_e', 'E', 66, '문제를 정의하고 해결하는 사고 프레임이 체화되어 있다.', 'transferable_legacy', 'likert7', false, '{"section":"legacy","subscale":"transferable_legacy","crossTags":["SP:Analytical","PT:T"]}'::jsonb),
  ('e_tl08', 'layer_e', 'E', 67, '협상과 설득 능력을 직업 외 상황에서도 발휘할 수 있다.', 'transferable_legacy', 'likert7', false, '{"section":"legacy","subscale":"transferable_legacy","crossTags":["BT:D","BT:I"]}'::jsonb),
  ('e_tl09', 'layer_e', 'E', 68, '재무·경영 감각이 개인 사업이나 투자에 도움이 된다.', 'transferable_legacy', 'likert7', false, '{"section":"legacy","subscale":"transferable_legacy","crossTags":["SP:Analytical"]}'::jsonb),
  ('e_tl10', 'layer_e', 'E', 69, '내 역량 중 어떤 것이 2막에서 가장 가치 있을지 알고 있다.', 'transferable_legacy', 'likert7', false, '{"section":"legacy","subscale":"transferable_legacy","crossTags":["UF:self","SP:Strategic"]}'::jsonb),
  ('e_kt01', 'layer_e', 'E', 70, '내가 알고 있는 것을 책이나 글로 남기고 싶다.', 'knowledge_transfer', 'likert7', false, '{"section":"legacy","subscale":"knowledge_transfer","crossTags":["AP:A","BT:C"]}'::jsonb),
  ('e_kt02', 'layer_e', 'E', 71, '후배들이 내 실수를 반복하지 않게 도와주고 싶다.', 'knowledge_transfer', 'likert7', false, '{"section":"legacy","subscale":"knowledge_transfer","crossTags":["BT:S","SP:Harmony"]}'::jsonb),
  ('e_kt03', 'layer_e', 'E', 72, '내 분야의 살아있는 역사로서 기록을 남기고 싶다.', 'knowledge_transfer', 'likert7', false, '{"section":"legacy","subscale":"knowledge_transfer","crossTags":["SP:Guard"]}'::jsonb),
  ('e_kt04', 'layer_e', 'E', 73, '내 노하우를 시스템이나 매뉴얼로 정리할 수 있다.', 'knowledge_transfer', 'likert7', false, '{"section":"legacy","subscale":"knowledge_transfer","crossTags":["BT:C","PT:J"]}'::jsonb),
  ('e_kt05', 'layer_e', 'E', 74, '나만 아는 것이 사라지는 것이 아까운 느낌이 든다.', 'knowledge_transfer', 'likert7', false, '{"section":"legacy","subscale":"knowledge_transfer","crossTags":["SP:Guard"]}'::jsonb),
  ('e_kt06', 'layer_e', 'E', 75, '유튜브, 블로그, 팟캐스트 등으로 지식을 공유하고 싶다.', 'knowledge_transfer', 'likert7', false, '{"section":"legacy","subscale":"knowledge_transfer","crossTags":["BT:I","PT:E"]}'::jsonb),
  ('e_kt07', 'layer_e', 'E', 76, '대학이나 교육기관에서 실무 경험을 가르치고 싶다.', 'knowledge_transfer', 'likert7', false, '{"section":"legacy","subscale":"knowledge_transfer","crossTags":["AP:S"]}'::jsonb),
  ('e_kt08', 'layer_e', 'E', 77, '내 경험을 콘텐츠로 만들면 사람들이 관심을 가질 것이다.', 'knowledge_transfer', 'likert7', false, '{"section":"legacy","subscale":"knowledge_transfer","crossTags":["UF:self"]}'::jsonb),
  ('e_kt09', 'layer_e', 'E', 78, '지식 전수보다 내 시간을 즐기는 것이 더 중요하다.', 'knowledge_transfer', 'likert7', true, '{"section":"legacy","subscale":"knowledge_transfer","crossTags":["PT:P"]}'::jsonb),
  ('e_kt10', 'layer_e', 'E', 79, '멘티가 성장하는 것을 보면 가장 큰 보람을 느낀다.', 'knowledge_transfer', 'likert7', false, '{"section":"legacy","subscale":"knowledge_transfer","crossTags":["BT:S","AP:S"]}'::jsonb),
  ('e_nc01', 'layer_e', 'E', 80, '이 나이에 새로운 기술을 배우는 것이 두렵지 않다.', 'new_capability', 'likert7', false, '{"section":"legacy","subscale":"new_capability","crossTags":["CH:growth","UF:temperament"]}'::jsonb),
  ('e_nc02', 'layer_e', 'E', 81, '디지털 도구를 능숙하게 다룬다.', 'new_capability', 'likert7', false, '{"section":"legacy","subscale":"new_capability","crossTags":["PT:S"]}'::jsonb),
  ('e_nc03', 'layer_e', 'E', 82, '온라인 강좌나 교육 프로그램을 수강한 경험이 있다.', 'new_capability', 'likert7', false, '{"section":"legacy","subscale":"new_capability","crossTags":["CH:growth"]}'::jsonb),
  ('e_nc04', 'layer_e', 'E', 83, '젊은 세대의 트렌드와 문화를 이해하려고 노력한다.', 'new_capability', 'likert7', false, '{"section":"legacy","subscale":"new_capability","crossTags":["UF:cultural","CH:growth"]}'::jsonb),
  ('e_nc05', 'layer_e', 'E', 84, '새로운 분야를 공부하면 두뇌가 활성화되는 느낌이다.', 'new_capability', 'likert7', false, '{"section":"legacy","subscale":"new_capability","crossTags":["CH:growth"]}'::jsonb),
  ('e_nc06', 'layer_e', 'E', 85, 'AI, 디지털 전환 등 기술 변화에 관심을 갖고 있다.', 'new_capability', 'likert7', false, '{"section":"legacy","subscale":"new_capability","crossTags":["PT:N","CH:growth"]}'::jsonb),
  ('e_nc07', 'layer_e', 'E', 86, '체력 유지를 위한 규칙적인 활동을 하고 있다.', 'new_capability', 'likert7', false, '{"section":"legacy","subscale":"new_capability","crossTags":["PT:J"]}'::jsonb),
  ('e_nc08', 'layer_e', 'E', 87, '새로운 언어(외국어 포함)를 배우는 것에 관심이 있다.', 'new_capability', 'likert7', false, '{"section":"legacy","subscale":"new_capability","crossTags":["CH:growth"]}'::jsonb),
  ('e_nc09', 'layer_e', 'E', 88, '나이를 핑계로 새로운 시도를 포기하고 싶지 않다.', 'new_capability', 'likert7', false, '{"section":"legacy","subscale":"new_capability","crossTags":["SP:Breakthrough","UF:self"]}'::jsonb),
  ('e_nc10', 'layer_e', 'E', 89, '2막을 위해 지금부터 준비해야 할 역량이 무엇인지 안다.', 'new_capability', 'likert7', false, '{"section":"legacy","subscale":"new_capability","crossTags":["SP:Strategic","UF:self"]}'::jsonb),
  ('e_nc11', 'layer_e', 'E', 90, '실패해도 배울 수 있다면 시도할 가치가 있다.', 'new_capability', 'likert7', false, '{"section":"legacy","subscale":"new_capability","crossTags":["CH:adventure"]}'::jsonb),
  ('e_nc12', 'layer_e', 'E', 91, '전문 분야 외의 교양(인문학, 예술, 철학)에 관심이 있다.', 'new_capability', 'likert7', false, '{"section":"legacy","subscale":"new_capability","crossTags":["AP:A","AP:I","CH:growth"]}'::jsonb),
  ('e_bl01', 'layer_e', 'E', 92, '어딘가에 소속되어 있는 것이 심리적으로 중요하다.', 'belonging', 'likert7', false, '{"section":"social","subscale":"belonging","crossTags":["BT:S","UF:peer"]}'::jsonb),
  ('e_bl02', 'layer_e', 'E', 93, '정기적으로 만나는 그룹이나 모임이 있다.', 'belonging', 'likert7', false, '{"section":"social","subscale":"belonging","crossTags":["BT:I"]}'::jsonb),
  ('e_bl03', 'layer_e', 'E', 94, '혼자 있는 시간이 길어지면 불안해진다.', 'belonging', 'likert7', true, '{"section":"social","subscale":"belonging","crossTags":["PT:E","CH:emotional"]}'::jsonb),
  ('e_bl04', 'layer_e', 'E', 95, '가족 외에 나를 필요로 하는 사람이 있었으면 좋겠다.', 'belonging', 'likert7', false, '{"section":"social","subscale":"belonging","crossTags":["UF:peer"]}'::jsonb),
  ('e_bl05', 'layer_e', 'E', 96, '직장을 떠나면 사회적 고립이 걱정된다.', 'belonging', 'likert7', true, '{"section":"social","subscale":"belonging","crossTags":["CH:emotional"]}'::jsonb),
  ('e_bl06', 'layer_e', 'E', 97, '새로운 커뮤니티를 찾아 참여할 의지가 있다.', 'belonging', 'likert7', false, '{"section":"social","subscale":"belonging","crossTags":["BT:I","CH:growth"]}'::jsonb),
  ('e_bl07', 'layer_e', 'E', 98, '은퇴 후에도 사회적 역할이 필요하다고 느낀다.', 'belonging', 'likert7', false, '{"section":"social","subscale":"belonging","crossTags":["BT:D"]}'::jsonb),
  ('e_bl08', 'layer_e', 'E', 99, '온라인 커뮤니티도 의미 있는 소속 경험이 될 수 있다.', 'belonging', 'likert7', false, '{"section":"social","subscale":"belonging","crossTags":["PT:P"]}'::jsonb),
  ('e_bl09', 'layer_e', 'E', 100, '세대가 다른 사람들과도 편하게 어울릴 수 있다.', 'belonging', 'likert7', false, '{"section":"social","subscale":"belonging","crossTags":["UF:cultural","BT:I"]}'::jsonb),
  ('e_bl10', 'layer_e', 'E', 101, '고독을 즐기는 편이라 혼자만의 시간도 충분히 가치 있다.', 'belonging', 'likert7', false, '{"section":"social","subscale":"belonging","crossTags":["PT:I","BT:S"]}'::jsonb),
  ('e_rn01', 'layer_e', 'E', 102, '누군가에게 쓸모 있는 사람이고 싶다.', 'role_necessity', 'likert7', false, '{"section":"social","subscale":"role_necessity","crossTags":["UF:self","BT:S"]}'::jsonb),
  ('e_rn02', 'layer_e', 'E', 103, '아무 역할도 없으면 존재 가치를 느끼기 어렵다.', 'role_necessity', 'likert7', true, '{"section":"social","subscale":"role_necessity","crossTags":["UF:self"]}'::jsonb),
  ('e_rn03', 'layer_e', 'E', 104, '가정 내에서 새로운 역할(가사, 육아 지원 등)을 수용할 수 있다.', 'role_necessity', 'likert7', false, '{"section":"social","subscale":"role_necessity","crossTags":["BT:S","PT:P"]}'::jsonb),
  ('e_rn04', 'layer_e', 'E', 105, '지역사회에서 리더 역할을 맡고 싶다.', 'role_necessity', 'likert7', false, '{"section":"social","subscale":"role_necessity","crossTags":["BT:D","AP:E"]}'::jsonb),
  ('e_rn05', 'layer_e', 'E', 106, '은퇴 후에도 명함이 필요하다고 느낀다.', 'role_necessity', 'likert7', false, '{"section":"social","subscale":"role_necessity","crossTags":["UF:self"]}'::jsonb),
  ('e_rn06', 'layer_e', 'E', 107, '타인에게 인정받는 것이 여전히 중요하다.', 'role_necessity', 'likert7', false, '{"section":"social","subscale":"role_necessity","crossTags":["UF:peer"]}'::jsonb),
  ('e_rn07', 'layer_e', 'E', 108, '역할이 없어도 내면의 평화를 유지할 수 있다.', 'role_necessity', 'likert7', false, '{"section":"social","subscale":"role_necessity","crossTags":["UF:self"]}'::jsonb),
  ('e_rn08', 'layer_e', 'E', 109, '작은 역할이라도 꾸준히 하는 것이 건강에 좋다고 생각한다.', 'role_necessity', 'likert7', false, '{"section":"social","subscale":"role_necessity","crossTags":["PT:J"]}'::jsonb),
  ('e_rn09', 'layer_e', 'E', 110, '배우자/가족이 나의 2막 역할에 대해 기대하는 바가 있다.', 'role_necessity', 'likert7', false, '{"section":"social","subscale":"role_necessity","crossTags":["UF:family"]}'::jsonb),
  ('e_rn10', 'layer_e', 'E', 111, '강제로 쉬게 되면 우울해질 것 같다.', 'role_necessity', 'likert7', true, '{"section":"social","subscale":"role_necessity","crossTags":["CH:emotional"]}'::jsonb),
  ('e_tr01', 'layer_e', 'E', 112, '은퇴 후의 하루 일과를 구체적으로 그려볼 수 있다.', 'time_readiness', 'likert7', false, '{"section":"readiness","subscale":"time_readiness","crossTags":["PT:N","PT:J"]}'::jsonb),
  ('e_tr02', 'layer_e', 'E', 113, '구조화된 일정 없이도 하루를 의미 있게 보낼 수 있다.', 'time_readiness', 'likert7', false, '{"section":"readiness","subscale":"time_readiness","crossTags":["PT:P"]}'::jsonb),
  ('e_tr03', 'layer_e', 'E', 114, '자유 시간이 많아지면 할 일의 목록이 있다.', 'time_readiness', 'likert7', false, '{"section":"readiness","subscale":"time_readiness","crossTags":["PT:J"]}'::jsonb),
  ('e_tr04', 'layer_e', 'E', 115, '시간 관리를 스스로 하는 것에 자신이 있다.', 'time_readiness', 'likert7', false, '{"section":"readiness","subscale":"time_readiness","crossTags":["CH:integrity"]}'::jsonb),
  ('e_tr05', 'layer_e', 'E', 116, '무료한 시간을 생산적으로 전환할 수 있다.', 'time_readiness', 'likert7', false, '{"section":"readiness","subscale":"time_readiness","crossTags":["SP:Execution"]}'::jsonb),
  ('e_tr06', 'layer_e', 'E', 117, '아침에 일어날 이유가 직장 외에도 충분히 있다.', 'time_readiness', 'likert7', false, '{"section":"readiness","subscale":"time_readiness","crossTags":["UF:self"]}'::jsonb),
  ('e_tr07', 'layer_e', 'E', 118, '느린 속도의 삶에 적응할 수 있다.', 'time_readiness', 'likert7', false, '{"section":"readiness","subscale":"time_readiness","crossTags":["BT:S","PT:P"]}'::jsonb),
  ('e_er01', 'layer_e', 'E', 119, '현재 체력과 건강 상태로 새로운 활동을 시작할 수 있다.', 'energy_readiness', 'likert7', false, '{"section":"readiness","subscale":"energy_readiness","crossTags":["UF:temperament"]}'::jsonb),
  ('e_er02', 'layer_e', 'E', 120, '스트레스를 관리하는 나만의 방법이 있다.', 'energy_readiness', 'likert7', false, '{"section":"readiness","subscale":"energy_readiness","crossTags":["CH:emotional"]}'::jsonb),
  ('e_er03', 'layer_e', 'E', 121, '정신적 에너지(학습, 집중)가 충분하다.', 'energy_readiness', 'likert7', false, '{"section":"readiness","subscale":"energy_readiness","crossTags":["CH:growth"]}'::jsonb),
  ('e_er04', 'layer_e', 'E', 122, '감정적으로 안정된 상태라고 느낀다.', 'energy_readiness', 'likert7', false, '{"section":"readiness","subscale":"energy_readiness","crossTags":["CH:emotional"]}'::jsonb),
  ('e_er05', 'layer_e', 'E', 123, '건강 검진을 정기적으로 받고 있다.', 'energy_readiness', 'likert7', false, '{"section":"readiness","subscale":"energy_readiness","crossTags":["CH:integrity"]}'::jsonb),
  ('e_er06', 'layer_e', 'E', 124, '2막을 시작할 체력을 만들기 위해 노력하고 있다.', 'energy_readiness', 'likert7', false, '{"section":"readiness","subscale":"energy_readiness","crossTags":["SP:Execution"]}'::jsonb),
  ('e_er07', 'layer_e', 'E', 125, '만성적인 피로나 번아웃 없이 새 출발할 수 있다.', 'energy_readiness', 'likert7', false, '{"section":"readiness","subscale":"energy_readiness","crossTags":["CH:emotional"]}'::jsonb),
  ('e_fr01', 'layer_e', 'E', 126, '은퇴 후 최소 2년간 소득이 없어도 생활할 수 있다.', 'financial_readiness', 'likert7', false, '{"section":"readiness","subscale":"financial_readiness","crossTags":["PT:S"]}'::jsonb),
  ('e_fr02', 'layer_e', 'E', 127, '은퇴 후 예상 지출을 계산해보았다.', 'financial_readiness', 'likert7', false, '{"section":"readiness","subscale":"financial_readiness","crossTags":["PT:S","BT:C"]}'::jsonb),
  ('e_fr03', 'layer_e', 'E', 128, '연금, 저축, 투자 등 노후 자금 계획이 있다.', 'financial_readiness', 'likert7', false, '{"section":"readiness","subscale":"financial_readiness","crossTags":["PT:J","SP:Strategic"]}'::jsonb),
  ('e_fr04', 'layer_e', 'E', 129, '재정적 불안이 2막 선택을 제한하고 있다.', 'financial_readiness', 'likert7', true, '{"section":"readiness","subscale":"financial_readiness","crossTags":["CH:emotional"]}'::jsonb),
  ('e_fr05', 'layer_e', 'E', 130, '수입이 줄어도 삶의 질을 유지할 수 있는 방법을 알고 있다.', 'financial_readiness', 'likert7', false, '{"section":"readiness","subscale":"financial_readiness","crossTags":["SP:Analytical"]}'::jsonb),
  ('e_fr06', 'layer_e', 'E', 131, '재정 상담을 받아본 적이 있다(또는 받을 계획이다).', 'financial_readiness', 'likert7', false, '{"section":"readiness","subscale":"financial_readiness","crossTags":["PT:J"]}'::jsonb),
  ('e_fr07', 'layer_e', 'E', 132, '보상 없이 하고 싶은 일을 할 수 있는 경제적 여유가 있다.', 'financial_readiness', 'likert7', false, '{"section":"readiness","subscale":"financial_readiness","crossTags":["UF:economic"]}'::jsonb),
  ('e_rr01', 'layer_e', 'E', 133, '배우자/가족과 은퇴 후 생활에 대해 충분히 대화했다.', 'relationship_readiness', 'likert7', false, '{"section":"readiness","subscale":"relationship_readiness","crossTags":["UF:family"]}'::jsonb),
  ('e_rr02', 'layer_e', 'E', 134, '직장 동료가 아닌 친구/지인 관계가 충분하다.', 'relationship_readiness', 'likert7', false, '{"section":"readiness","subscale":"relationship_readiness","crossTags":["UF:peer","BT:I"]}'::jsonb),
  ('e_rr03', 'layer_e', 'E', 135, '가족과 더 많은 시간을 보내는 것이 기대된다.', 'relationship_readiness', 'likert7', false, '{"section":"readiness","subscale":"relationship_readiness","crossTags":["UF:family"]}'::jsonb),
  ('e_rr04', 'layer_e', 'E', 136, '은퇴 후 배우자와의 관계 변화에 대해 준비하고 있다.', 'relationship_readiness', 'likert7', false, '{"section":"readiness","subscale":"relationship_readiness","crossTags":["UF:family"]}'::jsonb),
  ('e_rr05', 'layer_e', 'E', 137, '새로운 사람들과 관계를 맺을 의지와 에너지가 있다.', 'relationship_readiness', 'likert7', false, '{"section":"readiness","subscale":"relationship_readiness","crossTags":["BT:I","PT:E"]}'::jsonb),
  ('e_rr06', 'layer_e', 'E', 138, '자녀 세대와 건강한 거리감을 유지하고 있다.', 'relationship_readiness', 'likert7', false, '{"section":"readiness","subscale":"relationship_readiness","crossTags":["UF:family"]}'::jsonb),
  ('e_rr07', 'layer_e', 'E', 139, '은퇴 후의 삶에 대해 주변 사람들의 지지를 받고 있다.', 'relationship_readiness', 'likert7', false, '{"section":"readiness","subscale":"relationship_readiness","crossTags":["UF:peer","UF:family"]}'::jsonb),
  ('e_val01', 'layer_e', 'E', 140, '나는 인생에서 단 한 번도 후회한 적이 없다.', 'DECOY', 'likert7', false, '{"section":"decoy","subscale":"DECOY","crossTags":[]}'::jsonb),
  ('e_val02', 'layer_e', 'E', 141, '나이가 들면서 약해진 부분이 전혀 없다.', 'DECOY', 'likert7', false, '{"section":"decoy","subscale":"DECOY","crossTags":[]}'::jsonb);
