-- HIT Layer F: 154문항 (152 + 미끼 2)
-- 자동 생성: scripts/seed-hit-layer-f.js

DELETE FROM public.hit_questions WHERE module = 'layer_f';

INSERT INTO public.hit_questions
  (id, module, test_type, question_index, question_text, sub_domain, response_type, reverse_scored, scoring_key)
VALUES
  ('f_dc01', 'layer_f', 'F', 1, '경력 단절의 사유를 객관적으로 설명할 수 있다.', 'disruption_context', 'likert7', false, '{"section":"latent_capability","subscale":"disruption_context","crossTags":["PT:T","BT:C"]}'::jsonb),
  ('f_dc02', 'layer_f', 'F', 2, '단절 기간이 나에게 부정적 영향만 준 것은 아니다.', 'disruption_context', 'likert7', false, '{"section":"latent_capability","subscale":"disruption_context","crossTags":["UF:trauma(PTG)"]}'::jsonb),
  ('f_dc03', 'layer_f', 'F', 3, '단절 기간 동안 내가 선택한 것이 있다(돌봄, 학습, 치유 등).', 'disruption_context', 'likert7', false, '{"section":"latent_capability","subscale":"disruption_context","crossTags":["UF:self","SP:Guard"]}'::jsonb),
  ('f_dc04', 'layer_f', 'F', 4, '단절의 이유를 타인에게 솔직하게 말할 수 있다.', 'disruption_context', 'likert7', false, '{"section":"latent_capability","subscale":"disruption_context","crossTags":["CH:integrity","BT:I"]}'::jsonb),
  ('f_dc05', 'layer_f', 'F', 5, '경력 단절이 나의 전문성을 완전히 무효화시켰다고 생각한다.', 'disruption_context', 'likert7', true, '{"section":"latent_capability","subscale":"disruption_context","crossTags":["UF:self"]}'::jsonb),
  ('f_dc06', 'layer_f', 'F', 6, '단절 기간이 길어질수록 복귀가 어려워진다는 두려움이 있다.', 'disruption_context', 'likert7', true, '{"section":"latent_capability","subscale":"disruption_context","crossTags":["CH:emotional"]}'::jsonb),
  ('f_dc07', 'layer_f', 'F', 7, '단절 기간을 "공백"이 아닌 "다른 경험"으로 설명할 수 있다.', 'disruption_context', 'likert7', false, '{"section":"latent_capability","subscale":"disruption_context","crossTags":["UF:trauma(PTG)","SP:Creativity"]}'::jsonb),
  ('f_dc08', 'layer_f', 'F', 8, '비자발적 단절(해고, 질병 등)의 상처를 어느 정도 극복했다.', 'disruption_context', 'likert7', false, '{"section":"latent_capability","subscale":"disruption_context","crossTags":["UF:trauma","CH:emotional"]}'::jsonb),
  ('f_dc09', 'layer_f', 'F', 9, '단절 전 마지막 직무에서의 경험이 여전히 가치 있다고 느낀다.', 'disruption_context', 'likert7', false, '{"section":"latent_capability","subscale":"disruption_context","crossTags":["SP:Guard","UF:self"]}'::jsonb),
  ('f_dc10', 'layer_f', 'F', 10, '단절 기간 동안 사회적 고립을 경험했다.', 'disruption_context', 'likert7', true, '{"section":"latent_capability","subscale":"disruption_context","crossTags":["UF:peer","CH:emotional"]}'::jsonb),
  ('f_dc11', 'layer_f', 'F', 11, '단절의 원인이 해소되었거나 관리 가능한 상태다.', 'disruption_context', 'likert7', false, '{"section":"latent_capability","subscale":"disruption_context","crossTags":["CH:emotional"]}'::jsonb),
  ('f_dc12', 'layer_f', 'F', 12, '복귀 시점을 스스로 결정할 수 있는 상황이다.', 'disruption_context', 'likert7', false, '{"section":"latent_capability","subscale":"disruption_context","crossTags":["BT:D","UF:self"]}'::jsonb),
  ('f_hc01', 'layer_f', 'F', 13, '경력 단절 기간에도 새로운 것을 배운 경험이 있다.', 'hidden_competency', 'likert7', false, '{"section":"latent_capability","subscale":"hidden_competency","crossTags":["CH:growth","SP:Creativity"]}'::jsonb),
  ('f_hc02', 'layer_f', 'F', 14, '돌봄(육아, 간병)을 통해 인내력과 멀티태스킹 능력이 향상되었다.', 'hidden_competency', 'likert7', false, '{"section":"latent_capability","subscale":"hidden_competency","crossTags":["BT:S","SP:Execution"]}'::jsonb),
  ('f_hc03', 'layer_f', 'F', 15, '가사 관리나 가정 운영에서 기획·조직·예산 관리 역량을 발휘했다.', 'hidden_competency', 'likert7', false, '{"section":"latent_capability","subscale":"hidden_competency","crossTags":["SP:Analytical","PT:J"]}'::jsonb),
  ('f_hc04', 'layer_f', 'F', 16, '자원봉사, 커뮤니티 활동 등을 통해 사회적 스킬을 유지했다.', 'hidden_competency', 'likert7', false, '{"section":"latent_capability","subscale":"hidden_competency","crossTags":["BT:I","SP:Interpersonal"]}'::jsonb),
  ('f_hc05', 'layer_f', 'F', 17, '건강 회복 과정에서 자기 관리 능력이 강화되었다.', 'hidden_competency', 'likert7', false, '{"section":"latent_capability","subscale":"hidden_competency","crossTags":["UF:trauma(PTG)","CH:emotional"]}'::jsonb),
  ('f_hc06', 'layer_f', 'F', 18, '독학이나 온라인 학습으로 새로운 스킬을 습득했다.', 'hidden_competency', 'likert7', false, '{"section":"latent_capability","subscale":"hidden_competency","crossTags":["CH:growth"]}'::jsonb),
  ('f_hc07', 'layer_f', 'F', 19, '창작, 글쓰기, 디자인 등 개인 프로젝트를 수행했다.', 'hidden_competency', 'likert7', false, '{"section":"latent_capability","subscale":"hidden_competency","crossTags":["AP:A","SP:Creativity"]}'::jsonb),
  ('f_hc08', 'layer_f', 'F', 20, '단절 기간의 경험이 이전 직무에서 얻지 못한 관점을 주었다.', 'hidden_competency', 'likert7', false, '{"section":"latent_capability","subscale":"hidden_competency","crossTags":["PT:N","SP:Strategic"]}'::jsonb),
  ('f_hc09', 'layer_f', 'F', 21, '나의 비공식 경험이 고용주에게 가치 있을 수 있다고 생각한다.', 'hidden_competency', 'likert7', false, '{"section":"latent_capability","subscale":"hidden_competency","crossTags":["UF:self"]}'::jsonb),
  ('f_hc10', 'layer_f', 'F', 22, '단절 기간 동안 아무런 성장이 없었다고 느낀다.', 'hidden_competency', 'likert7', true, '{"section":"latent_capability","subscale":"hidden_competency","crossTags":["UF:self","CH:emotional"]}'::jsonb),
  ('f_ga01', 'layer_f', 'F', 23, '단절 기간에 자격증, 교육, 수료 등을 취득했다.', 'gap_activities', 'likert7', false, '{"section":"latent_capability","subscale":"gap_activities","crossTags":["CH:growth","PT:J"]}'::jsonb),
  ('f_ga02', 'layer_f', 'F', 24, '프리랜서, 아르바이트, 단기 프로젝트 등으로 업무 감각을 유지했다.', 'gap_activities', 'likert7', false, '{"section":"latent_capability","subscale":"gap_activities","crossTags":["SP:Execution"]}'::jsonb),
  ('f_ga03', 'layer_f', 'F', 25, '직무 관련 커뮤니티나 네트워크에 참여했다.', 'gap_activities', 'likert7', false, '{"section":"latent_capability","subscale":"gap_activities","crossTags":["BT:I"]}'::jsonb),
  ('f_ga04', 'layer_f', 'F', 26, '업계 동향을 꾸준히 파악하고 있었다.', 'gap_activities', 'likert7', false, '{"section":"latent_capability","subscale":"gap_activities","crossTags":["PT:N","SP:Strategic"]}'::jsonb),
  ('f_ga05', 'layer_f', 'F', 27, '단절 기간에 내가 한 활동을 이력서에 포함시킬 수 있다.', 'gap_activities', 'likert7', false, '{"section":"latent_capability","subscale":"gap_activities","crossTags":["BT:C","UF:self"]}'::jsonb),
  ('f_ga06', 'layer_f', 'F', 28, '개인 블로그, SNS, 포트폴리오 등으로 존재감을 유지했다.', 'gap_activities', 'likert7', false, '{"section":"latent_capability","subscale":"gap_activities","crossTags":["BT:I","PT:E"]}'::jsonb),
  ('f_ga07', 'layer_f', 'F', 29, '건강 관리, 체력 회복 등 복귀를 위한 기반을 다졌다.', 'gap_activities', 'likert7', false, '{"section":"latent_capability","subscale":"gap_activities","crossTags":["CH:integrity"]}'::jsonb),
  ('f_ga08', 'layer_f', 'F', 30, '완전히 쉬면서 충전한 시간도 의미 있었다.', 'gap_activities', 'likert7', false, '{"section":"latent_capability","subscale":"gap_activities","crossTags":["UF:trauma","CH:emotional"]}'::jsonb),
  ('f_ga09', 'layer_f', 'F', 31, '복귀를 위한 구체적 준비 활동을 시작했다.', 'gap_activities', 'likert7', false, '{"section":"latent_capability","subscale":"gap_activities","crossTags":["SP:Execution","PT:J"]}'::jsonb),
  ('f_ga10', 'layer_f', 'F', 32, '단절 기간을 전혀 활용하지 못하고 시간만 흘렀다.', 'gap_activities', 'likert7', true, '{"section":"latent_capability","subscale":"gap_activities","crossTags":["CH:emotional","UF:self"]}'::jsonb),
  ('f_jv01', 'layer_f', 'F', 33, '이전 직무가 현재 시장에서도 존재한다.', 'job_viability', 'likert7', false, '{"section":"career_viability","subscale":"job_viability","crossTags":["PT:S","SP:Strategic"]}'::jsonb),
  ('f_jv02', 'layer_f', 'F', 34, '이전 직무의 채용 공고를 최근 확인한 적이 있다.', 'job_viability', 'likert7', false, '{"section":"career_viability","subscale":"job_viability","crossTags":["PT:J","BT:C"]}'::jsonb),
  ('f_jv03', 'layer_f', 'F', 35, '이전 직무가 AI·자동화로 크게 변하지 않았다.', 'job_viability', 'likert7', false, '{"section":"career_viability","subscale":"job_viability","crossTags":["PT:N","SP:Strategic"]}'::jsonb),
  ('f_jv04', 'layer_f', 'F', 36, '이전 업종이 성장세이거나 최소한 유지 중이다.', 'job_viability', 'likert7', false, '{"section":"career_viability","subscale":"job_viability","crossTags":["PT:N"]}'::jsonb),
  ('f_jv05', 'layer_f', 'F', 37, '이전 직무와 동일한 직함의 포지션이 시장에 있다.', 'job_viability', 'likert7', false, '{"section":"career_viability","subscale":"job_viability","crossTags":["SP:Strategic"]}'::jsonb),
  ('f_jv06', 'layer_f', 'F', 38, '이전 직무의 요구 역량이 크게 바뀌지 않았다.', 'job_viability', 'likert7', false, '{"section":"career_viability","subscale":"job_viability","crossTags":["SP:Guard"]}'::jsonb),
  ('f_jv07', 'layer_f', 'F', 39, '이전 직장이나 유사 기업이 여전히 건재하다.', 'job_viability', 'likert7', false, '{"section":"career_viability","subscale":"job_viability","crossTags":["PT:S"]}'::jsonb),
  ('f_jv08', 'layer_f', 'F', 40, '이전 직무의 핵심 업무 방식이 근본적으로 바뀌었다.', 'job_viability', 'likert7', true, '{"section":"career_viability","subscale":"job_viability","crossTags":["PT:N"]}'::jsonb),
  ('f_jv09', 'layer_f', 'F', 41, '내가 했던 업무를 다시 설명하면 현재 고용주도 이해할 것이다.', 'job_viability', 'likert7', false, '{"section":"career_viability","subscale":"job_viability","crossTags":["BT:I","PT:T"]}'::jsonb),
  ('f_jv10', 'layer_f', 'F', 42, '이전 직무 경험이 "경력"으로 인정받을 수 있다고 확신한다.', 'job_viability', 'likert7', false, '{"section":"career_viability","subscale":"job_viability","crossTags":["UF:self"]}'::jsonb),
  ('f_jv11', 'layer_f', 'F', 43, '단절 기간이 채용 과정에서 불이익이 될 것이 걱정된다.', 'job_viability', 'likert7', true, '{"section":"career_viability","subscale":"job_viability","crossTags":["CH:emotional"]}'::jsonb),
  ('f_jv12', 'layer_f', 'F', 44, '이전 직무와 유사한 분야에서 일하고 싶다.', 'job_viability', 'likert7', false, '{"section":"career_viability","subscale":"job_viability","crossTags":["AP:방향유지"]}'::jsonb),
  ('f_sc01', 'layer_f', 'F', 45, '이전 직무에서 사용하던 도구와 기술을 지금도 다룰 수 있다.', 'skill_currency', 'likert7', false, '{"section":"career_viability","subscale":"skill_currency","crossTags":["SP:Execution","BT:C"]}'::jsonb),
  ('f_sc02', 'layer_f', 'F', 46, '이전 직무의 새로운 도구·기술·트렌드를 파악하고 있다.', 'skill_currency', 'likert7', false, '{"section":"career_viability","subscale":"skill_currency","crossTags":["CH:growth","PT:N"]}'::jsonb),
  ('f_sc03', 'layer_f', 'F', 47, '단절 기간 동안 업무 관련 스킬이 눈에 띄게 퇴화했다고 느낀다.', 'skill_currency', 'likert7', true, '{"section":"career_viability","subscale":"skill_currency","crossTags":["UF:self"]}'::jsonb),
  ('f_sc04', 'layer_f', 'F', 48, '새로운 업무 도구를 빠르게 배울 수 있다는 자신감이 있다.', 'skill_currency', 'likert7', false, '{"section":"career_viability","subscale":"skill_currency","crossTags":["CH:growth","SP:Creativity"]}'::jsonb),
  ('f_sc05', 'layer_f', 'F', 49, '이전에 쌓은 전문 지식이 여전히 유효하다.', 'skill_currency', 'likert7', false, '{"section":"career_viability","subscale":"skill_currency","crossTags":["SP:Guard"]}'::jsonb),
  ('f_sc06', 'layer_f', 'F', 50, '업계의 기술 변화 속도가 나의 공백 기간보다 빠르다.', 'skill_currency', 'likert7', true, '{"section":"career_viability","subscale":"skill_currency","crossTags":["PT:N"]}'::jsonb),
  ('f_sc07', 'layer_f', 'F', 51, '복귀 전 업데이트해야 할 기술 목록을 파악하고 있다.', 'skill_currency', 'likert7', false, '{"section":"career_viability","subscale":"skill_currency","crossTags":["PT:J","BT:C"]}'::jsonb),
  ('f_sc08', 'layer_f', 'F', 52, '이전 직무의 "하드 스킬"보다 "소프트 스킬"이 더 유효하다고 본다.', 'skill_currency', 'likert7', false, '{"section":"career_viability","subscale":"skill_currency","crossTags":["SP:Interpersonal"]}'::jsonb),
  ('f_sc09', 'layer_f', 'F', 53, '관련 자격증이나 인증이 유효 기간 내에 있다.', 'skill_currency', 'likert7', false, '{"section":"career_viability","subscale":"skill_currency","crossTags":["BT:C"]}'::jsonb),
  ('f_sc10', 'layer_f', 'F', 54, '단절 기간에 관련 분야 공부를 계속했다.', 'skill_currency', 'likert7', false, '{"section":"career_viability","subscale":"skill_currency","crossTags":["CH:growth"]}'::jsonb),
  ('f_sc11', 'layer_f', 'F', 55, '기술 격차를 메우는 데 3개월이면 충분하다고 생각한다.', 'skill_currency', 'likert7', false, '{"section":"career_viability","subscale":"skill_currency","crossTags":["UF:self"]}'::jsonb),
  ('f_sc12', 'layer_f', 'F', 56, '기술적으로 완전히 뒤처져서 처음부터 다시 배워야 한다고 느낀다.', 'skill_currency', 'likert7', true, '{"section":"career_viability","subscale":"skill_currency","crossTags":["UF:self","CH:emotional"]}'::jsonb),
  ('f_mr01', 'layer_f', 'F', 57, '경력단절자를 수용하는 기업이나 프로그램을 알고 있다.', 'market_reentry', 'likert7', false, '{"section":"career_viability","subscale":"market_reentry","crossTags":["PT:S","BT:C"]}'::jsonb),
  ('f_mr02', 'layer_f', 'F', 58, '내 분야에서 경력단절 후 복귀에 성공한 사례를 알고 있다.', 'market_reentry', 'likert7', false, '{"section":"career_viability","subscale":"market_reentry","crossTags":["PT:N"]}'::jsonb),
  ('f_mr03', 'layer_f', 'F', 59, '리턴십(returnship), 재취업 지원 프로그램을 탐색해보았다.', 'market_reentry', 'likert7', false, '{"section":"career_viability","subscale":"market_reentry","crossTags":["PT:J"]}'::jsonb),
  ('f_mr04', 'layer_f', 'F', 60, '파트타임, 계약직, 프리랜서 등 유연한 복귀 경로를 수용할 수 있다.', 'market_reentry', 'likert7', false, '{"section":"career_viability","subscale":"market_reentry","crossTags":["PT:P","BT:S"]}'::jsonb),
  ('f_mr05', 'layer_f', 'F', 61, '이전보다 낮은 직급에서 시작하는 것도 수용할 수 있다.', 'market_reentry', 'likert7', false, '{"section":"career_viability","subscale":"market_reentry","crossTags":["UF:self","BT:S"]}'::jsonb),
  ('f_mr06', 'layer_f', 'F', 62, '이전보다 낮은 보상도 수용할 수 있다.', 'market_reentry', 'likert7', false, '{"section":"career_viability","subscale":"market_reentry","crossTags":["UF:self"]}'::jsonb),
  ('f_mr07', 'layer_f', 'F', 63, '헤드헌터나 채용 담당자에게 연락해본 적이 있다.', 'market_reentry', 'likert7', false, '{"section":"career_viability","subscale":"market_reentry","crossTags":["BT:I","SP:Execution"]}'::jsonb),
  ('f_mr08', 'layer_f', 'F', 64, '이전 직장 동료나 업계 인맥이 아직 유효하다.', 'market_reentry', 'likert7', false, '{"section":"career_viability","subscale":"market_reentry","crossTags":["BT:I","SP:Interpersonal"]}'::jsonb),
  ('f_mr09', 'layer_f', 'F', 65, '복귀 시점에 대한 현실적인 타임라인이 있다.', 'market_reentry', 'likert7', false, '{"section":"career_viability","subscale":"market_reentry","crossTags":["PT:J","SP:Strategic"]}'::jsonb),
  ('f_mr10', 'layer_f', 'F', 66, '채용 시장이 경력단절자에게 우호적이라고 느낀다.', 'market_reentry', 'likert7', false, '{"section":"career_viability","subscale":"market_reentry","crossTags":["PT:S"]}'::jsonb),
  ('f_mr11', 'layer_f', 'F', 67, '면접에서 경력 공백에 대한 설득력 있는 답변이 준비되어 있다.', 'market_reentry', 'likert7', false, '{"section":"career_viability","subscale":"market_reentry","crossTags":["BT:I","PT:T"]}'::jsonb),
  ('f_mr12', 'layer_f', 'F', 68, '아무도 나를 뽑아주지 않을 것이라는 두려움이 있다.', 'market_reentry', 'likert7', true, '{"section":"career_viability","subscale":"market_reentry","crossTags":["UF:self","CH:emotional"]}'::jsonb),
  ('f_sn01', 'layer_f', 'F', 69, '경력 단절을 "실패"가 아닌 "전환"으로 해석한다.', 'self_narrative', 'likert7', false, '{"section":"resilience","subscale":"self_narrative","crossTags":["UF:trauma(PTG)"]}'::jsonb),
  ('f_sn02', 'layer_f', 'F', 70, '나의 가치는 직업 유무와 무관하다고 믿는다.', 'self_narrative', 'likert7', false, '{"section":"resilience","subscale":"self_narrative","crossTags":["UF:self"]}'::jsonb),
  ('f_sn03', 'layer_f', 'F', 71, '단절 기간에 대해 수치심보다 수용감이 크다.', 'self_narrative', 'likert7', false, '{"section":"resilience","subscale":"self_narrative","crossTags":["UF:self","CH:emotional"]}'::jsonb),
  ('f_sn04', 'layer_f', 'F', 72, '내 인생 스토리에서 단절도 의미 있는 챕터다.', 'self_narrative', 'likert7', false, '{"section":"resilience","subscale":"self_narrative","crossTags":["UF:trauma(PTG)"]}'::jsonb),
  ('f_sn05', 'layer_f', 'F', 73, '이 경험이 나를 더 강하게 만들었다.', 'self_narrative', 'likert7', false, '{"section":"resilience","subscale":"self_narrative","crossTags":["UF:trauma(PTG)","SP:Breakthrough"]}'::jsonb),
  ('f_sn06', 'layer_f', 'F', 74, '사람들이 내 경력 공백을 부정적으로 볼까 걱정된다.', 'self_narrative', 'likert7', true, '{"section":"resilience","subscale":"self_narrative","crossTags":["UF:peer","CH:emotional"]}'::jsonb),
  ('f_sn07', 'layer_f', 'F', 75, '경력 단절이 내 정체성에 큰 타격을 주었다.', 'self_narrative', 'likert7', true, '{"section":"resilience","subscale":"self_narrative","crossTags":["UF:self"]}'::jsonb),
  ('f_sn08', 'layer_f', 'F', 76, '단절 전과 후의 나는 다르지만 모두 나다.', 'self_narrative', 'likert7', false, '{"section":"resilience","subscale":"self_narrative","crossTags":["UF:self"]}'::jsonb),
  ('f_sn09', 'layer_f', 'F', 77, '내 이야기를 솔직하게 말하면 공감을 얻을 수 있다고 생각한다.', 'self_narrative', 'likert7', false, '{"section":"resilience","subscale":"self_narrative","crossTags":["BT:I","UF:self"]}'::jsonb),
  ('f_sn10', 'layer_f', 'F', 78, '이 경험을 다른 경력단절자에게 도움이 되도록 나눌 수 있다.', 'self_narrative', 'likert7', false, '{"section":"resilience","subscale":"self_narrative","crossTags":["AP:S","SP:Harmony"]}'::jsonb),
  ('f_se01', 'layer_f', 'F', 79, '나는 여전히 가치 있는 사람이라고 느낀다.', 'self_esteem', 'likert7', false, '{"section":"resilience","subscale":"self_esteem","crossTags":["UF:self"]}'::jsonb),
  ('f_se02', 'layer_f', 'F', 80, '내 능력에 대한 자신감이 단절 전과 비슷하다.', 'self_esteem', 'likert7', false, '{"section":"resilience","subscale":"self_esteem","crossTags":["UF:self"]}'::jsonb),
  ('f_se03', 'layer_f', 'F', 81, '일을 하지 않으면 무가치한 사람 같은 느낌이 든다.', 'self_esteem', 'likert7', true, '{"section":"resilience","subscale":"self_esteem","crossTags":["UF:self","CH:emotional"]}'::jsonb),
  ('f_se04', 'layer_f', 'F', 82, '주변 사람들이 나를 존중한다고 느낀다.', 'self_esteem', 'likert7', false, '{"section":"resilience","subscale":"self_esteem","crossTags":["UF:peer"]}'::jsonb),
  ('f_se05', 'layer_f', 'F', 83, '경력 단절이 내 자존감을 크게 손상시켰다.', 'self_esteem', 'likert7', true, '{"section":"resilience","subscale":"self_esteem","crossTags":["UF:self","CH:emotional"]}'::jsonb),
  ('f_se06', 'layer_f', 'F', 84, '새로운 도전을 시작할 자격이 있다고 느낀다.', 'self_esteem', 'likert7', false, '{"section":"resilience","subscale":"self_esteem","crossTags":["UF:self","SP:Breakthrough"]}'::jsonb),
  ('f_se07', 'layer_f', 'F', 85, '다른 경력단절자들과 비교하며 자괴감을 느낀다.', 'self_esteem', 'likert7', true, '{"section":"resilience","subscale":"self_esteem","crossTags":["UF:peer","CH:emotional"]}'::jsonb),
  ('f_se08', 'layer_f', 'F', 86, '나를 있는 그대로 받아들이는 편이다.', 'self_esteem', 'likert7', false, '{"section":"resilience","subscale":"self_esteem","crossTags":["UF:self","CH:emotional"]}'::jsonb),
  ('f_rw01', 'layer_f', 'F', 87, '다시 일을 시작할 강한 의지가 있다.', 'retry_willingness', 'likert7', false, '{"section":"resilience","subscale":"retry_willingness","crossTags":["BT:D","SP:Breakthrough"]}'::jsonb),
  ('f_rw02', 'layer_f', 'F', 88, '복귀 과정의 어려움을 감당할 준비가 되어 있다.', 'retry_willingness', 'likert7', false, '{"section":"resilience","subscale":"retry_willingness","crossTags":["CH:emotional","UF:self"]}'::jsonb),
  ('f_rw03', 'layer_f', 'F', 89, '거절당해도 계속 시도할 수 있다.', 'retry_willingness', 'likert7', false, '{"section":"resilience","subscale":"retry_willingness","crossTags":["UF:self","SP:Breakthrough"]}'::jsonb),
  ('f_rw04', 'layer_f', 'F', 90, '작은 것부터 시작해도 괜찮다.', 'retry_willingness', 'likert7', false, '{"section":"resilience","subscale":"retry_willingness","crossTags":["BT:S","PT:P"]}'::jsonb),
  ('f_rw05', 'layer_f', 'F', 91, '이전 수준을 회복하는 데 시간이 걸려도 인내할 수 있다.', 'retry_willingness', 'likert7', false, '{"section":"resilience","subscale":"retry_willingness","crossTags":["CH:integrity","BT:S"]}'::jsonb),
  ('f_rw06', 'layer_f', 'F', 92, '가족이나 주변의 지지가 나의 재도전을 돕고 있다.', 'retry_willingness', 'likert7', false, '{"section":"resilience","subscale":"retry_willingness","crossTags":["UF:family","UF:peer"]}'::jsonb),
  ('f_rw07', 'layer_f', 'F', 93, '재도전의 동기가 외부 압박이 아닌 내적 욕구에서 나온다.', 'retry_willingness', 'likert7', false, '{"section":"resilience","subscale":"retry_willingness","crossTags":["CH:growth","UF:self"]}'::jsonb),
  ('f_rw08', 'layer_f', 'F', 94, '포기하고 싶은 순간에도 다시 일어설 수 있다.', 'retry_willingness', 'likert7', false, '{"section":"resilience","subscale":"retry_willingness","crossTags":["UF:trauma(PTG)","SP:Breakthrough"]}'::jsonb),
  ('f_rw09', 'layer_f', 'F', 95, '나이나 공백 기간이 장애물이 아닌 도전 과제라고 본다.', 'retry_willingness', 'likert7', false, '{"section":"resilience","subscale":"retry_willingness","crossTags":["UF:self","CH:growth"]}'::jsonb),
  ('f_rw10', 'layer_f', 'F', 96, '복귀 후 성공하면 그 경험이 누군가에게 영감이 될 수 있다.', 'retry_willingness', 'likert7', false, '{"section":"resilience","subscale":"retry_willingness","crossTags":["AP:S","SP:Harmony"]}'::jsonb),
  ('f_cr01', 'layer_f', 'F', 97, '이전과 동일한 직무로 복귀하고 싶다.', 'career_restoration', 'likert7', false, '{"section":"direction_bifurcation","subscale":"career_restoration","crossTags":["SP:Guard"]}'::jsonb),
  ('f_cr02', 'layer_f', 'F', 98, '이전 직장(또는 동종업계)에서 다시 일하고 싶다.', 'career_restoration', 'likert7', false, '{"section":"direction_bifurcation","subscale":"career_restoration","crossTags":["BT:S"]}'::jsonb),
  ('f_cr03', 'layer_f', 'F', 99, '이전 직무의 전문성을 회복하는 것이 현실적이라 생각한다.', 'career_restoration', 'likert7', false, '{"section":"direction_bifurcation","subscale":"career_restoration","crossTags":["SP:Guard","UF:self"]}'::jsonb),
  ('f_cr04', 'layer_f', 'F', 100, '이전 인맥을 활용하면 복귀가 수월할 것이다.', 'career_restoration', 'likert7', false, '{"section":"direction_bifurcation","subscale":"career_restoration","crossTags":["BT:I","SP:Interpersonal"]}'::jsonb),
  ('f_cr05', 'layer_f', 'F', 101, '이전과 같은 수준의 보상을 기대한다.', 'career_restoration', 'likert7', false, '{"section":"direction_bifurcation","subscale":"career_restoration","crossTags":["BT:D"]}'::jsonb),
  ('f_cr06', 'layer_f', 'F', 102, '이전 직무가 나에게 가장 잘 맞는다고 여전히 믿는다.', 'career_restoration', 'likert7', false, '{"section":"direction_bifurcation","subscale":"career_restoration","crossTags":["AP:방향유지"]}'::jsonb),
  ('f_cr07', 'layer_f', 'F', 103, '빠르게 원래 수준으로 돌아갈 수 있다는 자신감이 있다.', 'career_restoration', 'likert7', false, '{"section":"direction_bifurcation","subscale":"career_restoration","crossTags":["UF:self","SP:Execution"]}'::jsonb),
  ('f_cr08', 'layer_f', 'F', 104, '경력 단절 전의 루틴으로 복귀하는 것이 편할 것이다.', 'career_restoration', 'likert7', false, '{"section":"direction_bifurcation","subscale":"career_restoration","crossTags":["BT:S","PT:J"]}'::jsonb),
  ('f_cr09', 'layer_f', 'F', 105, '"원래 하던 일"이 아닌 새로운 시도는 부담스럽다.', 'career_restoration', 'likert7', true, '{"section":"direction_bifurcation","subscale":"career_restoration","crossTags":["CH:growth(low)"]}'::jsonb),
  ('f_cr10', 'layer_f', 'F', 106, '이전 직무에 대한 열정이 아직 식지 않았다.', 'career_restoration', 'likert7', false, '{"section":"direction_bifurcation","subscale":"career_restoration","crossTags":["AP:유지"]}'::jsonb),
  ('f_cr11', 'layer_f', 'F', 107, '복귀 후 안정적으로 일할 수 있는 환경을 원한다.', 'career_restoration', 'likert7', false, '{"section":"direction_bifurcation","subscale":"career_restoration","crossTags":["BT:S"]}'::jsonb),
  ('f_cr12', 'layer_f', 'F', 108, '경력 복구가 가장 현실적이고 효율적인 선택이다.', 'career_restoration', 'likert7', false, '{"section":"direction_bifurcation","subscale":"career_restoration","crossTags":["PT:S","SP:Strategic"]}'::jsonb),
  ('f_cp01', 'layer_f', 'F', 109, '이전 직무와 다른 분야에서 새 가능성을 탐색하고 싶다.', 'career_pivot', 'likert7', false, '{"section":"direction_bifurcation","subscale":"career_pivot","crossTags":["PT:N","SP:Creativity"]}'::jsonb),
  ('f_cp02', 'layer_f', 'F', 110, '이전 경험을 살리되 다른 역할이나 산업으로 전환하고 싶다.', 'career_pivot', 'likert7', false, '{"section":"direction_bifurcation","subscale":"career_pivot","crossTags":["SP:Strategic"]}'::jsonb),
  ('f_cp03', 'layer_f', 'F', 111, '경력 단절이 오히려 방향을 바꿀 기회라고 생각한다.', 'career_pivot', 'likert7', false, '{"section":"direction_bifurcation","subscale":"career_pivot","crossTags":["UF:trauma(PTG)","SP:Breakthrough"]}'::jsonb),
  ('f_cp04', 'layer_f', 'F', 112, '이전 직무에 미련은 있지만 더 나은 선택이 있을 수 있다.', 'career_pivot', 'likert7', false, '{"section":"direction_bifurcation","subscale":"career_pivot","crossTags":["PT:N"]}'::jsonb),
  ('f_cp05', 'layer_f', 'F', 113, '관심 있는 새 분야가 구체적으로 있다.', 'career_pivot', 'likert7', false, '{"section":"direction_bifurcation","subscale":"career_pivot","crossTags":["AP:변화방향"]}'::jsonb),
  ('f_cp06', 'layer_f', 'F', 114, '전환에 필요한 학습이나 자격 취득을 시작할 의지가 있다.', 'career_pivot', 'likert7', false, '{"section":"direction_bifurcation","subscale":"career_pivot","crossTags":["CH:growth","PT:J"]}'::jsonb),
  ('f_cp07', 'layer_f', 'F', 115, '이전 역량의 일부가 새 분야에서도 쓸모 있을 것이다.', 'career_pivot', 'likert7', false, '{"section":"direction_bifurcation","subscale":"career_pivot","crossTags":["SP:Strategic"]}'::jsonb),
  ('f_cp08', 'layer_f', 'F', 116, '보상이 줄어도 더 만족스러운 일을 선택할 수 있다.', 'career_pivot', 'likert7', false, '{"section":"direction_bifurcation","subscale":"career_pivot","crossTags":["PT:F","CH:ethics"]}'::jsonb),
  ('f_cp09', 'layer_f', 'F', 117, '전환 과정의 불확실성을 감당할 수 있다.', 'career_pivot', 'likert7', false, '{"section":"direction_bifurcation","subscale":"career_pivot","crossTags":["CH:emotional","SP:Breakthrough"]}'::jsonb),
  ('f_cp10', 'layer_f', 'F', 118, '이전과 완전히 다른 환경에서 일하는 것이 오히려 설렌다.', 'career_pivot', 'likert7', false, '{"section":"direction_bifurcation","subscale":"career_pivot","crossTags":["CH:growth"]}'::jsonb),
  ('f_fs01', 'layer_f', 'F', 119, '이전 경력과 무관하게 완전히 새로운 일을 시작하고 싶다.', 'fresh_start', 'likert7', false, '{"section":"direction_bifurcation","subscale":"fresh_start","crossTags":["SP:Breakthrough","PT:N"]}'::jsonb),
  ('f_fs02', 'layer_f', 'F', 120, '지금까지의 경력을 백지로 돌려도 괜찮다는 생각이 든다.', 'fresh_start', 'likert7', false, '{"section":"direction_bifurcation","subscale":"fresh_start","crossTags":["UF:self"]}'::jsonb),
  ('f_fs03', 'layer_f', 'F', 121, '나이와 경험에 구애받지 않고 초심으로 돌아갈 수 있다.', 'fresh_start', 'likert7', false, '{"section":"direction_bifurcation","subscale":"fresh_start","crossTags":["CH:growth","UF:self"]}'::jsonb),
  ('f_fs04', 'layer_f', 'F', 122, '창업이나 1인 사업에 관심이 있다.', 'fresh_start', 'likert7', false, '{"section":"direction_bifurcation","subscale":"fresh_start","crossTags":["BT:D","AP:E"]}'::jsonb),
  ('f_fs05', 'layer_f', 'F', 123, '과거의 직업적 정체성을 완전히 내려놓을 준비가 되었다.', 'fresh_start', 'likert7', false, '{"section":"direction_bifurcation","subscale":"fresh_start","crossTags":["UF:self"]}'::jsonb),
  ('f_fs06', 'layer_f', 'F', 124, '내가 진정으로 원하는 것을 이제야 알게 되었다.', 'fresh_start', 'likert7', false, '{"section":"direction_bifurcation","subscale":"fresh_start","crossTags":["UF:trauma(PTG)","AP:변화"]}'::jsonb),
  ('f_fs07', 'layer_f', 'F', 125, '이전 경력이 오히려 새 시작의 발목을 잡는다고 느낀다.', 'fresh_start', 'likert7', true, '{"section":"direction_bifurcation","subscale":"fresh_start","crossTags":["UF:self"]}'::jsonb),
  ('f_fs08', 'layer_f', 'F', 126, '처음부터 다시 배우는 과정이 두렵지 않다.', 'fresh_start', 'likert7', false, '{"section":"direction_bifurcation","subscale":"fresh_start","crossTags":["CH:growth","SP:Breakthrough"]}'::jsonb),
  ('f_fs09', 'layer_f', 'F', 127, '안정보다 진정성 있는 삶을 선택하겠다.', 'fresh_start', 'likert7', false, '{"section":"direction_bifurcation","subscale":"fresh_start","crossTags":["CH:ethics","PT:F"]}'::jsonb),
  ('f_fs10', 'layer_f', 'F', 128, '완전히 새로운 사람으로 시작하는 상상을 하면 에너지가 올라간다.', 'fresh_start', 'likert7', false, '{"section":"direction_bifurcation","subscale":"fresh_start","crossTags":["SP:Breakthrough","PT:N"]}'::jsonb),
  ('f_su01', 'layer_f', 'F', 129, '복귀 대상 직무에 필요한 현재 스킬을 파악하고 있다.', 'skill_update', 'likert7', false, '{"section":"reentry_readiness","subscale":"skill_update","crossTags":["PT:S","BT:C"]}'::jsonb),
  ('f_su02', 'layer_f', 'F', 130, '갭을 메우기 위한 학습 계획이 있다.', 'skill_update', 'likert7', false, '{"section":"reentry_readiness","subscale":"skill_update","crossTags":["PT:J","CH:growth"]}'::jsonb),
  ('f_su03', 'layer_f', 'F', 131, '온라인 강좌, 부트캠프 등을 수강한(또는 수강 중인) 경험이 있다.', 'skill_update', 'likert7', false, '{"section":"reentry_readiness","subscale":"skill_update","crossTags":["CH:growth"]}'::jsonb),
  ('f_su04', 'layer_f', 'F', 132, '새로운 디지털 도구에 대한 적응력이 있다.', 'skill_update', 'likert7', false, '{"section":"reentry_readiness","subscale":"skill_update","crossTags":["CH:growth"]}'::jsonb),
  ('f_su05', 'layer_f', 'F', 133, '단기간에 집중 학습할 수 있는 환경이 확보되어 있다.', 'skill_update', 'likert7', false, '{"section":"reentry_readiness","subscale":"skill_update","crossTags":["PT:J"]}'::jsonb),
  ('f_su06', 'layer_f', 'F', 134, '복귀에 필요한 기술 격차가 극복 가능한 수준이라 판단한다.', 'skill_update', 'likert7', false, '{"section":"reentry_readiness","subscale":"skill_update","crossTags":["UF:self","SP:Strategic"]}'::jsonb),
  ('f_nw01', 'layer_f', 'F', 135, '이전 직장이나 업계 인맥과 연락이 가능하다.', 'network', 'likert7', false, '{"section":"reentry_readiness","subscale":"network","crossTags":["BT:I"]}'::jsonb),
  ('f_nw02', 'layer_f', 'F', 136, '복귀를 도와줄 멘토나 조력자가 있다.', 'network', 'likert7', false, '{"section":"reentry_readiness","subscale":"network","crossTags":["UF:peer"]}'::jsonb),
  ('f_nw03', 'layer_f', 'F', 137, '구직 활동에 활용할 네트워크가 충분하다.', 'network', 'likert7', false, '{"section":"reentry_readiness","subscale":"network","crossTags":["BT:I","SP:Interpersonal"]}'::jsonb),
  ('f_nw04', 'layer_f', 'F', 138, '네트워크를 재활성화하기 위한 활동을 시작했다.', 'network', 'likert7', false, '{"section":"reentry_readiness","subscale":"network","crossTags":["BT:I","PT:J"]}'::jsonb),
  ('f_nw05', 'layer_f', 'F', 139, '경력단절자 커뮤니티나 지원 모임에 참여하고 있다.', 'network', 'likert7', false, '{"section":"reentry_readiness","subscale":"network","crossTags":["UF:peer"]}'::jsonb),
  ('f_nw06', 'layer_f', 'F', 140, '새로운 사람과 관계를 맺는 것에 거부감이 없다.', 'network', 'likert7', false, '{"section":"reentry_readiness","subscale":"network","crossTags":["PT:E","BT:I"]}'::jsonb),
  ('f_sp01', 'layer_f', 'F', 141, '나를 소개할 때 경력 공백을 당당하게 설명할 수 있다.', 'self_presentation', 'likert7', false, '{"section":"reentry_readiness","subscale":"self_presentation","crossTags":["BT:I","UF:self"]}'::jsonb),
  ('f_sp02', 'layer_f', 'F', 142, '이력서에 경력 공백 기간을 어떻게 표현할지 준비되어 있다.', 'self_presentation', 'likert7', false, '{"section":"reentry_readiness","subscale":"self_presentation","crossTags":["BT:C","PT:T"]}'::jsonb),
  ('f_sp03', 'layer_f', 'F', 143, '면접에서 단절 사유를 긍정적으로 프레이밍할 수 있다.', 'self_presentation', 'likert7', false, '{"section":"reentry_readiness","subscale":"self_presentation","crossTags":["BT:I","PT:T"]}'::jsonb),
  ('f_sp04', 'layer_f', 'F', 144, '나의 강점과 차별점을 명확히 전달할 수 있다.', 'self_presentation', 'likert7', false, '{"section":"reentry_readiness","subscale":"self_presentation","crossTags":["SP:전반","BT:I"]}'::jsonb),
  ('f_sp05', 'layer_f', 'F', 145, '포트폴리오나 성과 자료를 준비하고 있다.', 'self_presentation', 'likert7', false, '{"section":"reentry_readiness","subscale":"self_presentation","crossTags":["BT:C","PT:J"]}'::jsonb),
  ('f_sp06', 'layer_f', 'F', 146, '자기 PR에 대한 자신감이 부족하다.', 'self_presentation', 'likert7', true, '{"section":"reentry_readiness","subscale":"self_presentation","crossTags":["UF:self","CH:emotional"]}'::jsonb),
  ('f_fl01', 'layer_f', 'F', 147, '현재 업계에서 사용하는 용어와 트렌드를 파악하고 있다.', 'field_language', 'likert7', false, '{"section":"reentry_readiness","subscale":"field_language","crossTags":["PT:N","BT:C"]}'::jsonb),
  ('f_fl02', 'layer_f', 'F', 148, '업무 현장의 분위기와 속도에 적응할 수 있다는 자신감이 있다.', 'field_language', 'likert7', false, '{"section":"reentry_readiness","subscale":"field_language","crossTags":["UF:temperament","CH:emotional"]}'::jsonb),
  ('f_fl03', 'layer_f', 'F', 149, '직장 문화(회의, 보고, 협업)에 재적응하는 데 큰 어려움은 없을 것이다.', 'field_language', 'likert7', false, '{"section":"reentry_readiness","subscale":"field_language","crossTags":["BT:S","UF:temperament"]}'::jsonb),
  ('f_fl04', 'layer_f', 'F', 150, '현재 고용 시장의 채용 프로세스(온라인 지원, AI 면접 등)를 이해하고 있다.', 'field_language', 'likert7', false, '{"section":"reentry_readiness","subscale":"field_language","crossTags":["CH:growth"]}'::jsonb),
  ('f_fl05', 'layer_f', 'F', 151, '복귀 후 첫 1개월이 가장 어려울 것이라 예상하고 대비하고 있다.', 'field_language', 'likert7', false, '{"section":"reentry_readiness","subscale":"field_language","crossTags":["PT:J","SP:Strategic"]}'::jsonb),
  ('f_fl06', 'layer_f', 'F', 152, '현장에 돌아가면 감을 빠르게 되찾을 수 있다고 생각한다.', 'field_language', 'likert7', false, '{"section":"reentry_readiness","subscale":"field_language","crossTags":["UF:self","SP:Execution"]}'::jsonb),
  ('f_val01', 'layer_f', 'F', 153, '나는 경력 단절 기간에 단 한 번도 불안을 느낀 적이 없다.', 'DECOY', 'likert7', false, '{"section":"decoy","subscale":"DECOY","crossTags":[]}'::jsonb),
  ('f_val02', 'layer_f', 'F', 154, '내가 복귀하면 모든 것이 즉시 예전처럼 될 것이다.', 'DECOY', 'likert7', false, '{"section":"decoy","subscale":"DECOY","crossTags":[]}'::jsonb);