-- HIT Layer F: 154문항 (152 + 미끼 2)
-- 자동 생성: scripts/seed-hit-layer-f.js

DELETE FROM public.hit_questions WHERE module = 'layer_f';

INSERT INTO public.hit_questions
  (id, module, test_type, question_index, question_text, sub_domain, response_type, reverse_scored, scoring_key)
VALUES
  ('f_dc01', 'layer_f', 'F', 1, '경력 공백의 주된 이유를 명확하게 설명할 수 있다.', 'disruption_context', 'likert7', false, '{"section":"break_context","subscale":"disruption_context","crossTags":["UF:clarity"]}'::jsonb),
  ('f_dc02', 'layer_f', 'F', 2, '경력 단절은 나의 선택이었다(또는 불가피한 상황이었다).', 'disruption_context', 'likert7', false, '{"section":"break_context","subscale":"disruption_context","crossTags":["UF:autonomy"]}'::jsonb),
  ('f_dc03', 'layer_f', 'F', 3, '공백 기간 동안에도 나름의 성장을 했다고 생각한다.', 'disruption_context', 'likert7', false, '{"section":"break_context","subscale":"disruption_context","crossTags":["SP:Growth"]}'::jsonb),
  ('f_dc04', 'layer_f', 'F', 4, '단절 기간이 예상보다 길어졌다.', 'disruption_context', 'likert7', true, '{"section":"break_context","subscale":"disruption_context","crossTags":["UF:security"]}'::jsonb),
  ('f_dc05', 'layer_f', 'F', 5, '단절의 원인이 해소되었거나 해소될 전망이 있다.', 'disruption_context', 'likert7', false, '{"section":"break_context","subscale":"disruption_context","crossTags":["UF:stability"]}'::jsonb),
  ('f_dc06', 'layer_f', 'F', 6, '단절 기간 동안 직업 세계와 완전히 단절되었다.', 'disruption_context', 'likert7', true, '{"section":"break_context","subscale":"disruption_context","crossTags":["UF:belonging"]}'::jsonb),
  ('f_dc07', 'layer_f', 'F', 7, '경력 공백에 대해 부끄러움이나 죄책감을 느낀다.', 'disruption_context', 'likert7', true, '{"section":"break_context","subscale":"disruption_context","crossTags":["CH:self_esteem"]}'::jsonb),
  ('f_dc08', 'layer_f', 'F', 8, '단절 기간에도 업계 동향을 파악하려고 노력했다.', 'disruption_context', 'likert7', false, '{"section":"break_context","subscale":"disruption_context","crossTags":["SP:Learning"]}'::jsonb),
  ('f_hc01', 'layer_f', 'F', 9, '육아/간병 경험을 통해 인내심과 위기관리 능력이 강해졌다.', 'hidden_competency', 'likert7', false, '{"section":"break_context","subscale":"hidden_competency","crossTags":["SP:Resilience","BT:S"]}'::jsonb),
  ('f_hc02', 'layer_f', 'F', 10, '한정된 자원(시간, 돈, 에너지)을 효율적으로 관리하는 법을 배웠다.', 'hidden_competency', 'likert7', false, '{"section":"break_context","subscale":"hidden_competency","crossTags":["SP:Execution","BT:C"]}'::jsonb),
  ('f_hc03', 'layer_f', 'F', 11, '여러 일을 동시에 처리하는 멀티태스킹 능력이 향상되었다.', 'hidden_competency', 'likert7', false, '{"section":"break_context","subscale":"hidden_competency","crossTags":["SP:Execution"]}'::jsonb),
  ('f_hc04', 'layer_f', 'F', 12, '타인의 감정을 읽고 대응하는 능력이 성장했다.', 'hidden_competency', 'likert7', false, '{"section":"break_context","subscale":"hidden_competency","crossTags":["BT:S","BT:I","CH:relational"]}'::jsonb),
  ('f_hc05', 'layer_f', 'F', 13, '스트레스 상황에서도 평정을 유지하는 법을 체득했다.', 'hidden_competency', 'likert7', false, '{"section":"break_context","subscale":"hidden_competency","crossTags":["SP:Resilience","CH:emotional"]}'::jsonb),
  ('f_hc06', 'layer_f', 'F', 14, '문제 해결 능력이 직장 밖 경험을 통해 더 강해졌다.', 'hidden_competency', 'likert7', false, '{"section":"break_context","subscale":"hidden_competency","crossTags":["SP:Thinking"]}'::jsonb),
  ('f_hc07', 'layer_f', 'F', 15, '의사결정을 혼자 내려야 하는 상황이 많아 결단력이 키워졌다.', 'hidden_competency', 'likert7', false, '{"section":"break_context","subscale":"hidden_competency","crossTags":["BT:D","SP:Leadership"]}'::jsonb),
  ('f_hc08', 'layer_f', 'F', 16, '계획대로 되지 않을 때 유연하게 대처하는 법을 배웠다.', 'hidden_competency', 'likert7', false, '{"section":"break_context","subscale":"hidden_competency","crossTags":["SP:Resilience"]}'::jsonb),
  ('f_hc09', 'layer_f', 'F', 17, '다양한 사람(의사, 교사, 행정기관 등)과 소통하는 경험이 늘었다.', 'hidden_competency', 'likert7', false, '{"section":"break_context","subscale":"hidden_competency","crossTags":["BT:I","CH:relational"]}'::jsonb),
  ('f_hc10', 'layer_f', 'F', 18, '단절 기간 동안 자기 자신에 대해 더 깊이 이해하게 되었다.', 'hidden_competency', 'likert7', false, '{"section":"break_context","subscale":"hidden_competency","crossTags":["CH:self_awareness","UF:clarity"]}'::jsonb),
  ('f_hc11', 'layer_f', 'F', 19, '새로운 분야(IT, 온라인 마켓, 부동산 등)를 독학한 경험이 있다.', 'hidden_competency', 'likert7', false, '{"section":"break_context","subscale":"hidden_competency","crossTags":["SP:Learning"]}'::jsonb),
  ('f_hc12', 'layer_f', 'F', 20, '직장 밖에서 쌓은 역량을 이력서에 어떻게 쓸지 모르겠다.', 'hidden_competency', 'likert7', true, '{"section":"break_context","subscale":"hidden_competency","crossTags":["UF:clarity"]}'::jsonb),
  ('f_ga01', 'layer_f', 'F', 21, '공백 기간 동안 자격증, 수료증 등을 취득한 적이 있다.', 'gap_activities', 'likert7', false, '{"section":"break_context","subscale":"gap_activities","crossTags":["SP:Learning"]}'::jsonb),
  ('f_ga02', 'layer_f', 'F', 22, '봉사활동이나 커뮤니티 활동에 참여한 경험이 있다.', 'gap_activities', 'likert7', false, '{"section":"break_context","subscale":"gap_activities","crossTags":["BT:S","UF:belonging"]}'::jsonb),
  ('f_ga03', 'layer_f', 'F', 23, '프리랜서, 부업, 아르바이트 등 수입 활동을 한 적이 있다.', 'gap_activities', 'likert7', false, '{"section":"break_context","subscale":"gap_activities","crossTags":["UF:income"]}'::jsonb),
  ('f_ga04', 'layer_f', 'F', 24, '온라인 강좌나 교육 프로그램을 수강한 적이 있다.', 'gap_activities', 'likert7', false, '{"section":"break_context","subscale":"gap_activities","crossTags":["SP:Learning"]}'::jsonb),
  ('f_ga05', 'layer_f', 'F', 25, '직접 사업을 시도해본 적이 있다(규모 무관).', 'gap_activities', 'likert7', false, '{"section":"break_context","subscale":"gap_activities","crossTags":["BT:D","UF:autonomy"]}'::jsonb),
  ('f_ga06', 'layer_f', 'F', 26, '블로그, SNS, 유튜브 등 콘텐츠를 만든 경험이 있다.', 'gap_activities', 'likert7', false, '{"section":"break_context","subscale":"gap_activities","crossTags":["SP:Expression"]}'::jsonb),
  ('f_ga07', 'layer_f', 'F', 27, '건강 관리(운동, 식단 등)에 집중한 시간이 있었다.', 'gap_activities', 'likert7', false, '{"section":"break_context","subscale":"gap_activities","crossTags":["SP:Resilience"]}'::jsonb),
  ('f_ga08', 'layer_f', 'F', 28, '독서, 학습 등 자기계발에 시간을 투자했다.', 'gap_activities', 'likert7', false, '{"section":"break_context","subscale":"gap_activities","crossTags":["SP:Learning","SP:Growth"]}'::jsonb),
  ('f_ga09', 'layer_f', 'F', 29, '가족이나 주변 사람의 문제를 해결하는 역할을 했다.', 'gap_activities', 'likert7', false, '{"section":"break_context","subscale":"gap_activities","crossTags":["BT:S","CH:relational"]}'::jsonb),
  ('f_ga10', 'layer_f', 'F', 30, '공백 기간에 아무것도 하지 못했다는 느낌이 있다.', 'gap_activities', 'likert7', true, '{"section":"break_context","subscale":"gap_activities","crossTags":["CH:self_esteem"]}'::jsonb),
  ('f_ga11', 'layer_f', 'F', 31, '단절 기간의 경험을 긍정적으로 프레이밍할 수 있다.', 'gap_activities', 'likert7', false, '{"section":"break_context","subscale":"gap_activities","crossTags":["SP:Resilience","UF:clarity"]}'::jsonb),
  ('f_ga12', 'layer_f', 'F', 32, '공백 기간 활동이 향후 경력에 도움이 될 것이라 생각한다.', 'gap_activities', 'likert7', false, '{"section":"break_context","subscale":"gap_activities","crossTags":["SP:Growth"]}'::jsonb),
  ('f_jv01', 'layer_f', 'F', 33, '단절 전 직무가 현재 시장에서도 존재한다.', 'job_viability', 'likert7', false, '{"section":"viability","subscale":"job_viability","crossTags":["UF:security"]}'::jsonb),
  ('f_jv02', 'layer_f', 'F', 34, '해당 직무의 채용 공고를 최근에 확인해보았다.', 'job_viability', 'likert7', false, '{"section":"viability","subscale":"job_viability","crossTags":["SP:Execution"]}'::jsonb),
  ('f_jv03', 'layer_f', 'F', 35, '단절 전 직무의 핵심 업무 내용이 크게 변하지 않았다.', 'job_viability', 'likert7', false, '{"section":"viability","subscale":"job_viability","crossTags":["UF:stability"]}'::jsonb),
  ('f_jv04', 'layer_f', 'F', 36, '해당 분야에서 요구하는 새로운 기술/도구가 많아졌다.', 'job_viability', 'likert7', true, '{"section":"viability","subscale":"job_viability","crossTags":["SP:Learning"]}'::jsonb),
  ('f_jv05', 'layer_f', 'F', 37, '단절 전 보유했던 자격증이나 인증이 여전히 유효하다.', 'job_viability', 'likert7', false, '{"section":"viability","subscale":"job_viability","crossTags":["UF:security"]}'::jsonb),
  ('f_jv06', 'layer_f', 'F', 38, '같은 직무를 다시 할 수 있는 자신감이 있다.', 'job_viability', 'likert7', false, '{"section":"viability","subscale":"job_viability","crossTags":["CH:self_esteem"]}'::jsonb),
  ('f_jv07', 'layer_f', 'F', 39, '공백 기간 동안 해당 분야의 변화를 어느 정도 파악하고 있다.', 'job_viability', 'likert7', false, '{"section":"viability","subscale":"job_viability","crossTags":["SP:Learning"]}'::jsonb),
  ('f_jv08', 'layer_f', 'F', 40, '단절 전 직무 경험이 3년 이상이었다.', 'job_viability', 'likert7', false, '{"section":"viability","subscale":"job_viability","crossTags":["SP:Expertise"]}'::jsonb),
  ('f_jv09', 'layer_f', 'F', 41, '해당 직무의 전문 용어와 업무 프로세스를 여전히 기억한다.', 'job_viability', 'likert7', false, '{"section":"viability","subscale":"job_viability","crossTags":["SP:Expertise"]}'::jsonb),
  ('f_jv10', 'layer_f', 'F', 42, '복귀한다면 교육 없이 바로 업무에 투입될 수 있다.', 'job_viability', 'likert7', false, '{"section":"viability","subscale":"job_viability","crossTags":["SP:Execution"]}'::jsonb),
  ('f_jv11', 'layer_f', 'F', 43, '해당 분야에서 나의 경력 수준(연차)이 경쟁력이 있다.', 'job_viability', 'likert7', false, '{"section":"viability","subscale":"job_viability","crossTags":["SP:Expertise"]}'::jsonb),
  ('f_jv12', 'layer_f', 'F', 44, '단절 기간이 3년 이상이다.', 'job_viability', 'likert7', true, '{"section":"viability","subscale":"job_viability","crossTags":["UF:stability"]}'::jsonb),
  ('f_sc01', 'layer_f', 'F', 45, '단절 전에 사용하던 도구/소프트웨어를 여전히 다룰 수 있다.', 'skill_currency', 'likert7', false, '{"section":"viability","subscale":"skill_currency","crossTags":["SP:Expertise"]}'::jsonb),
  ('f_sc02', 'layer_f', 'F', 46, '해당 분야에서 새로 등장한 도구/기술을 알고 있다.', 'skill_currency', 'likert7', false, '{"section":"viability","subscale":"skill_currency","crossTags":["SP:Learning"]}'::jsonb),
  ('f_sc03', 'layer_f', 'F', 47, '새 도구를 배우는 데 걸리는 시간을 현실적으로 예측할 수 있다.', 'skill_currency', 'likert7', false, '{"section":"viability","subscale":"skill_currency","crossTags":["SP:Thinking"]}'::jsonb),
  ('f_sc04', 'layer_f', 'F', 48, '기술 변화 속도가 빨라 따라잡기 어렵다고 느낀다.', 'skill_currency', 'likert7', true, '{"section":"viability","subscale":"skill_currency","crossTags":["SP:Resilience"]}'::jsonb),
  ('f_sc05', 'layer_f', 'F', 49, '단절 기간에도 관련 기술을 부분적으로 유지했다.', 'skill_currency', 'likert7', false, '{"section":"viability","subscale":"skill_currency","crossTags":["SP:Learning"]}'::jsonb),
  ('f_sc06', 'layer_f', 'F', 50, '업데이트가 필요한 스킬 목록을 구체적으로 작성할 수 있다.', 'skill_currency', 'likert7', false, '{"section":"viability","subscale":"skill_currency","crossTags":["SP:Execution"]}'::jsonb),
  ('f_sc07', 'layer_f', 'F', 51, '스킬 업데이트를 위한 교육 프로그램을 찾아본 적이 있다.', 'skill_currency', 'likert7', false, '{"section":"viability","subscale":"skill_currency","crossTags":["SP:Learning"]}'::jsonb),
  ('f_sc08', 'layer_f', 'F', 52, '기본기(core fundamentals)는 변하지 않아 여전히 유효하다.', 'skill_currency', 'likert7', false, '{"section":"viability","subscale":"skill_currency","crossTags":["SP:Expertise"]}'::jsonb),
  ('f_sc09', 'layer_f', 'F', 53, '디지털 리터러시(기본 IT 활용 능력)에 자신이 있다.', 'skill_currency', 'likert7', false, '{"section":"viability","subscale":"skill_currency","crossTags":["SP:Expertise"]}'::jsonb),
  ('f_sc10', 'layer_f', 'F', 54, '산업 전체가 구조적으로 변해 기존 스킬이 무의미해졌다.', 'skill_currency', 'likert7', true, '{"section":"viability","subscale":"skill_currency","crossTags":["UF:security"]}'::jsonb),
  ('f_sc11', 'layer_f', 'F', 55, '스킬 갭을 6개월 이내에 메울 수 있다고 생각한다.', 'skill_currency', 'likert7', false, '{"section":"viability","subscale":"skill_currency","crossTags":["SP:Growth"]}'::jsonb),
  ('f_sc12', 'layer_f', 'F', 56, '현장 언어(업계 용어, 약어 등)가 낯설어졌다.', 'skill_currency', 'likert7', true, '{"section":"viability","subscale":"skill_currency","crossTags":["SP:Expertise"]}'::jsonb),
  ('f_mr01', 'layer_f', 'F', 57, '경력 단절자를 채용하는 기업이나 프로그램이 있다는 것을 안다.', 'market_reentry', 'likert7', false, '{"section":"viability","subscale":"market_reentry","crossTags":["UF:belonging"]}'::jsonb),
  ('f_mr02', 'layer_f', 'F', 58, '재취업 지원 프로그램(정부, 기관)을 알아본 적이 있다.', 'market_reentry', 'likert7', false, '{"section":"viability","subscale":"market_reentry","crossTags":["SP:Execution"]}'::jsonb),
  ('f_mr03', 'layer_f', 'F', 59, '단절 전 업계에 아직 연락 가능한 사람이 있다.', 'market_reentry', 'likert7', false, '{"section":"viability","subscale":"market_reentry","crossTags":["UF:belonging"]}'::jsonb),
  ('f_mr04', 'layer_f', 'F', 60, '채용 시장에서 경력 단절에 대한 인식이 예전보다 나아졌다고 느낀다.', 'market_reentry', 'likert7', false, '{"section":"viability","subscale":"market_reentry","crossTags":["UF:stability"]}'::jsonb),
  ('f_mr05', 'layer_f', 'F', 61, '파트타임이나 계약직으로라도 복귀할 의지가 있다.', 'market_reentry', 'likert7', false, '{"section":"viability","subscale":"market_reentry","crossTags":["UF:income"]}'::jsonb),
  ('f_mr06', 'layer_f', 'F', 62, '단절 전보다 낮은 직급/급여도 수용할 수 있다.', 'market_reentry', 'likert7', false, '{"section":"viability","subscale":"market_reentry","crossTags":["UF:autonomy"]}'::jsonb),
  ('f_mr07', 'layer_f', 'F', 63, '새로운 분야로의 전환도 열려 있다.', 'market_reentry', 'likert7', false, '{"section":"viability","subscale":"market_reentry","crossTags":["BT:D","SP:Growth"]}'::jsonb),
  ('f_mr08', 'layer_f', 'F', 64, '내 경력 공백을 긍정적으로 설명할 수 있는 스토리가 있다.', 'market_reentry', 'likert7', false, '{"section":"viability","subscale":"market_reentry","crossTags":["SP:Expression","UF:clarity"]}'::jsonb),
  ('f_mr09', 'layer_f', 'F', 65, '재취업에 성공한 비슷한 상황의 롤모델이 있다.', 'market_reentry', 'likert7', false, '{"section":"viability","subscale":"market_reentry","crossTags":["UF:belonging"]}'::jsonb),
  ('f_mr10', 'layer_f', 'F', 66, '현재 거주 지역에서 재취업 기회가 충분하다.', 'market_reentry', 'likert7', false, '{"section":"viability","subscale":"market_reentry","crossTags":["UF:security"]}'::jsonb),
  ('f_mr11', 'layer_f', 'F', 67, '원격 근무(재택근무) 포지션도 적극 고려하고 있다.', 'market_reentry', 'likert7', false, '{"section":"viability","subscale":"market_reentry","crossTags":["UF:autonomy"]}'::jsonb),
  ('f_mr12', 'layer_f', 'F', 68, '재취업이 현실적으로 어렵다고 느낀다.', 'market_reentry', 'likert7', true, '{"section":"viability","subscale":"market_reentry","crossTags":["CH:self_esteem"]}'::jsonb),
  ('f_sn01', 'layer_f', 'F', 69, '경력 단절/실패를 내 탓으로만 돌리지 않는다.', 'self_narrative', 'likert7', false, '{"section":"resilience","subscale":"self_narrative","crossTags":["CH:self_esteem","SP:Resilience"]}'::jsonb),
  ('f_sn02', 'layer_f', 'F', 70, '이 경험을 통해 더 강해졌다고 느낀다.', 'self_narrative', 'likert7', false, '{"section":"resilience","subscale":"self_narrative","crossTags":["SP:Resilience"]}'::jsonb),
  ('f_sn03', 'layer_f', 'F', 71, '내 이야기를 부끄러워하지 않고 말할 수 있다.', 'self_narrative', 'likert7', false, '{"section":"resilience","subscale":"self_narrative","crossTags":["CH:self_esteem","SP:Expression"]}'::jsonb),
  ('f_sn04', 'layer_f', 'F', 72, '단절 전의 나보다 지금의 내가 더 나은 부분이 있다.', 'self_narrative', 'likert7', false, '{"section":"resilience","subscale":"self_narrative","crossTags":["SP:Growth"]}'::jsonb),
  ('f_sn05', 'layer_f', 'F', 73, '실패한 경험에서 구체적으로 배운 교훈이 있다.', 'self_narrative', 'likert7', false, '{"section":"resilience","subscale":"self_narrative","crossTags":["SP:Learning"]}'::jsonb),
  ('f_sn06', 'layer_f', 'F', 74, '다른 사람의 시선이 두려워 재도전을 망설인다.', 'self_narrative', 'likert7', true, '{"section":"resilience","subscale":"self_narrative","crossTags":["CH:emotional"]}'::jsonb),
  ('f_sn07', 'layer_f', 'F', 75, '내 가치가 직업적 성공에만 달려있지 않다고 믿는다.', 'self_narrative', 'likert7', false, '{"section":"resilience","subscale":"self_narrative","crossTags":["UF:meaning"]}'::jsonb),
  ('f_sn08', 'layer_f', 'F', 76, '과거의 경력을 흑역사가 아닌 자산으로 본다.', 'self_narrative', 'likert7', false, '{"section":"resilience","subscale":"self_narrative","crossTags":["SP:Resilience","UF:clarity"]}'::jsonb),
  ('f_sn09', 'layer_f', 'F', 77, '지금의 상황이 영원히 계속되지는 않을 것이다.', 'self_narrative', 'likert7', false, '{"section":"resilience","subscale":"self_narrative","crossTags":["SP:Resilience"]}'::jsonb),
  ('f_sn10', 'layer_f', 'F', 78, '나를 긍정적으로 평가해주는 사람이 주변에 있다.', 'self_narrative', 'likert7', false, '{"section":"resilience","subscale":"self_narrative","crossTags":["UF:belonging","BT:S"]}'::jsonb),
  ('f_se01', 'layer_f', 'F', 79, '경력 공백에도 불구하고 나는 유능한 사람이다.', 'self_esteem', 'likert7', false, '{"section":"resilience","subscale":"self_esteem","crossTags":["CH:self_esteem"]}'::jsonb),
  ('f_se02', 'layer_f', 'F', 80, '나를 채용하는 곳은 좋은 선택을 한 것이다.', 'self_esteem', 'likert7', false, '{"section":"resilience","subscale":"self_esteem","crossTags":["CH:self_esteem"]}'::jsonb),
  ('f_se03', 'layer_f', 'F', 81, '면접에서 자신 있게 나를 어필할 수 있다.', 'self_esteem', 'likert7', false, '{"section":"resilience","subscale":"self_esteem","crossTags":["BT:D","SP:Expression"]}'::jsonb),
  ('f_se04', 'layer_f', 'F', 82, '경력 단절 때문에 나는 다른 지원자보다 불리하다.', 'self_esteem', 'likert7', true, '{"section":"resilience","subscale":"self_esteem","crossTags":["CH:self_esteem"]}'::jsonb),
  ('f_se05', 'layer_f', 'F', 83, '내가 가진 경험의 총합은 여전히 가치가 있다.', 'self_esteem', 'likert7', false, '{"section":"resilience","subscale":"self_esteem","crossTags":["SP:Expertise"]}'::jsonb),
  ('f_se06', 'layer_f', 'F', 84, '나이가 들었다는 이유로 기회가 줄었다고 느낀다.', 'self_esteem', 'likert7', true, '{"section":"resilience","subscale":"self_esteem","crossTags":["CH:self_esteem"]}'::jsonb),
  ('f_se07', 'layer_f', 'F', 85, '새로운 환경에서도 나만의 방식으로 기여할 수 있다.', 'self_esteem', 'likert7', false, '{"section":"resilience","subscale":"self_esteem","crossTags":["SP:Leadership","BT:I"]}'::jsonb),
  ('f_se08', 'layer_f', 'F', 86, '다시 시작할 자격이 충분하다고 느낀다.', 'self_esteem', 'likert7', false, '{"section":"resilience","subscale":"self_esteem","crossTags":["CH:self_esteem"]}'::jsonb),
  ('f_rw01', 'layer_f', 'F', 87, '어떤 형태로든 다시 일하고 싶다는 의지가 강하다.', 'retry_willingness', 'likert7', false, '{"section":"resilience","subscale":"retry_willingness","crossTags":["BT:D","SP:Execution"]}'::jsonb),
  ('f_rw02', 'layer_f', 'F', 88, '재도전에 대한 두려움보다 기대감이 크다.', 'retry_willingness', 'likert7', false, '{"section":"resilience","subscale":"retry_willingness","crossTags":["SP:Resilience","BT:I"]}'::jsonb),
  ('f_rw03', 'layer_f', 'F', 89, '거절당해도 다시 지원할 수 있다.', 'retry_willingness', 'likert7', false, '{"section":"resilience","subscale":"retry_willingness","crossTags":["SP:Resilience"]}'::jsonb),
  ('f_rw04', 'layer_f', 'F', 90, '작은 것부터 시작해도 괜찮다.', 'retry_willingness', 'likert7', false, '{"section":"resilience","subscale":"retry_willingness","crossTags":["BT:S","BT:C"]}'::jsonb),
  ('f_rw05', 'layer_f', 'F', 91, '재도전을 위해 필요한 노력을 기꺼이 할 수 있다.', 'retry_willingness', 'likert7', false, '{"section":"resilience","subscale":"retry_willingness","crossTags":["SP:Execution"]}'::jsonb),
  ('f_rw06', 'layer_f', 'F', 92, '실패해도 다시 도전하는 것이 포기하는 것보다 낫다.', 'retry_willingness', 'likert7', false, '{"section":"resilience","subscale":"retry_willingness","crossTags":["SP:Resilience","BT:D"]}'::jsonb),
  ('f_rw07', 'layer_f', 'F', 93, '주변에서 재도전을 응원해주는 사람이 있다.', 'retry_willingness', 'likert7', false, '{"section":"resilience","subscale":"retry_willingness","crossTags":["UF:belonging"]}'::jsonb),
  ('f_rw08', 'layer_f', 'F', 94, '구체적인 재도전 계획을 세우기 시작했다.', 'retry_willingness', 'likert7', false, '{"section":"resilience","subscale":"retry_willingness","crossTags":["SP:Execution","BT:C"]}'::jsonb),
  ('f_rw09', 'layer_f', 'F', 95, '완벽하지 않아도 일단 시작하는 것이 중요하다고 생각한다.', 'retry_willingness', 'likert7', false, '{"section":"resilience","subscale":"retry_willingness","crossTags":["BT:D","SP:Execution"]}'::jsonb),
  ('f_rw10', 'layer_f', 'F', 96, '3개월 이내에 구체적인 행동을 시작할 수 있다.', 'retry_willingness', 'likert7', false, '{"section":"resilience","subscale":"retry_willingness","crossTags":["SP:Execution"]}'::jsonb),
  ('f_cr01', 'layer_f', 'F', 97, '단절 전과 같은 직무로 돌아가고 싶다.', 'career_restoration', 'likert7', false, '{"section":"direction","subscale":"career_restoration","crossTags":["UF:security"]}'::jsonb),
  ('f_cr02', 'layer_f', 'F', 98, '기존 경력을 살려 같은 업계에서 재취업하고 싶다.', 'career_restoration', 'likert7', false, '{"section":"direction","subscale":"career_restoration","crossTags":["UF:security","SP:Expertise"]}'::jsonb),
  ('f_cr03', 'layer_f', 'F', 99, '이전 직장(또는 비슷한 곳)에 복귀할 수 있다면 좋겠다.', 'career_restoration', 'likert7', false, '{"section":"direction","subscale":"career_restoration","crossTags":["UF:belonging"]}'::jsonb),
  ('f_cr04', 'layer_f', 'F', 100, '경력 공백을 메우고 원래 경력 트랙으로 돌아가고 싶다.', 'career_restoration', 'likert7', false, '{"section":"direction","subscale":"career_restoration","crossTags":["UF:stability"]}'::jsonb),
  ('f_cr05', 'layer_f', 'F', 101, '기존 전문성을 유지하고 발전시키는 것이 최선이다.', 'career_restoration', 'likert7', false, '{"section":"direction","subscale":"career_restoration","crossTags":["SP:Expertise"]}'::jsonb),
  ('f_cr06', 'layer_f', 'F', 102, '이전 분야의 사람들과 다시 연결되고 싶다.', 'career_restoration', 'likert7', false, '{"section":"direction","subscale":"career_restoration","crossTags":["UF:belonging","BT:I"]}'::jsonb),
  ('f_cr07', 'layer_f', 'F', 103, '경력 단절 전의 직급/보상 수준을 회복하고 싶다.', 'career_restoration', 'likert7', false, '{"section":"direction","subscale":"career_restoration","crossTags":["UF:income"]}'::jsonb),
  ('f_cr08', 'layer_f', 'F', 104, '기존 경력이 나의 정체성의 핵심이다.', 'career_restoration', 'likert7', false, '{"section":"direction","subscale":"career_restoration","crossTags":["UF:clarity"]}'::jsonb),
  ('f_cr09', 'layer_f', 'F', 105, '같은 분야에서 최신 기술/트렌드를 빠르게 따라잡을 수 있다.', 'career_restoration', 'likert7', false, '{"section":"direction","subscale":"career_restoration","crossTags":["SP:Learning"]}'::jsonb),
  ('f_cr10', 'layer_f', 'F', 106, '복귀 후 단절 전보다 더 잘할 자신이 있다.', 'career_restoration', 'likert7', false, '{"section":"direction","subscale":"career_restoration","crossTags":["CH:self_esteem","SP:Growth"]}'::jsonb),
  ('f_cp01', 'layer_f', 'F', 107, '이전과는 다른 분야에서 새로 시작하고 싶다.', 'career_pivot', 'likert7', false, '{"section":"direction","subscale":"career_pivot","crossTags":["BT:D","SP:Growth"]}'::jsonb),
  ('f_cp02', 'layer_f', 'F', 108, '단절 기간에 새롭게 관심이 생긴 분야가 있다.', 'career_pivot', 'likert7', false, '{"section":"direction","subscale":"career_pivot","crossTags":["BT:I","SP:Learning"]}'::jsonb),
  ('f_cp03', 'layer_f', 'F', 109, '이전 직무의 한계를 절감했기 때문에 전환이 필요하다.', 'career_pivot', 'likert7', false, '{"section":"direction","subscale":"career_pivot","crossTags":["UF:meaning"]}'::jsonb),
  ('f_cp04', 'layer_f', 'F', 110, '새로운 분야를 배우는 것이 기존 분야로 돌아가는 것보다 끌린다.', 'career_pivot', 'likert7', false, '{"section":"direction","subscale":"career_pivot","crossTags":["SP:Learning"]}'::jsonb),
  ('f_cp05', 'layer_f', 'F', 111, '기존 역량의 일부를 새 분야에 융합할 수 있다.', 'career_pivot', 'likert7', false, '{"section":"direction","subscale":"career_pivot","crossTags":["SP:Expertise","SP:Growth"]}'::jsonb),
  ('f_cp06', 'layer_f', 'F', 112, '전환하고 싶은 구체적인 직무나 산업이 있다.', 'career_pivot', 'likert7', false, '{"section":"direction","subscale":"career_pivot","crossTags":["SP:Execution"]}'::jsonb),
  ('f_cp07', 'layer_f', 'F', 113, '급여가 줄더라도 하고 싶은 일을 선택하겠다.', 'career_pivot', 'likert7', false, '{"section":"direction","subscale":"career_pivot","crossTags":["UF:meaning","UF:autonomy"]}'::jsonb),
  ('f_cp08', 'layer_f', 'F', 114, '단절이 오히려 새로운 방향을 발견하는 계기가 되었다.', 'career_pivot', 'likert7', false, '{"section":"direction","subscale":"career_pivot","crossTags":["SP:Growth"]}'::jsonb),
  ('f_cp09', 'layer_f', 'F', 115, '기존 경력에 미련이 없다.', 'career_pivot', 'likert7', false, '{"section":"direction","subscale":"career_pivot","crossTags":["UF:autonomy"]}'::jsonb),
  ('f_cp10', 'layer_f', 'F', 116, '인턴이나 수습 과정부터 다시 시작할 수 있다.', 'career_pivot', 'likert7', false, '{"section":"direction","subscale":"career_pivot","crossTags":["BT:S","CH:growth"]}'::jsonb),
  ('f_cp11', 'layer_f', 'F', 117, '새 분야에서 경쟁력을 갖추기 위한 교육 계획이 있다.', 'career_pivot', 'likert7', false, '{"section":"direction","subscale":"career_pivot","crossTags":["SP:Learning","SP:Execution"]}'::jsonb),
  ('f_cp12', 'layer_f', 'F', 118, '이전 경력과 전혀 무관한 일도 해볼 의지가 있다.', 'career_pivot', 'likert7', false, '{"section":"direction","subscale":"career_pivot","crossTags":["BT:D","UF:autonomy"]}'::jsonb),
  ('f_fs01', 'layer_f', 'F', 119, '직장 생활이 아닌 다른 삶의 형태(창업, 프리랜서, 자영업)를 원한다.', 'fresh_start', 'likert7', false, '{"section":"direction","subscale":"fresh_start","crossTags":["UF:autonomy","BT:D"]}'::jsonb),
  ('f_fs02', 'layer_f', 'F', 120, '과거 경력을 깨끗이 잊고 완전히 다시 시작하고 싶다.', 'fresh_start', 'likert7', false, '{"section":"direction","subscale":"fresh_start","crossTags":["UF:autonomy"]}'::jsonb),
  ('f_fs03', 'layer_f', 'F', 121, '직업 자체보다 삶의 질과 행복이 더 중요하다.', 'fresh_start', 'likert7', false, '{"section":"direction","subscale":"fresh_start","crossTags":["UF:meaning"]}'::jsonb),
  ('f_fs04', 'layer_f', 'F', 122, '기존의 성공 기준과 다른 나만의 기준을 만들고 싶다.', 'fresh_start', 'likert7', false, '{"section":"direction","subscale":"fresh_start","crossTags":["UF:meaning","UF:clarity"]}'::jsonb),
  ('f_fs05', 'layer_f', 'F', 123, '돈보다 의미 있는 일을 하고 싶다.', 'fresh_start', 'likert7', false, '{"section":"direction","subscale":"fresh_start","crossTags":["UF:meaning"]}'::jsonb),
  ('f_fs06', 'layer_f', 'F', 124, '조직에 소속되지 않고 독립적으로 살고 싶다.', 'fresh_start', 'likert7', false, '{"section":"direction","subscale":"fresh_start","crossTags":["UF:autonomy"]}'::jsonb),
  ('f_fs07', 'layer_f', 'F', 125, '이전 삶과 완전히 다른 환경(지역, 국가)에서 새 출발하고 싶다.', 'fresh_start', 'likert7', false, '{"section":"direction","subscale":"fresh_start","crossTags":["UF:autonomy"]}'::jsonb),
  ('f_fs08', 'layer_f', 'F', 126, '사회적 기대나 체면보다 내면의 소리를 따르겠다.', 'fresh_start', 'likert7', false, '{"section":"direction","subscale":"fresh_start","crossTags":["UF:meaning","UF:clarity"]}'::jsonb),
  ('f_fs09', 'layer_f', 'F', 127, '작은 규모라도 내가 주인인 일을 하고 싶다.', 'fresh_start', 'likert7', false, '{"section":"direction","subscale":"fresh_start","crossTags":["UF:autonomy","BT:D"]}'::jsonb),
  ('f_fs10', 'layer_f', 'F', 128, '단절을 통해 인생에서 정말 중요한 것이 무엇인지 알게 되었다.', 'fresh_start', 'likert7', false, '{"section":"direction","subscale":"fresh_start","crossTags":["UF:meaning","SP:Growth"]}'::jsonb),
  ('f_su01', 'layer_f', 'F', 129, '복귀에 필요한 핵심 스킬을 파악하고 있다.', 'skill_update', 'likert7', false, '{"section":"readiness","subscale":"skill_update","crossTags":["SP:Execution","SP:Learning"]}'::jsonb),
  ('f_su02', 'layer_f', 'F', 130, '스킬 업데이트를 위한 교육/학습을 시작했다(또는 계획이 있다).', 'skill_update', 'likert7', false, '{"section":"readiness","subscale":"skill_update","crossTags":["SP:Learning"]}'::jsonb),
  ('f_su03', 'layer_f', 'F', 131, '온라인 교육 플랫폼을 활용하여 학습할 수 있다.', 'skill_update', 'likert7', false, '{"section":"readiness","subscale":"skill_update","crossTags":["SP:Learning"]}'::jsonb),
  ('f_su04', 'layer_f', 'F', 132, '실무 감각을 되살리기 위한 구체적인 방법이 있다.', 'skill_update', 'likert7', false, '{"section":"readiness","subscale":"skill_update","crossTags":["SP:Execution"]}'::jsonb),
  ('f_su05', 'layer_f', 'F', 133, '학습에 투자할 시간과 비용을 확보하고 있다.', 'skill_update', 'likert7', false, '{"section":"readiness","subscale":"skill_update","crossTags":["UF:income","UF:stability"]}'::jsonb),
  ('f_su06', 'layer_f', 'F', 134, '현재 기술 수준으로는 바로 복귀하기 어렵다.', 'skill_update', 'likert7', true, '{"section":"readiness","subscale":"skill_update","crossTags":["SP:Expertise"]}'::jsonb),
  ('f_ns01', 'layer_f', 'F', 135, '단절 전 인맥 중 연락 가능한 사람이 있다.', 'network_status', 'likert7', false, '{"section":"readiness","subscale":"network_status","crossTags":["UF:belonging"]}'::jsonb),
  ('f_ns02', 'layer_f', 'F', 136, '새로운 인맥을 만들기 위한 활동을 하고 있다.', 'network_status', 'likert7', false, '{"section":"readiness","subscale":"network_status","crossTags":["BT:I","SP:Expression"]}'::jsonb),
  ('f_ns03', 'layer_f', 'F', 137, '재취업 관련 커뮤니티나 모임에 참여하고 있다.', 'network_status', 'likert7', false, '{"section":"readiness","subscale":"network_status","crossTags":["BT:S","UF:belonging"]}'::jsonb),
  ('f_ns04', 'layer_f', 'F', 138, '도움을 요청하는 것이 어렵지 않다.', 'network_status', 'likert7', false, '{"section":"readiness","subscale":"network_status","crossTags":["BT:I","BT:S"]}'::jsonb),
  ('f_ns05', 'layer_f', 'F', 139, '경력 단절자 대상 프로그램(정부지원 등)을 알고 있다.', 'network_status', 'likert7', false, '{"section":"readiness","subscale":"network_status","crossTags":["SP:Execution"]}'::jsonb),
  ('f_ns06', 'layer_f', 'F', 140, '사회적으로 고립된 느낌이 있다.', 'network_status', 'likert7', true, '{"section":"readiness","subscale":"network_status","crossTags":["UF:belonging","CH:emotional"]}'::jsonb),
  ('f_sp01', 'layer_f', 'F', 141, '경력 공백을 자연스럽고 긍정적으로 설명할 수 있다.', 'self_presentation', 'likert7', false, '{"section":"readiness","subscale":"self_presentation","crossTags":["SP:Expression","UF:clarity"]}'::jsonb),
  ('f_sp02', 'layer_f', 'F', 142, '이력서에 공백 기간을 어떻게 채울지 알고 있다.', 'self_presentation', 'likert7', false, '{"section":"readiness","subscale":"self_presentation","crossTags":["SP:Execution"]}'::jsonb),
  ('f_sp03', 'layer_f', 'F', 143, '면접에서 "왜 다시 일하려 하는가"에 설득력 있게 답할 수 있다.', 'self_presentation', 'likert7', false, '{"section":"readiness","subscale":"self_presentation","crossTags":["SP:Expression","BT:I"]}'::jsonb),
  ('f_sp04', 'layer_f', 'F', 144, '나의 강점을 3가지 이상 명확하게 말할 수 있다.', 'self_presentation', 'likert7', false, '{"section":"readiness","subscale":"self_presentation","crossTags":["UF:clarity","CH:self_esteem"]}'::jsonb),
  ('f_sp05', 'layer_f', 'F', 145, '경력 단절이 오히려 나를 더 매력적인 후보로 만들 수 있다.', 'self_presentation', 'likert7', false, '{"section":"readiness","subscale":"self_presentation","crossTags":["SP:Resilience","CH:self_esteem"]}'::jsonb),
  ('f_sp06', 'layer_f', 'F', 146, '포트폴리오나 성과 자료를 정리할 수 있다.', 'self_presentation', 'likert7', false, '{"section":"readiness","subscale":"self_presentation","crossTags":["SP:Execution"]}'::jsonb),
  ('f_fl01', 'layer_f', 'F', 147, '목표 분야의 최신 트렌드와 키워드를 알고 있다.', 'field_language', 'likert7', false, '{"section":"readiness","subscale":"field_language","crossTags":["SP:Learning"]}'::jsonb),
  ('f_fl02', 'layer_f', 'F', 148, '업계 뉴스나 미디어를 정기적으로 확인한다.', 'field_language', 'likert7', false, '{"section":"readiness","subscale":"field_language","crossTags":["SP:Learning"]}'::jsonb),
  ('f_fl03', 'layer_f', 'F', 149, '업무 관련 대화에서 자연스럽게 참여할 수 있다.', 'field_language', 'likert7', false, '{"section":"readiness","subscale":"field_language","crossTags":["SP:Expression","BT:I"]}'::jsonb),
  ('f_fl04', 'layer_f', 'F', 150, '채용 공고의 요구사항을 정확하게 이해할 수 있다.', 'field_language', 'likert7', false, '{"section":"readiness","subscale":"field_language","crossTags":["SP:Expertise"]}'::jsonb),
  ('f_fl05', 'layer_f', 'F', 151, '업계 커뮤니티의 토론이나 글을 이해하는 데 어려움이 없다.', 'field_language', 'likert7', false, '{"section":"readiness","subscale":"field_language","crossTags":["SP:Expertise"]}'::jsonb),
  ('f_fl06', 'layer_f', 'F', 152, '단절 기간이 길어져 현장 감각이 많이 떨어졌다.', 'field_language', 'likert7', true, '{"section":"readiness","subscale":"field_language","crossTags":["SP:Expertise"]}'::jsonb),
  ('f_val01', 'layer_f', 'F', 153, '나는 항상 모든 사람에게 100% 솔직하게 말한다.', 'DECOY', 'likert7', false, '{"section":"decoy","subscale":"DECOY","crossTags":[]}'::jsonb),
  ('f_val02', 'layer_f', 'F', 154, '나는 지금까지 단 한 번도 실수를 한 적이 없다.', 'DECOY', 'likert7', false, '{"section":"decoy","subscale":"DECOY","crossTags":[]}'::jsonb);