INSERT INTO public.hit_questions
  (id, module, test_type, question_index, question_text, sub_domain, response_type, reverse_scored, scoring_key)
VALUES
  ('f_dc01', 'layer_f', 'F', 1, '경력 공백의 주된 이유를 명확하게 설명할 수 있다.', 'disruption_context', 'likert7', false, '{"section":"break_context","subscale":"disruption_context","crossTags":["UF:clarity"]}'::jsonb),
  ('f_dc02', 'layer_f', 'F', 2, '경력 단절은 나의 선택이었다(또는 불가피한 상황이었다).', 'disruption_context', 'likert7', false, '{"section":"break_context","subscale":"disruption_context","crossTags":["UF:autonomy"]}'::jsonb),
  ('f_dc03', 'layer_f', 'F', 3, '공백 기간 동안에도 나름의 성장을 했다고 생각한다.', 'disruption_context', 'likert7', false, '{"section":"break_context","subscale":"disruption_context","crossTags":["SP:Growth"]}'::jsonb),
  ('f_dc04', 'layer_f', 'F', 4, '단절 기간이 예상보다 길어졌다.', 'disruption_context', 'likert7', true, '{"section":"break_context","subscale":"disruption_context","crossTags":["UF:security"]}'::jsonb),
  ('f_dc05', 'layer_f', 'F', 5, '단절의 원인이 해소되었거나 해소될 전망이 있다.', 'disruption_context', 'likert7', false, '{"section":"break_context","subscale":"disruption_context","crossTags":["UF:stability"]}'::jsonb),
  ('f_dc06', 'layer_f', 'F', 6, '단절 기간 동안 직업 세계와 완전히 단절되었다.', 'disruption_context', 'likert7', true, '{"section":"break_context","subscale":"disruption_context","crossTags":["UF:belonging"]}'::jsonb),
  ('f_dc07', 'layer_f', 'F', 7, '경력 공백에 대해 부끄러움이나 죄책감을 느낀다.', 'disruption_context', 'likert7', true, '{"section":"break_context","subscale":"disruption_context","crossTags":["CH:self_esteem"]}'::jsonb),
  ('f_dc08', 'layer_f', 'F', 8, '단절 기간에도 업계 동향을 파악하려고 노력했다.', 'disruption_context', 'likert7', false, '{"section":"break_context","subscale":"disruption_context","crossTags":["SP:Learning"]}'::jsonb),
  ('f_hc01', 'layer_f', 'F', 9, '육아/간병 경험을 통해 인내심과 위기관리 능력이 강해졌다.', 'hidden_competency', 'likert7', false, '{"section":"break_context","subscale":"hidden_competency","crossTags":["SP:Resilience","BT:S"]}'::jsonb),
  ('f_hc02', 'layer_f', 'F', 10, '한정된 자원(시간, 돈, 에너지)을 효율적으로 관리하는 법을 배웠다.', 'hidden_competency', 'likert7', false, '{"section":"break_context","subscale":"hidden_competency","crossTags":["SP:Execution","BT:C"]}'::jsonb),
  ('f_hc03', 'layer_f', 'F', 11, '여러 일을 동시에 처리하는 멀티태스킹 능력이 향상되었다.', 'hidden_competency', 'likert7', false, '{"section":"break_context","subscale":"hidden_competency","crossTags":["SP:Execution"]}'::jsonb),
  ('f_hc04', 'layer_f', 'F', 12, '타인의 감정을 읽고 대응하는 능력이 성장했다.', 'hidden_competency', 'likert7', false, '{"section":"break_context","subscale":"hidden_competency","crossTags":["BT:S","BT:I","CH:relational"]}'::jsonb),
  ('f_hc05', 'layer_f', 'F', 13, '스트레스 상황에서도 평정을 유지하는 법을 체득했다.', 'hidden_competency', 'likert7', false, '{"section":"break_context","subscale":"hidden_competency","crossTags":["SP:Resilience","CH:emotional"]}'::jsonb),
  ('f_hc06', 'layer_f', 'F', 14, '문제 해결 능력이 직장 밖 경험을 통해 더 강해졌다.', 'hidden_competency', 'likert7', false, '{"section":"break_context","subscale":"hidden_competency","crossTags":["SP:Thinking"]}'::jsonb),
  ('f_hc07', 'layer_f', 'F', 15, '의사결정을 혼자 내려야 하는 상황이 많아 결단력이 키워졌다.', 'hidden_competency', 'likert7', false, '{"section":"break_context","subscale":"hidden_competency","crossTags":["BT:D","SP:Leadership"]}'::jsonb),
  ('f_hc08', 'layer_f', 'F', 16, '계획대로 되지 않을 때 유연하게 대처하는 법을 배웠다.', 'hidden_competency', 'likert7', false, '{"section":"break_context","subscale":"hidden_competency","crossTags":["SP:Resilience"]}'::jsonb),
  ('f_hc09', 'layer_f', 'F', 17, '다양한 사람(의사, 교사, 행정기관 등)과 소통하는 경험이 늘었다.', 'hidden_competency', 'likert7', false, '{"section":"break_context","subscale":"hidden_competency","crossTags":["BT:I","CH:relational"]}'::jsonb),
  ('f_hc10', 'layer_f', 'F', 18, '단절 기간 동안 자기 자신에 대해 더 깊이 이해하게 되었다.', 'hidden_competency', 'likert7', false, '{"section":"break_context","subscale":"hidden_competency","crossTags":["CH:self_awareness","UF:clarity"]}'::jsonb),
  ('f_hc11', 'layer_f', 'F', 19, '새로운 분야(IT, 온라인 마켓, 부동산 등)를 독학한 경험이 있다.', 'hidden_competency', 'likert7', false, '{"section":"break_context","subscale":"hidden_competency","crossTags":["SP:Learning"]}'::jsonb),
  ('f_hc12', 'layer_f', 'F', 20, '직장 밖에서 쌓은 역량을 이력서에 어떻게 쓸지 모르겠다.', 'hidden_competency', 'likert7', true, '{"section":"break_context","subscale":"hidden_competency","crossTags":["UF:clarity"]}'::jsonb),
  ('f_ga01', 'layer_f', 'F', 21, '공백 기간 동안 자격증, 수료증 등을 취득한 적이 있다.', 'gap_activities', 'likert7', false, '{"section":"break_context","subscale":"gap_activities","crossTags":["SP:Learning"]}'::jsonb),
  ('f_ga02', 'layer_f', 'F', 22, '봉사활동이나 커뮤니티 활동에 참여한 경험이 있다.', 'gap_activities', 'likert7', false, '{"section":"break_context","subscale":"gap_activities","crossTags":["BT:S","UF:belonging"]}'::jsonb),
  ('f_ga03', 'layer_f', 'F', 23, '프리랜서, 부업, 아르바이트 등 수입 활동을 한 적이 있다.', 'gap_activities', 'likert7', false, '{"section":"break_context","subscale":"gap_activities","crossTags":["UF:income"]}'::jsonb),
  ('f_ga04', 'layer_f', 'F', 24, '온라인 강좌나 교육 프로그램을 수강한 적이 있다.', 'gap_activities', 'likert7', false, '{"section":"break_context","subscale":"gap_activities","crossTags":["SP:Learning"]}'::jsonb),
  ('f_ga05', 'layer_f', 'F', 25, '직접 사업을 시도해본 적이 있다(규모 무관).', 'gap_activities', 'likert7', false, '{"section":"break_context","subscale":"gap_activities","crossTags":["BT:D","UF:autonomy"]}'::jsonb),
  ('f_ga06', 'layer_f', 'F', 26, '블로그, SNS, 유튜브 등 콘텐츠를 만든 경험이 있다.', 'gap_activities', 'likert7', false, '{"section":"break_context","subscale":"gap_activities","crossTags":["SP:Expression"]}'::jsonb),
  ('f_ga07', 'layer_f', 'F', 27, '건강 관리(운동, 식단 등)에 집중한 시간이 있었다.', 'gap_activities', 'likert7', false, '{"section":"break_context","subscale":"gap_activities","crossTags":["SP:Resilience"]}'::jsonb),
  ('f_ga08', 'layer_f', 'F', 28, '독서, 학습 등 자기계발에 시간을 투자했다.', 'gap_activities', 'likert7', false, '{"section":"break_context","subscale":"gap_activities","crossTags":["SP:Learning","SP:Growth"]}'::jsonb),
  ('f_ga09', 'layer_f', 'F', 29, '가족이나 주변 사람의 문제를 해결하는 역할을 했다.', 'gap_activities', 'likert7', false, '{"section":"break_context","subscale":"gap_activities","crossTags":["BT:S","CH:relational"]}'::jsonb),
  ('f_ga10', 'layer_f', 'F', 30, '공백 기간에 아무것도 하지 못했다는 느낌이 있다.', 'gap_activities', 'likert7', true, '{"section":"break_context","subscale":"gap_activities","crossTags":["CH:self_esteem"]}'::jsonb),
  ('f_ga11', 'layer_f', 'F', 31, '단절 기간의 경험을 긍정적으로 프레이밍할 수 있다.', 'gap_activities', 'likert7', false, '{"section":"break_context","subscale":"gap_activities","crossTags":["SP:Resilience","UF:clarity"]}'::jsonb),
  ('f_ga12', 'layer_f', 'F', 32, '공백 기간 활동이 향후 경력에 도움이 될 것이라 생각한다.', 'gap_activities', 'likert7', false, '{"section":"break_context","subscale":"gap_activities","crossTags":["SP:Growth"]}'::jsonb),
  ('f_jv01', 'layer_f', 'F', 33, '단절 전 직무가 현재 시장에서도 존재한다.', 'job_viability', 'likert7', false, '{"section":"viability","subscale":"job_viability","crossTags":["UF:security"]}'::jsonb),
  ('f_jv02', 'layer_f', 'F', 34, '해당 직무의 채용 공고를 최근에 확인해보았다.', 'job_viability', 'likert7', false, '{"section":"viability","subscale":"job_viability","crossTags":["SP:Execution"]}'::jsonb),
  ('f_jv03', 'layer_f', 'F', 35, '단절 전 직무의 핵심 업무 내용이 크게 변하지 않았다.', 'job_viability', 'likert7', false, '{"section":"viability","subscale":"job_viability","crossTags":["UF:stability"]}'::jsonb),
  ('f_jv04', 'layer_f', 'F', 36, '해당 분야에서 요구하는 새로운 기술/도구가 많아졌다.', 'job_viability', 'likert7', true, '{"section":"viability","subscale":"job_viability","crossTags":["SP:Learning"]}'::jsonb),
  ('f_jv05', 'layer_f', 'F', 37, '단절 전 보유했던 자격증이나 인증이 여전히 유효하다.', 'job_viability', 'likert7', false, '{"section":"viability","subscale":"job_viability","crossTags":["UF:security"]}'::jsonb),
  ('f_jv06', 'layer_f', 'F', 38, '같은 직무를 다시 할 수 있는 자신감이 있다.', 'job_viability', 'likert7', false, '{"section":"viability","subscale":"job_viability","crossTags":["CH:self_esteem"]}'::jsonb),
  ('f_jv07', 'layer_f', 'F', 39, '공백 기간 동안 해당 분야의 변화를 어느 정도 파악하고 있다.', 'job_viability', 'likert7', false, '{"section":"viability","subscale":"job_viability","crossTags":["SP:Learning"]}'::jsonb),
  ('f_jv08', 'layer_f', 'F', 40, '단절 전 직무 경험이 3년 이상이었다.', 'job_viability', 'likert7', false, '{"section":"viability","subscale":"job_viability","crossTags":["SP:Expertise"]}'::jsonb),
  ('f_jv09', 'layer_f', 'F', 41, '해당 직무의 전문 용어와 업무 프로세스를 여전히 기억한다.', 'job_viability', 'likert7', false, '{"section":"viability","subscale":"job_viability","crossTags":["SP:Expertise"]}'::jsonb),
  ('f_jv10', 'layer_f', 'F', 42, '복귀한다면 교육 없이 바로 업무에 투입될 수 있다.', 'job_viability', 'likert7', false, '{"section":"viability","subscale":"job_viability","crossTags":["SP:Execution"]}'::jsonb),
  ('f_jv11', 'layer_f', 'F', 43, '해당 분야에서 나의 경력 수준(연차)이 경쟁력이 있다.', 'job_viability', 'likert7', false, '{"section":"viability","subscale":"job_viability","crossTags":["SP:Expertise"]}'::jsonb),
  ('f_jv12', 'layer_f', 'F', 44, '단절 기간이 3년 이상이다.', 'job_viability', 'likert7', true, '{"section":"viability","subscale":"job_viability","crossTags":["UF:stability"]}'::jsonb),
  ('f_sc01', 'layer_f', 'F', 45, '단절 전에 사용하던 도구/소프트웨어를 여전히 다룰 수 있다.', 'skill_currency', 'likert7', false, '{"section":"viability","subscale":"skill_currency","crossTags":["SP:Expertise"]}'::jsonb),
  ('f_sc02', 'layer_f', 'F', 46, '해당 분야에서 새로 등장한 도구/기술을 알고 있다.', 'skill_currency', 'likert7', false, '{"section":"viability","subscale":"skill_currency","crossTags":["SP:Learning"]}'::jsonb),
  ('f_sc03', 'layer_f', 'F', 47, '새 도구를 배우는 데 걸리는 시간을 현실적으로 예측할 수 있다.', 'skill_currency', 'likert7', false, '{"section":"viability","subscale":"skill_currency","crossTags":["SP:Thinking"]}'::jsonb),
  ('f_sc04', 'layer_f', 'F', 48, '기술 변화 속도가 빨라 따라잡기 어렵다고 느낀다.', 'skill_currency', 'likert7', true, '{"section":"viability","subscale":"skill_currency","crossTags":["SP:Resilience"]}'::jsonb),
  ('f_sc05', 'layer_f', 'F', 49, '단절 기간에도 관련 기술을 부분적으로 유지했다.', 'skill_currency', 'likert7', false, '{"section":"viability","subscale":"skill_currency","crossTags":["SP:Learning"]}'::jsonb),
  ('f_sc06', 'layer_f', 'F', 50, '업데이트가 필요한 스킬 목록을 구체적으로 작성할 수 있다.', 'skill_currency', 'likert7', false, '{"section":"viability","subscale":"skill_currency","crossTags":["SP:Execution"]}'::jsonb),
  ('f_sc07', 'layer_f', 'F', 51, '스킬 업데이트를 위한 교육 프로그램을 찾아본 적이 있다.', 'skill_currency', 'likert7', false, '{"section":"viability","subscale":"skill_currency","crossTags":["SP:Learning"]}'::jsonb),
  ('f_sc08', 'layer_f', 'F', 52, '기본기(core fundamentals)는 변하지 않아 여전히 유효하다.', 'skill_currency', 'likert7', false, '{"section":"viability","subscale":"skill_currency","crossTags":["SP:Expertise"]}'::jsonb),
  ('f_sc09', 'layer_f', 'F', 53, '디지털 리터러시(기본 IT 활용 능력)에 자신이 있다.', 'skill_currency', 'likert7', false, '{"section":"viability","subscale":"skill_currency","crossTags":["SP:Expertise"]}'::jsonb),
  ('f_sc10', 'layer_f', 'F', 54, '산업 전체가 구조적으로 변해 기존 스킬이 무의미해졌다.', 'skill_currency', 'likert7', true, '{"section":"viability","subscale":"skill_currency","crossTags":["UF:security"]}'::jsonb),
  ('f_sc11', 'layer_f', 'F', 55, '스킬 갭을 6개월 이내에 메울 수 있다고 생각한다.', 'skill_currency', 'likert7', false, '{"section":"viability","subscale":"skill_currency","crossTags":["SP:Growth"]}'::jsonb),
  ('f_sc12', 'layer_f', 'F', 56, '현장 언어(업계 용어, 약어 등)가 낯설어졌다.', 'skill_currency', 'likert7', true, '{"section":"viability","subscale":"skill_currency","crossTags":["SP:Expertise"]}'::jsonb),
  ('f_mr01', 'layer_f', 'F', 57, '경력 단절자를 채용하는 기업이나 프로그램이 있다는 것을 안다.', 'market_reentry', 'likert7', false, '{"section":"viability","subscale":"market_reentry","crossTags":["UF:belonging"]}'::jsonb),
  ('f_mr02', 'layer_f', 'F', 58, '재취업 지원 프로그램(정부, 기관)을 알아본 적이 있다.', 'market_reentry', 'likert7', false, '{"section":"viability","subscale":"market_reentry","crossTags":["SP:Execution"]}'::jsonb),
  ('f_mr03', 'layer_f', 'F', 59, '단절 전 업계에 아직 연락 가능한 사람이 있다.', 'market_reentry', 'likert7', false, '{"section":"viability","subscale":"market_reentry","crossTags":["UF:belonging"]}'::jsonb),
  ('f_mr04', 'layer_f', 'F', 60, '채용 시장에서 경력 단절에 대한 인식이 예전보다 나아졌다고 느낀다.', 'market_reentry', 'likert7', false, '{"section":"viability","subscale":"market_reentry","crossTags":["UF:stability"]}'::jsonb),
  ('f_mr05', 'layer_f', 'F', 61, '파트타임이나 계약직으로라도 복귀할 의지가 있다.', 'market_reentry', 'likert7', false, '{"section":"viability","subscale":"market_reentry","crossTags":["UF:income"]}'::jsonb),
  ('f_mr06', 'layer_f', 'F', 62, '단절 전보다 낮은 직급/급여도 수용할 수 있다.', 'market_reentry', 'likert7', false, '{"section":"viability","subscale":"market_reentry","crossTags":["UF:autonomy"]}'::jsonb),
  ('f_mr07', 'layer_f', 'F', 63, '새로운 분야로의 전환도 열려 있다.', 'market_reentry', 'likert7', false, '{"section":"viability","subscale":"market_reentry","crossTags":["BT:D","SP:Growth"]}'::jsonb),
  ('f_mr08', 'layer_f', 'F', 64, '내 경력 공백을 긍정적으로 설명할 수 있는 스토리가 있다.', 'market_reentry', 'likert7', false, '{"section":"viability","subscale":"market_reentry","crossTags":["SP:Expression","UF:clarity"]}'::jsonb),
  ('f_mr09', 'layer_f', 'F', 65, '재취업에 성공한 비슷한 상황의 롤모델이 있다.', 'market_reentry', 'likert7', false, '{"section":"viability","subscale":"market_reentry","crossTags":["UF:belonging"]}'::jsonb),
  ('f_mr10', 'layer_f', 'F', 66, '현재 거주 지역에서 재취업 기회가 충분하다.', 'market_reentry', 'likert7', false, '{"section":"viability","subscale":"market_reentry","crossTags":["UF:security"]}'::jsonb),
  ('f_mr11', 'layer_f', 'F', 67, '원격 근무(재택근무) 포지션도 적극 고려하고 있다.', 'market_reentry', 'likert7', false, '{"section":"viability","subscale":"market_reentry","crossTags":["UF:autonomy"]}'::jsonb),
  ('f_mr12', 'layer_f', 'F', 68, '재취업이 현실적으로 어렵다고 느낀다.', 'market_reentry', 'likert7', true, '{"section":"viability","subscale":"market_reentry","crossTags":["CH:self_esteem"]}'::jsonb),
  ('f_sn01', 'layer_f', 'F', 69, '경력 단절/실패를 내 탓으로만 돌리지 않는다.', 'self_narrative', 'likert7', false, '{"section":"resilience","subscale":"self_narrative","crossTags":["CH:self_esteem","SP:Resilience"]}'::jsonb),
  ('f_sn02', 'layer_f', 'F', 70, '이 경험을 통해 더 강해졌다고 느낀다.', 'self_narrative', 'likert7', false, '{"section":"resilience","subscale":"self_narrative","crossTags":["SP:Resilience"]}'::jsonb),
  ('f_sn03', 'layer_f', 'F', 71, '내 이야기를 부끄러워하지 않고 말할 수 있다.', 'self_narrative', 'likert7', false, '{"section":"resilience","subscale":"self_narrative","crossTags":["CH:self_esteem","SP:Expression"]}'::jsonb),
  ('f_sn04', 'layer_f', 'F', 72, '단절 전의 나보다 지금의 내가 더 나은 부분이 있다.', 'self_narrative', 'likert7', false, '{"section":"resilience","subscale":"self_narrative","crossTags":["SP:Growth"]}'::jsonb),
  ('f_sn05', 'layer_f', 'F', 73, '실패한 경험에서 구체적으로 배운 교훈이 있다.', 'self_narrative', 'likert7', false, '{"section":"resilience","subscale":"self_narrative","crossTags":["SP:Learning"]}'::jsonb),
  ('f_sn06', 'layer_f', 'F', 74, '다른 사람의 시선이 두려워 재도전을 망설인다.', 'self_narrative', 'likert7', true, '{"section":"resilience","subscale":"self_narrative","crossTags":["CH:emotional"]}'::jsonb),
  ('f_sn07', 'layer_f', 'F', 75, '내 가치가 직업적 성공에만 달려있지 않다고 믿는다.', 'self_narrative', 'likert7', false, '{"section":"resilience","subscale":"self_narrative","crossTags":["UF:meaning"]}'::jsonb),
  ('f_sn08', 'layer_f', 'F', 76, '과거의 경력을 흑역사가 아닌 자산으로 본다.', 'self_narrative', 'likert7', false, '{"section":"resilience","subscale":"self_narrative","crossTags":["SP:Resilience","UF:clarity"]}'::jsonb),
  ('f_sn09', 'layer_f', 'F', 77, '지금의 상황이 영원히 계속되지는 않을 것이다.', 'self_narrative', 'likert7', false, '{"section":"resilience","subscale":"self_narrative","crossTags":["SP:Resilience"]}'::jsonb);