-- HIT Layer B: 50문항 (competency_core 18 + readiness_core 32)
-- 자동 생성: Scripts/seed-hit-layer-b.js

DELETE FROM public.hit_questions WHERE module IN ('competency_core', 'readiness_core');

INSERT INTO public.hit_questions
  (id, module, test_type, question_index, question_text, sub_domain, response_type, reverse_scored, scoring_key)
VALUES
  ('b_ps01', 'competency_core', 'B', 1, '복잡한 문제를 작은 단위로 나누어 접근하는 편이다.', 'problem_solving', 'likert7', false, '{"section":"core_competency","subscale":"problem_solving","crossTags":["SP:Analytical","PT:T","BT:C"]}'::jsonb),
  ('b_ps02', 'competency_core', 'B', 2, '문제의 원인을 파악한 후 해결책을 찾는 순서를 따른다.', 'problem_solving', 'likert7', false, '{"section":"core_competency","subscale":"problem_solving","crossTags":["SP:Analytical","PT:T","PT:J"]}'::jsonb),
  ('b_ps03', 'competency_core', 'B', 3, '해결책이 바로 떠오르지 않아도 다양한 방법을 시도해본다.', 'problem_solving', 'likert7', false, '{"section":"core_competency","subscale":"problem_solving","crossTags":["SP:Breakthrough","PT:N","PT:P"]}'::jsonb),
  ('b_cm01', 'competency_core', 'B', 4, '내 생각을 상대방이 이해하기 쉽게 전달할 수 있다.', 'communication', 'likert7', false, '{"section":"core_competency","subscale":"communication","crossTags":["SP:Interpersonal","BT:I","PT:E"]}'::jsonb),
  ('b_cm02', 'competency_core', 'B', 5, '상대방의 말을 끝까지 듣고 핵심을 파악하는 편이다.', 'communication', 'likert7', false, '{"section":"core_competency","subscale":"communication","crossTags":["SP:Harmony","BT:S","PT:F"]}'::jsonb),
  ('b_cm03', 'competency_core', 'B', 6, '글로 자기 생각을 논리적으로 정리하는 것에 자신이 있다.', 'communication', 'likert7', false, '{"section":"core_competency","subscale":"communication","crossTags":["SP:Analytical","BT:C","PT:T"]}'::jsonb),
  ('b_in01', 'competency_core', 'B', 7, '시키지 않아도 필요한 일을 먼저 찾아서 하는 편이다.', 'initiative', 'likert7', false, '{"section":"core_competency","subscale":"initiative","crossTags":["SP:Execution","BT:D","PT:J"]}'::jsonb),
  ('b_in02', 'competency_core', 'B', 8, '새로운 아이디어가 있으면 직접 제안해본 경험이 있다.', 'initiative', 'likert7', false, '{"section":"core_competency","subscale":"initiative","crossTags":["SP:Creativity","BT:D","PT:N"]}'::jsonb),
  ('b_in03', 'competency_core', 'B', 9, '주어진 것 이상의 결과를 내려고 노력하는 편이다.', 'initiative', 'likert7', false, '{"section":"core_competency","subscale":"initiative","crossTags":["SP:Execution","BT:D"]}'::jsonb),
  ('b_cl01', 'competency_core', 'B', 10, '팀에서 내 역할을 파악하고 맡은 바를 책임지는 편이다.', 'collaboration', 'likert7', false, '{"section":"core_competency","subscale":"collaboration","crossTags":["SP:Guard","BT:S","PT:J"]}'::jsonb),
  ('b_cl02', 'competency_core', 'B', 11, '의견이 다른 팀원과도 생산적으로 협력할 수 있다.', 'collaboration', 'likert7', false, '{"section":"core_competency","subscale":"collaboration","crossTags":["SP:Harmony","BT:S","PT:F"]}'::jsonb),
  ('b_cl03', 'competency_core', 'B', 12, '팀 목표를 위해 내 의견을 양보한 경험이 있다.', 'collaboration', 'likert7', false, '{"section":"core_competency","subscale":"collaboration","crossTags":["SP:Harmony","BT:S"]}'::jsonb),
  ('b_sm01', 'competency_core', 'B', 13, '여러 과제가 동시에 있을 때 우선순위를 정해 처리한다.', 'self_management', 'likert7', false, '{"section":"core_competency","subscale":"self_management","crossTags":["SP:Execution","PT:J","BT:C"]}'::jsonb),
  ('b_sm02', 'competency_core', 'B', 14, '스트레스 상황에서도 감정을 조절하며 업무를 수행할 수 있다.', 'self_management', 'likert7', false, '{"section":"core_competency","subscale":"self_management","crossTags":["CH:emotional","BT:S"]}'::jsonb),
  ('b_sm03', 'competency_core', 'B', 15, '마감을 지키기 위해 스스로 일정을 관리하는 습관이 있다.', 'self_management', 'likert7', false, '{"section":"core_competency","subscale":"self_management","crossTags":["CH:integrity","PT:J"]}'::jsonb),
  ('b_la01', 'competency_core', 'B', 16, '처음 접하는 업무도 빠르게 파악하여 수행할 수 있다.', 'learning_agility', 'likert7', false, '{"section":"core_competency","subscale":"learning_agility","crossTags":["CH:growth","PT:N","UF:temperament"]}'::jsonb),
  ('b_la02', 'competency_core', 'B', 17, '실패에서 배운 점을 다음에 적용하려고 노력한다.', 'learning_agility', 'likert7', false, '{"section":"core_competency","subscale":"learning_agility","crossTags":["CH:growth","UF:trauma(PTG)"]}'::jsonb),
  ('b_la03', 'competency_core', 'B', 18, '피드백을 받으면 방어하기보다 개선점을 찾는 편이다.', 'learning_agility', 'likert7', false, '{"section":"core_competency","subscale":"learning_agility","crossTags":["CH:growth","BT:S"]}'::jsonb),
  ('b_su01', 'readiness_core', 'B', 19, '내 강점과 약점을 구체적으로 설명할 수 있다.', 'self_understanding', 'likert7', false, '{"section":"core_readiness","subscale":"self_understanding","crossTags":["UF:self","SP:전반"]}'::jsonb),
  ('b_su02', 'readiness_core', 'B', 20, '내가 일에서 가장 중요하게 생각하는 가치가 무엇인지 안다.', 'self_understanding', 'likert7', false, '{"section":"core_readiness","subscale":"self_understanding","crossTags":["CH:ethics","AP:방향"]}'::jsonb),
  ('b_su03', 'readiness_core', 'B', 21, '어떤 환경에서 내가 가장 잘 일하는지 파악하고 있다.', 'self_understanding', 'likert7', false, '{"section":"core_readiness","subscale":"self_understanding","crossTags":["BT:전반","PT:전반"]}'::jsonb),
  ('b_su04', 'readiness_core', 'B', 22, '내 성격이 직무에 미치는 영향을 이해하고 있다.', 'self_understanding', 'likert7', false, '{"section":"core_readiness","subscale":"self_understanding","crossTags":["PT:전반","BT:전반"]}'::jsonb),
  ('b_su05', 'readiness_core', 'B', 23, '다른 사람이 나를 어떻게 보는지에 대한 인식이 있다.', 'self_understanding', 'likert7', false, '{"section":"core_readiness","subscale":"self_understanding","crossTags":["UF:peer","BT:전반"]}'::jsonb),
  ('b_su06', 'readiness_core', 'B', 24, '나에게 맞지 않는 직무 유형이 무엇인지 안다.', 'self_understanding', 'likert7', false, '{"section":"core_readiness","subscale":"self_understanding","crossTags":["AP:역방향"]}'::jsonb),
  ('b_su07', 'readiness_core', 'B', 25, '내가 스트레스를 받는 상황과 대처 방식을 이해한다.', 'self_understanding', 'likert7', false, '{"section":"core_readiness","subscale":"self_understanding","crossTags":["CH:emotional","UF:temperament"]}'::jsonb),
  ('b_su08', 'readiness_core', 'B', 26, '자기소개서에 내 강점을 구체적 사례와 함께 쓸 수 있다.', 'self_understanding', 'likert7', false, '{"section":"core_readiness","subscale":"self_understanding","crossTags":["BT:I","UF:self"]}'::jsonb),
  ('b_ju01', 'readiness_core', 'B', 27, '희망 직무의 하루 업무를 구체적으로 설명할 수 있다.', 'job_understanding', 'likert7', false, '{"section":"core_readiness","subscale":"job_understanding","crossTags":["PT:S","BT:C"]}'::jsonb),
  ('b_ju02', 'readiness_core', 'B', 28, '희망 산업의 시장 상황과 전망을 파악하고 있다.', 'job_understanding', 'likert7', false, '{"section":"core_readiness","subscale":"job_understanding","crossTags":["PT:N","SP:Strategic"]}'::jsonb),
  ('b_ju03', 'readiness_core', 'B', 29, '희망 직무에서 요구하는 핵심 역량을 알고 있다.', 'job_understanding', 'likert7', false, '{"section":"core_readiness","subscale":"job_understanding","crossTags":["SP:전반"]}'::jsonb),
  ('b_ju04', 'readiness_core', 'B', 30, '관심 기업 3곳 이상의 특징을 설명할 수 있다.', 'job_understanding', 'likert7', false, '{"section":"core_readiness","subscale":"job_understanding","crossTags":["PT:S","BT:C"]}'::jsonb),
  ('b_ju05', 'readiness_core', 'B', 31, '해당 직무의 성장 경로(커리어 패스)를 이해하고 있다.', 'job_understanding', 'likert7', false, '{"section":"core_readiness","subscale":"job_understanding","crossTags":["SP:Strategic","PT:N"]}'::jsonb),
  ('b_ju06', 'readiness_core', 'B', 32, '현직자와 대화하거나 정보를 수집한 경험이 있다.', 'job_understanding', 'likert7', false, '{"section":"core_readiness","subscale":"job_understanding","crossTags":["BT:I","PT:E"]}'::jsonb),
  ('b_ju07', 'readiness_core', 'B', 33, '직무와 관련된 뉴스나 트렌드를 정기적으로 확인한다.', 'job_understanding', 'likert7', false, '{"section":"core_readiness","subscale":"job_understanding","crossTags":["CH:growth","PT:N"]}'::jsonb),
  ('b_ju08', 'readiness_core', 'B', 34, '내 강점이 희망 직무에서 어떻게 발휘될지 설명할 수 있다.', 'job_understanding', 'likert7', false, '{"section":"core_readiness","subscale":"job_understanding","crossTags":["SP:전반","UF:self"]}'::jsonb),
  ('b_sr01', 'readiness_core', 'B', 35, '희망 직무와 관련된 자격증이나 수료증을 보유하고 있다.', 'skill_readiness', 'likert7', false, '{"section":"core_readiness","subscale":"skill_readiness","crossTags":["CH:integrity","PT:J"]}'::jsonb),
  ('b_sr02', 'readiness_core', 'B', 36, '인턴, 아르바이트, 프로젝트 등 실무 경험이 있다.', 'skill_readiness', 'likert7', false, '{"section":"core_readiness","subscale":"skill_readiness","crossTags":["SP:Execution"]}'::jsonb),
  ('b_sr03', 'readiness_core', 'B', 37, '포트폴리오나 결과물을 제출할 수 있는 상태다.', 'skill_readiness', 'likert7', false, '{"section":"core_readiness","subscale":"skill_readiness","crossTags":["BT:C","PT:J"]}'::jsonb),
  ('b_sr04', 'readiness_core', 'B', 38, '희망 직무에 필요한 도구(소프트웨어, 장비 등)를 다룰 수 있다.', 'skill_readiness', 'likert7', false, '{"section":"core_readiness","subscale":"skill_readiness","crossTags":["SP:Execution"]}'::jsonb),
  ('b_sr05', 'readiness_core', 'B', 39, '역량 갭을 인식하고 있으며 보완 계획이 있다.', 'skill_readiness', 'likert7', false, '{"section":"core_readiness","subscale":"skill_readiness","crossTags":["SP:Strategic","CH:growth"]}'::jsonb),
  ('b_sr06', 'readiness_core', 'B', 40, '관련 분야 스터디, 동아리, 커뮤니티에 참여한 경험이 있다.', 'skill_readiness', 'likert7', false, '{"section":"core_readiness","subscale":"skill_readiness","crossTags":["BT:I","CH:growth"]}'::jsonb),
  ('b_sr07', 'readiness_core', 'B', 41, '현재 역량 수준을 객관적으로 평가할 수 있다.', 'skill_readiness', 'likert7', false, '{"section":"core_readiness","subscale":"skill_readiness","crossTags":["UF:self","SP:Analytical"]}'::jsonb),
  ('b_sr08', 'readiness_core', 'B', 42, '역량 부족 영역을 보완하기 위해 현재 활동 중인 것이 있다.', 'skill_readiness', 'likert7', false, '{"section":"core_readiness","subscale":"skill_readiness","crossTags":["CH:growth","SP:Execution"]}'::jsonb),
  ('b_ar01', 'readiness_core', 'B', 43, '이력서가 최신 상태로 준비되어 있다.', 'action_readiness', 'likert7', false, '{"section":"core_readiness","subscale":"action_readiness","crossTags":["PT:J","BT:C"]}'::jsonb),
  ('b_ar02', 'readiness_core', 'B', 44, '자기소개서를 기업별로 맞춤 작성할 수 있다.', 'action_readiness', 'likert7', false, '{"section":"core_readiness","subscale":"action_readiness","crossTags":["PT:N","BT:C"]}'::jsonb),
  ('b_ar03', 'readiness_core', 'B', 45, '면접에서 자기 소개를 자신 있게 할 수 있다.', 'action_readiness', 'likert7', false, '{"section":"core_readiness","subscale":"action_readiness","crossTags":["BT:I","UF:self"]}'::jsonb),
  ('b_ar04', 'readiness_core', 'B', 46, '면접에서 예상 질문에 대한 답변을 준비하고 있다.', 'action_readiness', 'likert7', false, '{"section":"core_readiness","subscale":"action_readiness","crossTags":["PT:J","BT:C"]}'::jsonb),
  ('b_ar05', 'readiness_core', 'B', 47, '취업 관련 네트워킹(OB 방문, 박람회 등)에 참여한 적이 있다.', 'action_readiness', 'likert7', false, '{"section":"core_readiness","subscale":"action_readiness","crossTags":["BT:I","PT:E"]}'::jsonb),
  ('b_ar06', 'readiness_core', 'B', 48, '구직 활동에 투자하는 시간을 정기적으로 확보하고 있다.', 'action_readiness', 'likert7', false, '{"section":"core_readiness","subscale":"action_readiness","crossTags":["CH:integrity","PT:J"]}'::jsonb),
  ('b_ar07', 'readiness_core', 'B', 49, '지원 결과에 대한 불안을 관리하며 꾸준히 활동할 수 있다.', 'action_readiness', 'likert7', false, '{"section":"core_readiness","subscale":"action_readiness","crossTags":["CH:emotional","SP:Breakthrough"]}'::jsonb),
  ('b_ar08', 'readiness_core', 'B', 50, '취업 활동을 지지해주는 가족, 친구, 멘토가 있다.', 'action_readiness', 'likert7', false, '{"section":"core_readiness","subscale":"action_readiness","crossTags":["UF:family","UF:peer"]}'::jsonb);