// 마케팅 용어 사전 데이터
// 카테고리별로 분류, 검색/필터 지원 — 전체 500+ 용어 수록

export interface GlossaryTerm {
  en: string;
  ko: string;
  abbr?: string;
  definition: string;
  category: string;
}

export const CATEGORIES = [
  '전체', 'SEO/GEO', '광고', '분석', '브랜딩', '콘텐츠', 'CRM', '소셜미디어',
  '디자인', '데이터', '애자일', '고객서비스', '전환최적화', '프로그래매틱',
  '이커머스', '이메일마케팅', '모바일', '영상', 'PR', '전략',
];

export const GLOSSARY: GlossaryTerm[] = [
  // ── A ──
  { en: 'A/B Test', ko: 'A/B 테스트', definition: '두 가지 버전을 실험하여 더 높은 효과를 낸 것을 선택하는 방식', category: '전환최적화' },
  { en: 'A/B/n Test', ko: 'A/B/n 테스트', definition: '세 개 이상의 변형을 동시에 비교하는 다변량 실험 방식', category: '전환최적화' },
  { en: 'Above the Fold', ko: '어보브 더 폴드', definition: '스크롤 없이 화면에 바로 보이는 영역', category: '디자인' },
  { en: 'Above the Line', ko: '매스미디어 광고', abbr: 'ATL', definition: 'TV, 라디오 등 전통적 대중매체를 통한 광고 활동', category: '광고' },
  { en: 'Account-Based Marketing', ko: '계정 기반 마케팅', abbr: 'ABM', definition: '특정 기업을 타겟으로 맞춤형 마케팅을 진행하는 B2B 전략', category: 'CRM' },
  { en: 'Acquisition', ko: '획득', definition: '새로운 고객을 확보하는 단계', category: '분석' },
  { en: 'Activation', ko: '활성화', definition: '사용자가 핵심 기능을 처음으로 경험하는 단계 (AARRR 프레임워크)', category: '분석' },
  { en: 'Active Users', ko: '활성 사용자', definition: '일정 기간 내에 서비스를 이용한 사용자 수 (DAU/WAU/MAU)', category: '분석' },
  { en: 'Ad Blocker', ko: '광고 차단기', definition: '브라우저에서 광고를 차단하는 소프트웨어', category: '광고' },
  { en: 'Ad Exchange', ko: '광고 교환소', definition: '광고 인벤토리를 실시간으로 거래하는 디지털 마켓플레이스', category: '프로그래매틱' },
  { en: 'Ad Extension', ko: '광고 확장', definition: '검색 광고에 추가 정보(전화번호, 위치, 링크 등)를 표시하는 기능', category: '광고' },
  { en: 'Ad Fatigue', ko: '광고 피로도', definition: '같은 광고를 반복 노출하여 사용자의 반응이 감소하는 현상', category: '광고' },
  { en: 'Ad Fraud', ko: '광고 사기', definition: '가짜 클릭이나 허위 트래픽으로 광고비를 부정하게 획득하는 행위', category: '광고' },
  { en: 'Ad Group', ko: '광고 그룹', definition: '공통 타겟팅을 공유하는 광고 묶음 단위', category: '광고' },
  { en: 'Ad Impression', ko: '광고 노출', definition: '광고가 사용자 화면에 표시된 횟수', category: '광고' },
  { en: 'Ad Inventory', ko: '광고 인벤토리', definition: '매체가 보유한 광고 노출 공간의 총량', category: '프로그래매틱' },
  { en: 'Ad Network', ko: '광고 네트워크', definition: '여러 매체의 광고 공간을 묶어 광고주에게 제공하는 플랫폼', category: '프로그래매틱' },
  { en: 'Ad Placement', ko: '광고 배치', definition: '광고가 노출되는 구체적인 위치 (뉴스피드, 스토리, 사이드바 등)', category: '광고' },
  { en: 'Ad Rank', ko: '광고 순위', definition: '검색 광고의 노출 순서를 결정하는 점수 (입찰가 × 품질점수)', category: '광고' },
  { en: 'Ad Recall', ko: '광고 회상', definition: '광고를 본 사용자가 나중에 해당 광고를 기억하는 정도', category: '광고' },
  { en: 'Ad Rotation', ko: '광고 로테이션', definition: '여러 광고 소재를 순환하여 노출하는 방식', category: '광고' },
  { en: 'Ad Server', ko: '광고 서버', definition: '디지털 광고를 저장, 관리, 전달하는 기술 플랫폼', category: '프로그래매틱' },
  { en: 'Ad Serving', ko: '광고 서빙', definition: '광고를 사용자에게 전달하는 기술적 프로세스', category: '프로그래매틱' },
  { en: 'Ad Spend', ko: '광고비', definition: '광고 집행에 사용한 총 비용', category: '광고' },
  { en: 'Ad Tech', ko: '광고 기술', definition: '디지털 광고를 생성, 관리, 최적화하는 기술의 총칭', category: '프로그래매틱' },
  { en: 'Addressable TV', ko: '어드레서블 TV', definition: '가구별로 다른 광고를 송출할 수 있는 TV 광고 기술', category: '광고' },
  { en: 'Affiliate Marketing', ko: '제휴 마케팅', definition: '파트너가 제품을 홍보하고 성과에 따라 수수료를 받는 마케팅 모델', category: '광고' },
  { en: 'Agile Marketing', ko: '애자일 마케팅', definition: '반복적이고 유연한 방식으로 마케팅 캠페인을 실행하는 방법론', category: '애자일' },
  { en: 'AI Overview', ko: 'AI 오버뷰', definition: 'Google 검색 결과 상단에 AI가 생성한 요약 답변을 표시하는 기능', category: 'SEO/GEO' },
  { en: 'AIDA Model', ko: 'AIDA 모델', definition: '주의(Attention)→관심(Interest)→욕구(Desire)→행동(Action)의 소비자 반응 단계', category: '전략' },
  { en: 'AISAS Model', ko: 'AISAS 모델', definition: '주의→관심→검색(Search)→행동→공유(Share)의 디지털 소비자 행동 모델', category: '전략' },
  { en: 'Algorithm', ko: '알고리즘', definition: '콘텐츠와 사용자 간 연결을 최적화하기 위한 규칙과 절차', category: 'SEO/GEO' },
  { en: 'Alt Text', ko: '대체 텍스트', definition: '이미지를 설명하는 텍스트로 접근성과 SEO에 중요', category: 'SEO/GEO' },
  { en: 'Ambient Marketing', ko: '앰비언트 마케팅', definition: '일상적인 환경에 자연스럽게 녹아든 비전통적 광고', category: '광고' },
  { en: 'AMP', ko: '가속 모바일 페이지', abbr: 'AMP', definition: '모바일에서 빠르게 로딩되도록 최적화된 웹 페이지 포맷', category: '모바일' },
  { en: 'Analytics', ko: '분석', definition: '데이터를 수집하고 분석하여 마케팅 성과를 측정하는 활동', category: '분석' },
  { en: 'Anchor Text', ko: '앵커 텍스트', definition: '하이퍼링크에 사용되는 클릭 가능한 텍스트', category: 'SEO/GEO' },
  { en: 'API', ko: '애플리케이션 프로그래밍 인터페이스', abbr: 'API', definition: '소프트웨어 간 데이터를 교환하기 위한 인터페이스', category: '데이터' },
  { en: 'App Store Optimization', ko: '앱스토어 최적화', abbr: 'ASO', definition: '앱스토어에서 앱의 검색 순위와 전환율을 높이는 최적화 작업', category: '모바일' },
  { en: 'Assisted Conversion', ko: '보조 전환', definition: '최종 전환 이전에 기여한 채널의 전환 기여도', category: '분석' },
  { en: 'Attribution Model', ko: '기여도 모델', definition: '전환에 기여한 채널을 평가하는 방식', category: '분석' },
  { en: 'Attribution Window', ko: '기여 기간', definition: '광고 노출 후 전환으로 인정하는 시간 범위', category: '분석' },
  { en: 'Audience Network', ko: '오디언스 네트워크', definition: '소셜 플랫폼의 광고를 외부 앱과 사이트에도 확장 노출하는 네트워크', category: '광고' },
  { en: 'Audience Segmentation', ko: '오디언스 세분화', definition: '고객을 특성별로 그룹화하여 맞춤형 마케팅을 진행하는 방법', category: 'CRM' },
  { en: 'Augmented Reality', ko: '증강현실', abbr: 'AR', definition: '현실 환경에 디지털 요소를 겹쳐 보여주는 기술', category: '디자인' },
  { en: 'Automated Bidding', ko: '자동 입찰', definition: 'AI가 목표에 맞게 광고 입찰가를 자동으로 조절하는 방식', category: '광고' },
  { en: 'Average Order Value', ko: '평균 주문 금액', abbr: 'AOV', definition: '고객당 평균 주문 금액', category: '이커머스' },
  { en: 'Average Revenue Per User', ko: '사용자당 평균 매출', abbr: 'ARPU', definition: '사용자 한 명이 발생시키는 평균 매출액', category: '분석' },
  { en: 'Awareness', ko: '인지도', definition: '소비자가 브랜드나 제품을 알고 있는 정도', category: '브랜딩' },

  // ── B ──
  { en: 'B2B Marketing', ko: 'B2B 마케팅', definition: '기업 간 거래를 위한 마케팅 활동', category: '전략' },
  { en: 'B2C Marketing', ko: 'B2C 마케팅', definition: '기업과 소비자 간 거래를 위한 마케팅 활동', category: '전략' },
  { en: 'Backlink', ko: '백링크', definition: '외부 사이트에서 자신의 사이트로 연결되는 링크. SEO의 핵심 요소', category: 'SEO/GEO' },
  { en: 'Banner Ad', ko: '배너 광고', definition: '웹페이지에 표시되는 이미지 형태의 디스플레이 광고', category: '광고' },
  { en: 'Banner Blindness', ko: '배너 실명', definition: '사용자가 배너 광고를 무의식적으로 무시하는 현상', category: '광고' },
  { en: 'Behavioral Targeting', ko: '행동 타겟팅', definition: '사용자의 과거 행동 데이터를 기반으로 광고를 맞춤 노출하는 방식', category: '프로그래매틱' },
  { en: 'Below the Line', ko: '비대중매체 광고', abbr: 'BTL', definition: 'DM, 이벤트, 프로모션 등 직접적인 소비자 접점을 활용한 광고', category: '광고' },
  { en: 'Benchmarking', ko: '벤치마킹', definition: '경쟁사나 업계 최고 수준과 자사 성과를 비교 분석하는 활동', category: '분석' },
  { en: 'Bid Strategy', ko: '입찰 전략', definition: '광고 경매에서 입찰가를 결정하는 방식 (수동, 자동, 타겟 CPA 등)', category: '광고' },
  { en: 'Big Data', ko: '빅데이터', definition: '기존 방식으로 처리하기 어려운 대규모의 복잡한 데이터', category: '데이터' },
  { en: 'Black Hat SEO', ko: '블랙햇 SEO', definition: '검색 엔진 가이드라인을 위반하는 비정상적인 SEO 기법', category: 'SEO/GEO' },
  { en: 'Blog', ko: '블로그', definition: '정기적으로 콘텐츠를 게시하는 웹사이트 또는 웹페이지', category: '콘텐츠' },
  { en: 'Bounce Rate', ko: '이탈률', definition: '사용자가 단일 페이지에서 이탈하는 비율', category: '분석' },
  { en: 'Brand Advocacy', ko: '브랜드 옹호', definition: '고객이 자발적으로 브랜드를 홍보하고 추천하는 행위', category: '브랜딩' },
  { en: 'Brand Ambassador', ko: '브랜드 앰배서더', definition: '브랜드를 대표하여 홍보하는 인물 (유명인 또는 충성 고객)', category: '브랜딩' },
  { en: 'Brand Architecture', ko: '브랜드 아키텍처', definition: '기업이 보유한 브랜드들의 구조와 관계를 정의하는 체계', category: '브랜딩' },
  { en: 'Brand Audit', ko: '브랜드 감사', definition: '브랜드의 현재 위치, 강점, 약점을 종합적으로 분석하는 활동', category: '브랜딩' },
  { en: 'Brand Awareness', ko: '브랜드 인지도', definition: '소비자가 특정 브랜드를 인식하고 기억하는 정도', category: '브랜딩' },
  { en: 'Brand Consistency', ko: '브랜드 일관성', definition: '모든 접점에서 동일한 브랜드 메시지와 비주얼을 유지하는 것', category: '브랜딩' },
  { en: 'Brand Equity', ko: '브랜드 자산', definition: '소비자에게 인식되는 브랜드의 신뢰, 인지도, 이미지가 매출로 전환되는 능력', category: '브랜딩' },
  { en: 'Brand Experience', ko: '브랜드 경험', definition: '고객이 브랜드와의 모든 접점에서 느끼는 총체적 경험', category: '브랜딩' },
  { en: 'Brand Identity', ko: '브랜드 정체성', abbr: 'BI', definition: '브랜드가 전달하고자 하는 시각적·정서적 요소들의 집합', category: '브랜딩' },
  { en: 'Brand Lift', ko: '브랜드 리프트', definition: '광고 캠페인이 브랜드 인지도, 호감도, 구매 의향에 미친 영향을 측정하는 조사', category: '브랜딩' },
  { en: 'Brand Loyalty', ko: '브랜드 충성도', definition: '소비자가 특정 브랜드를 지속적으로 선택하는 경향', category: '브랜딩' },
  { en: 'Brand Positioning', ko: '브랜드 포지셔닝', definition: '시장에서 경쟁사 대비 브랜드의 차별적 위치를 설정하는 전략', category: '브랜딩' },
  { en: 'Brand Safety', ko: '브랜드 안전', definition: '부적절한 콘텐츠 옆에 광고가 노출되지 않도록 보호하는 조치', category: '프로그래매틱' },
  { en: 'Brand Storytelling', ko: '브랜드 스토리텔링', definition: '브랜드의 가치와 목적을 이야기 형식으로 전달하는 마케팅 기법', category: '브랜딩' },
  { en: 'Brand Voice', ko: '브랜드 보이스', definition: '브랜드가 소통할 때 사용하는 일관된 톤과 스타일', category: '브랜딩' },
  { en: 'Branded Content', ko: '브랜디드 콘텐츠', definition: '브랜드가 제작하되 광고가 아닌 가치 있는 콘텐츠', category: '콘텐츠' },
  { en: 'Breadcrumb', ko: '브레드크럼', definition: '사이트 내 현재 위치를 계층적으로 표시하는 네비게이션 요소', category: 'SEO/GEO' },
  { en: 'Broad Match', ko: '확장 검색', definition: '검색 광고에서 유사 키워드까지 포함하여 넓게 매칭하는 방식', category: '광고' },
  { en: 'Burn Rate', ko: '자금 소진 속도', definition: '기업이 자금을 소진하는 월간 속도', category: '전략' },
  { en: 'Business Intelligence', ko: '비즈니스 인텔리전스', abbr: 'BI', definition: '데이터를 분석하여 비즈니스 의사결정을 지원하는 기술과 도구', category: '데이터' },
  { en: 'Buyer Persona', ko: '구매자 페르소나', definition: '이상적인 고객을 구체적으로 정의한 가상의 프로필', category: '전략' },
  { en: 'Buzz Marketing', ko: '버즈 마케팅', definition: '소비자 사이에서 입소문을 유발하여 자연스러운 관심을 만드는 마케팅', category: '소셜미디어' },

  // ── C ──
  { en: 'CAC Payback Period', ko: 'CAC 회수 기간', definition: '고객 획득 비용을 회수하는 데 걸리는 기간', category: '분석' },
  { en: 'Call to Action', ko: '행동 유도', abbr: 'CTA', definition: '사용자가 특정 행동을 취하도록 유도하는 문구나 버튼', category: '전환최적화' },
  { en: 'Campaign', ko: '캠페인', definition: '특정 목표를 달성하기 위해 계획된 일련의 마케팅 활동', category: '광고' },
  { en: 'Canonical URL', ko: '캐노니컬 URL', definition: '중복 페이지 중 대표 URL을 지정하여 SEO 문제를 방지하는 태그', category: 'SEO/GEO' },
  { en: 'Cart Abandonment', ko: '장바구니 이탈', definition: '고객이 장바구니에 상품을 담고 구매를 완료하지 않는 현상', category: '이커머스' },
  { en: 'Cart Abandonment Rate', ko: '장바구니 이탈률', definition: '장바구니를 생성한 사용자 중 구매를 완료하지 않은 비율', category: '이커머스' },
  { en: 'Case Study', ko: '사례 연구', definition: '제품이나 서비스의 성공 사례를 상세히 기술한 마케팅 콘텐츠', category: '콘텐츠' },
  { en: 'CDP', ko: '고객 데이터 플랫폼', abbr: 'CDP', definition: '다양한 소스의 고객 데이터를 통합 관리하여 개인화된 마케팅을 가능하게 하는 플랫폼', category: '데이터' },
  { en: 'Channel Mix', ko: '채널 믹스', definition: '마케팅 예산을 여러 채널에 분배하는 전략', category: '전략' },
  { en: 'Chatbot', ko: '챗봇', definition: 'AI를 활용해 고객 문의에 자동으로 응답하는 프로그램', category: '고객서비스' },
  { en: 'Churn Rate', ko: '이탈률 (해지율)', definition: '일정 기간 동안 서비스를 떠나는 고객의 비율', category: '분석' },
  { en: 'Citation', ko: '인용', definition: 'AI 검색 결과에서 특정 출처를 참조하여 표시하는 것 (GEO의 핵심 지표)', category: 'SEO/GEO' },
  { en: 'Click Fraud', ko: '클릭 사기', definition: '경쟁자나 봇이 의도적으로 광고를 클릭하여 광고비를 낭비시키는 행위', category: '광고' },
  { en: 'Click Map', ko: '클릭 맵', definition: '사용자의 클릭 위치를 시각적으로 보여주는 히트맵', category: '분석' },
  { en: 'Click Path', ko: '클릭 경로', definition: '사용자가 사이트 내에서 이동하는 페이지 순서', category: '분석' },
  { en: 'Click-Through Rate', ko: '클릭률', abbr: 'CTR', definition: '광고 노출 횟수 대비 실제 클릭 비율', category: '광고' },
  { en: 'Clickbait', ko: '클릭베이트', definition: '과장된 제목으로 사용자의 클릭을 유도하는 콘텐츠', category: '콘텐츠' },
  { en: 'CMS', ko: '콘텐츠 관리 시스템', abbr: 'CMS', definition: '웹사이트 콘텐츠를 쉽게 생성, 편집, 관리할 수 있는 소프트웨어 (WordPress 등)', category: '콘텐츠' },
  { en: 'Co-Marketing', ko: '공동 마케팅', definition: '두 개 이상의 브랜드가 협력하여 진행하는 마케팅 활동', category: '전략' },
  { en: 'Cohort Analysis', ko: '코호트 분석', definition: '동일한 특성을 가진 사용자 그룹의 행동을 시간에 따라 추적하는 분석 방법', category: '분석' },
  { en: 'Cold Calling', ko: '콜드 콜링', definition: '사전 관계 없이 잠재 고객에게 처음으로 연락하는 영업 활동', category: 'CRM' },
  { en: 'Cold Email', ko: '콜드 이메일', definition: '사전 관계 없는 대상에게 보내는 첫 접촉 이메일', category: '이메일마케팅' },
  { en: 'Community Management', ko: '커뮤니티 관리', definition: '브랜드의 온라인 커뮤니티를 관리하고 참여를 촉진하는 활동', category: '소셜미디어' },
  { en: 'Competitive Analysis', ko: '경쟁 분석', definition: '경쟁사의 전략, 강점, 약점을 분석하는 활동', category: '전략' },
  { en: 'Connected TV', ko: '커넥티드 TV', abbr: 'CTV', definition: '인터넷에 연결된 TV를 통한 스트리밍 광고', category: '광고' },
  { en: 'Content Calendar', ko: '콘텐츠 캘린더', definition: '콘텐츠 제작과 배포 일정을 관리하는 계획표', category: '콘텐츠' },
  { en: 'Content Curation', ko: '콘텐츠 큐레이션', definition: '관련성 높은 콘텐츠를 선별하여 공유하는 활동', category: '콘텐츠' },
  { en: 'Content Gap Analysis', ko: '콘텐츠 갭 분석', definition: '경쟁사 대비 부족한 콘텐츠 영역을 발견하는 분석', category: '콘텐츠' },
  { en: 'Content Marketing', ko: '콘텐츠 마케팅', definition: '유용한 콘텐츠를 제공하여 브랜드 인지도를 높이고 참여를 유도하는 전략', category: '콘텐츠' },
  { en: 'Content Pillar', ko: '콘텐츠 필러', definition: '브랜드의 핵심 주제를 중심으로 한 대형 콘텐츠 허브', category: '콘텐츠' },
  { en: 'Content Syndication', ko: '콘텐츠 신디케이션', definition: '기존 콘텐츠를 외부 플랫폼에 재배포하여 도달 범위를 확대하는 전략', category: '콘텐츠' },
  { en: 'Contextual Advertising', ko: '문맥 광고', definition: '웹페이지의 콘텐츠 맥락에 맞는 광고를 자동으로 표시하는 방식', category: '프로그래매틱' },
  { en: 'Conversion', ko: '전환', definition: '사용자가 원하는 목표 행동(구매, 가입 등)을 완료하는 것', category: '전환최적화' },
  { en: 'Conversion Funnel', ko: '전환 퍼널', definition: '사용자가 인지에서 구매까지 이르는 단계별 경로', category: '전환최적화' },
  { en: 'Conversion Path', ko: '전환 경로', definition: '사용자가 전환에 도달하기까지 거치는 접점들의 순서', category: '전환최적화' },
  { en: 'Conversion Rate', ko: '전환율', definition: '방문자 중 목표 행동을 완료한 비율', category: '전환최적화' },
  { en: 'Conversion Rate Optimization', ko: '전환율 최적화', abbr: 'CRO', definition: '전환율을 높이기 위해 웹사이트나 랜딩 페이지를 분석하고 개선하는 작업', category: '전환최적화' },
  { en: 'Cookie', ko: '쿠키', definition: '웹사이트가 사용자 브라우저에 저장하는 작은 데이터 파일', category: '데이터' },
  { en: 'Cookieless Tracking', ko: '쿠키리스 추적', definition: '제3자 쿠키 없이 사용자를 추적하는 방법 (서버 사이드 등)', category: '데이터' },
  { en: 'Copy', ko: '카피', definition: '광고나 마케팅 자료에 사용되는 텍스트', category: '콘텐츠' },
  { en: 'Copywriting', ko: '카피라이팅', definition: '제품 판매나 브랜드 인지도를 높이기 위한 설득력 있는 글쓰기', category: '콘텐츠' },
  { en: 'Core Web Vitals', ko: '코어 웹 바이탈', definition: 'Google이 정한 웹 페이지 사용자 경험 핵심 지표 (LCP, FID, CLS)', category: 'SEO/GEO' },
  { en: 'Cost Per Acquisition', ko: '획득당 비용', abbr: 'CPA', definition: '전환 당 발생하는 비용', category: '광고' },
  { en: 'Cost Per Click', ko: '클릭당 비용', abbr: 'CPC', definition: '광고가 클릭될 때마다 발생하는 비용', category: '광고' },
  { en: 'Cost Per Install', ko: '설치당 비용', abbr: 'CPI', definition: '앱 설치 한 건당 발생하는 광고 비용', category: '모바일' },
  { en: 'Cost Per Lead', ko: '리드당 비용', abbr: 'CPL', definition: '리드(잠재고객 정보) 한 건을 확보하는 데 드는 비용', category: '광고' },
  { en: 'Cost Per Mille', ko: '1,000회 노출당 비용', abbr: 'CPM', definition: '광고가 1,000회 노출될 때 발생하는 비용', category: '광고' },
  { en: 'Cost Per View', ko: '조회당 비용', abbr: 'CPV', definition: '영상 광고 1회 조회당 발생하는 비용', category: '영상' },
  { en: 'Crawl Budget', ko: '크롤 예산', definition: '검색 엔진 봇이 사이트를 크롤링할 수 있는 할당량', category: 'SEO/GEO' },
  { en: 'Crawler', ko: '크롤러', definition: '검색 엔진이 웹 페이지를 탐색하고 인덱싱하는 자동 프로그램', category: 'SEO/GEO' },
  { en: 'Creative Brief', ko: '크리에이티브 브리프', definition: '광고 소재 제작을 위한 기획 문서 (목표, 타겟, 메시지, 톤 등)', category: '콘텐츠' },
  { en: 'Cross-Channel Marketing', ko: '크로스 채널 마케팅', definition: '여러 채널을 연계하여 일관된 고객 경험을 제공하는 마케팅', category: '전략' },
  { en: 'Cross-Selling', ko: '교차 판매', definition: '기존 고객에게 관련 제품이나 보완 상품을 추가로 판매하는 전략', category: '이커머스' },
  { en: 'CSS', ko: '캐스케이딩 스타일 시트', abbr: 'CSS', definition: '웹 페이지의 시각적 스타일을 정의하는 언어', category: '디자인' },
  { en: 'Customer Acquisition Cost', ko: '고객 획득 비용', abbr: 'CAC', definition: '신규 고객 한 명을 획득하는 데 드는 총 비용', category: '분석' },
  { en: 'Customer Data Platform', ko: '고객 데이터 플랫폼', abbr: 'CDP', definition: '다양한 소스의 고객 데이터를 통합 관리하여 개인화된 마케팅을 가능하게 하는 플랫폼', category: '데이터' },
  { en: 'Customer Experience', ko: '고객 경험', abbr: 'CX', definition: '고객이 브랜드와의 모든 접점에서 느끼는 전체적인 경험', category: '고객서비스' },
  { en: 'Customer Journey', ko: '고객 여정', definition: '고객이 제품을 인지하고 구매하기까지의 전체 과정', category: 'CRM' },
  { en: 'Customer Journey Map', ko: '고객 여정 맵', definition: '고객의 경험을 각 접점별로 시각적으로 표현한 다이어그램', category: 'CRM' },
  { en: 'Customer Lifetime Value', ko: '고객 생애 가치', abbr: 'LTV', definition: '고객이 브랜드와 관계를 유지하는 동안 제공할 수 있는 예상 수익', category: 'CRM' },
  { en: 'Customer Relationship Management', ko: '고객 관계 관리', abbr: 'CRM', definition: '고객과의 관계를 효과적으로 관리하고 강화하기 위한 시스템과 프로세스', category: 'CRM' },
  { en: 'Customer Retention', ko: '고객 유지', definition: '기존 고객이 계속 서비스를 이용하도록 유지하는 전략', category: 'CRM' },
  { en: 'Customer Satisfaction Score', ko: '고객 만족도 점수', abbr: 'CSAT', definition: '고객이 제품이나 서비스에 대해 느끼는 만족도를 수치화한 지표', category: '고객서비스' },
  { en: 'Customer Segmentation', ko: '고객 세분화', definition: '고객을 유사한 특성별로 그룹화하여 차별화된 전략을 수립하는 방법', category: 'CRM' },
  { en: 'Customer Success', ko: '고객 성공', definition: '고객이 제품을 통해 원하는 목표를 달성할 수 있도록 지원하는 활동', category: '고객서비스' },

  // ── D ──
  { en: 'Dark Funnel', ko: '다크 퍼널', definition: '추적 불가능한 채널(입소문, 메신저 등)에서 발생하는 고객 여정', category: '분석' },
  { en: 'Dark Post', ko: '다크 포스트', definition: '타임라인에 노출되지 않고 타겟 오디언스에게만 보이는 소셜 광고', category: '소셜미디어' },
  { en: 'Dark Social', ko: '다크 소셜', definition: '추적이 어려운 비공개 채널(메신저, 이메일 등)을 통한 콘텐츠 공유', category: '소셜미디어' },
  { en: 'Dashboard', ko: '대시보드', definition: '핵심 지표를 한눈에 볼 수 있도록 시각화한 관리 화면', category: '분석' },
  { en: 'Data Clean Room', ko: '데이터 클린룸', definition: '개인정보를 보호하면서 여러 기업의 데이터를 안전하게 결합·분석하는 환경', category: '데이터' },
  { en: 'Data-Driven Marketing', ko: '데이터 기반 마케팅', definition: '데이터를 기반으로 소비자 행동과 트렌드를 분석해 마케팅 전략을 수립하는 방식', category: '데이터' },
  { en: 'Data Lake', ko: '데이터 레이크', definition: '구조화/비구조화 데이터를 원시 형태로 저장하는 대규모 저장소', category: '데이터' },
  { en: 'Data Management Platform', ko: '데이터 관리 플랫폼', abbr: 'DMP', definition: '다양한 소스의 데이터를 수집, 분류, 관리하여 광고 타겟팅에 활용하는 플랫폼', category: '프로그래매틱' },
  { en: 'Data Warehouse', ko: '데이터 웨어하우스', definition: '분석을 위해 구조화된 데이터를 중앙에 저장하는 시스템', category: '데이터' },
  { en: 'Day Parting', ko: '시간대별 광고', definition: '하루 중 특정 시간대에 집중하여 광고를 노출하는 전략', category: '광고' },
  { en: 'Demand Generation', ko: '수요 창출', definition: '잠재 고객의 관심을 끌어 수요를 만들어내는 마케팅 활동', category: '전략' },
  { en: 'Demand Side Platform', ko: '수요 측 플랫폼', abbr: 'DSP', definition: '광고주가 프로그래매틱 방식으로 광고 인벤토리를 구매하는 플랫폼', category: '프로그래매틱' },
  { en: 'Demographics', ko: '인구통계', definition: '연령, 성별, 소득, 교육 수준 등 인구 특성 데이터', category: '분석' },
  { en: 'Digital Asset Management', ko: '디지털 자산 관리', abbr: 'DAM', definition: '브랜드의 디지털 콘텐츠(이미지, 영상, 문서 등)를 중앙에서 관리하는 시스템', category: '콘텐츠' },
  { en: 'Digital Marketing', ko: '디지털 마케팅', definition: '인터넷과 디지털 채널을 활용한 마케팅 활동의 총칭', category: '전략' },
  { en: 'Digital PR', ko: '디지털 PR', definition: '온라인 매체와 인플루언서를 활용한 홍보 활동', category: 'PR' },
  { en: 'Direct Marketing', ko: '다이렉트 마케팅', definition: '소비자에게 직접 도달하는 마케팅 (DM, 이메일, SMS 등)', category: '전략' },
  { en: 'Direct Response', ko: '직접 반응', definition: '즉각적인 행동(구매, 가입 등)을 유도하는 광고 유형', category: '광고' },
  { en: 'Direct Traffic', ko: '직접 유입', definition: 'URL 직접 입력이나 북마크를 통해 발생한 웹사이트 방문', category: '분석' },
  { en: 'Discovery Ad', ko: '디스커버리 광고', definition: 'Google Discover, YouTube 홈 등에 노출되는 네이티브 형태의 광고', category: '광고' },
  { en: 'Display Advertising', ko: '디스플레이 광고', definition: '웹사이트에 배너, 이미지, 영상 형태로 노출되는 광고', category: '광고' },
  { en: 'DM (Direct Message)', ko: '다이렉트 메시지', abbr: 'DM', definition: '소셜 미디어에서 비공개로 주고받는 개인 메시지', category: '소셜미디어' },
  { en: 'Domain Authority', ko: '도메인 권위도', abbr: 'DA', definition: '검색 엔진에서 사이트의 신뢰도와 영향력을 나타내는 지표', category: 'SEO/GEO' },
  { en: 'Drip Campaign', ko: '드립 캠페인', definition: '미리 설정된 일정에 따라 자동으로 이메일을 순차 발송하는 캠페인', category: '이메일마케팅' },
  { en: 'Dwell Time', ko: '체류 시간', definition: '검색 결과를 클릭한 후 해당 페이지에 머무는 시간', category: 'SEO/GEO' },
  { en: 'Dynamic Content', ko: '동적 콘텐츠', definition: '사용자의 특성이나 행동에 따라 자동으로 변하는 콘텐츠', category: '전환최적화' },
  { en: 'Dynamic Creative Optimization', ko: '동적 크리에이티브 최적화', abbr: 'DCO', definition: '광고 배너 요소를 실시간으로 최적화하여 맞춤형 광고를 자동 생성하는 기술', category: '프로그래매틱' },
  { en: 'Dynamic Pricing', ko: '동적 가격 책정', definition: '수요, 경쟁, 고객 세그먼트에 따라 가격을 실시간으로 조정하는 전략', category: '이커머스' },

  // ── E ──
  { en: 'E-A-T', ko: 'E-A-T', definition: '전문성(Expertise), 권위성(Authority), 신뢰성(Trust) — Google의 콘텐츠 품질 평가 기준', category: 'SEO/GEO' },
  { en: 'E-E-A-T', ko: 'E-E-A-T', definition: '경험(Experience), 전문성, 권위성, 신뢰성 — Google의 확장된 품질 평가 기준', category: 'SEO/GEO' },
  { en: 'Earned Media', ko: '획득 미디어', definition: '소비자가 자발적으로 공유한 콘텐츠나 리뷰 등 직접 구매하지 않은 미디어 노출', category: '소셜미디어' },
  { en: 'eCommerce', ko: '이커머스', definition: '인터넷을 통해 상품이나 서비스를 거래하는 상업 활동', category: '이커머스' },
  { en: 'Edge SEO', ko: '엣지 SEO', definition: 'CDN 레벨에서 SEO 변경 사항을 적용하는 기법', category: 'SEO/GEO' },
  { en: 'Editorial Calendar', ko: '에디토리얼 캘린더', definition: '콘텐츠 발행 일정을 체계적으로 관리하는 계획표', category: '콘텐츠' },
  { en: 'Email Automation', ko: '이메일 자동화', definition: '특정 트리거에 따라 자동으로 이메일을 발송하는 시스템', category: '이메일마케팅' },
  { en: 'Email Deliverability', ko: '이메일 도달률', definition: '발송한 이메일이 받은편지함에 실제로 도착하는 비율', category: '이메일마케팅' },
  { en: 'Email Marketing', ko: '이메일 마케팅', definition: '이메일을 통해 고객에게 마케팅 메시지를 전달하는 방법', category: '이메일마케팅' },
  { en: 'Email Open Rate', ko: '이메일 오픈율', definition: '발송된 이메일 중 수신자가 열어본 비율', category: '이메일마케팅' },
  { en: 'Engagement', ko: '참여', definition: '사용자가 콘텐츠와 상호작용하는 모든 활동 (좋아요, 댓글, 공유 등)', category: '소셜미디어' },
  { en: 'Engagement Rate', ko: '참여율', definition: '광고와의 상호작용 비율 (클릭, 좋아요, 공유 등)', category: '소셜미디어' },
  { en: 'Ephemeral Content', ko: '일시적 콘텐츠', definition: '일정 시간 후 사라지는 콘텐츠 (인스타 스토리 등)', category: '소셜미디어' },
  { en: 'Event Tracking', ko: '이벤트 추적', definition: '사용자의 특정 행동(클릭, 스크롤, 다운로드 등)을 추적하는 기능', category: '분석' },
  { en: 'Evergreen Content', ko: '에버그린 콘텐츠', definition: '시간이 지나도 가치가 유지되는 장기적으로 유용한 콘텐츠', category: '콘텐츠' },
  { en: 'Exit Intent', ko: '이탈 의도', definition: '사용자가 페이지를 떠나려는 행동을 감지하여 팝업 등을 표시하는 기술', category: '전환최적화' },
  { en: 'Exit Rate', ko: '종료율', definition: '특정 페이지에서 사이트를 떠나는 사용자의 비율', category: '분석' },
  { en: 'Experiential Marketing', ko: '체험 마케팅', definition: '소비자가 직접 체험할 수 있는 경험을 제공하는 마케팅', category: '전략' },
  { en: 'Explainer Video', ko: '설명 영상', definition: '제품이나 서비스를 쉽게 설명하는 짧은 영상 콘텐츠', category: '영상' },

  // ── F ──
  { en: 'Facebook Pixel', ko: '페이스북 픽셀', definition: '웹사이트 방문자의 행동을 추적하여 Facebook 광고를 최적화하는 코드', category: '광고' },
  { en: 'Featured Snippet', ko: '추천 스니펫', definition: 'Google 검색 결과 상단에 요약 형태로 표시되는 콘텐츠 (Position Zero)', category: 'SEO/GEO' },
  { en: 'First-Party Data', ko: '자사 데이터', definition: '기업이 직접 수집한 고객 데이터 (웹사이트 행동, 구매 이력 등)', category: '데이터' },
  { en: 'First Touch Attribution', ko: '최초 접촉 기여', definition: '고객이 처음 접촉한 채널에 전환 공로를 부여하는 기여 모델', category: '분석' },
  { en: 'Flywheel', ko: '플라이휠', definition: '고객 경험을 중심으로 성장 모멘텀을 만드는 순환 모델 (퍼널의 대안)', category: '전략' },
  { en: 'FOMO', ko: '포모', abbr: 'FOMO', definition: 'Fear Of Missing Out — 놓칠까 두려워하는 심리를 활용한 마케팅 기법', category: '전략' },
  { en: 'Frequency', ko: '빈도', definition: '동일 사용자에게 광고가 노출된 평균 횟수', category: '광고' },
  { en: 'Frequency Capping', ko: '빈도 제한', definition: '동일 사용자에게 광고가 과도하게 노출되지 않도록 제한하는 설정', category: '광고' },
  { en: 'Friction', ko: '마찰', definition: '사용자가 전환을 완료하는 것을 방해하는 요소', category: '전환최적화' },
  { en: 'Full-Funnel Marketing', ko: '풀퍼널 마케팅', definition: '인지부터 전환까지 고객 여정 전체를 아우르는 통합 마케팅 전략', category: '전략' },
  { en: 'Funnel', ko: '퍼널', definition: '고객이 구매에 이르기까지 거치는 단계 (인지→고려→전환)', category: '분석' },

  // ── G ──
  { en: 'Gamification', ko: '게이미피케이션', definition: '게임 요소를 비게임 환경에 적용하여 참여를 유도하는 전략', category: '전략' },
  { en: 'Gated Content', ko: '게이트 콘텐츠', definition: '이메일 등 정보를 제공해야 접근할 수 있는 콘텐츠', category: '콘텐츠' },
  { en: 'Generative AI', ko: '생성형 AI', definition: '텍스트, 이미지, 영상 등을 자동으로 생성하는 인공지능 기술', category: 'SEO/GEO' },
  { en: 'GEO (Generative Engine Optimization)', ko: '생성형 검색엔진 최적화', abbr: 'GEO', definition: 'AI 검색(ChatGPT, Perplexity 등)에서 브랜드가 노출되도록 최적화하는 전략', category: 'SEO/GEO' },
  { en: 'Geofencing', ko: '지오펜싱', definition: 'GPS를 활용하여 특정 지리적 영역 내의 사용자를 타겟팅하는 기술', category: '모바일' },
  { en: 'Geotargeting', ko: '지역 타겟팅', definition: '사용자의 지리적 위치를 기반으로 광고를 맞춤 노출하는 방식', category: '광고' },
  { en: 'Google Ads', ko: '구글 애즈', definition: 'Google의 온라인 광고 플랫폼 (검색, 디스플레이, 영상, 쇼핑 광고)', category: '광고' },
  { en: 'Google Analytics', ko: '구글 애널리틱스', abbr: 'GA', definition: '웹사이트 트래픽과 사용자 행동을 분석하는 Google의 무료 분석 도구', category: '분석' },
  { en: 'Google Business Profile', ko: '구글 비즈니스 프로필', definition: 'Google 검색과 지도에 사업체 정보를 관리하는 무료 도구 (구 Google My Business)', category: 'SEO/GEO' },
  { en: 'Google Search Console', ko: '구글 서치 콘솔', definition: '웹사이트의 Google 검색 성과를 모니터링하고 최적화하는 도구', category: 'SEO/GEO' },
  { en: 'Google Tag Manager', ko: '구글 태그 매니저', abbr: 'GTM', definition: '웹사이트 태그(추적 코드)를 코딩 없이 관리할 수 있는 도구', category: '데이터' },
  { en: 'Growth Hacking', ko: '그로스 해킹', definition: '데이터와 실험을 통해 빠르게 성장하는 마케팅 전략', category: '분석' },
  { en: 'Growth Loop', ko: '그로스 루프', definition: '사용자 행동이 자연스럽게 신규 사용자를 유입시키는 순환 구조', category: '전략' },
  { en: 'Growth Marketing', ko: '그로스 마케팅', definition: '전체 고객 라이프사이클에 걸쳐 데이터 기반 실험으로 성장을 추구하는 마케팅', category: '전략' },
  { en: 'Guerrilla Marketing', ko: '게릴라 마케팅', definition: '적은 비용으로 창의적이고 비전통적인 방법을 사용하는 마케팅', category: '전략' },
  { en: 'Guest Posting', ko: '게스트 포스팅', definition: '다른 사이트에 기고하여 백링크와 노출을 얻는 콘텐츠 전략', category: 'SEO/GEO' },

  // ── H ──
  { en: 'Hashtag', ko: '해시태그', definition: '# 기호를 사용하여 콘텐츠를 분류하고 검색을 용이하게 하는 태그', category: '소셜미디어' },
  { en: 'Header Tags', ko: '헤더 태그', definition: 'HTML에서 제목 구조를 나타내는 태그 (H1~H6)', category: 'SEO/GEO' },
  { en: 'Heatmap', ko: '히트맵', definition: '사용자의 클릭, 스크롤, 마우스 이동을 색상으로 시각화한 분석 도구', category: '분석' },
  { en: 'Hero Image', ko: '히어로 이미지', definition: '웹페이지 상단에 크게 배치되는 메인 이미지', category: '디자인' },
  { en: 'Hreflang', ko: 'Hreflang', definition: '다국어 사이트에서 검색 엔진에 언어와 지역을 알려주는 HTML 속성', category: 'SEO/GEO' },
  { en: 'HTML', ko: '하이퍼텍스트 마크업 언어', abbr: 'HTML', definition: '웹 페이지의 구조를 정의하는 마크업 언어', category: '디자인' },
  { en: 'Hyperlocal Marketing', ko: '하이퍼로컬 마케팅', definition: '매우 제한된 지역(특정 동네, 거리 수준)을 타겟팅하는 마케팅', category: '모바일' },

  // ── I ──
  { en: 'ICE Score', ko: 'ICE 점수', definition: 'Impact(영향), Confidence(확신), Ease(용이성)로 실험 우선순위를 결정하는 프레임워크', category: '애자일' },
  { en: 'Ideal Customer Profile', ko: '이상적 고객 프로필', abbr: 'ICP', definition: '가장 높은 가치를 제공할 수 있는 이상적 고객의 특성을 정의한 프로필', category: 'CRM' },
  { en: 'Inbound Marketing', ko: '인바운드 마케팅', definition: '소비자가 자발적으로 브랜드에 유입되도록 콘텐츠를 통해 정보를 제공하는 마케팅 기법', category: '콘텐츠' },
  { en: 'Indexing', ko: '인덱싱', definition: '검색 엔진이 웹 페이지를 데이터베이스에 등록하는 과정', category: 'SEO/GEO' },
  { en: 'Influencer Marketing', ko: '인플루언서 마케팅', definition: '영향력 있는 개인(인플루언서)을 활용한 마케팅 활동', category: '소셜미디어' },
  { en: 'Infographic', ko: '인포그래픽', definition: '정보를 시각적으로 표현한 그래픽 콘텐츠', category: '콘텐츠' },
  { en: 'In-App Advertising', ko: '인앱 광고', definition: '모바일 앱 내에서 표시되는 광고', category: '모바일' },
  { en: 'In-App Message', ko: '인앱 메시지', definition: '앱 사용 중 화면에 표시되는 메시지 (프로모션, 안내 등)', category: '모바일' },
  { en: 'Integrated Marketing', ko: '통합 마케팅', definition: '모든 마케팅 채널과 메시지를 일관되게 통합하는 전략', category: '전략' },
  { en: 'Intent Data', ko: '의도 데이터', definition: '사용자의 구매 의도를 나타내는 온라인 행동 데이터', category: '데이터' },
  { en: 'Interactive Content', ko: '인터랙티브 콘텐츠', definition: '사용자의 참여를 유도하는 쌍방향 콘텐츠 (퀴즈, 계산기, 투표 등)', category: '콘텐츠' },
  { en: 'Internal Link', ko: '내부 링크', definition: '같은 사이트 내의 다른 페이지로 연결하는 링크', category: 'SEO/GEO' },
  { en: 'Interstitial Ad', ko: '전면 광고', definition: '콘텐츠 전환 사이에 전체 화면으로 노출되는 광고', category: '모바일' },

  // ── J ──
  { en: 'JavaScript Rendering', ko: '자바스크립트 렌더링', definition: '검색 엔진이 JavaScript로 생성된 콘텐츠를 처리하는 방식', category: 'SEO/GEO' },
  { en: 'Jobs-to-be-Done', ko: '해결 과제 프레임워크', abbr: 'JTBD', definition: '고객이 제품을 "고용"하여 해결하려는 근본적 과제에 초점을 맞추는 프레임워크', category: '전략' },
  { en: 'Journey Orchestration', ko: '여정 오케스트레이션', definition: '고객 여정의 각 접점에서 최적의 경험을 자동으로 제공하는 기술', category: 'CRM' },

  // ── K ──
  { en: 'Key Opinion Leader', ko: '핵심 오피니언 리더', abbr: 'KOL', definition: '특정 분야에서 영향력을 가진 전문가적 인플루언서', category: '소셜미디어' },
  { en: 'Key Performance Indicator', ko: '핵심 성과 지표', abbr: 'KPI', definition: '목표 달성 여부를 측정하기 위해 사용하는 핵심 성과 지표', category: '분석' },
  { en: 'Keyword', ko: '키워드', definition: '사용자가 검색 엔진에 입력하는 검색어', category: 'SEO/GEO' },
  { en: 'Keyword Cannibalization', ko: '키워드 카니발라이제이션', definition: '같은 사이트의 여러 페이지가 동일 키워드로 경쟁하는 문제', category: 'SEO/GEO' },
  { en: 'Keyword Density', ko: '키워드 밀도', definition: '콘텐츠 내 특정 키워드가 차지하는 비율', category: 'SEO/GEO' },
  { en: 'Keyword Research', ko: '키워드 리서치', definition: '타겟 키워드를 발굴하고 검색량, 경쟁도를 분석하는 과정', category: 'SEO/GEO' },
  { en: 'Keyword Stuffing', ko: '키워드 스터핑', definition: '콘텐츠에 과도하게 키워드를 삽입하는 블랙햇 SEO 기법', category: 'SEO/GEO' },
  { en: 'Knowledge Graph', ko: '지식 그래프', definition: 'Google이 검색 결과에 표시하는 구조화된 정보 패널', category: 'SEO/GEO' },
  { en: 'Knowledge Panel', ko: '지식 패널', definition: 'Google 검색 결과 오른쪽에 표시되는 정보 박스', category: 'SEO/GEO' },

  // ── L ──
  { en: 'Landing Page', ko: '랜딩 페이지', definition: '특정 캠페인을 위해 설계된 페이지로, 방문자를 고객으로 전환하는 것이 목적', category: '전환최적화' },
  { en: 'Landing Page Optimization', ko: '랜딩 페이지 최적화', abbr: 'LPO', definition: '랜딩 페이지의 전환율을 높이기 위한 최적화 작업', category: '전환최적화' },
  { en: 'Last Touch Attribution', ko: '최종 접촉 기여', definition: '전환 직전 마지막 접점에 전환 공로를 부여하는 기여 모델', category: '분석' },
  { en: 'Latent Semantic Indexing', ko: '잠재 의미 분석', abbr: 'LSI', definition: '문맥적으로 관련된 용어를 분석하여 콘텐츠 관련성을 판단하는 기법', category: 'SEO/GEO' },
  { en: 'Lead', ko: '리드', definition: '제품이나 서비스에 관심을 보인 잠재 고객', category: 'CRM' },
  { en: 'Lead Generation', ko: '리드 생성', definition: '잠재 고객을 유입시키기 위해 정보를 제공하고 리드를 확보하는 활동', category: 'CRM' },
  { en: 'Lead Magnet', ko: '리드 마그넷', definition: '잠재 고객의 연락처를 얻기 위해 제공하는 무료 가치 (eBook, 체크리스트 등)', category: 'CRM' },
  { en: 'Lead Nurturing', ko: '리드 육성', definition: '잠재 고객에게 지속적으로 가치를 제공하여 구매 준비 단계로 이끄는 과정', category: 'CRM' },
  { en: 'Lead Scoring', ko: '리드 점수 매기기', definition: '잠재 고객의 행동과 특성을 점수화하여 구매 가능성이 높은 리드를 식별하는 기법', category: 'CRM' },
  { en: 'Lifecycle Marketing', ko: '라이프사이클 마케팅', definition: '고객의 라이프사이클 단계별로 맞춤화된 마케팅을 제공하는 전략', category: 'CRM' },
  { en: 'Link Building', ko: '링크 빌딩', definition: '외부 사이트로부터 자사 사이트로의 백링크를 확보하는 SEO 활동', category: 'SEO/GEO' },
  { en: 'Link Equity', ko: '링크 가치', definition: '하이퍼링크를 통해 전달되는 SEO 가치 (페이지 랭크)', category: 'SEO/GEO' },
  { en: 'Live Streaming', ko: '라이브 스트리밍', definition: '실시간으로 영상을 송출하여 시청자와 소통하는 콘텐츠 형식', category: '영상' },
  { en: 'Local SEO', ko: '로컬 SEO', definition: '지역 검색에서 높은 순위를 차지하기 위한 최적화 전략', category: 'SEO/GEO' },
  { en: 'Long-Tail Keyword', ko: '롱테일 키워드', definition: '검색량은 적지만 전환율이 높은 구체적이고 긴 키워드', category: 'SEO/GEO' },
  { en: 'Lookalike Audience', ko: '유사 타겟층', definition: '기존 고객의 행동 패턴을 기반으로 유사한 잠재 고객을 타겟팅하는 방식', category: '광고' },
  { en: 'Loss Leader', ko: '로스 리더', definition: '다른 제품 판매를 유도하기 위해 원가 이하로 판매하는 전략', category: '이커머스' },

  // ── M ──
  { en: 'Machine Learning', ko: '머신러닝', definition: '데이터에서 패턴을 학습하여 예측과 의사결정을 자동화하는 AI 기술', category: '데이터' },
  { en: 'MAP (Minimum Advertised Price)', ko: '최저 광고 가격', abbr: 'MAP', definition: '제조사가 설정한 최저 광고 가격 — 이 이하로 광고 불가', category: '이커머스' },
  { en: 'Marketing Automation', ko: '마케팅 자동화', definition: '소프트웨어를 사용해 마케팅 업무를 자동화하여 효율성을 높이는 기술', category: 'CRM' },
  { en: 'Marketing Cloud', ko: '마케팅 클라우드', definition: '마케팅 활동을 통합 관리하는 클라우드 기반 플랫폼 (Salesforce, Adobe 등)', category: 'CRM' },
  { en: 'Marketing Funnel', ko: '마케팅 퍼널', definition: '고객이 인지에서 구매까지 이르는 단계적 프로세스', category: '전략' },
  { en: 'Marketing Mix', ko: '마케팅 믹스', definition: '마케팅 전략의 핵심 요소 (4P: 제품, 가격, 유통, 촉진)', category: '전략' },
  { en: 'Marketing Qualified Lead', ko: '마케팅 적격 리드', abbr: 'MQL', definition: '마케팅 활동으로 확보된 리드 중 영업 팀에 전달할 자격이 있는 리드', category: 'CRM' },
  { en: 'Marketplace', ko: '마켓플레이스', definition: '다수의 판매자와 구매자를 연결하는 온라인 거래 플랫폼', category: '이커머스' },
  { en: 'Media Buying', ko: '미디어 바잉', definition: '광고 지면을 구매하는 과정과 전략', category: '광고' },
  { en: 'Media Kit', ko: '미디어 킷', definition: '광고주에게 제공하는 매체의 광고 상품 정보 자료', category: 'PR' },
  { en: 'Media Planning', ko: '미디어 플래닝', definition: '광고 예산을 최적의 매체에 배분하는 전략적 계획', category: '광고' },
  { en: 'Mention', ko: '멘션', definition: '소셜 미디어에서 브랜드나 사용자를 태그하는 행위', category: '소셜미디어' },
  { en: 'Meta Description', ko: '메타 설명', definition: '검색 결과에 표시되는 웹페이지 요약 텍스트', category: 'SEO/GEO' },
  { en: 'Meta Tags', ko: '메타 태그', definition: 'HTML에서 페이지 정보를 검색 엔진에 전달하는 태그', category: 'SEO/GEO' },
  { en: 'Micro-Conversion', ko: '마이크로 전환', definition: '최종 전환 이전의 작은 목표 달성 (뉴스레터 구독, 장바구니 담기 등)', category: '전환최적화' },
  { en: 'Micro-Influencer', ko: '마이크로 인플루언서', definition: '1,000~100,000 팔로워를 보유한 영향력 있는 소셜 미디어 사용자', category: '소셜미디어' },
  { en: 'Micro-Moment', ko: '마이크로 모먼트', definition: '소비자가 즉각적으로 정보를 찾는 순간 (알고 싶을 때, 가고 싶을 때, 하고 싶을 때, 사고 싶을 때)', category: '모바일' },
  { en: 'Middle of Funnel', ko: '미들 퍼널', abbr: 'MOFU', definition: '인지와 전환 사이의 고려 단계에 있는 고객을 대상으로 한 마케팅', category: '전략' },
  { en: 'Minimum Viable Product', ko: '최소 기능 제품', abbr: 'MVP', definition: '핵심 기능만 갖춘 최소한의 제품으로 시장을 테스트하는 전략', category: '애자일' },
  { en: 'Mobile Marketing', ko: '모바일 마케팅', definition: '모바일 기기를 대상으로 한 마케팅 활동의 총칭', category: '모바일' },
  { en: 'Mobile-First Indexing', ko: '모바일 우선 인덱싱', definition: 'Google이 모바일 버전의 페이지를 우선적으로 크롤링하고 인덱싱하는 방식', category: 'SEO/GEO' },
  { en: 'Moment Marketing', ko: '모먼트 마케팅', definition: '실시간 트렌드나 이벤트에 즉각 반응하여 콘텐츠를 제작하는 마케팅', category: '소셜미디어' },
  { en: 'Monthly Recurring Revenue', ko: '월간 반복 매출', abbr: 'MRR', definition: '매월 반복적으로 발생하는 매출 (SaaS 핵심 지표)', category: '분석' },
  { en: 'Multi-Touch Attribution', ko: '멀티터치 기여', definition: '전환에 기여한 모든 접점에 가중치를 분배하는 기여 모델', category: '분석' },
  { en: 'Multivariate Testing', ko: '다변량 테스트', abbr: 'MVT', definition: '여러 요소의 조합을 동시에 테스트하여 최적의 구성을 찾는 실험 방법', category: '전환최적화' },

  // ── N ──
  { en: 'Native Advertising', ko: '네이티브 광고', definition: '매체의 콘텐츠와 동일한 형태로 자연스럽게 노출되는 광고', category: '광고' },
  { en: 'Negative Keyword', ko: '제외 키워드', definition: '광고가 노출되지 않도록 제외하는 키워드', category: '광고' },
  { en: 'Net Promoter Score', ko: '순수 고객 추천 지수', abbr: 'NPS', definition: '고객이 브랜드를 추천할 의향을 평가하는 지표 (0~10점 척도)', category: '고객서비스' },
  { en: 'Net Revenue Retention', ko: '순 매출 유지율', abbr: 'NRR', definition: '기존 고객으로부터의 매출 유지율 (업셀링/다운그레이드/이탈 포함)', category: '분석' },
  { en: 'Newsletter', ko: '뉴스레터', definition: '정기적으로 구독자에게 발송하는 이메일 콘텐츠', category: '이메일마케팅' },
  { en: 'Niche Market', ko: '니치 마켓', definition: '특정 관심사나 수요를 가진 소규모 전문 시장', category: '전략' },
  { en: 'Nofollow', ko: '노팔로우', definition: '검색 엔진에게 해당 링크의 페이지 랭크를 전달하지 말라는 지시 속성', category: 'SEO/GEO' },
  { en: 'North Star Metric', ko: '북극성 지표', abbr: 'NSM', definition: '회사의 성장을 가장 잘 나타내는 단일 핵심 지표', category: '분석' },
  { en: 'Notification', ko: '알림', definition: '사용자에게 정보를 전달하는 푸시, 이메일, SMS 등의 메시지', category: '모바일' },

  // ── O ──
  { en: 'OKR', ko: '목표와 핵심 결과', abbr: 'OKR', definition: 'Objectives and Key Results — 목표를 설정하고 측정 가능한 결과로 추적하는 성과 관리 프레임워크', category: '애자일' },
  { en: 'Omnichannel Marketing', ko: '옴니채널 마케팅', definition: '온·오프라인 모든 채널을 통합하여 일관된 고객 경험을 제공하는 마케팅 전략', category: 'CRM' },
  { en: 'On-Page SEO', ko: '온페이지 SEO', definition: '웹 페이지 자체를 최적화하는 SEO (콘텐츠, 메타태그, 구조 등)', category: 'SEO/GEO' },
  { en: 'One-to-One Marketing', ko: '일대일 마케팅', definition: '개별 고객에게 맞춤화된 메시지와 경험을 제공하는 마케팅', category: 'CRM' },
  { en: 'Online Reputation Management', ko: '온라인 평판 관리', abbr: 'ORM', definition: '브랜드의 온라인 평판을 모니터링하고 관리하는 활동', category: 'PR' },
  { en: 'Open Graph', ko: '오픈 그래프', definition: '소셜 미디어 공유 시 표시되는 정보를 제어하는 메타 태그 프로토콜', category: '소셜미디어' },
  { en: 'Opt-In', ko: '옵트인', definition: '사용자가 마케팅 수신에 능동적으로 동의하는 것', category: '이메일마케팅' },
  { en: 'Opt-Out', ko: '옵트아웃', definition: '사용자가 마케팅 수신을 거부하는 것', category: '이메일마케팅' },
  { en: 'Organic Reach', ko: '유기적 도달', definition: '유료 광고 없이 자연적으로 도달한 사용자 수', category: '소셜미디어' },
  { en: 'Organic Traffic', ko: '유기적 트래픽', definition: '검색 엔진을 통해 자연스럽게 발생한 웹사이트 방문자 수', category: 'SEO/GEO' },
  { en: 'OTT (Over-The-Top)', ko: 'OTT', abbr: 'OTT', definition: '인터넷을 통해 영상 콘텐츠를 제공하는 스트리밍 서비스', category: '영상' },
  { en: 'Outbound Marketing', ko: '아웃바운드 마케팅', definition: '기업이 소비자에게 먼저 접근하는 마케팅 (콜드콜, 광고 등)', category: '전략' },
  { en: 'Owned Media', ko: '자사 미디어', definition: '브랜드가 직접 소유하고 관리하는 미디어 채널 (웹사이트, 블로그 등)', category: '전략' },

  // ── P ──
  { en: 'Page Authority', ko: '페이지 권위도', abbr: 'PA', definition: '특정 웹 페이지의 검색 엔진에서의 순위 가능성을 나타내는 지표', category: 'SEO/GEO' },
  { en: 'Page Speed', ko: '페이지 속도', definition: '웹 페이지가 완전히 로드되는 데 걸리는 시간', category: 'SEO/GEO' },
  { en: 'PageRank', ko: '페이지랭크', definition: 'Google이 웹 페이지의 중요도를 평가하는 알고리즘', category: 'SEO/GEO' },
  { en: 'Pageview', ko: '페이지뷰', definition: '웹 페이지가 로드된 횟수', category: '분석' },
  { en: 'Paid Media', ko: '유료 미디어', definition: '광고비를 지불하고 구매한 미디어 노출', category: '광고' },
  { en: 'Paid Search', ko: '유료 검색', definition: '검색 엔진에서 키워드 입찰을 통해 노출되는 광고', category: '광고' },
  { en: 'Pay Per Click', ko: '클릭당 지불', abbr: 'PPC', definition: '광고가 클릭될 때만 비용이 발생하는 광고 모델', category: '광고' },
  { en: 'Paywall', ko: '페이월', definition: '콘텐츠 접근을 위해 결제를 요구하는 장벽', category: '콘텐츠' },
  { en: 'Performance Marketing', ko: '퍼포먼스 마케팅', definition: '성과(전환, 클릭 등)에 기반하여 비용을 지불하는 마케팅', category: '광고' },
  { en: 'Permission Marketing', ko: '퍼미션 마케팅', definition: '소비자의 사전 동의를 얻은 후 마케팅 메시지를 전달하는 방식', category: '전략' },
  { en: 'Persona', ko: '페르소나', definition: '목표 사용자를 나타내는 가상 인물로, 디자인과 마케팅을 맞춤화하기 위해 사용', category: '디자인' },
  { en: 'Personalization', ko: '개인화', definition: '고객 데이터를 기반으로 맞춤화된 경험을 제공하는 전략', category: '전환최적화' },
  { en: 'PESO Model', ko: 'PESO 모델', definition: 'Paid, Earned, Shared, Owned 미디어를 통합한 커뮤니케이션 프레임워크', category: 'PR' },
  { en: 'Pillar Page', ko: '필러 페이지', definition: '특정 주제의 포괄적인 가이드 페이지 — 관련 서브 콘텐츠로 링크되는 허브', category: 'SEO/GEO' },
  { en: 'Pipeline', ko: '파이프라인', definition: '잠재 고객이 구매에 이르기까지의 영업 단계를 관리하는 구조', category: 'CRM' },
  { en: 'Pixel', ko: '픽셀', definition: '웹사이트에 삽입하여 사용자 행동을 추적하는 작은 코드 (Facebook Pixel 등)', category: '데이터' },
  { en: 'Podcast', ko: '팟캐스트', definition: '주기적으로 발행되는 오디오 콘텐츠 시리즈', category: '콘텐츠' },
  { en: 'Pop-up', ko: '팝업', definition: '웹페이지 위에 별도 창으로 나타나는 메시지나 양식', category: '전환최적화' },
  { en: 'Positioning', ko: '포지셔닝', definition: '소비자 마음속에서 경쟁 대비 브랜드의 차별적 위치를 설정하는 전략', category: '브랜딩' },
  { en: 'Post-Click Experience', ko: '포스트 클릭 경험', definition: '광고를 클릭한 후 도달하는 페이지에서의 사용자 경험', category: '전환최적화' },
  { en: 'Predictive Analytics', ko: '예측 분석', definition: '과거 데이터를 분석해 미래 행동을 예측하여 마케팅 전략을 최적화하는 기술', category: '데이터' },
  { en: 'Predictive Lead Scoring', ko: '예측 리드 스코어링', definition: 'AI를 활용하여 리드의 구매 가능성을 자동으로 점수화하는 기술', category: 'CRM' },
  { en: 'Press Release', ko: '보도자료', definition: '언론에 배포하기 위해 작성된 공식 뉴스 문서', category: 'PR' },
  { en: 'Product-Led Growth', ko: '제품 주도 성장', abbr: 'PLG', definition: '제품 자체가 사용자 획득, 전환, 확장을 이끄는 성장 전략', category: '전략' },
  { en: 'Product-Market Fit', ko: '제품-시장 적합성', abbr: 'PMF', definition: '제품이 시장의 필요를 충족시키는 상태', category: '전략' },
  { en: 'Programmatic Advertising', ko: '프로그래매틱 광고', definition: '알고리즘과 AI를 활용해 실시간으로 광고를 자동 구매하고 타겟팅하는 기술', category: '프로그래매틱' },
  { en: 'Progressive Web App', ko: '프로그레시브 웹 앱', abbr: 'PWA', definition: '앱과 같은 경험을 제공하는 웹 기술 기반 애플리케이션', category: '모바일' },
  { en: 'Promotion', ko: '프로모션', definition: '제품이나 서비스의 판매를 촉진하기 위한 한시적 마케팅 활동', category: '전략' },
  { en: 'Psychographics', ko: '심리통계', definition: '라이프스타일, 가치관, 관심사 등 심리적 특성 데이터', category: '분석' },
  { en: 'Public Relations', ko: '홍보', abbr: 'PR', definition: '매체와 대중과의 관계를 관리하여 브랜드 이미지를 구축하는 활동', category: 'PR' },
  { en: 'Push Notification', ko: '푸시 알림', definition: '앱이나 웹에서 사용자에게 전송하는 알림 메시지', category: '모바일' },

  // ── Q ──
  { en: 'QR Code', ko: 'QR 코드', definition: '스마트폰으로 스캔하여 정보에 접근할 수 있는 2차원 바코드', category: '모바일' },
  { en: 'Qualified Lead', ko: '적격 리드', definition: '구매 가능성이 높다고 판단된 잠재 고객', category: 'CRM' },
  { en: 'Quality Score', ko: '품질 점수', definition: 'Google Ads에서 광고, 키워드, 랜딩 페이지의 품질을 평가한 점수', category: '광고' },
  { en: 'Query', ko: '검색 쿼리', definition: '사용자가 검색 엔진에 입력하는 검색어나 질문', category: 'SEO/GEO' },

  // ── R ──
  { en: 'Reach', ko: '도달', definition: '콘텐츠나 광고가 도달한 고유 사용자 수', category: '광고' },
  { en: 'Real-Time Bidding', ko: '실시간 입찰', abbr: 'RTB', definition: '광고가 노출될 때마다 실시간 경매를 통해 인벤토리를 판매하는 방식', category: '프로그래매틱' },
  { en: 'Real-Time Marketing', ko: '실시간 마케팅', definition: '현재 이벤트나 트렌드에 즉각적으로 반응하는 마케팅', category: '전략' },
  { en: 'Reciprocity', ko: '상호성', definition: '무료 가치를 제공하여 고객의 보답 심리를 유도하는 마케팅 원리', category: '전략' },
  { en: 'Redirect', ko: '리다이렉트', definition: '한 URL에서 다른 URL로 자동 이동시키는 것 (301, 302 등)', category: 'SEO/GEO' },
  { en: 'Referral Marketing', ko: '추천 마케팅', definition: '기존 고객의 추천을 통해 신규 고객을 획득하는 마케팅 전략', category: 'CRM' },
  { en: 'Referral Traffic', ko: '추천 트래픽', definition: '다른 웹사이트의 링크를 통해 유입된 방문자', category: '분석' },
  { en: 'Remarketing', ko: '리마케팅', definition: '이탈한 사용자에게 다시 광고를 노출하여 재참여를 유도하는 전략', category: '광고' },
  { en: 'Responsive Design', ko: '반응형 디자인', definition: '디바이스 화면 크기에 따라 자동으로 레이아웃이 조정되는 웹 디자인', category: '디자인' },
  { en: 'Retention Rate', ko: '유지율', definition: '브랜드와의 관계를 유지하는 고객의 비율', category: '분석' },
  { en: 'Retargeting', ko: '리타겟팅', definition: '이전에 사이트를 방문한 사용자에게 다시 광고를 노출하는 전략', category: '광고' },
  { en: 'Return on Ad Spend', ko: '광고 지출 대비 수익', abbr: 'ROAS', definition: '광고비 대비 발생한 매출을 나타내는 지표', category: '광고' },
  { en: 'Return on Investment', ko: '투자 수익률', abbr: 'ROI', definition: '마케팅 비용 대비 수익을 나타내는 비율', category: '분석' },
  { en: 'Revenue Per Visit', ko: '방문당 매출', abbr: 'RPV', definition: '웹사이트 방문 1회당 발생하는 평균 매출', category: '이커머스' },
  { en: 'Rich Snippet', ko: '리치 스니펫', definition: '검색 결과에 별점, 가격, 이미지 등 추가 정보가 표시되는 형태', category: 'SEO/GEO' },
  { en: 'Robots.txt', ko: '로봇 텍스트', definition: '검색 엔진 크롤러의 접근을 제어하는 텍스트 파일', category: 'SEO/GEO' },

  // ── S ──
  { en: 'SaaS', ko: '서비스형 소프트웨어', abbr: 'SaaS', definition: '클라우드를 통해 소프트웨어를 구독 방식으로 제공하는 모델', category: '전략' },
  { en: 'Sales Enablement', ko: '세일즈 인에이블먼트', definition: '영업 팀이 효과적으로 판매할 수 있도록 콘텐츠, 도구, 교육을 제공하는 활동', category: 'CRM' },
  { en: 'Sales Funnel', ko: '세일즈 퍼널', definition: '잠재 고객이 구매에 이르기까지의 영업 단계', category: 'CRM' },
  { en: 'Sales Qualified Lead', ko: '영업 적격 리드', abbr: 'SQL', definition: '영업 팀이 직접 접촉할 가격이 있다고 판단한 리드', category: 'CRM' },
  { en: 'Schema Markup', ko: '스키마 마크업', definition: '검색 엔진이 콘텐츠를 이해하도록 구조화된 데이터를 추가하는 마크업', category: 'SEO/GEO' },
  { en: 'Scroll Depth', ko: '스크롤 깊이', definition: '사용자가 페이지를 얼마나 아래로 스크롤했는지 측정한 지표', category: '분석' },
  { en: 'Search Engine Marketing', ko: '검색 엔진 마케팅', abbr: 'SEM', definition: '검색 엔진을 활용한 유료 광고와 유기적 최적화를 포함한 마케팅', category: '광고' },
  { en: 'Search Engine Optimization', ko: '검색 엔진 최적화', abbr: 'SEO', definition: '검색 엔진에서 콘텐츠가 더 높은 순위에 오를 수 있도록 최적화하는 활동', category: 'SEO/GEO' },
  { en: 'Search Engine Results Page', ko: '검색 결과 페이지', abbr: 'SERP', definition: '검색어에 대한 결과를 표시하는 페이지', category: 'SEO/GEO' },
  { en: 'Search Intent', ko: '검색 의도', definition: '사용자가 검색하는 근본적인 목적 (정보, 탐색, 거래, 상업)', category: 'SEO/GEO' },
  { en: 'Second-Party Data', ko: '제2자 데이터', definition: '파트너사가 수집한 자사 데이터를 공유받은 데이터', category: '데이터' },
  { en: 'Seed Audience', ko: '시드 오디언스', definition: '유사 타겟(Lookalike) 생성의 기반이 되는 원본 고객 그룹', category: '광고' },
  { en: 'Sentiment Analysis', ko: '감성 분석', definition: '소셜 미디어와 리뷰에서 사용자 감정을 분석하여 브랜드 여론을 파악하는 기법', category: '소셜미디어' },
  { en: 'SEO Audit', ko: 'SEO 감사', definition: '웹사이트의 SEO 상태를 종합적으로 분석하고 개선점을 도출하는 과정', category: 'SEO/GEO' },
  { en: 'Session', ko: '세션', definition: '사용자가 사이트를 방문하여 활동하는 한 번의 기간', category: '분석' },
  { en: 'Share of Voice', ko: '점유율', abbr: 'SOV', definition: '시장에서 브랜드가 차지하는 광고 또는 미디어 노출 비율', category: '브랜딩' },
  { en: 'Shopping Cart', ko: '장바구니', definition: '온라인 쇼핑에서 구매할 상품을 담아두는 가상의 공간', category: '이커머스' },
  { en: 'Short-Form Video', ko: '숏폼 영상', definition: '60초 이내의 짧은 형태의 영상 콘텐츠 (TikTok, Reels, Shorts)', category: '영상' },
  { en: 'Sitemap', ko: '사이트맵', definition: '웹사이트의 페이지 구조를 검색 엔진에 알려주는 파일', category: 'SEO/GEO' },
  { en: 'SKU', ko: '재고 관리 단위', abbr: 'SKU', definition: '개별 상품을 식별하기 위한 고유 코드', category: '이커머스' },
  { en: 'Slogan', ko: '슬로건', definition: '브랜드의 핵심 메시지를 함축적으로 표현한 짧은 문구', category: '브랜딩' },
  { en: 'Smart Bidding', ko: '스마트 입찰', definition: 'Google의 머신러닝 기반 자동 입찰 전략 (타겟 CPA, 타겟 ROAS 등)', category: '광고' },
  { en: 'SMS Marketing', ko: 'SMS 마케팅', definition: '문자 메시지를 통해 고객에게 마케팅 메시지를 전달하는 방법', category: '모바일' },
  { en: 'Snackable Content', ko: '스낵커블 콘텐츠', definition: '짧고 쉽게 소비할 수 있는 콘텐츠', category: '콘텐츠' },
  { en: 'Social Commerce', ko: '소셜 커머스', definition: '소셜 미디어 플랫폼 내에서 직접 상품을 판매하는 방식', category: '소셜미디어' },
  { en: 'Social Listening', ko: '소셜 리스닝', definition: '소셜 미디어에서 브랜드 관련 대화와 언급을 모니터링하는 활동', category: '소셜미디어' },
  { en: 'Social Media Marketing', ko: '소셜 미디어 마케팅', abbr: 'SMM', definition: '소셜 미디어 플랫폼을 활용한 마케팅 활동', category: '소셜미디어' },
  { en: 'Social Proof', ko: '사회적 증명', definition: '다른 사용자의 리뷰나 추천을 활용해 신뢰도를 높이고 구매를 유도하는 요소', category: '소셜미디어' },
  { en: 'Social Selling', ko: '소셜 셀링', definition: '소셜 미디어를 통해 잠재 고객과 관계를 구축하고 판매하는 영업 방식', category: '소셜미디어' },
  { en: 'Spam Score', ko: '스팸 점수', definition: '이메일이나 사이트가 스팸으로 분류될 가능성을 나타내는 점수', category: 'SEO/GEO' },
  { en: 'Split Testing', ko: '스플릿 테스트', definition: 'A/B 테스트와 동일 — 두 가지 이상의 변형을 비교하는 실험', category: '전환최적화' },
  { en: 'Sponsored Content', ko: '스폰서드 콘텐츠', definition: '비용을 지불하고 매체에 게재하는 편집 형태의 광고 콘텐츠', category: '광고' },
  { en: 'Sprint', ko: '스프린트', definition: '정해진 기간(보통 2주) 내에 특정 목표를 달성하는 애자일 작업 주기', category: '애자일' },
  { en: 'SQL (Sales Qualified Lead)', ko: '영업 적격 리드', abbr: 'SQL', definition: '영업 팀이 직접 접촉할 가치가 있다고 판단한 리드', category: 'CRM' },
  { en: 'Stickiness', ko: '접착성', definition: '사용자가 서비스를 반복적으로 사용하는 정도 (DAU/MAU 비율)', category: '분석' },
  { en: 'Storytelling', ko: '스토리텔링', definition: '이야기 형식으로 브랜드 메시지를 전달하여 감정적 연결을 만드는 기법', category: '브랜딩' },
  { en: 'Structured Data', ko: '구조화 데이터', definition: '검색 엔진이 콘텐츠를 이해하도록 표준화된 형식으로 마크업한 데이터', category: 'SEO/GEO' },
  { en: 'Subscription Model', ko: '구독 모델', definition: '정기적으로 요금을 지불하고 제품이나 서비스를 이용하는 비즈니스 모델', category: '이커머스' },
  { en: 'Supply Side Platform', ko: '공급 측 플랫폼', abbr: 'SSP', definition: '매체가 광고 인벤토리를 프로그래매틱으로 판매하는 플랫폼', category: '프로그래매틱' },
  { en: 'SWOT Analysis', ko: 'SWOT 분석', definition: '강점(S), 약점(W), 기회(O), 위협(T)을 분석하는 전략 프레임워크', category: '전략' },

  // ── T ──
  { en: 'Tag Management', ko: '태그 관리', definition: '웹사이트에 삽입된 마케팅 태그(추적 코드)를 중앙에서 관리하는 시스템', category: '데이터' },
  { en: 'Target Audience', ko: '타겟 오디언스', definition: '마케팅 활동의 대상이 되는 특정 고객 그룹', category: '전략' },
  { en: 'Technical SEO', ko: '테크니컬 SEO', definition: '사이트 속도, 모바일 최적화, 크롤링 등 기술적 SEO 요소를 개선하는 작업', category: 'SEO/GEO' },
  { en: 'Third-Party Cookie', ko: '제3자 쿠키', definition: '방문 중인 사이트가 아닌 다른 도메인이 설정한 쿠키 (광고 추적용)', category: '데이터' },
  { en: 'Third-Party Data', ko: '제3자 데이터', definition: '외부 데이터 제공 업체로부터 구매한 소비자 데이터', category: '데이터' },
  { en: 'Thought Leadership', ko: '사상적 리더십', definition: '업계에서 전문가적 입지를 구축하기 위한 콘텐츠 전략', category: 'PR' },
  { en: 'Time on Page', ko: '페이지 체류 시간', definition: '사용자가 특정 페이지에 머무는 평균 시간', category: '분석' },
  { en: 'Title Tag', ko: '타이틀 태그', definition: 'HTML에서 페이지 제목을 정의하는 태그 — 검색 결과에 표시', category: 'SEO/GEO' },
  { en: 'Top of Funnel', ko: '탑 퍼널', abbr: 'TOFU', definition: '인지 단계에 있는 잠재 고객을 대상으로 한 마케팅', category: '전략' },
  { en: 'Topic Cluster', ko: '토픽 클러스터', definition: '핵심 주제(필러)를 중심으로 관련 콘텐츠를 연결하는 SEO 전략', category: 'SEO/GEO' },
  { en: 'Total Addressable Market', ko: '전체 시장 규모', abbr: 'TAM', definition: '제품이 도달할 수 있는 전체 시장의 규모', category: '전략' },
  { en: 'Touchpoint', ko: '접점', definition: '고객이 브랜드와 상호작용하는 모든 순간', category: 'CRM' },
  { en: 'Tracking Pixel', ko: '추적 픽셀', definition: '웹페이지에 삽입된 보이지 않는 이미지로 사용자 행동을 추적', category: '데이터' },
  { en: 'Traffic', ko: '트래픽', definition: '웹사이트를 방문하는 사용자의 수와 흐름', category: '분석' },
  { en: 'Triggered Email', ko: '트리거 이메일', definition: '특정 사용자 행동(가입, 구매 등)에 의해 자동 발송되는 이메일', category: '이메일마케팅' },
  { en: 'TrueView', ko: '트루뷰', definition: 'YouTube의 스킵 가능한 영상 광고 포맷', category: '영상' },

  // ── U ──
  { en: 'Unique Selling Proposition', ko: '고유 판매 제안', abbr: 'USP', definition: '경쟁사와 차별화되는 제품의 고유한 강점이나 가치', category: '브랜딩' },
  { en: 'Unique Visitor', ko: '순 방문자', definition: '일정 기간 동안 사이트를 방문한 중복 제거된 고유 사용자 수', category: '분석' },
  { en: 'Unit Economics', ko: '단위 경제학', definition: '고객 1명 또는 거래 1건 기준의 수익성 분석', category: '분석' },
  { en: 'Unsubscribe Rate', ko: '수신 거부율', definition: '이메일 수신자 중 수신 거부를 한 비율', category: '이메일마케팅' },
  { en: 'Up-Selling', ko: '업셀링', definition: '기존 고객에게 더 비싼 제품이나 업그레이드 옵션을 제안하는 전략', category: '이커머스' },
  { en: 'URL', ko: '유알엘', abbr: 'URL', definition: '인터넷 상의 리소스 위치를 나타내는 주소', category: '디자인' },
  { en: 'Usability', ko: '사용성', definition: '사용자가 제품을 쉽고 효율적으로 사용할 수 있는 정도', category: '디자인' },
  { en: 'User Acquisition', ko: '사용자 획득', definition: '새로운 사용자를 앱이나 서비스로 유입시키는 활동', category: '모바일' },
  { en: 'User Experience', ko: '사용자 경험', abbr: 'UX', definition: '사용자가 제품을 사용할 때의 전반적인 경험', category: '디자인' },
  { en: 'User Flow', ko: '사용자 흐름', definition: '사용자가 사이트나 앱 내에서 이동하는 경로를 시각화한 것', category: '디자인' },
  { en: 'User Interface', ko: '사용자 인터페이스', abbr: 'UI', definition: '사용자가 제품과 상호작용하는 시각적 요소의 총체', category: '디자인' },
  { en: 'User Persona', ko: '사용자 페르소나', definition: '대상 사용자를 대표하는 가상의 인물 프로필', category: '디자인' },
  { en: 'User-Generated Content', ko: '사용자 생성 콘텐츠', abbr: 'UGC', definition: '사용자가 생성한 콘텐츠 (리뷰, 사진, 비디오 등)', category: '소셜미디어' },
  { en: 'UTM Parameters', ko: 'UTM 매개변수', definition: 'URL에 추가하여 마케팅 캠페인의 트래픽 소스를 추적하는 매개변수', category: '분석' },

  // ── V ──
  { en: 'Value Proposition', ko: '가치 제안', definition: '고객에게 제공하는 핵심적인 가치와 차별점을 명확하게 정의한 것', category: '브랜딩' },
  { en: 'Vanity Metric', ko: '허영 지표', definition: '실질적인 비즈니스 가치를 나타내지 않는 표면적 지표 (좋아요 수 등)', category: '분석' },
  { en: 'Video Marketing', ko: '영상 마케팅', definition: '영상 콘텐츠를 활용한 마케팅 활동', category: '영상' },
  { en: 'View-Through Rate', ko: '조회 완료율', abbr: 'VTR', definition: '영상 광고를 끝까지 시청한 사용자의 비율', category: '영상' },
  { en: 'Viewability', ko: '가시성', definition: '광고가 실제로 사용자 화면에 보이는지 여부를 측정하는 지표', category: '프로그래매틱' },
  { en: 'Viral Coefficient', ko: '바이럴 계수', definition: '기존 사용자 한 명이 유입시키는 신규 사용자 수 (K값)', category: '분석' },
  { en: 'Viral Marketing', ko: '바이럴 마케팅', definition: '입소문과 소셜 미디어를 통해 자발적으로 콘텐츠가 확산되도록 유도하는 마케팅 기법', category: '소셜미디어' },
  { en: 'Virtual Reality', ko: '가상현실', abbr: 'VR', definition: '완전한 디지털 환경에 사용자를 몰입시키는 기술', category: '디자인' },
  { en: 'Visual Search', ko: '비주얼 검색', definition: '이미지를 입력하여 유사한 상품이나 정보를 검색하는 기술', category: 'SEO/GEO' },
  { en: 'Voice of Customer', ko: '고객의 소리', abbr: 'VoC', definition: '고객의 피드백, 기대, 선호도를 체계적으로 수집하고 분석하는 활동', category: '고객서비스' },
  { en: 'Voice Search', ko: '음성 검색', definition: '음성 명령을 통해 정보를 검색하는 방식 (Siri, Alexa 등)', category: 'SEO/GEO' },
  { en: 'VSEO', ko: '비디오 SEO', definition: '동영상 콘텐츠의 검색 엔진 최적화', category: '영상' },

  // ── W ──
  { en: 'Warm Lead', ko: '웜 리드', definition: '제품에 이미 관심을 보인 잠재 고객', category: 'CRM' },
  { en: 'Web Analytics', ko: '웹 분석', definition: '웹사이트의 트래픽과 사용자 행동을 측정하고 분석하는 활동', category: '분석' },
  { en: 'Web Crawling', ko: '웹 크롤링', definition: '검색 엔진 봇이 웹 페이지를 자동으로 탐색하고 수집하는 과정', category: 'SEO/GEO' },
  { en: 'Webinar', ko: '웨비나', definition: '인터넷을 통해 진행하는 실시간 세미나나 프레젠테이션', category: '콘텐츠' },
  { en: 'Website Personalization', ko: '웹사이트 개인화', definition: '방문자의 특성과 행동에 따라 웹사이트 콘텐츠를 맞춤 표시하는 기술', category: '전환최적화' },
  { en: 'White Hat SEO', ko: '화이트햇 SEO', definition: '검색 엔진 가이드라인을 준수하는 정상적인 SEO 기법', category: 'SEO/GEO' },
  { en: 'White Paper', ko: '백서', definition: '특정 주제에 대한 깊이 있는 분석과 솔루션을 제시하는 전문 보고서', category: '콘텐츠' },
  { en: 'Wireframe', ko: '와이어프레임', definition: '웹페이지나 앱 화면의 구조적 레이아웃을 보여주는 기초 설계도', category: '디자인' },
  { en: 'Word-of-Mouth', ko: '입소문', abbr: 'WOM', definition: '소비자 간 자연스러운 대화를 통한 브랜드 정보 전파', category: '소셜미디어' },
  { en: 'Workflow Automation', ko: '워크플로우 자동화', definition: '반복적인 마케팅 작업을 자동화하여 효율을 높이는 기술', category: 'CRM' },

  // ── X ──
  { en: 'XML Sitemap', ko: 'XML 사이트맵', definition: '검색 엔진 크롤러에게 사이트 구조를 알려주는 XML 형식의 파일', category: 'SEO/GEO' },

  // ── Y ──
  { en: 'Yield Management', ko: '수익 관리', definition: '가격과 재고를 동적으로 관리하여 수익을 최대화하는 전략', category: '이커머스' },
  { en: 'YouTube Ads', ko: '유튜브 광고', definition: 'YouTube 플랫폼에서 진행하는 영상 광고 (프리롤, 미드롤, 범퍼 등)', category: '영상' },

  // ── Z ──
  { en: 'Zero-Click Search', ko: '제로 클릭 검색', definition: '검색 결과 페이지에서 링크를 클릭하지 않고 정보를 얻는 검색', category: 'SEO/GEO' },
  { en: 'Zero Moment of Truth', ko: '제로 진실의 순간', abbr: 'ZMOT', definition: '소비자가 구매 전 온라인에서 정보를 검색하고 결정하는 순간', category: '전략' },
  { en: 'Zero-Party Data', ko: '제로파티 데이터', definition: '고객이 의도적으로 브랜드에 직접 제공하는 데이터 (설문, 선호도 등)', category: '데이터' },

  // ── 추가 용어 (한국 마케팅 환경 특화) ──
  { en: 'Naver Search Ads', ko: '네이버 검색광고', abbr: 'NSA', definition: '네이버 검색 결과에 노출되는 키워드 광고', category: '광고' },
  { en: 'Naver Blog Marketing', ko: '네이버 블로그 마케팅', definition: '네이버 블로그를 활용한 콘텐츠 마케팅 전략', category: '콘텐츠' },
  { en: 'Naver Smart Store', ko: '네이버 스마트스토어', definition: '네이버가 제공하는 이커머스 플랫폼', category: '이커머스' },
  { en: 'Naver Cue', ko: '네이버 큐', definition: '네이버의 AI 검색 요약 기능 — GEO 최적화의 핵심 대상', category: 'SEO/GEO' },
  { en: 'Kakao Moment', ko: '카카오 모먼트', definition: '카카오의 통합 광고 플랫폼 (카카오톡, 다음, 카카오스토리 등)', category: '광고' },
  { en: 'Kakao Channel', ko: '카카오 채널', definition: '카카오톡 내 브랜드 공식 채널 (구 플러스친구)', category: 'CRM' },
  { en: 'Kakao Talk Marketing', ko: '카카오톡 마케팅', definition: '카카오톡 메시지와 채널을 활용한 마케팅 활동', category: 'CRM' },
  { en: 'Coupang Ads', ko: '쿠팡 광고', definition: '쿠팡 마켓플레이스 내 상품 광고 시스템', category: '이커머스' },
  { en: 'Power Link', ko: '파워링크', definition: '네이버 검색 결과 상단에 노출되는 CPC 광고 상품', category: '광고' },
  { en: 'Shopping Search Ads', ko: '쇼핑 검색 광고', definition: '네이버 쇼핑 탭에 노출되는 상품 검색 광고', category: '이커머스' },
  { en: 'Brand Search', ko: '브랜드 검색', definition: '네이버 검색 결과 상단에 브랜드 전용 영역을 노출하는 광고 상품', category: '광고' },
  { en: 'Influencer Commerce', ko: '인플루언서 커머스', definition: '인플루언서를 통해 직접 상품을 판매하는 소셜 커머스 모델', category: '소셜미디어' },
  { en: 'Live Commerce', ko: '라이브 커머스', definition: '실시간 방송을 통해 상품을 판매하는 커머스 형태', category: '이커머스' },
  { en: 'Content Commerce', ko: '콘텐츠 커머스', definition: '콘텐츠를 매개로 자연스럽게 상품 구매를 유도하는 마케팅 방식', category: '콘텐츠' },

  // ── 추가: 그로스 해킹 / 데이터 분석 심화 ──
  { en: 'AARRR Framework', ko: 'AARRR 프레임워크', definition: 'Acquisition→Activation→Retention→Revenue→Referral — 그로스 해킹의 핵심 퍼널 프레임워크', category: '분석' },
  { en: 'Aha Moment', ko: '아하 모먼트', definition: '사용자가 제품의 핵심 가치를 처음 경험하는 결정적 순간', category: '전략' },
  { en: 'ARPDAU', ko: '일일 활성 사용자당 평균 수익', abbr: 'ARPDAU', definition: 'DAU 기준 사용자 한 명이 하루에 발생시키는 평균 수익', category: '분석' },
  { en: 'Bayesian Testing', ko: '베이지안 테스트', definition: '사전 확률을 반영하여 실험 결과를 분석하는 통계적 테스트 방법', category: '전환최적화' },
  { en: 'Breakeven ROAS', ko: '손익분기 ROAS', definition: '광고비를 회수하기 위한 최소 ROAS 값', category: '광고' },
  { en: 'Channel Attribution', ko: '채널 어트리뷰션', definition: '전환에 기여한 각 마케팅 채널의 공헌도를 측정하는 방법', category: '분석' },
  { en: 'Conversion Lift', ko: '전환 리프트', definition: '광고 캠페인으로 인한 전환의 순 증가분을 측정하는 방법', category: '분석' },
  { en: 'Conversion Window', ko: '전환 기간', definition: '광고 노출 후 전환으로 인정하는 기간 (1일, 7일, 28일 등)', category: '분석' },
  { en: 'Customer Effort Score', ko: '고객 노력 점수', abbr: 'CES', definition: '고객이 문제를 해결하기 위해 들인 노력의 정도를 측정하는 지표', category: '고객서비스' },
  { en: 'DAU/MAU Ratio', ko: 'DAU/MAU 비율', definition: '일일 활성 사용자 대비 월간 활성 사용자 비율 — 서비스 접착성 지표', category: '분석' },
  { en: 'Feature Flag', ko: '피처 플래그', definition: '코드 배포 없이 특정 기능을 켜고 끌 수 있는 기술', category: '애자일' },
  { en: 'Incrementality Testing', ko: '증분성 테스트', definition: '마케팅 활동의 순 효과(인과관계)를 측정하기 위한 실험', category: '분석' },
  { en: 'LTV:CAC Ratio', ko: 'LTV:CAC 비율', definition: '고객 생애 가치 대비 고객 획득 비용의 비율 — 3:1 이상이 건강한 상태', category: '분석' },
  { en: 'Magic Number', ko: '매직 넘버', definition: 'SaaS에서 마케팅 효율성을 판단하는 지표 (순 신규 ARR / 전기 S&M 비용)', category: '분석' },
  { en: 'Media Mix Modeling', ko: '미디어 믹스 모델링', abbr: 'MMM', definition: '통계적 기법으로 각 미디어 채널의 매출 기여도를 분석하는 방법', category: '분석' },
  { en: 'Negative Churn', ko: '네거티브 이탈', definition: '기존 고객의 업셀링/확장 매출이 이탈 매출을 초과하는 상태', category: '분석' },
  { en: 'Onboarding', ko: '온보딩', definition: '신규 사용자가 제품을 효과적으로 사용하기 시작하도록 안내하는 과정', category: '전환최적화' },
  { en: 'Payback Period', ko: '투자 회수 기간', definition: 'CAC를 회수하는 데 걸리는 기간', category: '분석' },
  { en: 'Power User', ko: '파워 유저', definition: '제품을 가장 적극적으로 사용하는 상위 사용자 그룹', category: '분석' },
  { en: 'Quick Ratio', ko: '퀵 레이시오', definition: '(신규 사용자 + 복귀 사용자) / 이탈 사용자 — 사용자 증가 건전성 지표', category: '분석' },
  { en: 'Revenue Attribution', ko: '매출 기여', definition: '마케팅 활동이 매출에 기여한 정도를 측정하는 분석', category: '분석' },
  { en: 'Signup Flow', ko: '가입 흐름', definition: '사용자가 서비스에 가입하는 과정의 단계적 흐름', category: '전환최적화' },
  { en: 'Statistical Significance', ko: '통계적 유의성', definition: '실험 결과가 우연이 아닌 실제 차이를 반영하는지 판단하는 기준', category: '전환최적화' },
  { en: 'Time to Value', ko: '가치 도달 시간', abbr: 'TTV', definition: '사용자가 제품에서 처음으로 가치를 느끼는 데 걸리는 시간', category: '전략' },
  { en: 'Virality', ko: '바이럴리티', definition: '콘텐츠나 제품이 사용자 간에 자연스럽게 확산되는 정도', category: '분석' },
  { en: 'Win Rate', ko: '성사율', definition: '영업 기회 중 실제 계약으로 이어진 비율', category: 'CRM' },
];
