import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

// Rule-based keyword extraction (will be replaced by Claude API later)
function extractKeywords(texts: string[]): { keyword: string; count: number }[] {
  const stopWords = new Set([
    'the', 'a', 'an', 'is', 'are', 'was', 'were', 'be', 'been', 'being',
    'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would', 'could',
    'should', 'may', 'might', 'can', 'shall', 'to', 'of', 'in', 'for',
    'on', 'with', 'at', 'by', 'from', 'as', 'into', 'through', 'during',
    'before', 'after', 'above', 'below', 'between', 'out', 'off', 'over',
    'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when',
    'where', 'why', 'how', 'all', 'both', 'each', 'few', 'more', 'most',
    'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same',
    'so', 'than', 'too', 'very', 'just', 'because', 'but', 'and', 'or',
    'if', 'while', 'about', 'up', 'its', 'it', 'this', 'that', 'these',
    'those', 'what', 'which', 'who', 'whom', 'new', 'also', 'like', 'get',
    'one', 'two', 'first', 'said', 'says', 'say', 'year', 'years', 'way',
    'make', 'makes', 'made', 'use', 'used', 'using', 'many', 'much',
  ]);

  const freq: Record<string, number> = {};
  const combined = texts.join(' ');

  // Extract multi-word phrases (2-grams) and single words
  const words = combined
    .replace(/<[^>]+>/g, '')
    .replace(/[^a-zA-Z0-9\s-]/g, ' ')
    .split(/\s+/)
    .filter(w => w.length > 2)
    .map(w => w.toLowerCase());

  // Single words
  for (const w of words) {
    if (!stopWords.has(w) && w.length > 3) {
      freq[w] = (freq[w] || 0) + 1;
    }
  }

  // 2-grams for compound terms
  for (let i = 0; i < words.length - 1; i++) {
    if (!stopWords.has(words[i]) && !stopWords.has(words[i + 1])) {
      const bigram = `${words[i]} ${words[i + 1]}`;
      if (bigram.length > 6) {
        freq[bigram] = (freq[bigram] || 0) + 1;
      }
    }
  }

  return Object.entries(freq)
    .filter(([, count]) => count >= 2)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 20)
    .map(([keyword, count]) => ({ keyword, count }));
}

// Group articles by topic and generate a summary
function generateInsight(articles: any[], keywords: { keyword: string; count: number }[]): string {
  const topKeywords = keywords.slice(0, 5).map(k => k.keyword);
  const sourceNames = [...new Set(articles.map(a => a.source_name))];
  const topicCounts: Record<string, number> = {};
  for (const a of articles) {
    topicCounts[a.topic || 'general'] = (topicCounts[a.topic || 'general'] || 0) + 1;
  }

  const topTopics = Object.entries(topicCounts)
    .sort((a, b) => b[1] - a[1])
    .map(([t]) => t);

  return [
    `Analysis of ${articles.length} articles from ${sourceNames.length} sources.`,
    `Top keywords: ${topKeywords.join(', ')}.`,
    `Primary topics: ${topTopics.join(', ')}.`,
    `Key signals: ${topKeywords.slice(0, 3).map(k => `"${k}" appeared ${keywords.find(kw => kw.keyword === k)?.count || 0} times`).join('; ')}.`,
  ].join(' ');
}

// Generate content draft from analysis
function generateDraft(
  articles: any[],
  keywords: { keyword: string; count: number }[],
  format: 'article' | 'newsletter' | 'report'
): { title: string; body: string } {
  const topKw = keywords.slice(0, 3).map(k => k.keyword);
  const topArticles = articles.slice(0, 5);

  if (format === 'newsletter') {
    const title = `Weekly Signal: ${topKw.map(k => k.charAt(0).toUpperCase() + k.slice(1)).join(', ')}`;
    const sections = topArticles.map((a, i) =>
      `### ${i + 1}. ${a.title || 'Untitled'}\n${a.content?.substring(0, 200) || 'No preview available.'}...\n[Source: ${a.source_name}](${a.url || '#'})`
    );
    const body = [
      `# ${title}\n`,
      `This week's top signals across ${[...new Set(articles.map(a => a.source_name))].length} sources.\n`,
      `**Trending Keywords:** ${topKw.join(' · ')}\n`,
      `---\n`,
      ...sections,
      `\n---\n`,
      `*Auto-generated by Mindle Pipeline · ${new Date().toISOString().split('T')[0]}*`,
    ].join('\n');
    return { title, body };
  }

  if (format === 'report') {
    const title = `Trend Report: ${topKw[0]?.charAt(0).toUpperCase()}${topKw[0]?.slice(1) || 'Weekly'} — Week ${getWeekNumber()}`;
    const body = [
      `# ${title}\n`,
      `## Executive Summary\n`,
      `Based on ${articles.length} collected data points, the dominant signals this period are: ${topKw.join(', ')}.\n`,
      `## Key Findings\n`,
      ...topArticles.map((a, i) =>
        `${i + 1}. **${a.title || 'Signal'}** (${a.source_name})\n   ${a.content?.substring(0, 150) || ''}...\n`
      ),
      `## Keyword Heatmap\n`,
      ...keywords.slice(0, 10).map(k => `- **${k.keyword}**: ${k.count} mentions`),
      `\n---\n`,
      `*Auto-generated by Mindle Pipeline · ${new Date().toISOString().split('T')[0]}*`,
    ].join('\n');
    return { title, body };
  }

  // article format
  const title = `${topKw[0]?.charAt(0).toUpperCase()}${topKw[0]?.slice(1) || 'Trending'}: What the Data Says This Week`;
  const body = [
    `# ${title}\n`,
    `The latest signals point to a surge in interest around **${topKw.join(', ')}**.`,
    `Across ${articles.length} sources, these themes dominated conversations.\n`,
    ...topArticles.slice(0, 3).map(a =>
      `> "${a.title}" — ${a.source_name}`
    ),
    `\n*Draft generated by Mindle Content Pipeline*`,
  ].join('\n');
  return { title, body };
}

function getWeekNumber(): number {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 1);
  const diff = now.getTime() - start.getTime();
  return Math.ceil(diff / (7 * 24 * 60 * 60 * 1000));
}

export async function POST() {
  const supabase = createClient(supabaseUrl, supabaseKey);

  try {
    // Fetch recent collected data (last 24 hours)
    const since = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
    const { data: articles, error: fetchErr } = await supabase
      .from('collected_data')
      .select('*')
      .gte('collected_at', since)
      .order('collected_at', { ascending: false })
      .limit(100);

    if (fetchErr) throw fetchErr;
    if (!articles || articles.length === 0) {
      return NextResponse.json({ success: true, message: 'No recent data to analyze', analyzed: 0 });
    }

    // Extract keywords
    const texts = articles.map(a => `${a.title || ''} ${a.content || ''}`);
    const keywords = extractKeywords(texts);

    // Generate insight
    const insightSummary = generateInsight(articles, keywords);

    // Save insight to th_insights
    const today = new Date().toISOString().split('T')[0];
    const { error: insightErr } = await supabase.from('th_insights').insert({
      period_type: 'daily',
      period_start: today,
      insight_type: 'trend',
      scope: 'all',
      summary: insightSummary,
      data: { keywords, articleCount: articles.length, sources: [...new Set(articles.map(a => a.source_name))] },
    });

    // Generate content drafts (newsletter + report + article)
    const formats: ('newsletter' | 'report' | 'article')[] = ['newsletter', 'report', 'article'];
    const drafts = formats.map(format => {
      const { title, body } = generateDraft(articles, keywords, format);
      return {
        title,
        body,
        target_brand: 'Mindle',
        target_format: format,
        source_data: { keywords: keywords.slice(0, 10), articleCount: articles.length, generatedAt: new Date().toISOString() },
        status: 'draft',
      };
    });

    const { error: draftErr } = await supabase.from('content_drafts').insert(drafts);

    return NextResponse.json({
      success: true,
      analyzed: articles.length,
      keywords: keywords.slice(0, 10),
      insight: insightSummary,
      draftsCreated: drafts.length,
      errors: [insightErr?.message, draftErr?.message].filter(Boolean),
    });
  } catch (e: any) {
    return NextResponse.json({ success: false, error: e.message }, { status: 500 });
  }
}

// GET for manual trigger / testing
export async function GET() {
  return POST();
}
