import { Brand, HistoryEvent } from '@/types/brand';
import { UniverseEvent } from '@/types/event';
import { Asset } from '@/types/asset';
import { Contact } from '@/types/contact';

export interface ContentItem {
    id: string;
    title: string;
    type: 'Video' | 'Post' | 'Blog' | 'Shorts';
    status: 'Idea' | 'Scripting' | 'Production' | 'Review' | 'Scheduled' | 'Published';
    brandId: string;
    dueDate?: string;
    assignee?: string;
    aiGenerated?: boolean;
}

export const contentItems: ContentItem[] = [
    { id: 'c1', title: 'LUKI Debut Teaser', type: 'Video', status: 'Published', brandId: 'luki', dueDate: '2025-08-15', aiGenerated: true },
    { id: 'c2', title: 'RooK Concept Art Reveal', type: 'Post', status: 'Scheduled', brandId: 'rook', dueDate: '2025-10-01' },
    { id: 'c3', title: 'Weekly AI News', type: 'Blog', status: 'Scripting', brandId: 'tenone', assignee: 'Cheonil', aiGenerated: true },
    { id: 'c4', title: 'Lumi Dance Challenge', type: 'Shorts', status: 'Idea', brandId: 'luki' },
];

export const brands: Brand[] = [
    {
        id: 'tenone',
        name: 'Ten:One™',
        category: 'Corporate',
        description: "Integrated Management System & Headquarters.",
        tagline: "가치로 연결된 하나의 거대한 세계관",
        domain: 'TenOne.biz',
        logoUrl: '/logos/tenone.png',
        thumbnailUrl: '/thumbnails/tenone.webp',
        websiteUrl: '/',
        status: 'Active',
        tags: ['HQ', 'System', 'Universe'],
    },
    {
        id: 'hero',
        name: 'HeRo',
        category: 'AI Creator',
        description: "Talent Agency for AI Idols & Creators.",
        tagline: "We Believe in your talent",
        domain: 'hero.ne.kr',
        logoUrl: '/logos/hero.png',
        thumbnailUrl: '/thumbnails/hero.webp',
        websiteUrl: '/hero',
        status: 'Active',
        tags: ['Agency', 'Management', 'AI'],
    },
    {
        id: 'badak',
        name: 'Badak',
        category: 'Community',
        description: "Marketing & Ad Industry Networking Community.",
        tagline: "약한 연결 고리가 만드는 강력한 기회",
        domain: 'Badak.biz',
        logoUrl: '/logos/badak.png',
        thumbnailUrl: '/thumbnails/badak.webp',
        websiteUrl: '/badak',
        status: 'Active',
        tags: ['Networking', 'Marketing', 'Ad'],
    },
    {
        id: 'madleap',
        name: 'MAD Leap',
        category: 'Community',
        description: "Marketing & Ad University Student Club.",
        tagline: "미치지 않으면 미치지 못한다",
        domain: 'MADLeap.co.kr',
        logoUrl: '/logos/madleap.png',
        thumbnailUrl: '/thumbnails/madleap.webp',
        websiteUrl: '/madleap',
        status: 'Active',
        tags: ['Student', 'Club', 'Education'],
    },
    {
        id: 'madleague',
        name: 'MAD League',
        category: 'Project Group',
        description: "Project Alliance & Contest Platform.",
        tagline: "실전이 우리를 강하게 하리라",
        domain: 'MADLeague.net',
        logoUrl: '/logos/madleague.png',
        thumbnailUrl: '/thumbnails/madleague.webp',
        websiteUrl: '/madleague',
        status: 'Active',
        tags: ['Alliance', 'Contest', 'Project'],
    },
    {
        id: 'youinone',
        name: 'YouInOne',
        category: 'Startup',
        description: "Project Group & Business Alliance.",
        tagline: "비즈니스 연대",
        domain: 'YouInOne.com',
        logoUrl: '/logos/youinone.png',
        thumbnailUrl: '/thumbnails/youinone.webp',
        websiteUrl: '/youinone',
        status: 'Active',
        tags: ['Business', 'Alliance', 'Startup'],
    },
    {
        id: 'fwn',
        name: 'FWN',
        category: 'Fashion',
        description: "World Fashion Week Network.",
        tagline: "세계 패션위크 네트워크",
        domain: 'FWN.co.kr',
        logoUrl: '/logos/fwn.png',
        thumbnailUrl: '/thumbnails/fwn.webp',
        websiteUrl: '/fwn',
        status: 'Development',
        tags: ['Fashion', 'Global', 'Network'],
    },
    {
        id: '0gamja',
        name: '0gamja',
        category: 'Character',
        description: "Zero Gamja: Trivial & Cute Potato Stories.",
        tagline: "하찮고 귀여운 감자들의 공감 이야기",
        domain: '0gamja.com',
        logoUrl: '/logos/0gamja.png',
        thumbnailUrl: '/thumbnails/0gamja.webp',
        websiteUrl: '/0gamja',
        status: 'Active',
        tags: ['Content', 'Webtoon', 'Character'],
    },
    {
        id: 'luki',
        name: 'LUKI',
        category: 'AI Idol',
        description: "AI 4-member girl group from planet Lumina.",
        tagline: "파괴된 행성 루미나의 빛 조각, AI 4인조 걸그룹",
        logoUrl: '/logos/luki.png',
        thumbnailUrl: '/thumbnails/luki.webp',
        websiteUrl: 'https://youtube.com/@LUKI-AIdol',
        foundedDate: '2025-08-29',
        status: 'Active',
        tags: ['K-Pop', 'AI', 'Virtual', 'Music'],
    },
    {
        id: 'rook',
        name: 'RooK',
        category: 'AI Creator',
        description: "AI Creator. 'Early bird gets the worm'.",
        tagline: "새로운 사람, 새로운 방법. 인공지능 크리에이터",
        domain: 'RooK.co.kr',
        logoUrl: '/logos/rook.png',
        thumbnailUrl: '/thumbnails/rook.webp',
        websiteUrl: '/rook',
        foundedDate: '2025-04-03',
        status: 'Active',
        tags: ['Art', 'Design', 'GenAI'],
    },
    {
        id: 'smarcomm',
        name: 'SmarComm.',
        category: 'Marketing',
        description: "AI-Powered Marketing Communication Solutions.",
        tagline: "AI가 마케팅을 바꾸는 순간",
        domain: 'smarcomm.co.kr',
        websiteUrl: '/smarcomm',
        status: 'Active',
        tags: ['GEO', 'SEO', 'AI Marketing', 'SaaS'],
    },
    {
        id: 'wio',
        name: 'WIO',
        category: 'Platform',
        description: "Work In One. 프로젝트 중심 통합 운영 플랫폼.",
        tagline: "5개 앱 열어서 한 줄 보고하는 거 이상하지 않아?",
        domain: 'wio.tenone.biz',
        websiteUrl: '/wio',
        status: 'Active',
        tags: ['SaaS', 'Project', 'CRM', 'HR'],
    },
    {
        id: 'mindle',
        name: 'Mindle',
        category: 'Content',
        description: "Trend Intelligence Platform. Bloom insights from signals.",
        tagline: "신호에서 인사이트를 피우다",
        domain: 'mindle.tenone.biz',
        websiteUrl: '/mindle',
        status: 'Active',
        tags: ['Trend', 'AI Crawler', 'Newsletter'],
    },
    {
        id: 'evschool',
        name: 'Evolution School',
        category: 'Education',
        description: "직무 교육 플랫폼. 현업 전문가의 실전 교육.",
        tagline: "진화는 배움에서 시작된다",
        websiteUrl: '/evschool',
        status: 'Active',
        tags: ['LMS', 'Education', 'Career'],
    },
    {
        id: 'planners',
        name: "Planner's",
        category: 'Education',
        description: "기획 도구·교육 플랫폼. Vrief & GPR 프레임워크.",
        tagline: "기획의 기본기를 세우다",
        websiteUrl: '/planners',
        status: 'Active',
        tags: ['Planning', 'Vrief', 'GPR', 'Tool'],
    },
    {
        id: 'brandgravity',
        name: 'Brand Gravity',
        category: 'Consulting',
        description: "브랜딩 컨설팅. 트렌드 기반 브랜드 전략.",
        tagline: "끌어당기는 브랜드를 만듭니다",
        websiteUrl: '/brandgravity',
        status: 'Active',
        tags: ['Branding', 'Strategy', 'Consulting'],
    },
    {
        id: 'namingfactory',
        name: 'Naming Factory',
        category: 'Consulting',
        description: "AI+전문가 하이브리드 네이밍·슬로건 솔루션.",
        tagline: "이름이 브랜드의 시작이다",
        websiteUrl: '/namingfactory',
        status: 'Active',
        tags: ['Naming', 'Slogan', 'AI'],
    },
    {
        id: 'changeup',
        name: 'ChangeUp',
        category: 'Project Group',
        description: "대학생 프로젝트 그룹. 실전 경험의 장.",
        tagline: "변화를 일으키는 사람들",
        websiteUrl: '/changeup',
        status: 'Active',
        tags: ['Project', 'Student', 'Competition'],
    },
    {
        id: 'domo',
        name: 'domo',
        category: 'Network',
        description: "시니어 비즈니스맨 네트워킹 플랫폼.",
        tagline: "경험이 만나는 곳",
        websiteUrl: '/domo',
        status: 'Development',
        tags: ['Senior', 'Networking', 'Business'],
    },
    {
        id: 'montz',
        name: 'MoNTZ',
        category: 'Content',
        description: "포토그래피 브랜드. 순간을 영원으로.",
        tagline: "Capture the moment",
        websiteUrl: '/montz',
        status: 'Development',
        tags: ['Photography', 'Creative', 'Visual'],
    },
    {
        id: 'myverse',
        name: 'Myverse',
        category: 'Platform',
        description: "My Universe. AI 에이전트 플랫폼.",
        tagline: "나만의 우주를 만들다",
        websiteUrl: '/myverse',
        status: 'Development',
        tags: ['AI Agent', 'Personal', 'Platform'],
    },
    {
        id: 'seoul360',
        name: 'Seoul/360°',
        category: 'Content',
        description: "서울 지하철 관광 가이드. 360도로 서울을 만나다.",
        tagline: "지하철로 만나는 서울의 모든 것",
        websiteUrl: '/seoul360',
        status: 'Development',
        tags: ['Tourism', 'Seoul', 'Local'],
    },
    {
        id: 'jakka',
        name: 'Jakka',
        category: 'Platform',
        description: "아티스트·작가 포트폴리오 플랫폼. 창작자가 작품을 전시하고 연결되는 공간.",
        tagline: "작가들의 작품 전시·연결",
        websiteUrl: '/jakka',
        status: 'Development',
        tags: ['Portfolio', 'Artist', 'Creator'],
    },
    {
        id: 'townity',
        name: 'Townity',
        category: 'Community',
        description: "Town + Community. 하이퍼로컬 동네 커뮤니티 플랫폼.",
        tagline: "동네에서 시작되는 연결",
        websiteUrl: '/townity',
        status: 'Development',
        tags: ['Local', 'Community', 'Neighborhood'],
    },
    {
        id: 'mullaesian',
        name: 'Mullaesian',
        category: 'Community',
        description: "문래동 창작촌 라이프 미디어. 동네 사람들의 이야기.",
        tagline: "문래동 사람들의 연결",
        websiteUrl: '/mullaesian',
        status: 'Development',
        tags: ['Local', 'Mullae', 'Media'],
    },
    {
        id: 'naturebox',
        name: 'NatureBox',
        category: 'Platform',
        description: "자연함(自然函). 강원도 정선 친환경 농작물 브랜드.",
        tagline: "자연에서 온 식품 이야기",
        websiteUrl: '/naturebox',
        status: 'Development',
        tags: ['Food', 'Nature', 'Local'],
    },
];

export const events: UniverseEvent[] = [
    {
        id: '1',
        title: "LUKI Debute Showcase",
        date: '2025-08-29',
        time: '18:00',
        type: 'Event',
        brandId: 'luki',
        status: 'Completed',
        description: "Online debut showcase streaming."
    },
    {
        id: '2',
        title: "RooK 'Cyber Punk' Exhibition",
        date: '2025-10-15',
        type: 'Event',
        brandId: 'rook',
        status: 'Scheduled',
        description: "Digital art exhibition in Metaverse."
    },
    {
        id: '3',
        title: "MAD League Season 1 Finals",
        date: '2025-11-20',
        type: 'Event',
        brandId: 'madleague',
        status: 'Scheduled',
    },
    {
        id: '4',
        title: "Badak Networking Night",
        date: '2025-09-05',
        time: '19:00',
        type: 'Meeting',
        brandId: 'badak',
        status: 'Completed',
    },
    {
        id: '5',
        title: "LUKI 2nd Single Teaser",
        date: '2025-12-01',
        type: 'Content',
        brandId: 'luki',
        status: 'Scheduled',
    }
];

export const assets: Asset[] = [
    {
        id: 'a1',
        title: 'LUKI Concept Photo #1',
        type: 'Image',
        brandId: 'luki',
        url: '/assets/luki_01.png',
        createdAt: '2025-08-10',
        size: '4.2 MB'
    },
    {
        id: 'a2',
        title: 'RooK Portfolio PDF',
        type: 'Document',
        brandId: 'rook',
        url: '/assets/rook_portfolio.pdf',
        createdAt: '2025-04-01',
        size: '12 MB'
    },
    {
        id: 'a3',
        title: 'Badak Logo Vector',
        type: 'Image',
        brandId: 'badak',
        url: '/logos/badak.png',
        createdAt: '2025-01-15',
        size: '1.5 MB'
    },
    {
        id: 'a4',
        title: 'LUKI Debut Teaser Video',
        type: 'Video',
        brandId: 'luki',
        url: '#',
        createdAt: '2025-08-20',
        size: '450 MB'
    },
    {
        id: 'a5',
        title: 'Gen AI Prompt: Space Background',
        type: 'Prompt',
        brandId: 'rook',
        url: '',
        createdAt: '2025-10-10',
        size: '1 KB'
    }
];

export const contacts: Contact[] = [
    {
        id: 'c1',
        name: 'Sarah Kim',
        role: 'Partner',
        company: 'CJ ENM',
        email: 'sarah.kim@cjenm.com',
        phone: '010-1234-5678',
        status: 'Active',
        brandAssociation: ['luki', 'badak'],
        lastContacted: '2025-08-28',
        notes: 'Key contact for LUKI debut distribution.'
    },
    {
        id: 'c2',
        name: 'David Lee',
        role: 'Vendor',
        company: 'Visual FX Studio',
        email: 'david@vfx.kr',
        phone: '010-9876-5432',
        status: 'Active',
        brandAssociation: ['rook'],
        lastContacted: '2025-07-15',
        notes: 'Main 3D asset supplier for RooK.'
    },
    {
        id: 'c3',
        name: 'Minji Park',
        role: 'Influencer',
        company: 'Freelance',
        email: 'minji.vlog@gmail.com',
        phone: '010-5555-5555',
        status: 'Lead',
        brandAssociation: ['madleague'],
        lastContacted: '2025-09-01',
        notes: 'Potential ambassador for MAD League Season 2.'
    },
    {
        id: 'c4',
        name: 'James Chen',
        role: 'Client',
        company: 'Global Tech',
        email: 'james@globaltech.com',
        status: 'Inactive',
        brandAssociation: ['youinone'],
        lastContacted: '2024-12-20',
    }
];

// 연혁 SSOT — TenOne Works(실제 기록) 기준으로만 작성. Works에 없는 사건은 넣지 않는다. (2026-10-05 재정리)
export const historyEvents: HistoryEvent[] = [
    { id: 'h01', date: '2020-03-11', year: '2020', title: 'Ten:One™ 사이트 오픈', description: '"나의 세계관을 만들기로 했다." 플래너 속 계획들을 다시 꺼내 세상에 내놓기 시작.', brandId: 'tenone' },
    { id: 'h02', date: '2020-06-12', year: '2020', title: '업계 네트워킹 오픈채팅방', description: '"사람 좀 없나?" 직접 사람을 찾기 위해 만든 카카오 오픈채팅방. 짧은 기간에 천 명 이상 참여.', brandId: 'badak' },
    { id: 'h03', date: '2021-02-08', year: '2021', title: 'Badak.biz 사이트 오픈', description: '"바닥 좁다고 했잖아" 오픈채팅방을 보완하는 마케팅/광고 업계 네트워킹 커뮤니티.', brandId: 'badak', link: 'http://badak.biz' },
    { id: 'h04', date: '2021-02-13', year: '2021', title: "Planner's Planner", description: '"우리는 모두 기획자다." 아이패드 굿노트 등에서 쓸 수 있는 플래너 제작.', brandId: 'planners' },
    { id: 'h05', date: '2021-11-01', year: '2021', title: 'MADLeap 창단', description: '대학생 마케팅/광고 연합동아리 매드립 창단 — 열정과 현실이 만나다.', brandId: 'madleap' },
    { id: 'h06', date: '2022-01-01', year: '2022', title: 'domo 비즈니스 네트워킹', description: '"훗날을 도모하다." 신뢰 기반으로 함께 결과를 내는 네트워킹, 사이드 프로젝트로 시작.', brandId: 'domo' },
    { id: 'h07', date: '2022-07-18', year: '2022', title: 'MAD League 출범', description: '마케팅&광고 대학생 프로젝트 연합. 실전 프로젝트로 업계 진출 기회를 만든다.', brandId: 'madleague', link: 'http://madleague.net' },
    { id: 'h08', date: '2023-01-07', year: '2023', title: 'D.A.M Party', description: '"자네 나와 일 한번 해보지 않겠나?" 취업을 원하는 학생과 사람을 찾는 회사가 직접 만나는 네트워킹 파티.', brandId: 'madleague' },
    { id: 'h09', date: '2023-01-07', year: '2023', title: '대학생 스타트업 "유인원" 인수', description: '광고에 빠져 창업한 대학생들과 새벽 이메일 한 통으로 인연이 되어 함께하기로.', brandId: 'youinone' },
    { id: 'h10', date: '2023-02-02', year: '2023', title: 'Chat with ChatGPT 출간', description: 'Ask Human, Answer AI. 인간이 묻고 ChatGPT가 답하며 만든 책.', brandId: 'tenone' },
    { id: 'h11', date: '2023-05-04', year: '2023', title: 'DAM Party Season 2', description: '"진짜 될까? 이게 되네!" 참가 학생과 기업이 연결돼 인턴·정규 채용까지.', brandId: 'madleague' },
    { id: 'h12', date: '2023-05-15', year: '2023', title: 'YouInOne.com 프로젝트 그룹', description: 'Project Group of Thinking Apes. 누구나 프로젝트를 발제하고 함께 실행하는 그룹.', brandId: 'youinone', link: 'http://youinone.com' },
    { id: 'h13', date: '2023-09-09', year: '2023', title: '#StreetRunway', description: '#StreetRunway로 서울패션위크를 하이재킹.', brandId: 'fwn' },
    { id: 'h14', date: '2023-09-25', year: '2023', title: 'FWN.co.kr — Fashion Week Network', description: '전 세계 패션위크 소식과 패션 종사자를 잇는 네트워크.', brandId: 'fwn', link: 'http://fwn.co.kr' },
    { id: 'h15', date: '2023-11-02', year: '2023', title: 'DAM Party Season 3', description: '홍대 문화 전시 공간 "네버 마인드"에서 규모를 키운 칵테일 네트워킹 파티.', brandId: 'madleague' },
    { id: 'h16', date: '2023-11-13', year: '2023', title: 'Creazy Challenge', description: 'Creative & Crazy — 대학생 대상 세계 광고제 도전 프로그램 시작.', brandId: 'madleague' },
    { id: 'h17', date: '2023-12-08', year: '2023', title: 'PAM 합류', description: '1994년부터 이어온 부산 대학생 연합 광고 동아리 PAM(Pusan Ad Mania)이 매드리그 네트워크에 합류.', brandId: 'madleague' },
    { id: 'h18', date: '2024-01-17', year: '2024', title: '0gamja 사이트 오픈', description: '인공지능을 활용해 각자의 관심사를 콘텐츠로 만들어 보자는 아이데이션에서 시작.', brandId: '0gamja', link: 'http://0gamja.com' },
    { id: 'h19', date: '2024-02-02', year: '2024', title: 'ADlle 합류', description: '대구·경북 대학생 연합 광고 동아리 ADlle가 매드리그 네트워크에 합류.', brandId: 'madleague' },
    { id: 'h20', date: '2024-05-18', year: '2024', title: 'ChangeUp', description: '기업가 정신을 가르치는 선생님들과 함께 고등학생·대학생 대상 창업/기업가 정신 활동 시작.', brandId: 'changeup', link: 'http://changeup.company' },
    { id: 'h21', date: '2024-09-27', year: '2024', title: '지평주조 경쟁 PT', description: '지평주조를 호스트 브랜드로 ADlle·MADLeap·PAM 3개 동아리가 경쟁 PT 진행.', brandId: 'madleague' },
    { id: 'h22', date: '2024-11-12', year: '2024', title: 'ABC 합류', description: '조선대학교 마케팅 광고 동아리 ABC가 광주·전남 거점으로 합류.', brandId: 'madleague' },
    { id: 'h23', date: '2025-01-13', year: '2025', title: 'SUZAK 합류', description: '제주 지역 대표 마케팅 광고 동아리 수작(SUZAK) 결성·합류. 전국 5개 동아리.', brandId: 'madleague' },
    { id: 'h24', date: '2025-03-31', year: '2025', title: 'DAM Be 캐릭터', description: '"범 잡아 먹는 담비가 있다." 한국 노란목 담비를 상징화한 MAD League 캐릭터.', brandId: 'madleague' },
    { id: 'h25', date: '2025-04-03', year: '2025', title: 'MADzine 창간', description: '마케팅, 광고에 미친(MAD) 우리들의 이야기. 형식도 주기도 없는 매거진.', brandId: 'madleague' },
    { id: 'h26', date: '2025-08-04', year: '2025', title: '대성학원 경쟁 PT', description: '대성학원을 호스트 브랜드로 연간 소셜 캠페인 제안 경쟁 PT (2025 1차).', brandId: 'madleague' },
    { id: 'h27', date: '2025-08-29', year: '2025', title: 'RooK — 인공지능 크리에이터 플랫폼', description: '"길바닥에 동전은 먼저 줍는 사람이 임자." 기다리지 않고 시작한 작은 시도.', brandId: 'rook', link: 'http://rook.co.kr' },
    { id: 'h28', date: '2025-08-31', year: '2025', title: 'LUKI — AI 아이돌', description: "생성형 AI 4인조 여성 아이돌 그룹 'LUKI'. 파괴된 행성 루미나의 빛 조각이 지구에 불시착.", brandId: 'luki', link: 'https://youtube.com/@LUKI-AIdol' },
    { id: 'h29', date: '2025-11-04', year: '2025', title: '리제로스 경쟁 PT', description: '자연친화 스타트업 리제로스의 배달·포장 음식 냉매제 시장 진출 전략 경쟁 PT (2025 2차).', brandId: 'madleague' },
    { id: 'h30', date: '2025-12-01', year: '2025', title: 'P:ad 합류', description: '한림대학교 기반 대학생 광고 동아리 P:ad가 강원권 거점으로 합류.', brandId: 'madleague' },
    { id: 'h31', date: '2026-01-05', year: '2026', title: 'AD Zone 합류', description: '고려대 세종캠퍼스 기반 AD Zone이 충청권 거점으로 합류. 전국 7개 동아리.', brandId: 'madleague' },
    { id: 'h32', date: '2026-05-06', year: '2026', title: '춤추는고래 경쟁 PT', description: '여성 위생용품 브랜드 춤추는고래를 호스트 브랜드로 한 MADLeap 경쟁 PT.', brandId: 'madleap' },
];
